// JCL_DEBUG_EXPERT_GENERATEJDBG ON
program Adjutor;

{$define ADJUTOR}





uses
  Vcl.Forms,
  Vcl.Themes,
  Vcl.Styles,
  System.SysUtils,
  Datasnap.Midas,
  Uteis in 'infosaga\Uteis.pas',
  BaseForm in 'infosaga\BaseForm.pas' {frmBase},
  InicioDB in 'infosaga\InicioDB.pas' {dbInicio: Delphi\Componentes\06-infosaga_desktop\BaseDBForm.pas' {frmBaseDB},
  BaseDBForm in 'infosaga\BaseDBForm.pas' {frmBaseDB},
  BaseDBPesquisaBaseForm in 'infosaga\BaseDBPesquisaBaseForm.pas' {frmBaseDBPesquisaBase},
  BaseDBPesquisaForm in 'infosaga\BaseDBPesquisaForm.pas' {frmBaseDBPesquisa},
  BaseDBEditForm in 'infosaga\BaseDBEditForm.pas' {frmBaseDBEdit},
  BaseTelaRelatorioForm in 'infosaga\BaseTelaRelatorioForm.pas' {frmBaseTelaRelatorio},
  BaseReportForm in 'infosaga\BaseReportForm.pas' {frmBaseReport},
  ErrorForm in 'infosaga\ErrorForm.pas' {FrmError},
  BaseDBPesquisaSimplesForm in 'infosaga\BaseDBPesquisaSimplesForm.pas' {frmBaseDBPesquisaSimples},
  Almox0002 in 'dfmpas2\Almox0002.pas' {FormAlmoxGrid},
  Ban0001 in 'dfmpas2\Ban0001.pas' {FormBanco},
  Ban0002 in 'dfmpas2\Ban0002.pas' {FormBancoGrid},
  Caixa001 in 'dfmpas2\Caixa001.pas' {FormCaixaFixo},
  Caixa002 in 'dfmpas2\Caixa002.pas' {FormCaixaFecha},
  CEL0001 in 'dfmpas2\CEL0001.pas' {FormCelula},
  CEL0002 in 'dfmpas2\CEL0002.pas' {FormComponentes},
  CEL0003 in 'dfmpas2\CEL0003.pas' {FormComponenteGrid},
  Cel0005 in 'dfmpas2\Cel0005.pas' {FormMetaProd},
  CEL0006 in 'dfmpas2\CEL0006.pas' {FormMetasGrid},
  CELN0007 in 'dfmpas2\CELN0007.pas' {FormEnviaCelulaNovo},
  CEL0008 in 'dfmpas2\CEL0008.pas' {FormMovCelulas},
  CEL0009 in 'dfmpas2\CEL0009.pas' {FormManutMovCel},
  CEL0010 in 'dfmpas2\CEL0010.pas' {FormCelPesquisa},
  CLI0004 in 'dfmpas2\CLI0004.pas' {FormCliAtividade},
  Cus0001 in 'dfmpas2\Cus0001.pas' {FormCusto},
  Cus0002 in 'dfmpas2\Cus0002.pas' {FormCustoGlobal},
  DataCad in 'dfmpas2\DataCad.pas' {DataCadastros: TDataModule},
  DataCad1 in 'dfmpas2\DataCad1.pas' {DataCadastros1: TDataModule},
  DataMov in 'dfmpas2\DataMov.pas' {DataMovimento: TDataModule},
  DataMov2 in 'dfmpas2\DataMov2.pas' {DataMovimento2: TDataModule},
  DmProdu in 'dfmpas2\DmProdu.pas' {DmProducao: TDataModule},
  DmSysCfg in 'dfmpas2\DmSysCfg.pas' {DmCfg: TDataModule},
  Emp0001 in 'dfmpas2\Emp0001.pas' {FormEmpresa},
  Evr0001 in 'dfmpas2\Evr0001.pas' {FormEveRepres},
  Flu0001 in 'dfmpas2\Flu0001.pas' {FormFluxoCaixa},
  Flu0002 in 'dfmpas2\Flu0002.pas' {FormFluxoInterv},
  For0003 in 'dfmpas2\For0003.pas' {FormForXProd},
  GImpAdmi in 'dfmpas2\GImpAdmi.pas' {FormGImpRelAdm},
  GImpCel in 'dfmpas2\GImpCel.pas' {FormGImpCel},
  GImpCFix in 'dfmpas2\GImpCFix.pas' {FormGimpCxFixo},
  GImpClie in 'dfmpas2\GImpClie.pas' {FormGImpClie},
  GImpComp in 'dfmpas2\GImpComp.pas' {FormGimpComponentes},
  GimpCust in 'dfmpas2\GimpCust.pas' {FormGimpCusto},
  GImpEve in 'dfmpas2\GImpEve.pas' {FormGimpEveRep},
  GimpFichaCliente in 'dfmpas2\GimpFichaCliente.pas' {FormGimpFichas},
  GImpForn in 'dfmpas2\GImpForn.pas' {FormGImpForn},
  GimpOC in 'dfmpas2\GimpOC.pas' {FormGimpOC},
  GImpOPrd in 'dfmpas2\GImpOPrd.pas' {FormGimpOP},
  GImpPaga in 'dfmpas2\GImpPaga.pas' {FormGImpPagar},
  GImpProd in 'dfmpas2\GImpProd.pas' {FormGImpProduto},
  GImpRece in 'dfmpas2\GImpRece.pas' {FormGImpRece},
  GImpRepr in 'dfmpas2\GImpRepr.pas' {FormGimpRepr},
  GImpTran in 'dfmpas2\GImpTran.pas' {FormGImpTran},
  ICMS0000 in 'dfmpas2\ICMS0000.pas' {FormAliqICms},
  Men0001 in 'dfmpas2\Men0001.pas' {FrmMenu},
  OCP0001 in 'dfmpas2\OCP0001.pas' {FormOrdCompra},
  Ocp0002 in 'dfmpas2\Ocp0002.pas' {FormOrdCompraGrid},
  Ope0001 in 'dfmpas2\Ope0001.pas' {FormOperFisc},
  Ope0002 in 'dfmpas2\Ope0002.pas' {FormOperFiscGrid},
  Pag0001 in 'dfmpas2\Pag0001.pas' {FormContasPagar},
  Pag0002 in 'dfmpas2\Pag0002.pas' {FormContasPagParcelas},
  Pag0004 in 'dfmpas2\Pag0004.pas' {FormContasPagarGrid},
  PrdMedio in 'dfmpas2\PrdMedio.pas' {FormRecalculaPMedio},
  Ped0004 in 'dfmpas2\Ped0004.pas' {FormPedidoGrid},
  Ped0008 in 'dfmpas2\Ped0008.pas' {FormConsultaPedido},
  Rec0002 in 'dfmpas2\Rec0002.pas' {FormContasRecParcelas},
  Rec0003 in 'dfmpas2\Rec0003.pas' {FormContasRecParceGrid},
  Rec0001 in 'dfmpas2\Rec0001.pas' {FormContasReceber},
  Prd0002 in 'dfmpas2\Prd0002.pas' {FormProdGrupo},
  Prd0003 in 'dfmpas2\Prd0003.pas' {FormProdTipo},
  Prd0004 in 'dfmpas2\Prd0004.pas' {FormPrd_IPI},
  Prd0005 in 'dfmpas2\Prd0005.pas' {FormPrdLinha},
  Prmd0001 in 'dfmpas2\Prmd0001.pas' {FormParametros},
  Rep0002 in 'dfmpas2\Rep0002.pas' {FormRepresGrid},
  Rep0001 in 'dfmpas2\Rep0001.pas' {FormRepres},
  Nfs0003 in 'dfmpas2\Nfs0003.pas' {FormConsNFGrid},
  sis00072 in 'dfmpas2\sis00072.pas' {FrmExportacaoContabilitadade},
  SINTEGRA in 'dfmpas2\SINTEGRA.pas' {FormSINTEGRA},
  Reg0001 in 'dfmpas2\Reg0001.pas' {FormRegiao},
  GImpPedi in 'dfmpas2\GImpPedi.pas' {FormGImpPedido},
  Fat0003 in 'dfmpas2\Fat0003.pas' {FormFatPedido},
  TRP0002 in 'dfmpas2\TRP0002.pas' {FormTransportGrid},
  Trp0001 in 'dfmpas2\Trp0001.pas' {FormTransport},
  Sab0001 in 'dfmpas2\Sab0001.pas' {FormSaldoBanco},
  Fat0002 in 'dfmpas2\Fat0002.pas' {FormFaturar},
  GImpBoletos in 'dfmpas2\GImpBoletos.pas' {FrmGimpBoletos},
  Nfs0002 in 'dfmpas2\Nfs0002.pas' {FormNfPagar},
  ConfiguraBancoForm in 'dfmpas2\ConfiguraBancoForm.pas' {FrmConfiguraBanco},
  cnab0003 in 'dfmpas2\cnab0003.pas' {FrmRetornoCNAB_Novo},
  cnab0001 in 'dfmpas2\cnab0001.pas' {FormGeradorCNAB},
  SEQ0000 in 'dfmpas2\SEQ0000.pas' {FrmSequenciador},
  Fat0004 in 'dfmpas2\Fat0004.pas' {FrmConsultaNFSaida},
  Prd0001 in 'dfmpas2\Prd0001.pas' {FormProduto},
  Prd0012 in 'dfmpas2\Prd0012.pas' {FormAlterarRef},
  Prd0013 in 'dfmpas2\Prd0013.pas' {FrmPrdEquivalente},
  Prmd0002 in 'dfmpas2\Prmd0002.pas' {FrmParamDuplicar},
  Ped0009 in 'dfmpas2\Ped0009.pas' {FormPedidoDuplicar},
  ShareDb in 'dfmpas2\ShareDb.pas' {FormShare},
  Osv0005 in 'dfmpas2\Osv0005.pas' {FormConcluirOP},
  Osv0002 in 'dfmpas2\Osv0002.pas' {FormOrdServGera},
  PrevC002 in 'dfmpas2\PrevC002.pas' {FormPrevConsGrid},
  OsvN0007 in 'dfmpas2\OsvN0007.pas' {FormOrdServConsiderar},
  OsvN0003 in 'dfmpas2\OsvN0003.pas' {FormConsultaOSV},
  Osv0001 in 'dfmpas2\Osv0001.pas' {FormOrdServCentro},
  PrevCN002 in 'dfmpas2\PrevCN002.pas' {FormPrevisaoProducao},
  OsvN0002 in 'dfmpas2\OsvN0002.pas' {FormOrdServCentroGerar},
  Osv0006 in 'dfmpas2\Osv0006.pas' {FormOrdServRefazer},
  Dep0001 in 'dfmpas2\Dep0001.pas' {FormDepartamento},
  CEL0007 in 'dfmpas2\CEL0007.pas' {FormEnviaCelula},
  Usuar001 in 'dfmpas2\Usuar001.pas' {FrmCadastroUsuario},
  Mnt0001 in 'dfmpas2\Mnt0001.pas' {frmmanutencao},
  Nat0001 in 'dfmpas2\Nat0001.pas' {frmopnatureza},
  Rec0006 in 'dfmpas2\Rec0006.pas' {FrmAtualizaLimite},
  Rec0004 in 'dfmpas2\Rec0004.pas' {FormRetencoes},
  Rec0005 in 'dfmpas2\Rec0005.pas' {FrmRemessaDescontar},
  ImpCh in 'dfmpas2\ImpCh.pas' {FormImpCheque},
  Motivo in 'dfmpas2\Motivo.pas' {FrmMotivo},
  Cheque0002 in 'dfmpas2\Cheque0002.pas' {FrmChequeConsulta},
  GimpCheques in 'dfmpas2\GimpCheques.pas' {FrmGimpCheques},
  FluCx0001 in 'dfmpas2\FluCx0001.pas' {FrmFluxoCaixa},
  OsvN0008 in 'dfmpas2\OsvN0008.pas' {FormProdutosOPs},
  TRANSFCTACAIXA in 'dfmpas2\TRANSFCTACAIXA.pas' {FrmTransfCtaCaixa},
  Ftc0002 in 'dfmpas2\Ftc0002.pas' {FormFichaTecGrid},
  ftc0003 in 'dfmpas2\ftc0003.pas' {FormCopiaFichaTec},
  GimpReqCompra in 'dfmpas2\GimpReqCompra.pas' {FrmGimpReqCompra},
  Fat0005 in 'dfmpas2\Fat0005.pas' {FrmInformativoNF},
  Pcl0002 in 'dfmpas2\Pcl0002.pas' {FormParcelasGrid},
  Pcl0001 in 'dfmpas2\Pcl0001.pas' {FormParcelas},
  CID0001 in 'dfmpas2\CID0001.pas' {FormCadCidade},
  CID0002 in 'dfmpas2\CID0002.pas' {FormCidadeGrid},
  FATPARC in 'dfmpas2\FATPARC.pas' {frmFATPARC},
  markup001 in 'dfmpas2\markup001.pas' {FormTabelaMarkup},
  UFUNCOES in 'dfmpas2\UFUNCOES.PAS',
  LicencaForm in 'dfmpas2\LicencaForm.pas' {FrmLicenca},
  val0002 in 'dfmpas2\val0002.pas',
  Comimedia in 'dfmpas2\Comimedia.pas' {FormRecalculaComisPed},
  EFD0001 in 'dfmpas2\EFD0001.pas' {FrmEFD},
  KAR0001 in 'dfmpas2\KAR0001.pas' {FrmKardex},
  KAR0002 in 'dfmpas2\KAR0002.pas' {Form1},
  Nfs0004 in 'dfmpas2\Nfs0004.pas' {FrmNotaFiscalServico},
  fat0007 in 'dfmpas2\fat0007.pas' {FormComplementarNFe},
  uFinanceiroAnaliseCredito in 'dfmpas2\uFinanceiroAnaliseCredito.pas' {FrmFinanceiroAnaliseCredito},
  uFinanceiroAnaliseCreditoConfirma in 'dfmpas2\uFinanceiroAnaliseCreditoConfirma.pas' {FrmFinanceiroAnaliseCreditoConfirma},
  uPedidoDAO in 'dfmpas2\uPedidoDAO.pas',
  uPedidoItem in 'dfmpas2\uPedidoItem.pas' {FrmPedidoItem},
  uPedidoTipo in 'dfmpas2\uPedidoTipo.pas' {a},
  uProdutoCompraVenda in 'dfmpas2\uProdutoCompraVenda.pas' {FrmProdutoCompraVenda},
  fat0008 in 'dfmpas2\fat0008.pas' {FormFaturamentoOpcao},
  uPedidoReajuste in 'dfmpas2\uPedidoReajuste.pas' {FrmPedidoReajuste},
  uEntradaNotaXml in 'dfmpas2\uEntradaNotaXml.pas' {FrmEntradaNotaXml},
  uEntradaNotaXmlItem in 'dfmpas2\uEntradaNotaXmlItem.pas' {FrmEntradaNotaXmlItem},
  uFinanceiroConciliacao in 'dfmpas2\uFinanceiroConciliacao.pas' {FrmFinanceiroConciliacao},
  EnfIndustrializacao in 'dfmpas2\EnfIndustrializacao.pas' {Form2},
  uVinculacaoIndustrializacaoRetorno in 'dfmpas2\uVinculacaoIndustrializacaoRetorno.pas' {FrmVinculacaoIndustrializacaoRetorno},
  uVinculacaoIndustrializacaoRetornoVincula in 'dfmpas2\uVinculacaoIndustrializacaoRetornoVincula.pas' {FrmVinculacaoIndustrializacaoRetornoVincula},
  uFaturamentoNotaFiscal in 'dfmpas2\uFaturamentoNotaFiscal.pas' {FrmFaturamentoNovoNotaFiscal},
  uFaturamentoNotaFiscalOpcao in 'dfmpas2\uFaturamentoNotaFiscalOpcao.pas' {FrmFaturamentoNovoOpcao},
  ContatoCliente in 'dfmpas2\ContatoCliente.pas' {FrmContatoCliente},
  uIndustrializacao_SitObs in 'uIndustrializacao_SitObs.pas' {FrmIndSitObs},
  uFinanceiroPlanoContasCentroCusto in 'dfmpas2\uFinanceiroPlanoContasCentroCusto.pas' {FrmFinanceiroPlanoContasCentroCusto},
  uAvisos in 'dfmpas2\uAvisos.pas' {FormAviSos},
  IBPTForm in 'dfmpas2\IBPTForm.pas' {frmIbpt},
  EditIBPTForm in 'dfmpas2\EditIBPTForm.pas' {frmEditIBPT},
  CestForm in 'dfmpas2\CestForm.pas' {frmCEST},
  EditCestForm in 'dfmpas2\EditCestForm.pas' {FrmEditCest},
  CSOSNForm in 'dfmpas2\CSOSNForm.pas' {frmCSOSN},
  EditCSOSNform in 'dfmpas2\EditCSOSNform.pas' {frmEditCSOSN},
  ScriptForm in 'dfmpas2\ScriptForm.pas' {FrmScript},
  ExportProdutoExcelForm in 'dfmpas2\ExportProdutoExcelForm.pas' {FrmExportProdutoExcel},
  ExportCodFornForm in 'dfmpas2\ExportCodFornForm.pas' {FrmExportCodForn},
  ProdutosPorVendedorForm in 'dfmpas2\ProdutosPorVendedorForm.pas' {FrmProdutosPorVendedor},
  DiretivasItemForm in 'dfmpas2\DiretivasItemForm.pas' {FrmDiretivasItem},
  EditDiretivaItemForm in 'dfmpas2\EditDiretivaItemForm.pas' {frmEditDiretivaItem},
  uCadastroDiretiva in 'dfmpas2\uCadastroDiretiva.pas' {FormDiretiva},
  uFinanceiroDao in 'dfmpas2\uFinanceiroDao.pas',
  uCadastroFormaPagamento in 'dfmpas2\uCadastroFormaPagamento.pas' {FrmCadastroFormaPagamento},
  uPlanoContasCentroCusto in 'dfmpas2\uPlanoContasCentroCusto.pas' {FrmPlanoContasCentroCusto},
  PCX0000 in 'dfmpas2\PCX0000.pas' {FormProjCaixa},
  uPlanoContasCentroCustoManual in 'dfmpas2\uPlanoContasCentroCustoManual.pas' {FrmPlanoContasCentroCustoManual},
  uCadastroPerfilRateio in 'dfmpas2\uCadastroPerfilRateio.pas' {FrmCadastroPerfilRateio},
  RecErro in 'dfmpas2\RecErro.pas' {ReconcileErrorForm},
  Pag0007 in 'dfmpas2\Pag0007.pas' {FormContasPagarBaixa},
  uCheque in 'dfmpas2\uCheque.pas' {FrmCheque},
  uChequeCadastro in 'dfmpas2\uChequeCadastro.pas' {FrmChequeCadastro},
  uChequeStatus in 'dfmpas2\uChequeStatus.pas' {FrmChequeStatus},
  Ftc0001 in 'dfmpas2\Ftc0001.pas' {FormFichaTecnica},
  uCadastroLote in 'dfmpas2\uCadastroLote.pas' {FrmCadastroProdutoLote},
  KAR0003 in 'dfmpas2\KAR0003.pas' {FrmKardexLancamentoManual},
  uProdutoDao in 'dfmpas2\uProdutoDao.pas',
  uCadastroConversaoMedida in 'dfmpas2\uCadastroConversaoMedida.pas' {FormCadastroConversaoMedida},
  uFornecedorDao in 'dfmpas2\uFornecedorDao.pas',
  uNaturezaOperacaoDao in 'dfmpas2\uNaturezaOperacaoDao.pas',
  uPedidoWebAcao in 'dfmpas2\uPedidoWebAcao.pas' {FrmPedidoWebAcao},
  uPedidoTipoInicial in 'dfmpas2\uPedidoTipoInicial.pas' {FrmPedidoTipoInicial},
  IndTipoRetorno in 'dfmpas2\IndTipoRetorno.pas' {FrmCadastroTipoRetorno},
  uCadastroGrade in 'dfmpas2\uCadastroGrade.pas' {FrmCadastroGrade},
  uCadastroFrases in 'dfmpas2\uCadastroFrases.pas' {FrmCadastroObservacao},
  uPedidoWeb in 'dfmpas2\uPedidoWeb.pas' {FrmPedidoWeb},
  uClienteDao in 'dfmpas2\uClienteDao.pas',
  PrevC003 in 'dfmpas2\PrevC003.pas' {FormGimpPrevisao},
  PrevC004 in 'dfmpas2\PrevC004.pas' {FormComprar},
  REQ0001 in 'dfmpas2\REQ0001.pas' {FrmReqCompra},
  FrmTemporario in 'dfmpas2\FrmTemporario.pas' {FrmTemp},
  uPedidoCancelamento in 'dfmpas2\uPedidoCancelamento.pas' {FrmPedidoCancelemento},
  uPedidoConsultaProducao in 'dfmpas2\uPedidoConsultaProducao.pas' {FrmPedidoConsultaProducao},
  uFinanceiroAnaliseCreditoCliente in 'dfmpas2\uFinanceiroAnaliseCreditoCliente.pas' {FrmFinanceiroAnaliseCreditoCliente},
  PesquisaTabelasForm in 'dfmpas2\PesquisaTabelasForm.pas' {frmPesquisaTabelas},
  EditTabelasForm in 'dfmpas2\EditTabelasForm.pas' {frmEditTabelas},
  ReajusteTabelaPrecosForm in 'dfmpas2\ReajusteTabelaPrecosForm.pas' {frmReajusteTabelaPrecos},
  RNOP0001 in 'dfmpas2\RNOP0001.pas' {FormRegraNatOp},
  uEntradaSaidaProdutos in 'dfmpas2\uEntradaSaidaProdutos.pas' {FrmEntradaSaidaProdutos},
  TelaCopiaProdutoForm in 'dfmpas2\TelaCopiaProdutoForm.pas' {FrmTelaCopiaProduto},
  AutorizaForm in 'dfmpas2\AutorizaForm.pas' {FrmAutoriza},
  uEntradaNotaXmlOpcao in 'dfmpas2\uEntradaNotaXmlOpcao.pas' {FrmEntradaNotaXmlOpcao},
  EditCompartilhamentoDb in 'dfmpas2\EditCompartilhamentoDb.pas' {frmEditCompartilhamentoDb},
  RelatoriosPedidoForm in 'dfmpas2\RelatoriosPedidoForm.pas' {FrmRelatoriosPedido},
  PrdPreco in 'dfmpas2\PrdPreco.pas' {FormAtualizaPreco},
  PCX0002 in 'dfmpas2\PCX0002.pas' {FrmProjetoObraNotaEntrada},
  uNotaFiscalDao in 'dfmpas2\uNotaFiscalDao.pas',
  uEntradaNotaPedidoCompra in 'dfmpas2\uEntradaNotaPedidoCompra.pas' {FormNfEntradaPedidoCompra},
  Pcp0001 in 'dfmpas2\Pcp0001.pas' {FormPCPCadastro},
  Pcp0002 in 'dfmpas2\Pcp0002.pas' {FormPCPGrid},
  Pag0008 in 'dfmpas2\Pag0008.pas' {FormContasPagarBaixas},
  uRecibo in 'dfmpas2\uRecibo.pas' {FrmRecibo},
  Pag0009 in 'dfmpas2\Pag0009.pas' {FormContasPagarRepetir},
  fat0009 in 'dfmpas2\fat0009.pas' {FormContasReceberBaixa},
  fat0010 in 'dfmpas2\fat0010.pas' {FormContasReceberBaixas},
  Rec0007 in 'dfmpas2\Rec0007.pas' {FormContasReceberRepetir},
  Sab0002 in 'dfmpas2\Sab0002.pas' {FormSaldoBancoGrid},
  Trib0001 in 'dfmpas2\Trib0001.pas' {FormCadTributos},
  RNOP0002 in 'dfmpas2\RNOP0002.pas' {FormRNOPGrid},
  STR0002 in 'dfmpas2\STR0002.pas' {FormConsultaSitTrib},
  STR0001 in 'dfmpas2\STR0001.pas' {FormCadSitTributaria},
  Eve0001 in 'dfmpas2\Eve0001.pas' {FormEvento},
  Flu0001Simples in 'dfmpas2\Flu0001Simples.pas' {FormFluxoCaixaSimples},
  GImpDupl in 'dfmpas2\GImpDupl.pas' {FormGimpDuplicata},
  bkp00001 in 'dfmpas2\bkp00001.pas' {FrmBackup},
  TRANSFCLIE in 'dfmpas2\TRANSFCLIE.pas' {FormTransfClie},
  CPRA001 in 'dfmpas2\CPRA001.pas' {formCompraMenu},
  KAR0004 in 'dfmpas2\KAR0004.pas' {KardexZerarEstoque},
  PCX0001 in 'dfmpas2\PCX0001.pas' {FrmProjetoObraCusto},
  Opv00001 in 'dfmpas2\Opv00001.pas' {FrmCadastroTipoPedido},
  uPedidoProducao in 'dfmpas2\uPedidoProducao.pas' {FrmPedidoProducao},
  uBackupRestore in 'dfmpas2\uBackupRestore.pas' {FrmBackupRestore},
  uFinanceiroConciliacaoLancamento in 'dfmpas2\uFinanceiroConciliacaoLancamento.pas' {FrmFinanceiroConciliacaoLancamento},
  uCadastroFinanceiroHistoricoLancamentos in 'dfmpas2\uCadastroFinanceiroHistoricoLancamentos.pas' {FrmCadastroHistoricoConciliacao},
  uFinanceiroConciliacaoTransferencia in 'dfmpas2\uFinanceiroConciliacaoTransferencia.pas' {FrmFinanceiroConciliacaoTransferencia},
  SIE0000 in 'dfmpas2\SIE0000.pas' {FrmSie},
  Sped in 'dfmpas2\Sped.pas' {FrmSped},
  uPedidoPCP in 'dfmpas2\uPedidoPCP.pas' {FrmPedidoPCP},
  uPedidoPCPLanca in 'dfmpas2\uPedidoPCPLanca.pas' {FrmPedidoPCPLanca},
  uConsulaMarkup in 'dfmpas2\uConsulaMarkup.pas' {FrmConsultaMarkup},
  uConsulaMarkupPedido in 'dfmpas2\uConsulaMarkupPedido.pas' {FrmConsultaMarkupPedido},
  uConsulaMarkupManu in 'dfmpas2\uConsulaMarkupManu.pas' {FrmConsultaMarkupManu},
  SpedFiscal in 'dfmpas2\SpedFiscal.pas' {FrmSpedFiscal},
  uFinanceiroManutencaoRateio in 'dfmpas2\uFinanceiroManutencaoRateio.pas' {FrmFinanceiroRateioCentroCusto},
  uPlanoContasCentroCustoCopia in 'dfmpas2\uPlanoContasCentroCustoCopia.pas' {FrmPlanoContasCentroCustoCopia},
  For0001 in 'dfmpas2\For0001.pas' {FormFornec},
  uRelatorioInventarioCiclico in 'dfmpas2\uRelatorioInventarioCiclico.pas' {RelatorioInventarioCiclicoForm},
  uProdutoEnderecamento in 'dfmpas2\uProdutoEnderecamento.pas' {FrmProdutoEnderecamento},
  uPedido in 'dfmpas2\uPedido.pas' {FrmPedido},
  InsereRateioIndiceForm in 'dfmpas2\InsereRateioIndiceForm.pas' {frmInsereRateioIndice},
  CCT0001 in 'dfmpas2\CCT0001.pas' {FormContAnalise},
  SelectStyleForm in 'dfmpas2\SelectStyleForm.pas' {FrmSelectStyle},
  ufrmPreviewRB in 'dfmpas2\ufrmPreviewRB.pas' {frmPreviewrb},
  Fat0000_Romaneio in 'dfmpas2\Fat0000_Romaneio.pas' {FrmFat0000_Romaneio},
  Fat0000_etiquetas in 'dfmpas2\Fat0000_etiquetas.pas' {FrmFat0000_etiquetas},
  BaseDbEstoqueForm in 'dfmpas2\BaseDbEstoqueForm.pas' {frmBaseDbEstoque},
  BaseDbFaturamentoForm in 'dfmpas2\BaseDbFaturamentoForm.pas' {frmBaseDbFaturamento},
  ImportarXMLMigracaoNovi in 'dfmpas2\ImportarXMLMigracaoNovi.pas' {frmImportarXMLMigracaoNovi},
  PesquisaClientesForm in 'dfmpas2\PesquisaClientesForm.pas' {frmPesquisaClientes},
  Nfs0001 in 'dfmpas2\Nfs0001.pas' {FormNfEntrada},
  OsvN0001 in 'dfmpas2\OsvN0001.pas' {FormOrdServCentroNovo},
  Prd0006 in 'dfmpas2\Prd0006.pas' {FormProdutoGrid},
  PrevC001 in 'dfmpas2\PrevC001.pas' {FormPrevConsumo},
  For0002 in 'dfmpas2\For0002.pas' {FormFornecGrid},
  uPedidosExpedicao in 'dfmpas2\uPedidosExpedicao.pas' {FrmExpedicaoPedidos},
  uEtiquetasProdutos in 'dfmpas2\uEtiquetasProdutos.pas' {FrmEtiquetasProdutos},
  uEtiquetasExpedicao2 in 'dfmpas2\uEtiquetasExpedicao2.pas' {FrmEtiquetasExpedicao2},
  uEtiquetasEntrada in 'dfmpas2\uEtiquetasEntrada.pas' {FrmEtiquetasEntrada},
  Almox0001 in 'dfmpas2\Almox0001.pas' {FormCadAlmox},
  EMAIL0001 in 'dfmpas2\EMAIL0001.pas' {frmEMAIL0001},
  CustomSettings in 'infosaga\CustomSettings.pas',
  MemoForm in 'infosaga\MemoForm.pas' {frmMemo},
  InsereRateioCustoForm in 'dfmpas2\InsereRateioCustoForm.pas' {frmInsereRateioCusto},
  Email0000 in 'dfmpas2\Email0000.pas' {FrmEmail},
  Balanco in 'dfmpas2\Balanco.pas' {FormBalanco},
  PRD0011 in 'dfmpas2\PRD0011.pas' {FrmSincronizarSaldo},
  uEtiquetasExpedicao in 'dfmpas2\uEtiquetasExpedicao.pas' {FrmEtiquetasExpedicao},
  uEtqFaturamento in 'dfmpas2\uEtqFaturamento.pas' {frmEtqFaturamento},
  InsereRateioColaboradorForm in 'dfmpas2\InsereRateioColaboradorForm.pas' {frmInsereRateioColaborador},
  cnab0002 in 'dfmpas2\cnab0002.pas' {FrmRetornoCNAB},
  uGiroDoEstoque in 'dfmpas2\uGiroDoEstoque.pas' {FrmGiroDoEstoquexCompras},
  ConsultaEstruturaForm in 'dfmpas2\ConsultaEstruturaForm.pas' {frmConsultaEstrutura},
  UBarra in 'dfmpas2\UBarra.pas' {frmBarra},
  Animacao in 'dfmpas2\Animacao.pas' {fmAnimacao},
  UContaCorrenteCredito in 'dfmpas2\UContaCorrenteCredito.pas' {fmContaCorrenteCredito},
  UPesqContaCorrenteCredito in 'dfmpas2\UPesqContaCorrenteCredito.pas' {fmPesqContaCorrenteCredito},
  UPesqEquip in 'dfmpas2\UPesqEquip.pas' {fmPesqEquip},
  UEquip in 'dfmpas2\UEquip.pas' {fmEquip},
  UPesqOcorrencia in 'dfmpas2\UPesqOcorrencia.pas' {fmPesqOcorrencia},
  UOcorrencia in 'dfmpas2\UOcorrencia.pas' {fmOcorrencia},
  UOPERACOES in 'dfmpas2\UOPERACOES.pas' {fmOperacoes},
  UPesqColaborador in 'dfmpas2\UPesqColaborador.pas' {fmPesqColaborador},
  EtiqGerenciador in 'dfmpas2\EtiqGerenciador.pas' {FrmGerenciadorEtiquetas},
  Cli0001 in 'dfmpas2\Cli0001.pas' {FormCliente},
  UColaborador in 'dfmpas2\UColaborador.pas' {FmColaborador},
  UPesqOperacoes in 'dfmpas2\UPesqOperacoes.pas' {fmPesqOperacoes},
  PesqPedidoGrade in 'dfmpas2\PesqPedidoGrade.pas' {FrmPesquisaPedidoGrade},
  uEspecificacao in 'dfmpas2\uEspecificacao.pas' {fmEspecificacao},
  uEngenhariaProcesso in 'dfmpas2\uEngenhariaProcesso.pas' {fmEngenhariaProcesso},
  frmApontamentoFab in 'dfmpas2\frmApontamentoFab.pas' {frmApontamento},
  uapontar in 'dfmpas2\uapontar.pas' {frmApontarProcessos},
  FrmEventoOcorrencia in 'dfmpas2\FrmEventoOcorrencia.pas' {FrmEventoOcorrencias},
  MonOperacoes in 'dfmpas2\MonOperacoes.pas' {frmMonitorOperacoes},
  nfse_principal in 'dfmpas2\nfse_principal.pas' {frmNfse},
  UPesqServico in 'dfmpas2\UPesqServico.pas' {frmPesqServico},
  UServico in 'dfmpas2\UServico.pas' {frmItemServico},
  uCnae in 'dfmpas2\uCnae.pas' {FormCnae},
  copiarEngenharia in 'dfmpas2\copiarEngenharia.pas' {frmCopiarEngenharia},
  ConsultarCNPJ in 'dfmpas2\ConsultarCNPJ.pas' {FrmConsultarCNPJ},
  uHistoricoExpedicao in 'dfmpas2\uHistoricoExpedicao.pas' {frmHistoricoExpedicao},
  importCliente in 'dfmpas2\importCliente.pas' {FormImpCliente},
  Nfe40_main in 'dfmpas2\Nfe40_main.pas' {frmNfe40},
  importProduto in 'dfmpas2\importProduto.pas' {frmImporProduto},
  NfeInutilizar in 'dfmpas2\NfeInutilizar.pas' {FrmInutilizar},
  uProcessarNF in 'dfmpas2\uProcessarNF.pas' {frmProcessaNFe},
  UPedidoDoacao in 'dfmpas2\UPedidoDoacao.pas' {frmPedidoDoacao},
  UPedidoPesqDoacao in 'dfmpas2\UPedidoPesqDoacao.pas' {frmPesqDoacao},
  CartaCorrecaoNFe in 'dfmpas2\CartaCorrecaoNFe.pas' {FrmCartaNfe},
  uJustificativa in 'dfmpas2\uJustificativa.pas' {frmjustificativa},
  RWFunc in 'dfmpas2\RWFunc.pas',
  PesqVendaPerdida in 'dfmpas2\PesqVendaPerdida.pas' {frmVendaPerdidas},
  PesqCodigoOriginal in 'dfmpas2\PesqCodigoOriginal.pas' {frmPesqCodOriginal},
  Fat0000 in 'dfmpas2\Fat0000.pas' {FormFaturamento},
  CteXML in 'dfmpas2\CteXML.pas' {frmCte},
  ctexmlopcao in 'dfmpas2\ctexmlopcao.pas' {frmCtexmlopcao},
  PesqCTe in 'dfmpas2\PesqCTe.pas' {frmPesqCTE},
  uPesqTarefas in 'dfmpas2\uPesqTarefas.pas' {PesqTarefas},
  uFrmTarefas in 'dfmpas2\uFrmTarefas.pas' {frmTarefas},
  uPesqRenovacao in 'dfmpas2\uPesqRenovacao.pas' {FrmPesqRenovacao},
  uRenovacao in 'dfmpas2\uRenovacao.pas' {FrmRenovar},
  uimportFornecedor in 'dfmpas2\uimportFornecedor.pas' {FrmImportarFornecedor},
  usobre in 'dfmpas2\usobre.pas' {frmSobre},
  uDetalheFluxo in 'dfmpas2\uDetalheFluxo.pas' {frmDetalheFluxo},
  uAlterarFaturaParcela in 'dfmpas2\uAlterarFaturaParcela.pas' {formParcelaFatura},
  uFiltroExportarExcel in 'dfmpas2\uFiltroExportarExcel.pas' {frmFiltroExportar},
  uPesqInadimplencia in 'dfmpas2\uPesqInadimplencia.pas' {frmPesquisaInadimplencia},
  uDetalheInadimplencia in 'dfmpas2\uDetalheInadimplencia.pas' {frmDetalheInadimplenciaCliente},
  uDetSaldoFluxo in 'dfmpas2\uDetSaldoFluxo.pas' {frmDetSaldoFluxo},
  uPesqTurno in 'dfmpas2\uPesqTurno.pas' {frmPesqTurnos},
  uTurno in 'dfmpas2\uTurno.pas' {frmTurnos},
  BaseFormFDAC in 'infosaga\BaseFormFDAC.pas' {frmBasefdac},
  BaseDBFormFdac in 'infosaga\BaseDBFormFdac.pas' {frmBaseDBFDAC},
  BaseDBPesquisaFDAC in 'infosaga\BaseDBPesquisaFDAC.pas' {frmBaseDBPesquisaFDAC},
  UPesqOrcamentoPRO in 'dfmpas2\UPesqOrcamentoPRO.pas' {PesqOrcamentoProducao},
  BaseDBEditFormFDAC in 'infosaga\BaseDBEditFormFDAC.pas' {frmBaseDBEditFDAC},
  uEditOrcamentoPRO in 'dfmpas2\uEditOrcamentoPRO.pas' {FrmEditOrcamentoPRO},
  uOrcamentoItemPro in 'dfmpas2\uOrcamentoItemPro.pas' {frmitemOrcamento},
  BaseDBEditDetailFDAC in 'infosaga\BaseDBEditDetailFDAC.pas' {frmBaseDBEditDetailFDAC},
  uPesqServicoPRO in 'dfmpas2\uPesqServicoPRO.pas' {frmServicos},
  uEditServicoPro in 'dfmpas2\uEditServicoPro.pas' {frmEditServico},
  uPesqFormaPrecos in 'dfmpas2\uPesqFormaPrecos.pas' {frmFormacaoPreco},
  uEditCustoPro in 'dfmpas2\uEditCustoPro.pas' {frmCustoMesAno},
  uPesqProcessos in 'dfmpas2\uPesqProcessos.pas' {frmPesqProcessos},
  uEditProcessos in 'dfmpas2\uEditProcessos.pas' {frmEditProcessos},
  uSimulacaoPrecoServico in 'dfmpas2\uSimulacaoPrecoServico.pas' {frmSimularPrecoServicos},
  ExportProdutoImport in 'dfmpas2\ExportProdutoImport.pas' {frmExportProdutoImportLeiaute},
  uPesqCreditoFatura in 'dfmpas2\uPesqCreditoFatura.pas' {frmPesqcreditoFatura},
  uedParamQualidade in 'dfmpas2\uedParamQualidade.pas' {frmParametrosQualidade},
  uASCii in 'dfmpas2\uASCii.pas' {frmAscII},
  uQualidadeProducao in 'dfmpas2\uQualidadeProducao.pas' {frmQualidadeOperacao},
  uPesqpcp in 'dfmpas2\uPesqpcp.pas' {frmPCP},
  PesqApontamentos in 'dfmpas2\PesqApontamentos.pas' {frmApontamentosCargas},
  uPesqPedidoIndus in 'dfmpas2\uPesqPedidoIndus.pas' {frmPedidoIndustrializacao},
  uPivotCliente in 'dfmpas2\uPivotCliente.pas' {frmBasePivotFDAC},
  uIncApontaIndustrial in 'dfmpas2\uIncApontaIndustrial.pas' {frmApontamentoIndustrial},
  uExpSeparacao in 'dfmpas2\uExpSeparacao.pas' {frmExpSeparacao},
  uPosicaoEstoque in 'dfmpas2\uPosicaoEstoque.pas' {frmPosicaoEstoque},
  uPesqEmpresa in 'dfmpas2\uPesqEmpresa.pas' {frmPesqEmpresa},
  uTransfTitulos in 'dfmpas2\uTransfTitulos.pas' {frmTransfTitulo},
  uPesqOCP in 'dfmpas2\uPesqOCP.pas' {frmPesqOCP},
  uUndTributaria in 'dfmpas2\uUndTributaria.pas' {frmUndTributaria},
  uPesqISSMunicipio in 'dfmpas2\uPesqISSMunicipio.pas' {frmIssMunicipios},
  uEditISS_Municipio in 'dfmpas2\uEditISS_Municipio.pas' {frmEditISS_Municipio},
  uparamResultado in 'dfmpas2\uparamResultado.pas' {frmParamResultados},
  uResultadoInspecao in 'dfmpas2\uResultadoInspecao.pas' {frmResultadoInspecao},
  uGerarCarga in 'dfmpas2\uGerarCarga.pas' {frmGerarCarga},
  uMercosAtualizacao in 'dfmpas2\uMercosAtualizacao.pas' {frmAtualizaMercos},
  ClasseCliente in 'restful\ClasseCliente.pas',
  ClassePedido in 'restful\ClassePedido.pas',
  ClasseProdutos in 'restful\ClasseProdutos.pas',
  ClasseFaturamento in 'restful\ClasseFaturamento.pas',
  ClasseTabelaPrecos in 'restful\ClasseTabelaPrecos.pas',
  ClasseVendedor in 'restful\ClasseVendedor.pas',
  uPesqCodigoOriginalFabricante in 'dfmpas2\uPesqCodigoOriginalFabricante.pas' {frmCodOriginalFabricante},
  BaseDBPesquisaGerarFDAC in 'dfmpas2\BaseDBPesquisaGerarFDAC.pas' {FrmBaseDBPesquisaGeraFDAC},
  uDashboradCom in 'dfmpas2\uDashboradCom.pas' {frmDashBoardComecialFin},
  uPesqCliOrigem in 'dfmpas2\uPesqCliOrigem.pas' {frmPesqOrigemCliente},
  uClienteOrigem in 'dfmpas2\uClienteOrigem.pas' {frmClieOrigem},
  PesqTipoProduto in 'dfmpas2\PesqTipoProduto.pas' {frmPesqTipoProduto},
  uK280 in 'dfmpas2\uK280.pas' {frmK280},
  PesqUnidade in 'dfmpas2\PesqUnidade.pas' {frmCadUnidadeMedida},
  uUnidade in 'dfmpas2\uUnidade.pas' {frmEditUnidade},
  uAprovarPag in 'dfmpas2\uAprovarPag.pas' {frmAprovarPagamento},
  uPesqChaveRefer in 'dfmpas2\uPesqChaveRefer.pas' {frmPesqChaveRefer},
  uDemandaProducao in 'dfmpas2\uDemandaProducao.pas' {frmDemandaProducao},
  uProducaoDAO in 'dfmpas2\uProducaoDAO.pas' {ProducaoDao},
  uGerenciamentoPCP in 'dfmpas2\uGerenciamentoPCP.pas' {frmGerenciamentoPCP},
  uSelProduto in 'dfmpas2\uSelProduto.pas' {frmSelecaoProduto},
  uEmpenharLote in 'dfmpas2\uEmpenharLote.pas' {frmEmpenharLote},
  uConclusaoOP in 'dfmpas2\uConclusaoOP.pas' {frmConclusaoOP},
  uNovoAponta in 'dfmpas2\uNovoAponta.pas' {frmNovoApontamento},
  uEstruturaFicha in 'dfmpas2\uEstruturaFicha.pas' {frmEstruturaFicha},
  uOdemProgramacao in 'dfmpas2\uOdemProgramacao.pas' {frmOrdemProgramacao},
  uConfirmaDemanda in 'dfmpas2\uConfirmaDemanda.pas' {frmConfirmaDemanda},
  uVinculandoServico in 'dfmpas2\uVinculandoServico.pas' {frmVinculandoServico},
  uPrevisaoCompras in 'dfmpas2\uPrevisaoCompras.pas' {FrmPrevisaoCompras},
  uEnvaseProdutos in 'dfmpas2\uEnvaseProdutos.pas' {frmEnvaseProdutos},
  uEnvasar in 'dfmpas2\uEnvasar.pas' {frmExecutarEnvase},
  frmPesqLote in 'dfmpas2\frmPesqLote.pas' {frmPesqSelecaoLote},
  uProducaoSemPedido in 'dfmpas2\uProducaoSemPedido.pas' {frmProdutoSemPedido},
  uPesqArtefato in 'dfmpas2\uPesqArtefato.pas' {frmPesqArtefato},
  uArtefatoEdit in 'dfmpas2\uArtefatoEdit.pas' {frmArtefato},
  uPesqArame in 'dfmpas2\uPesqArame.pas' {frmPesqArame},
  uArameEdit in 'dfmpas2\uArameEdit.pas' {frmArameEdit},
  uPesqClassificacao in 'dfmpas2\uPesqClassificacao.pas' {frmPesqClassificacao},
  uClassificacaoEdit in 'dfmpas2\uClassificacaoEdit.pas' {frmClassificacao},
  uGanchoEdit in 'dfmpas2\uGanchoEdit.pas' {frmGanchoEdit},
  uPesqGancho in 'dfmpas2\uPesqGancho.pas' {frmPesqGancho},
  uAcabamentoSupEdit in 'dfmpas2\uAcabamentoSupEdit.pas' {frmAcabamentoSuperEdit},
  uPesqAcabamentoSup in 'dfmpas2\uPesqAcabamentoSup.pas' {frmPesqAcabamentoSup},
  PesqCores in 'dfmpas2\PesqCores.pas' {frmPesqCores},
  uCoresEdit in 'dfmpas2\uCoresEdit.pas' {frmCoresEdit},
  uTratamentoEDIT in 'dfmpas2\uTratamentoEDIT.pas' {frmTratamentoEdit},
  uPesqTratamento in 'dfmpas2\uPesqTratamento.pas' {frmPesqTratamento},
  uTipoMolaEdit in 'dfmpas2\uTipoMolaEdit.pas' {frmTipoMola},
  uPesqTipoMola in 'dfmpas2\uPesqTipoMola.pas' {frmPesqTipoMola},
  uInfLote in 'dfmpas2\uInfLote.pas' {frmInfLotePrd},
  uNovaEtiquetaEntradas in 'dfmpas2\uNovaEtiquetaEntradas.pas' {frmNovaEtiquetaEntrada},
  uPesqParametrosDaQualidade in 'dfmpas2\uPesqParametrosDaQualidade.pas' {frmPesqParametrosDaQualidade},
  uCadParametrosDaQualidade in 'dfmpas2\uCadParametrosDaQualidade.pas' {frmCadParametrosDaQualidade},
  uControleDeQualidade in 'dfmpas2\uControleDeQualidade.pas' {frmControleDeQualidade},
  uCadControleDeQualidade in 'dfmpas2\uCadControleDeQualidade.pas' {frmCadControleDeQualidade},
  uPesqSetor in 'dfmpas2\uPesqSetor.pas' {frmPesquisaSetor},
  USetor in 'dfmpas2\USetor.pas' {fmSetor},
  uPesqTipoEmbalagem in 'dfmpas2\uPesqTipoEmbalagem.pas' {frmPesquisaTipoEmbalagem},
  UTipoEmbalagem in 'dfmpas2\UTipoEmbalagem.pas' {fmTipoEmbalagem},
  CustoFabricaCentroCusto in 'dfmpas2\CustoFabricaCentroCusto.pas' {frmCustoFabricaCentroCusto},
  uRentabilidadeOS in 'dfmpas2\uRentabilidadeOS.pas' {frmRentabilidadeOS},
  uCopiaUsuario in 'dfmpas2\uCopiaUsuario.pas' {frmCopiaUsuario},
  uNovoApontamentoImprime in 'dfmpas2\uNovoApontamentoImprime.pas' {frmNovoApontamentoImprime},
  uControleNFIndustrializacao in 'dfmpas2\uControleNFIndustrializacao.pas' {frmControleNFIndustrializacao},
  uSolicitacaoCompra in 'dfmpas2\uSolicitacaoCompra.pas' {frmSolicitacaoCompra},
  uSolicitacaoCompraCadastro in 'dfmpas2\uSolicitacaoCompraCadastro.pas' {frmSolicitacaoCompraCadastro},
  uIndustrializacaoPorKit in 'dfmpas2\uIndustrializacaoPorKit.pas' {FrmIndustrializacaoPorKit},
  uDataSimples in 'dfmpas2\uDataSimples.pas' {frmDataSimples},
  uXMLSCOAManaus in 'dfmpas2\uXMLSCOAManaus.pas' {frmXMLSCOAManaus},
  uProgramacaoProcessoFabricacao in 'dfmpas2\uProgramacaoProcessoFabricacao.pas' {frmProgramacaoProcessoFabricacao},
  uPesquisaOperacaoProcessoFabricacao in 'dfmpas2\uPesquisaOperacaoProcessoFabricacao.pas' {frmPesquisaOperacaoProcessoFabricacao},
  uModificacaoOperacaoProcessoFabricacao in 'dfmpas2\uModificacaoOperacaoProcessoFabricacao.pas' {frmModificacaoOperacaoProcessoFabricacao},
  UCotacaoPesquisa in 'dfmpas2\UCotacaoPesquisa.pas' {frmCotacaoPesquisa},
  uCotacaoCadastro in 'dfmpas2\uCotacaoCadastro.pas' {frmCotacaoCadastro},
  uCotacaoAutorizacao in 'dfmpas2\uCotacaoAutorizacao.pas' {frmCotacaoAutorizacao},
  uCotacaoFornecedor in 'dfmpas2\uCotacaoFornecedor.pas' {frmCotacaoFornecedor},
  uSelecionaCentroDeCusto in 'dfmpas2\uSelecionaCentroDeCusto.pas' {frmSelecionaCentroDeCusto},
  uRegularizacaoEstoque in 'dfmpas2\uRegularizacaoEstoque.pas' {frmRegularizacaoEstoque},
  uRegularizacaoEstoquePesq in 'dfmpas2\uRegularizacaoEstoquePesq.pas' {frmRegularizacaoEstoquePesq},
  uAutorizaPedidoAbaixoMinimo in 'dfmpas2\uAutorizaPedidoAbaixoMinimo.pas' {frmAutorizaPedidoAbaixoMinimo},
  uRequisicaoMaterial in 'dfmpas2\uRequisicaoMaterial.pas' {frmRequisicaoMaterial},
  uRequisicaoMaterialPesq in 'dfmpas2\uRequisicaoMaterialPesq.pas' {frmRequisicaoMaterialPesq},
  uRequisicaoMaterialAutorizacao in 'dfmpas2\uRequisicaoMaterialAutorizacao.pas' {frmRequisicaoMaterialAutorizacao},
  uRequisicaoMaterialCadastraItem in 'dfmpas2\uRequisicaoMaterialCadastraItem.pas' {frmRequisicaoMaterialCadastraItem},
  uEtiquetaFinalizacaoProcesso in 'dfmpas2\uEtiquetaFinalizacaoProcesso.pas' {frmEtiquetaFinalizacaoProcesso},
  uDadosEtiquetaPallet in 'dfmpas2\uDadosEtiquetaPallet.pas' {frmDadosEtiquetaPallet},
  uPCPObservacaoIOP in 'dfmpas2\uPCPObservacaoIOP.pas' {frmPCPObservacaoIOP},
  uCadastroNaturezaContaContabil in 'dfmpas2\uCadastroNaturezaContaContabil.pas' {FrmCadastroNaturezaContaContabil},
  uIndustrializacaoNotaObs in 'dfmpas2\uIndustrializacaoNotaObs.pas' {frmIndustrializacaoNotaObs},
  uPesqRequisicaoMaterialOri in 'dfmpas2\uPesqRequisicaoMaterialOri.pas' {frmPesqRequisicaoMaterialOri},
  URequisicaoMaterialOri in 'dfmpas2\URequisicaoMaterialOri.pas' {frmRequisicaoMaterialOri},
  uPesqCapacidade in 'dfmpas2\uPesqCapacidade.pas' {frmPesqCapacidade},
  uCapacidade in 'dfmpas2\uCapacidade.pas' {frmCapacidade},
  uFinanceiroConciliacaoLancamentoPagarReceber in 'dfmpas2\uFinanceiroConciliacaoLancamentoPagarReceber.pas' {frmFinanceiroConciliacaoLancamentoPagarReceber},
  uInfoComplFichaTecnica in 'dfmpas2\uInfoComplFichaTecnica.pas' {frmInfoComplFichaTecnica},
  uContasReceberAgrupa in 'dfmpas2\uContasReceberAgrupa.pas' {formContasReceberAgrupa},
  uEmpresaMailAlias in 'dfmpas2\uEmpresaMailAlias.pas' {frmEmpresaMailAlias},
  uFinanceiroConciliacaoTransferenciaManutencao in 'dfmpas2\uFinanceiroConciliacaoTransferenciaManutencao.pas' {frmFinanceiroConciliacaoTransferenciaManutencao},
  uFinanceiroConciliacaoTransferenciaManutencaoHistorico in 'dfmpas2\uFinanceiroConciliacaoTransferenciaManutencaoHistorico.pas' {frmFinanceiroConciliacaoTransferenciaManutencaoHistorico},
  uEnfIndustrializacoEnviaDemanda in 'dfmpas2\uEnfIndustrializacoEnviaDemanda.pas' {frmEnfIndustrializacoEnviaDemanda},
  uPCPInformaFornecedor in 'dfmpas2\uPCPInformaFornecedor.pas' {frmPCPInformaFornecedor},
  uEnfIndustrializacoSelecionaCor in 'dfmpas2\uEnfIndustrializacoSelecionaCor.pas' {frmEnfIndustrializacoSelecionaCor},
  uFichaConteudoImportacao in 'dfmpas2\uFichaConteudoImportacao.pas' {frmFichaConteudoImportacao},
  uVinculacaoCoresRetorno in 'dfmpas2\uVinculacaoCoresRetorno.pas' {frmVinculacaoCoresRetorno},
  uHistoricoEmail in 'dfmpas2\uHistoricoEmail.pas' {frmHistoricoEmail},
  uEmpresaExportacao in 'dfmpas2\uEmpresaExportacao.pas' {frmEmpresaExportacao},
  uMolaToleranciaDiametroMedio in 'dfmpas2\uMolaToleranciaDiametroMedio.pas' {frmMolaToleranciaDiametroMedio},
  uDevolucaoNotaEntrada in 'dfmpas2\uDevolucaoNotaEntrada.pas' {frmDevolucaoNotaEntrada},
  uSelecinaCFOP in 'dfmpas2\uSelecinaCFOP.pas' {frmSelecionaCFOP},
  uSelecionaAlmoxarifado in 'dfmpas2\uSelecionaAlmoxarifado.pas' {frmSelecionaAlmoxarifado};

{$R *.res}
{$D+}

procedure SetAsMainForm(aForm:TForm);
var P:Pointer;
begin
     Application.MainFormOnTaskBar := False;
     try
        P := @Application.Mainform;
        Pointer(P^) := aForm;
        aForm.Show;
     finally
            Application.MainFormOnTaskBar := True;
     end;
end;


begin
if InicioDb.SplashStart( True ) then
begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TDataCadastros, DataCadastros);
  Application.CreateForm(TDataCadastros1, DataCadastros1);
  Application.CreateForm(TDataMovimento, DataMovimento);
  Application.CreateForm(TDataMovimento2, DataMovimento2);
  Application.CreateForm(TDmProducao, DmProducao);
  Application.CreateForm(TDmCfg, DmCfg);
  Application.CreateForm(TFrmMenu, FrmMenu);
  if dbInicio.ModulosComoAplicacao then
  begin
     Application.CreateForm(TfrmBaseDBFDAC, frmBaseDBFDAC);
      if dbInicio.modulo.ToUpper='CLIENTES' then
      BEGIN
           Application.Title:='Clientes';
           Application.CreateForm(tFormCliente, FormCliente);
           SetAsMainForm(FormCliente);
      END
      Else
      if dbInicio.modulo.ToUpper='PRODUTOS' then
      BEGIN
           Application.Title:='Produtos';
           Application.CreateForm(tFormProduto, FormProduto);
           SetAsMainForm(FormProduto);
      END
      Else
      if dbInicio.modulo.ToUpper='PEDIDOS' then
      BEGIN
           Application.Title:='Pedidos';
           Application.CreateForm(tFrmPedido,FrmPedido);
           SetAsMainForm(FrmPedido);
      END
      Else
      if dbInicio.modulo.ToUpper='FATURAMENTO' then
      BEGIN
           Application.Title:='Faturamento';
           Application.CreateForm(tFormFaturamento,FormFaturamento);
           SetAsMainForm(FormFaturamento);
      END
      Else
          FrmMenu.ShowModal ;
      Application.Run;
  end
  Else
  begin
    Application.CreateForm(TfrmBaseDBFDAC, frmBaseDBFDAC);
    FrmMenu.ShowModal ;
    Application.Run;
  end;
     end
     Else
         Freeandnil( dbInicio );

end.

