/******************************************************************************/
/***          Generated by IBExpert 2012.02.21 03/07/2020 13:34:37          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;

CREATE DATABASE 'C:\Jobdados\exemplo\EXEMPLO.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 4096
DEFAULT CHARACTER SET NONE;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE ENF_IT01 (
    ENF_REGISTRO                INTEGER NOT NULL,
    ENF_IT_NOTANUMBER           VARCHAR(10) NOT NULL,
    OCP_CODIGO                  VARCHAR(6) NOT NULL,
    PRD_REFER                   VARCHAR(20) CHARACTER SET WIN1252 COLLATE WIN_PTBR,
    PRD_DESCRI                  VARCHAR(80) CHARACTER SET WIN1252 COLLATE WIN_PTBR,
    ENF_QTDE                    DECIMAL6,
    ENF_QTDE_LANCADO_PROJETO    DECIMAL6,
    ENF_QTDE_PEDIDO_COMPRA      DECIMAL6,
    OCI_REGISTRO                INTEGER,
    ENF_PRECO                   DECIMAL5,
    ENF_CUSTO                   DECIMAL6,
    ENF_IPIALIQ                 DECIMAL6,
    ENF_ICMSALIQ                DECIMAL6,
    ENF_VLSUBST                 DECIMAL6,
    FOR_CODIGO                  VARCHAR(4),
    AMX_CODIGO                  VARCHAR(4),
    EMP_CODIGO                  VARCHAR(3),
    ENF_UNIDADE_TRABALHO        DECIMAL6,
    ENF_LOTE                    VARCHAR(15) CHARACTER SET WIN1252 COLLATE WIN_PTBR,
    PRD_CODIGO                  VARCHAR(6),
    ENF_ICMS                    DECIMAL6,
    ENF_CFOP                    VARCHAR(4),
    ENF_IT_VLIPI                DECIMAL6,
    ENF_IT_BASEIPI              DECIMAL6,
    ENF_IT_NUM_DI               DECIMAL6,
    ENF_IT_NCM                  INTEGER,
    ENF_IT_DESCTO               DECIMAL6,
    ENF_IT_BASEICMS             DECIMAL6,
    ENF_IT_BASESUBTRIB          DECIMAL6,
    ENF_IT_VALFRETE             DECIMAL6,
    ENF_IT_VLSEGURO             DECIMAL6,
    ENF_IT_VLDESP_ACES          DECIMAL6,
    ENF_IT_VLSUBTRIB            DECIMAL6,
    ENF_IT_ALIQSUBTRIB          DECIMAL6,
    ENF_IT_ISSQN                DECIMAL6,
    ENF_IT_ALIQISSQN            DECIMAL6,
    ENF_IT_VLISSQN              DECIMAL6,
    ENF_IT_ALIQPIS              DECIMAL6,
    ENF_IT_VLPIS                DECIMAL6,
    ENF_IT_ALIQCOFINS           DECIMAL6,
    ENF_IT_VLCOFINS             DECIMAL6,
    ENF_CST_PIS                 DECIMAL6,
    ENF_BASEPIS                 DECIMAL6,
    ENF_CST_COFINS              DECIMAL6,
    ENF_BASECOFINS              DECIMAL6,
    USU_CODIGO                  INTEGER,
    PRF_REGISTRO                INTEGER,
    REPETICAO_REFER             INTEGER,
    STB_TRIBUTACAO              VARCHAR(3),
    CST_PIS                     VARCHAR(3),
    CST_COFINS                  VARCHAR(3),
    CST_IPI                     VARCHAR(3),
    ENF_ATUALIZA_PRECO          VARCHAR(1),
    ENF_ATUALIZA_ESTOQUE        VARCHAR(1),
    PRDL_REGISTRO               INTEGER,
    ENF_QUANTIDADE_IND_RETORNO  DECIMAL6,
    ITT_REGISTRO                INTEGER,
    ENF_OBS_INDUSTRIALIZACAO    BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    ENF_PESO_ENTRADA            DECIMAL6,
    OPE_CODIGO                  VARCHAR(3),
    ENF_UCOM                    VARCHAR(5),
    ENF_UTRIB                   VARCHAR(5),
    ENF_PRECO_ORIGINAL          NUMERIC(18,5),
    ENF_QTDE_ORIGINAL           NUMERIC(18,5),
    ENF_PTOTAL_ORIGINAL         NUMERIC(18,5),
    ENF_PERC_FCP_ST             NUMERIC(6,2),
    ENF_VALOR_FCP_ST            NUMERIC(15,4),
    ENF_BASE_FCP_ST             NUMERIC(15,4)
);

CREATE TABLE ENF0001 (
    ENF_REGISTRO              INTEGER NOT NULL,
    ENF_NOTANUMBER            VARCHAR(10),
    ENF_MODELO_NF             VARCHAR(2),
    ENF_SERIE                 VARCHAR(3),
    OPV_CODIGO                INTEGER,
    ENF_EMISSAO               DATE,
    ENF_ENTRADA               DATE,
    PCL_CODIGO                VARCHAR(3),
    OPE_CODIGO                VARCHAR(3),
    OPE_NATUREZA              VARCHAR(4),
    OCP_CODIGO                VARCHAR(6),
    FOR_CODIGO                VARCHAR(4),
    AMX_CODIGO                VARCHAR(3),
    CCT_CODIGO                VARCHAR(3),
    ENF_TIPO_FRETE            INTEGER,
    ENF_VLFRETE               DECIMAL6,
    ENF_VLSEGURO              DECIMAL6,
    ENF_DESP_ACES             DECIMAL6,
    ENF_ALIQ_ICMS             DECIMAL6,
    ENF_BASEICMS              DECIMAL6,
    ENF_VL_ICMS               DECIMAL6,
    ENF_VLBASESUBTRIB         DECIMAL6,
    ENF_VL_SUBTRIB            DECIMAL6,
    ENF_TOT_CSUB              DECIMAL6,
    ENF_TOT_PROD              DECIMAL6,
    ENF_TOT_NOTA              DECIMAL6,
    ENF_VL_IPI                DECIMAL6,
    ENF_BASE_IPI              DECIMAL6,
    ENF_VL_DESCTO             DECIMAL6,
    ENF_OBS_NOTA              VARCHAR(120) CHARACTER SET WIN1252 COLLATE WIN_PTBR,
    ENF_INTERNO               VARCHAR(1),
    ENF_CANCELADA             VARCHAR(1),
    ENF_TIPO_NF_ENTRADA       VARCHAR(1),
    EMP_CODIGO                VARCHAR(3),
    ENF_CHAVE_NFE             VARCHAR(60) CHARACTER SET WIN1252 COLLATE WIN_PTBR,
    ENF_VLPIS                 DECIMAL6,
    ENF_VLCOFINS              DECIMAL6,
    ENF_ALIQCOFINS            DECIMAL6,
    ENF_ALIQPIS               DECIMAL6,
    ENF_CHAVE_NFESE           CHAR(60) CHARACTER SET WIN1252 COLLATE WIN_PTBR,
    ENF_DADOS_ADICIONAIS      BLOB SUB_TYPE 1 SEGMENT SIZE 2048,
    ENF_FECHADO_PROJETO_OBRA  CHAR(1) DEFAULT 'N',
    ENF_FRETEPARTICIPATOT     VARCHAR(1),
    SMDF_REGISTRO             INTEGER,
    ENF_XML                   BLOB SUB_TYPE 0 SEGMENT SIZE 80,
    PCX_CODIGO                VARCHAR(3),
    ENF_INDUSTRIALIZACAO      VARCHAR(1) DEFAULT 'N',
    ENF_ATUALIZA_ESTOQUE      VARCHAR(1),
    ENF_MODALIDADE            VARCHAR(1),
    ENF_VLFRETEPORFORA        NUMERIC(18,5),
    ENF_VLRDIFICMS            NUMERIC(18,5),
    ENF_VLOUTROS              NUMERIC(18,5)
);



/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE ENF0001 ADD CONSTRAINT PK_ENF0001 PRIMARY KEY (ENF_REGISTRO);
ALTER TABLE ENF_IT01 ADD CONSTRAINT PK_ENF_IT01 PRIMARY KEY (ENF_REGISTRO);


/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE INDEX ENF0001_IDX1 ON ENF0001 (ENF_NOTANUMBER);
CREATE INDEX ENF0001_IDX2 ON ENF0001 (ENF_ENTRADA);
CREATE INDEX ENF_IT01_IDX1 ON ENF_IT01 (PRD_REFER);
CREATE INDEX ENF_IT01_IDX2 ON ENF_IT01 (OCP_CODIGO);
CREATE INDEX ENF_IT01_IDX3 ON ENF_IT01 (ENF_IT_NOTANUMBER);
CREATE INDEX ENF_IT01_IDX4 ON ENF_IT01 (PRD_CODIGO);


/******************************************************************************/
/***                              Descriptions                              ***/
/******************************************************************************/

DESCRIBE TABLE ENF0001
'NOTA DE ENTRADA';

DESCRIBE TABLE ENF_IT01
'ITEM DA NOTA ENTRADA';



/******************************************************************************/
/***                          Fields descriptions                           ***/
/******************************************************************************/

DESCRIBE FIELD ENF_MODELO_NF TABLE ENF0001
'MODELO DA NOTA FISCAL';

DESCRIBE FIELD ENF_SERIE TABLE ENF0001
'SERIE DA NOTA';

DESCRIBE FIELD ENF_EMISSAO TABLE ENF0001
'EMISSAO DA NOTA FISCAL';

DESCRIBE FIELD ENF_ENTRADA TABLE ENF0001
'DATA DE ENTRADA';

DESCRIBE FIELD PCL_CODIGO TABLE ENF0001
'REFERENCIA DE PRAZO DE PAGAMENTO';

DESCRIBE FIELD OPE_CODIGO TABLE ENF0001
'CHAVE REFERENCIA DA OPERACAO FISCAL (OPE0000)';

DESCRIBE FIELD OPE_NATUREZA TABLE ENF0001
'CFOP DA OPERACAO FISCAL';

DESCRIBE FIELD FOR_CODIGO TABLE ENF0001
'REFERENCIA DO CADASTRO DE FORNECEDORES';

DESCRIBE FIELD CCT_CODIGO TABLE ENF0001
'CODIGO DA CONTA CONTABIL';

DESCRIBE FIELD ENF_TIPO_FRETE TABLE ENF0001
'Modalidade do Frete = 0 = Outros
                      1 = CIF
                      2 = FOB';

DESCRIBE FIELD ENF_VLFRETE TABLE ENF0001
'VALOR DO FRETE VINDO NA NOTA';

DESCRIBE FIELD ENF_TIPO_NF_ENTRADA TABLE ENF0001
'ENF_TIPO_NF_ENTRADA = (N = Nota Normal)
                      (C = Nota de conhecimento de transporte)';

DESCRIBE FIELD EMP_CODIGO TABLE ENF0001
'CHAVE REFERENCIA DA TABELA EMPRESA (EMP0000)';

DESCRIBE FIELD SMDF_REGISTRO TABLE ENF0001
'registro do modelo de documento fiscal';

DESCRIBE FIELD ENF_XML TABLE ENF0001
'XML DA NOTA';

DESCRIBE FIELD PCX_CODIGO TABLE ENF0001
'CODIGO DO CENTRO DE CUSTO';

DESCRIBE FIELD ENF_ATUALIZA_ESTOQUE TABLE ENF0001
'NOTA ATUALIZA ESTOQUE';

