program NFE2;

uses
  Forms,
  dialogs,
  MidasLib,
  BaseForm in 'C:\Delphi\Componentes\06-infosaga_desktop\BaseForm.pas' {frmBase},
  BaseReportForm in 'C:\Delphi\Componentes\06-infosaga_desktop\BaseReportForm.pas' {frmBaseReport},
  BaseTelaRelatorioForm in 'C:\Delphi\Componentes\06-infosaga_desktop\BaseTelaRelatorioForm.pas' {frmBaseTelaRelatorio},
  ErrorForm in 'C:\Delphi\Componentes\06-infosaga_desktop\ErrorForm.pas' {FrmError},
  InicioDB in 'C:\Delphi\Componentes\06-infosaga_desktop\InicioDB.pas' {DBInicio},
  Uteis in 'C:\Delphi\Componentes\06-infosaga_desktop\Uteis.pas',
  BaseDBEditForm in 'C:\Delphi\Componentes\06-infosaga_desktop\BaseDBEditForm.pas',
  BaseDBForm in 'C:\Delphi\Componentes\06-infosaga_desktop\BaseDBForm.pas' {frmBaseDB},
  BaseDBPesquisaForm in 'C:\Delphi\Componentes\06-infosaga_desktop\BaseDBPesquisaForm.pas' {frmBaseDBPesquisa},
  uRelatorios in '..\AdjutorNfe\Fontes\Forms\uRelatorios.pas' {FrmRelatorios},
  uEmail in '..\AdjutorNfe\Fontes\Forms\uEmail.pas' {FrmEmail},
  uErro in '..\AdjutorNfe\Fontes\Forms\uErro.pas' {FrmErro},
  uErroWebService in '..\AdjutorNfe\Fontes\Forms\uErroWebService.pas' {FrmErroWebService},
  uExportaXML in '..\AdjutorNfe\Fontes\Forms\uExportaXML.pas' {FrmExportaXml},
  uFormularioControle in '..\AdjutorNfe\Fontes\Forms\uFormularioControle.pas',
  uInutilizacao in '..\AdjutorNfe\Fontes\Forms\uInutilizacao.pas' {FrmInutilizacao},
  uLogin in '..\AdjutorNfe\Fontes\Forms\uLogin.pas' {FrmLogin},
  uPesquisa in '..\AdjutorNfe\Fontes\Forms\uPesquisa.pas' {FrmPesquisa},
  uUsuario in '..\AdjutorNfe\Fontes\Classes\uUsuario.pas',
  uCertificado in '..\AdjutorNfe\Fontes\Classes\uCertificado.pas',
  uConexao in '..\AdjutorNfe\Fontes\Classes\uConexao.pas',
  uDestinatario in '..\AdjutorNfe\Fontes\Classes\uDestinatario.pas',
  uEmpresa in '..\AdjutorNfe\Fontes\Classes\uEmpresa.pas',
  uEmpresaParametro in '..\AdjutorNfe\Fontes\Classes\uEmpresaParametro.pas',
  uEndereco in '..\AdjutorNfe\Fontes\Classes\uEndereco.pas',
  uErroXml in '..\AdjutorNfe\Fontes\Classes\uErroXml.pas',
  uEstado in '..\AdjutorNfe\Fontes\Classes\uEstado.pas',
  uFuncoesNf in '..\AdjutorNfe\Fontes\Classes\uFuncoesNf.pas',
  uMensagensWs in '..\AdjutorNfe\Fontes\Classes\uMensagensWs.pas',
  uMunicipio in '..\AdjutorNfe\Fontes\Classes\uMunicipio.pas',
  uNaturezaOperacao in '..\AdjutorNfe\Fontes\Classes\uNaturezaOperacao.pas',
  uNotaFiscal in '..\AdjutorNfe\Fontes\Classes\uNotaFiscal.pas',
  uNotaFiscalHistorico in '..\AdjutorNfe\Fontes\Classes\uNotaFiscalHistorico.pas',
  uNotaFiscalItem in '..\AdjutorNfe\Fontes\Classes\uNotaFiscalItem.pas',
  uNotaFiscalParcela in '..\AdjutorNfe\Fontes\Classes\uNotaFiscalParcela.pas',
  uNotaFiscalXML in '..\AdjutorNfe\Fontes\Classes\uNotaFiscalXML.pas',
  uPais in '..\AdjutorNfe\Fontes\Classes\uPais.pas',
  uProduto in '..\AdjutorNfe\Fontes\Classes\uProduto.pas',
  uSistema in '..\AdjutorNfe\Fontes\Classes\uSistema.pas',
  uTransportadora in '..\AdjutorNfe\Fontes\Classes\uTransportadora.pas',
  uTributacao in '..\AdjutorNfe\Fontes\Classes\uTributacao.pas',
  uWebServiceControle in '..\AdjutorNfe\Fontes\Controles\uWebServiceControle.pas',
  uBaseControle in '..\AdjutorNfe\Fontes\Controles\uBaseControle.pas',
  uCertificadoControle in '..\AdjutorNfe\Fontes\Controles\uCertificadoControle.pas',
  uControlePais in '..\AdjutorNfe\Fontes\Controles\uControlePais.pas',
  uDestinatarioControle in '..\AdjutorNfe\Fontes\Controles\uDestinatarioControle.pas',
  uEstadoControle in '..\AdjutorNfe\Fontes\Controles\uEstadoControle.pas',
  uMensagensWsControle in '..\AdjutorNfe\Fontes\Controles\uMensagensWsControle.pas',
  uMunicipioControle in '..\AdjutorNfe\Fontes\Controles\uMunicipioControle.pas',
  uNaturezaOperacaoControle in '..\AdjutorNfe\Fontes\Controles\uNaturezaOperacaoControle.pas',
  uNotaFiscaHistoricoControle in '..\AdjutorNfe\Fontes\Controles\uNotaFiscaHistoricoControle.pas',
  uNotaFiscalControle in '..\AdjutorNfe\Fontes\Controles\uNotaFiscalControle.pas',
  uNotaFiscalItemControle in '..\AdjutorNfe\Fontes\Controles\uNotaFiscalItemControle.pas',
  uNotaFiscaParcelaControle in '..\AdjutorNfe\Fontes\Controles\uNotaFiscaParcelaControle.pas',
  uProdutoControle in '..\AdjutorNfe\Fontes\Controles\uProdutoControle.pas',
  uTransportadoraControle in '..\AdjutorNfe\Fontes\Controles\uTransportadoraControle.pas',
  uTributacaoControle in '..\AdjutorNfe\Fontes\Controles\uTributacaoControle.pas',
  uUsuarioControle in '..\AdjutorNfe\Fontes\Controles\uUsuarioControle.pas',
  uUsuarioDao in '..\AdjutorNfe\Fontes\Daos\uUsuariodaonf.pas',
  uBaseDaoNf in '..\AdjutorNfe\Fontes\Daos\uBaseDaoNf.pas',
  uDestinatarioDaoNF in '..\AdjutorNfe\Fontes\Daos\uDestinatarioDaoNF.pas',
  uEmpresaDao in '..\AdjutorNfe\Fontes\Daos\uEmpresadaonf.pas',
  uEstadoDao in '..\AdjutorNfe\Fontes\Daos\uEstadodaonf.pas',
  uMensagensWsDao in '..\AdjutorNfe\Fontes\Daos\uMensagensWsdaonf.pas',
  uMunicipioDao in '..\AdjutorNfe\Fontes\Daos\uMunicipiodaonf.pas',
  uNaturezaOperacaoDao in '..\AdjutorNfe\Fontes\Daos\uNaturezaOperacaodaonf.pas',
  uNotaFiscalDao in '..\AdjutorNfe\Fontes\Daos\uNotaFiscaldaonf.pas',
  uNotaFiscalHistoricoDao in '..\AdjutorNfe\Fontes\Daos\uNotaFiscalHistoricodaonf.pas',
  uNotaFiscalItemDao in '..\AdjutorNfe\Fontes\Daos\uNotaFiscalItemdaonf.pas',
  uNotaFiscalParcelaDao in '..\AdjutorNfe\Fontes\Daos\uNotaFiscalParceladaonf.pas',
  uProdutoDao in '..\AdjutorNfe\Fontes\Daos\uProdutodaonf.pas',
  uTransportadoraDao in '..\AdjutorNfe\Fontes\Daos\uTransportadoradaonf.pas',
  uTributacaoDao in '..\AdjutorNfe\Fontes\Daos\uTributacaodaonf.pas',
  uDM in '..\AdjutorNfe\Fontes\DM\uDM.pas' {DM: TDataModule},
  uInutilizacoes in '..\AdjutorNfe\Fontes\Classes\uInutilizacoes.pas',
  uInutilizacoesDao in '..\AdjutorNfe\Fontes\Daos\uInutilizacoesdaonf.pas',
  uInutilizacoesControle in '..\AdjutorNfe\Fontes\Controles\uInutilizacoesControle.pas',
  uSequencia in '..\AdjutorNfe\Fontes\Classes\uSequencia.pas',
  uSequenciaDao in '..\AdjutorNfe\Fontes\Daos\uSequenciadaonf.pas',
  uSequenciaControle in '..\AdjutorNfe\Fontes\Controles\uSequenciaControle.pas',
  sSplash in '..\AdjutorNfe\Fontes\Forms\sSplash.pas' {FrmFlash},
  uJustificativa in '..\AdjutorNfe\Fontes\Forms\uJustificativa.pas' {FrmJustificativa},
  uUtil in '..\AdjutorNfe\Fontes\Classes\uUtil.pas',
  uTipoImpressao in '..\AdjutorNfe\Fontes\Forms\uTipoImpressao.pas' {FrmTipoDanfe},
  uDocumentoImportacaoControle in '..\AdjutorNfe\Fontes\Controles\uDocumentoImportacaoControle.pas',
  uImportacao in '..\AdjutorNfe\Fontes\Classes\uImportacao.pas',
  uImportacaoDao in '..\AdjutorNfe\Fontes\Daos\uImportacaodaonf.pas',
  uCartaCorrecao in '..\AdjutorNfe\Fontes\Forms\uCartaCorrecao.pas' {FrmCartaCorrecao},
  uPrincipal in '..\AdjutorNfe\Novos\uPrincipal.pas' {FrmPrincipal};

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Iniciodb.SplashStart(False);

  Application.CreateForm(TFrmFlash, FrmFlash);
  Application.CreateForm(TFrmPrincipal, FrmPrincipal);
  //Application.CreateForm(TFrmPrincipal, FrmPrincipal);
  Application.Run;
end.
