    create table tipo_mola (
	tim_codigo integer not null,
	pti_codigo varchar(3),
    mmo_tempo_producao varchar(1),
    mmo_peso_especifico varchar(1),
    mmo_cisalhamento varchar(1),
    mmo_res_tracao varchar(1),
    mmo_tratamento_termico varchar(1),
    mmo_tempo_tempera varchar(1), 
    mmo_temperatura_tempera varchar(1),
    mmo_tempo_revenimento varchar(1), 
    mmo_temperatura_revenimento varchar(1),
    mmo_dureza_minima varchar(1),
    mmo_dureza_maxima varchar(1),
    mmo_tratamento_superficial varchar(1),
    mmo_diametro_arame varchar(1),
    mmo_tolerancia_dia_min varchar(1),
    mmo_tolerancia_dia_max varchar(1),
    mmo_diametro_interno varchar(1),
    mmo_tolerancia_di_min varchar(1),
    mmo_tolerancia_di_max varchar(1),
    mmo_diametro_medio varchar(1),
    mmo_tolerancia_dm_min varchar(1),
    mmo_tolerancia_dm_max varchar(1),
    mmo_diametro_externo varchar(1),
    mmo_tolerancia_de_min varchar(1),
    mmo_tolerancia_de_max varchar(1),
    mmo_diametro_externo_meio varchar(1),
    mmo_tolerancia_dem_min varchar(1),
    mmo_tolerancia_dem_max varchar(1),
    mmo_vao varchar(1),
    mmo_tolerancia_vao_min varchar(1),
    mmo_tolerancia_vao_max varchar(1),
    mmo_passo varchar(1),
    mmo_tolerancia_passo_min varchar(1),
    mmo_tolerancia_passo_max varchar(1),
    mmo_com_livre varchar(1),
    mmo_tolerancia_livre_min varchar(1),
    mmo_tolerancia_livre_max varchar(1),
    mmo_com_solido varchar(1),
    mmo_tolerancia_solido_min varchar(1),
    mmo_tolerancia_solido_max varchar(1),    
    mmo_espirais_uteis varchar(1),
    mmo_tolerancia_esputeis_min varchar(1),
    mmo_tolerancia_esputeis_max varchar(1),
    mmo_espiral_total varchar(1),
    mmo_tolerancia_espt_min varchar(1),
    mmo_tolerancia_espt_max varchar(1),
    mmo_desenvolvimento varchar(1),
    mmo_tolerancia_des_min varchar(1),
    mmo_tolerancia_des_max varchar(1),    
    mmo_retificado varchar(1),
    mmo_paralielismo varchar(1),
    mmo_perpendicularimo varchar(1),
    mmo_sentido varchar(1),
    mmo_peso varchar(1),     
    mmo_observacao varchar(1),
    mmo_constante_espe varchar(1),
    mmo_tolerancia_const_min varchar(1),
    mmo_tolerancia_const_max varchar(1),    
    mmo_constante_calculada varchar(1),
     mmo_const_calc_min varchar(1),
    mmo_const_calc_max varchar(1),
    mmo_altural1 varchar(1),
    mmo_tolerancia_alt1_min varchar(1),
    mmo_tolerancia_alt1_max varchar(1),
    mmo_altural2 varchar(1),
    mmo_tolerancia_alt2_min varchar(1),
    mmo_tolerancia_alt2_max varchar(1),
    mmo_altural3 varchar(1),
    mmo_tolerancia_alt3_min varchar(1),
    mmo_tolerancia_alt3_max varchar(1),
    mmo_altural4 varchar(1),
    mmo_tolerancia_alt4_min varchar(1),
    mmo_tolerancia_alt4_max varchar(1),
    mmo_cursos1 varchar(1),
    mmo_tolerancia_curs1_min varchar(1),
    mmo_tolerancia_curs1_max varchar(1),
    mmo_cursos2 varchar(1),
    mmo_tolerancia_curs2_min varchar(1),
    mmo_tolerancia_curs2_max varchar(1),    
    mmo_cursos3 varchar(1),
    mmo_tolerancia_curs3_min varchar(1),
    mmo_tolerancia_curs3_max varchar(1),    
    mmo_cursos4 varchar(1),
    mmo_tolerancia_curs4_min varchar(1),
    mmo_tolerancia_curs4_max varchar(1),    
    mmo_cargap1 varchar(1),
    mmo_tolerancia_carga1_min varchar(1),
    mmo_tolerancia_carga1_max varchar(1),    
    mmo_cargap2 varchar(1),
    mmo_tolerancia_carga2_min varchar(1),
    mmo_tolerancia_carga2_max varchar(1),        
    mmo_cargap3 varchar(1),
    mmo_tolerancia_carga3_min varchar(1),
    mmo_tolerancia_carga3_max varchar(1),        
    mmo_cargap4 varchar(1),
    mmo_tolerancia_carga4_min varchar(1),
    mmo_tolerancia_carga4_max varchar(1),        
    mmo_tensao1 varchar(1),
    mmo_tolerancia_tensao1_min varchar(1),
    mmo_tolerancia_tensao1_max varchar(1),    
    mmo_tensao2 varchar(1),
    mmo_tolerancia_tensao2_min varchar(1),
    mmo_tolerancia_tensao2_max varchar(1),        
    mmo_tensao3 varchar(1),
    mmo_tolerancia_tensao3_min varchar(1),
    mmo_tolerancia_tensao3_max varchar(1),        
    mmo_tensao4 varchar(1),
    mmo_tolerancia_tensao4_min varchar(1),
    mmo_tolerancia_tensao4_max varchar(1),        
    mmo_carga varchar(1),
    mmo_tolerancia_carga_min varchar(1),
    mmo_tolerancia_carga_max varchar(1),    
    mmo_tensao varchar(1),    
    mmo_tolerancia_ten_min varchar(1),    
    mmo_tolerancia_ten_max varchar(1),    
    mmo_maquina varchar(1),
    mmo_mandril varchar(1),
    mmo_cachimbo varchar(1),
    mmo_copiador varchar(1),
    mmo_gancho varchar(1),
    mmo_disco varchar(1),
    mmo_outros varchar(1),
    mmo_localizacao varchar(1),
    mmo_setor varchar(1),
    mmo_obsgerais varchar(1));	
	
	
CREATE SEQUENCE GEN_TIPO_MOLA;

SET TERM ^ ;

create trigger tipo_mola_bi for tipo_mola
active before insert position 0
as
begin
  if (new.tim_codigo is null) then
    new.tim_codigo = gen_id(GEN_TIPO_MOLA,1);
end^

SET TERM ; ^
