unit DataMov;

interface

uses
  SysUtils, Classes, FMTBCd, DB, DBClient, Provider, SqlExpr,RwFunc,
  DBLocal, DBLocalS,recErro, MIDASLIB;

type
  TDataMovimento = class(TDataModule)
    SqlReceber: tsqlquery;
    DspReceber: TDataSetProvider;
    CdsReceber: TClientDataSet;
    DsReceber: TDataSource;
    SqlReceberFAT_CODIGO: TStringField;
    SqlReceberCLI_CODIGO: TStringField;
    SqlReceberFAT_CANCELADA: TStringField;
    SqlReceberREP_CODIGO: TStringField;
    SqlReceberPCX_CODIGO: TStringField;
    SqlReceberCCT_CODIGO: TStringField;
    SqlReceberFAT_PREVISAO: TStringField;
    SqlReceberFAT_QTDITEM: TFMTBCdField;
    SqlReceberFAT_VLNCOMIS: TFMTBCdField;
    SqlReceberFAT_DTEMIS: TSQLTimeStampField;
    SqlReceberFAT_COMIS1: TFMTBCdField;
    SqlReceberFAT_COMIS2: TFMTBCdField;
    SqlReceberFAT_COMIS3: TFMTBCdField;
    SqlReceberFAT_OBS: TStringField;
    SqlReceberFAT_OPERACAO: TStringField;
    SqlReceberFAT_BASESUB: TFMTBCdField;
    SqlReceberFAT_ICMSRET: TFMTBCdField;
    SqlReceberFAT_DESP_ACES: TFMTBCdField;
    SqlReceberFAT_BASEICMS: TFMTBCdField;
    SqlReceberFAT_VL_IPI: TFMTBCdField;
    SqlReceberFAT_ALIQUOTA: TFMTBCdField;
    SqlReceberFAT_OBSLIVRO: TStringField;
    SqlReceberFAT_OPERUF: TStringField;
    SqlReceberFAT_LIVRO: TStringField;
    SqlReceberEMP_CODIGO: TStringField;
    CdsReceberFAT_CODIGO: TStringField;
    CdsReceberCLI_CODIGO: TStringField;
    CdsReceberFAT_CANCELADA: TStringField;
    CdsReceberREP_CODIGO: TStringField;
    CdsReceberPCX_CODIGO: TStringField;
    CdsReceberCCT_CODIGO: TStringField;
    CdsReceberFAT_PREVISAO: TStringField;
    CdsReceberFAT_QTDITEM: TFMTBCdField;
    CdsReceberFAT_VLNCOMIS: TFMTBCdField;
    CdsReceberFAT_DTEMIS: TSQLTimeStampField;
    CdsReceberFAT_COMIS1: TFMTBCdField;
    CdsReceberFAT_COMIS2: TFMTBCdField;
    CdsReceberFAT_COMIS3: TFMTBCdField;
    CdsReceberFAT_OBS: TStringField;
    CdsReceberFAT_OPERACAO: TStringField;
    CdsReceberFAT_BASESUB: TFMTBCdField;
    CdsReceberFAT_ICMSRET: TFMTBCdField;
    CdsReceberFAT_DESP_ACES: TFMTBCdField;
    CdsReceberFAT_BASEICMS: TFMTBCdField;
    CdsReceberFAT_VL_IPI: TFMTBCdField;
    CdsReceberFAT_ALIQUOTA: TFMTBCdField;
    CdsReceberFAT_OBSLIVRO: TStringField;
    CdsReceberFAT_OPERUF: TStringField;
    CdsReceberFAT_LIVRO: TStringField;
    CdsReceberEMP_CODIGO: TStringField;
    CdsRecParce: TClientDataSet;
    DspRecParce: TDataSetProvider;
    SqlRecParce: tsqlquery;
    SqlRecParceFAT_CODIGO: TStringField;
    SqlRecParceFPC_NUMER: TStringField;
    SqlRecParceREP_CODIGO: TStringField;
    SqlRecParceBAN_CODIGO: TStringField;
    SqlRecParceCCT_CODIGO: TStringField;
    SqlRecParcePCX_CODIGO: TStringField;
    SqlRecParceFPC_DTEMIS: TSQLTimeStampField;
    SqlRecParceFPC_NPARCELAS: TSmallintField;
    SqlRecParceFPC_COBTIPO: TStringField;
    SqlRecParceFPC_STATUS: TStringField;
    SqlRecParceFPC_DESCTO: TFMTBCdField;
    SqlRecParceFPC_DTDESC: TSQLTimeStampField;
    SqlRecParceFPC_VENCTO: TSQLTimeStampField;
    SqlRecParceFPC_PAGTO: TSQLTimeStampField;
    SqlRecParceFPC_OBS: TStringField;
    SqlRecParceFPC_SITPAG: TStringField;
    SqlRecParceEMP_CODIGO: TStringField;
    SqlRecParceCLI_CODIGO: TStringField;
    SqlRecParceFPC_IMPDUP: TStringField;
    CdsRecParceFAT_CODIGO: TStringField;
    CdsRecParceFPC_NUMER: TStringField;
    CdsRecParceREP_CODIGO: TStringField;
    CdsRecParceBAN_CODIGO: TStringField;
    CdsRecParceCCT_CODIGO: TStringField;
    CdsRecParcePCX_CODIGO: TStringField;
    CdsRecParceFPC_DTEMIS: TSQLTimeStampField;
    CdsRecParceFPC_NPARCELAS: TSmallintField;
    CdsRecParceFPC_COBTIPO: TStringField;
    CdsRecParceFPC_STATUS: TStringField;
    CdsRecParceFPC_DESCTO: TFMTBCdField;
    CdsRecParceFPC_DTDESC: TSQLTimeStampField;
    CdsRecParceFPC_VENCTO: TSQLTimeStampField;
    CdsRecParceFPC_PAGTO: TSQLTimeStampField;
    CdsRecParceFPC_OBS: TStringField;
    CdsRecParceFPC_SITPAG: TStringField;
    CdsRecParceEMP_CODIGO: TStringField;
    CdsRecParceCLI_CODIGO: TStringField;
    CdsRecParceFPC_IMPDUP: TStringField;
    DsrecParc: TDataSource;
    SqlRecParceFAT_REGISTRO: TIntegerField;
    CdsRecParceFAT_REGISTRO: TIntegerField;
    SqlPagar: tsqlquery;
    DspPagar: TDataSetProvider;
    CdsPagar: TClientDataSet;
    DsPagar: TDataSource;
    SqlPagarPAG_CODIGO: TStringField;
    SqlPagarFOR_CODIGO: TStringField;
    SqlPagarPAG_TIPO: TStringField;
    SqlPagarPAG_DTEMIS: TSQLTimeStampField;
    SqlPagarCCT_CODIGO: TStringField;
    SqlPagarPCX_CODIGO: TStringField;
    SqlPagarPAG_PREVISAO: TStringField;
    SqlPagarPAG_VLNOTA: TFMTBCdField;
    SqlPagarPAG_SERIE: TStringField;
    SqlPagarPAG_BASEICMS: TFMTBCdField;
    SqlPagarPAG_ALIQICMS: TFMTBCdField;
    SqlPagarPAG_BASEIPI: TFMTBCdField;
    SqlPagarPAG_VL_IPI: TFMTBCdField;
    SqlPagarPAG_OBS: TStringField;
    SqlPagarPAG_FAVORECIDO: TStringField;
    SqlPagarPAG_LIVRO: TStringField;
    SqlPagarPAG_OPERACAO: TStringField;
    SqlPagarEMP_CODIGO: TStringField;
    CdsPagarPAG_CODIGO: TStringField;
    CdsPagarFOR_CODIGO: TStringField;
    CdsPagarPAG_TIPO: TStringField;
    CdsPagarPAG_DTEMIS: TSQLTimeStampField;
    CdsPagarCCT_CODIGO: TStringField;
    CdsPagarPCX_CODIGO: TStringField;
    CdsPagarPAG_PREVISAO: TStringField;
    CdsPagarPAG_VLNOTA: TFMTBCdField;
    CdsPagarPAG_SERIE: TStringField;
    CdsPagarPAG_BASEICMS: TFMTBCdField;
    CdsPagarPAG_ALIQICMS: TFMTBCdField;
    CdsPagarPAG_BASEIPI: TFMTBCdField;
    CdsPagarPAG_VL_IPI: TFMTBCdField;
    CdsPagarPAG_OBS: TStringField;
    CdsPagarPAG_FAVORECIDO: TStringField;
    CdsPagarPAG_LIVRO: TStringField;
    CdsPagarPAG_OPERACAO: TStringField;
    CdsPagarEMP_CODIGO: TStringField;
    SqlSaldoBanco: tsqlquery;
    DspSaldoBanco: TDataSetProvider;
    CdsSaldoBanco: TClientDataSet;
    DsSaldoBanco: TDataSource;
    SqlSaldoBancoSAB_CODIGO: TStringField;
    SqlSaldoBancoBAN_CODIGO: TStringField;
    SqlSaldoBancoSAB_DIA: TSQLTimeStampField;
    SqlSaldoBancoSAB_SALDO: TFMTBCdField;
    SqlSaldoBancoSAB_BLOQUEADO: TFMTBCdField;
    SqlSaldoBancoSAB_APLICADO: TFMTBCdField;
    SqlSaldoBancoSAB_TIPOAPL: TStringField;
    SqlSaldoBancoSAB_OBS: TStringField;
    SqlSaldoBancoEMP_CODIGO: TStringField;
    CdsSaldoBancoSAB_CODIGO: TStringField;
    CdsSaldoBancoBAN_CODIGO: TStringField;
    CdsSaldoBancoSAB_DIA: TSQLTimeStampField;
    CdsSaldoBancoSAB_SALDO: TFMTBCdField;
    CdsSaldoBancoSAB_BLOQUEADO: TFMTBCdField;
    CdsSaldoBancoSAB_APLICADO: TFMTBCdField;
    CdsSaldoBancoSAB_TIPOAPL: TStringField;
    CdsSaldoBancoSAB_OBS: TStringField;
    CdsSaldoBancoEMP_CODIGO: TStringField;
    SqlFluxoCaixa: tsqlquery;
    CdsFluxoCaixa: TClientDataSet;
    DpsFluxoCaixa: TDataSetProvider;
    DsFluxoCaixa: TDataSource;
    SqlFluxoCaixaFLU_DIA: TSQLTimeStampField;
    SqlFluxoCaixaFLU_RECEBE: TFMTBCdField;
    SqlFluxoCaixaFLU_PAGAR: TFMTBCdField;
    SqlFluxoCaixaFLU_BANCO: TFMTBCdField;
    SqlFluxoCaixaFLU_SALDO: TFMTBCdField;
    SqlFluxoCaixaFLU_ACUMULO: TFMTBCdField;
    SqlFluxoCaixaEMP_CODIGO: TStringField;
    CdsFluxoCaixaFLU_DIA: TSQLTimeStampField;
    CdsFluxoCaixaFLU_RECEBE: TFMTBCdField;
    CdsFluxoCaixaFLU_PAGAR: TFMTBCdField;
    CdsFluxoCaixaFLU_BANCO: TFMTBCdField;
    CdsFluxoCaixaFLU_SALDO: TFMTBCdField;
    CdsFluxoCaixaFLU_ACUMULO: TFMTBCdField;
    CdsFluxoCaixaEMP_CODIGO: TStringField;
    SqlPedidos: tsqlquery;
    CdsPedidos: TClientDataSet;
    DspPedidos: TDataSetProvider;
    DsPedidos: TDataSource;
    SqlPedItem: tsqlquery;
    DspPedItem: TDataSetProvider;
    CdsPedItem: TClientDataSet;
    DsPedItem: TDataSource;
    SQLRecItem: tsqlquery;
    DspRecItem: TDataSetProvider;
    CdsRecItem: TClientDataSet;
    DsRecItem: TDataSource;
    SQLRecItemREG: TIntegerField;
    SQLRecItemFAT_CODIGO: TStringField;
    SQLRecItemPRD_CODIGO: TStringField;
    SQLRecItemPRD_REFER: TStringField;
    SQLRecItemFIT_QTDE: TFMTBCdField;
    SQLRecItemFIT_IPIALIQ: TFMTBCdField;
    SQLRecItemFIT_PRECO: TFMTBCdField;
    SQLRecItemFIT_COMIS: TFMTBCdField;
    SQLRecItemFIT_DESCTO: TFMTBCdField;
    SQLRecItemFIT_SUBSTIT: TFMTBCdField;
    SQLRecItemEMP_CODIGO: TStringField;
    CdsRecItemREG: TIntegerField;
    CdsRecItemFAT_CODIGO: TStringField;
    CdsRecItemPRD_CODIGO: TStringField;
    CdsRecItemPRD_REFER: TStringField;
    CdsRecItemFIT_QTDE: TFMTBCdField;
    CdsRecItemFIT_IPIALIQ: TFMTBCdField;
    CdsRecItemFIT_PRECO: TFMTBCdField;
    CdsRecItemFIT_COMIS: TFMTBCdField;
    CdsRecItemFIT_DESCTO: TFMTBCdField;
    CdsRecItemFIT_SUBSTIT: TFMTBCdField;
    CdsRecItemEMP_CODIGO: TStringField;
    DspFechaCaixa: TDataSetProvider;
    DspCaixaFixo: TDataSetProvider;
    CdsCaixaFixo: TClientDataSet;
    CdsFechaCaixa: TClientDataSet;
    DsFechaCaixa: TDataSource;
    DsCaixaFixo: TDataSource;
    SqlCaixaFixo: tsqlquery;
    SqlFechaCaixa: tsqlquery;
    SqlCaixaFixoCXA_LANCTO: TStringField;
    SqlCaixaFixoCXA_DATA: TSQLTimeStampField;
    SqlCaixaFixoCCT_CODIGO: TStringField;
    SqlCaixaFixoCXA_HISTORICO: TStringField;
    SqlCaixaFixoCXA_DOCUMENTO: TStringField;
    SqlCaixaFixoCXA_TIPODOC: TStringField;
    SqlCaixaFixoCXA_SAIDA: TFMTBCdField;
    SqlCaixaFixoCXA_ENTRADA: TFMTBCdField;
    SqlCaixaFixoCXA_SITUACAO: TStringField;
    SqlCaixaFixoEMP_CODIGO: TStringField;
    CdsCaixaFixoCXA_LANCTO: TStringField;
    CdsCaixaFixoCXA_DATA: TSQLTimeStampField;
    CdsCaixaFixoCCT_CODIGO: TStringField;
    CdsCaixaFixoCXA_HISTORICO: TStringField;
    CdsCaixaFixoCXA_DOCUMENTO: TStringField;
    CdsCaixaFixoCXA_TIPODOC: TStringField;
    CdsCaixaFixoCXA_SAIDA: TFMTBCdField;
    CdsCaixaFixoCXA_ENTRADA: TFMTBCdField;
    CdsCaixaFixoCXA_SITUACAO: TStringField;
    CdsCaixaFixoEMP_CODIGO: TStringField;
    SqlFechaCaixaCXF_CODIGO: TStringField;
    SqlFechaCaixaCXF_ANTERIOR: TFMTBCdField;
    SqlFechaCaixaCXF_DATAFECHA: TSQLTimeStampField;
    SqlFechaCaixaCXF_ENTRADAS: TFMTBCdField;
    SqlFechaCaixaCXF_SAIDAS: TFMTBCdField;
    SqlFechaCaixaCXF_DINICIO: TSQLTimeStampField;
    SqlFechaCaixaCXF_DFIM: TSQLTimeStampField;
    SqlFechaCaixaEMP_CODIGO: TStringField;
    CdsFechaCaixaCXF_CODIGO: TStringField;
    CdsFechaCaixaCXF_ANTERIOR: TFMTBCdField;
    CdsFechaCaixaCXF_DATAFECHA: TSQLTimeStampField;
    CdsFechaCaixaCXF_ENTRADAS: TFMTBCdField;
    CdsFechaCaixaCXF_SAIDAS: TFMTBCdField;
    CdsFechaCaixaCXF_DINICIO: TSQLTimeStampField;
    CdsFechaCaixaCXF_DFIM: TSQLTimeStampField;
    CdsFechaCaixaEMP_CODIGO: TStringField;
    CdsFechaCaixaCC_SALDOCAIXA: TCurrencyField;
    CdsPedidosREP_CODIGO: TStringField;
    CdsPedidosPED_DTENTRADA: TSQLTimeStampField;
    CdsPedidosPED_COMIS1: TFMTBCdField;
    CdsPedidosPED_COMIS2: TFMTBCdField;
    CdsPedidosPED_COMIS3: TFMTBCdField;
    CdsPedidosCLI_CODIGO: TStringField;
    CdsPedidosPED_DESCTOVL: TFMTBCdField;
    CdsPedidosPED_DESCTOPC1: TFMTBCdField;
    CdsPedidosPED_DESCTOPC2: TFMTBCdField;
    CdsPedidosTRP_CODIGO: TStringField;
    CdsPedidosPED_FRETE2: TStringField;
    CdsPedidosPED_FRETE: TStringField;
    CdsPedidosTRP_REDESP: TStringField;
    CdsPedidosPED_OBSNOTA: TStringField;
    CdsPedidosPED_VLFATURADO: TFMTBCdField;
    CdsPedidosPED_SITCRED: TStringField;
    CdsPedidosPED_DTEMBARQUE: TSQLTimeStampField;
    CdsPedidosPED_DTLIM_ATD: TSQLTimeStampField;
    CdsPedidosPED_DTSAIDA: TSQLTimeStampField;
    CdsPedidosPED_PRIORIDADE: TStringField;
    CdsPedidosPED_EXPEDICAO: TStringField;
    CdsPedidosEMP_CODIGO: TStringField;
    CdsPedidosPED_DESCTONF: TStringField;
    CdsPedItemPRF_REGISTRO: TIntegerField;
    CdsPedItemPRF_QTDE: TFMTBCdField;
    CdsPedItemPRF_QTDEFAT: TFMTBCdField;
    CdsPedItemPRF_SITUACAO: TStringField;
    CdsPedItemPRF_ITEMCOMIS: TFMTBCdField;
    CdsPedItemPRF_IPIALIQ: TFMTBCdField;
    CdsPedItemPRF_ICMSALIQ: TFMTBCdField;
    CdsPedItemPRF_VAR1: TFMTBCdField;
    CdsPedItemPRF_VAR2: TFMTBCdField;
    CdsPedItemPRF_VAR3: TFMTBCdField;
    CdsPedItemPRF_VAR4: TFMTBCdField;
    CdsPedItemPRF_VAR5: TFMTBCdField;
    CdsPedItemPRF_VAR6: TFMTBCdField;
    CdsPedItemPRF_VAR7: TFMTBCdField;
    CdsPedItemPRF_VAR8: TFMTBCdField;
    CdsPedItemEMP_CODIGO: TStringField;
    CdsPedItemPRF_TOTAL_CC: TCurrencyField;
    CdsPedItemPRF_TOTAL_BRUTO_CC: TCurrencyField;
    SQlNota: tsqlquery;
    DspNota: TDataSetProvider;
    CdsNotaFiscal: TClientDataSet;
    DsNotaFiscal: TDataSource;
    CdsNotaFiscalNF_REGISTRO: TIntegerField;
    SqlItemNota: tsqlquery;
    DspItemNota: TDataSetProvider;
    CdsItemNota: TClientDataSet;
    DsItemNota: TDataSource;
    CdsItemNotaNF_QTDE: TFMTBCdField;
    CdsItemNotaNF_IPIALIQ: TFMTBCdField;
    CdsItemNotaNF_VLSUBST: TFMTBCdField;
    CdsItemNotaNF_IDESCTO1: TFMTBCdField;
    CdsItemNotaNF_IDESCTO2: TFMTBCdField;
    CdsItemNotaNF_REGISTRO: TIntegerField;
    SqlItemNotaNF_QTDE: TFMTBCdField;
    SqlItemNotaNF_IPIALIQ: TFMTBCdField;
    SqlItemNotaNF_VLSUBST: TFMTBCdField;
    SqlItemNotaNF_IDESCTO1: TFMTBCdField;
    SqlItemNotaNF_IDESCTO2: TFMTBCdField;
    SqlItemNotaNF_REGISTRO: TIntegerField;
    CdsItemNotaNF_TOTAL_CC: TCurrencyField;
    CdsPedItemPRF_QTDE_ITENS: TAggregateField;
    CdsPedidosCLI_RAZAO: TStringField;
    CdsPedidosCLI_CIDADE: TStringField;
    CdsPedidosCLI_UF: TStringField;
    CdsPedItemPED_QTDE_PEND_CC: TStringField;
    CdsPedidosOPV_CODIGO: TIntegerField;
    CdsPedidosOPE_CODIGO: TIntegerField;
    SqlPedItemPRF_REGISTRO: TIntegerField;
    SqlPedItemPRF_QTDE: TFMTBCdField;
    SqlPedItemPRF_QTDEFAT: TFMTBCdField;
    SqlPedItemPRF_SITUACAO: TStringField;
    SqlPedItemPRF_ITEMCOMIS: TFMTBCdField;
    SqlPedItemPRF_IPIALIQ: TFMTBCdField;
    SqlPedItemPRF_ICMSALIQ: TFMTBCdField;
    //SqlPedItemPRF_PRDDESCRI: TStringField;
    SqlPedItemPRF_VAR1: TFMTBCdField;
    SqlPedItemPRF_VAR2: TFMTBCdField;
    SqlPedItemPRF_VAR3: TFMTBCdField;
    SqlPedItemPRF_VAR4: TFMTBCdField;
    SqlPedItemPRF_VAR5: TFMTBCdField;
    SqlPedItemPRF_VAR6: TFMTBCdField;
    SqlPedItemPRF_VAR7: TFMTBCdField;
    SqlPedItemPRF_VAR8: TFMTBCdField;
    SqlPedItemEMP_CODIGO: TStringField;
    CdsPedidosPED_SITUACAO: TStringField;
    CdsPedItemPRF_QTDE_FATURAR_CC: TCurrencyField;
    SqlItemNotaNF_IT_NOTANUMER: TStringField;
    CdsItemNotaNF_IT_NOTANUMER: TStringField;
    CdsItemNotaNF_TOTAL_PROD_CC: TAggregateField;
    SQlNotaNF_REGISTRO: TIntegerField;
    CdsPedItemPRF_TOTAL_PRODUTOS: TAggregateField;
    SqlPedidosCLI_CODIGO: TStringField;
    SqlPedidosREP_CODIGO: TStringField;
    SqlPedidosPED_DTENTRADA: TSQLTimeStampField;
    SqlPedidosPED_COMIS1: TFMTBCdField;
    SqlPedidosPED_COMIS2: TFMTBCdField;
    SqlPedidosPED_COMIS3: TFMTBCdField;
    SqlPedidosPED_DESCTOVL: TFMTBCdField;
    SqlPedidosPED_DESCTOPC1: TFMTBCdField;
    SqlPedidosPED_DESCTOPC2: TFMTBCdField;
    SqlPedidosTRP_CODIGO: TStringField;
    SqlPedidosPED_FRETE2: TStringField;
    SqlPedidosPED_FRETE: TStringField;
    SqlPedidosTRP_REDESP: TStringField;
    SqlPedidosPED_OBSNOTA: TStringField;
    SqlPedidosPED_VLTOTAL_LIQ: TFMTBCdField;
    SqlPedidosPED_VLFATURADO: TFMTBCdField;
    SqlPedidosPED_SITCRED: TStringField;
    SqlPedidosPED_DTEMBARQUE: TSQLTimeStampField;
    SqlPedidosPED_DTLIM_ATD: TSQLTimeStampField;
    SqlPedidosPED_DTSAIDA: TSQLTimeStampField;
    SqlPedidosPED_PRIORIDADE: TStringField;
    SqlPedidosPED_EXPEDICAO: TStringField;
    SqlPedidosEMP_CODIGO: TStringField;
    SqlPedidosOPV_CODIGO: TIntegerField;
    SqlPedidosOPE_CODIGO: TIntegerField;
    SqlPedidosPED_DESCTONF: TStringField;
    SqlPedidosPED_SITUACAO: TStringField;
    SqlPedidosPED_VLTOTAL_BRUTO: TFMTBCdField;
    CdsPedidosPED_VLTOTAL_LIQ: TFMTBCdField;
    CdsPedidosPED_VLTOTAL_BRUTO: TFMTBCdField;
    CdsRecParceFPC_SITUACAO_CC: TStringField;
    SqlEmbalagem: tsqlquery;
    DspEmbalagem: TDataSetProvider;
    CdsEmbalagem: TClientDataSet;
    DsEmbalagem: TDataSource;
    SqlEmbalagemPRD_CODIGO: TStringField;
    SqlEmbalagemPEB_PRECO: TFMTBCdField;
    SqlEmbalagemPEB_QTDE: TFMTBCdField;
    SqlEmbalagemEMP_CODIGO: TStringField;
    SqlEmbalagemPRD_REFER: TStringField;
    SqlEmbalagemPEB_REGISTRO: TIntegerField;
    CdsEmbalagemPEB_REGISTRO: TIntegerField;
    CdsEmbalagemPRD_CODIGO: TStringField;
    CdsEmbalagemPEB_PRECO: TFMTBCdField;
    CdsEmbalagemPEB_QTDE: TFMTBCdField;
    CdsEmbalagemEMP_CODIGO: TStringField;
    CdsEmbalagemPRD_REFER: TStringField;
    SqlItemEmb: tsqlquery;
    DspItemEmb: TDataSetProvider;
    CdsItemEmb: TClientDataSet;
    DsItemEmb: TDataSource;
    SqlEmbalagemPRD_DESCRI: TStringField;
    CdsEmbalagemPRD_DESCRI: TStringField;
    SqlNF_PED: tsqlquery;
    CdsNfPed: TClientDataSet;
    DspNf_PED: TDataSetProvider;
    DsNF_PED: TDataSource;
    SqlNF_PEDNP_REGISTRO: TIntegerField;
    CdsNfPedNP_REGISTRO: TIntegerField;
    SqlNF_PEDNP_NOTANUMER: TStringField;
    CdsNfPedNP_NOTANUMER: TStringField;
    SqlRecParceFPC_TIPODOC: TStringField;
    CdsRecParceFPC_TIPODOC: TStringField;
    SqlReceberFAT_VL_RET: TFMTBCdField;
    CdsReceberFAT_VL_RET: TFMTBCdField;
    SqlRecParceFPC_JUROS: TFMTBCdField;
    SqlRecParceFPC_MULTA: TFMTBCdField;
    CdsRecParceFPC_JUROS: TFMTBCdField;
    CdsRecParceFPC_MULTA: TFMTBCdField;
    SqlReceberPCL_CODIGO: TStringField;
    CdsReceberPCL_CODIGO: TStringField;
    SqlRecParceFPC_VL_RET: TFMTBCdField;
    CdsRecParceFPC_VL_RET: TFMTBCdField;
    SqlReceberFAT_IRPJ_RET: TFMTBCdField;
    SqlReceberFAT_PIS_RET: TFMTBCdField;
    SqlReceberFAT_COFINS_RET: TFMTBCdField;
    SqlReceberFAT_INSS_RET: TFMTBCdField;
    SqlReceberFAT_CONTSOCIAL_RET: TFMTBCdField;
    CdsReceberFAT_IRPJ_RET: TFMTBCdField;
    CdsReceberFAT_PIS_RET: TFMTBCdField;
    CdsReceberFAT_COFINS_RET: TFMTBCdField;
    CdsReceberFAT_INSS_RET: TFMTBCdField;
    CdsReceberFAT_CONTSOCIAL_RET: TFMTBCdField;
    SqlReceberFAT_BASE_ISS: TFMTBCdField;
    SqlReceberFAT_BASE_INSS: TFMTBCdField;
    SqlReceberFAT_IRPJ_PERC: TFMTBCdField;
    SqlReceberFAT_PIS_PERC: TFMTBCdField;
    SqlReceberFAT_COFINS_PERC: TFMTBCdField;
    SqlReceberFAT_INSS_PERC: TFMTBCdField;
    SqlReceberFAT_CONTSOCIAL_PERC: TFMTBCdField;
    CdsReceberFAT_BASE_ISS: TFMTBCdField;
    CdsReceberFAT_BASE_INSS: TFMTBCdField;
    CdsReceberFAT_IRPJ_PERC: TFMTBCdField;
    CdsReceberFAT_PIS_PERC: TFMTBCdField;
    CdsReceberFAT_COFINS_PERC: TFMTBCdField;
    CdsReceberFAT_INSS_PERC: TFMTBCdField;
    CdsReceberFAT_CONTSOCIAL_PERC: TFMTBCdField;
    SqlPagarPAG_IRPJ_RET: TFMTBCdField;
    SqlPagarPAG_PIS_RET: TFMTBCdField;
    SqlPagarPAG_COFINS_RET: TFMTBCdField;
    SqlPagarPAG_INSS_RET: TFMTBCdField;
    SqlPagarPAG_BASE_ISS: TFMTBCdField;
    SqlPagarPAG_BASE_INSS: TFMTBCdField;
    SqlPagarPAG_IRPJ_PERC: TFMTBCdField;
    SqlPagarPAG_PIS_PERC: TFMTBCdField;
    SqlPagarPAG_COFINS_PERC: TFMTBCdField;
    SqlPagarPAG_INSS_PERC: TFMTBCdField;
    SqlPagarPAG_CONTSOCIAL_PERC: TFMTBCdField;
    SqlPagarPAG_CONTSOCIAL_RET: TFMTBCdField;
    CdsPagarPAG_IRPJ_RET: TFMTBCdField;
    CdsPagarPAG_PIS_RET: TFMTBCdField;
    CdsPagarPAG_COFINS_RET: TFMTBCdField;
    CdsPagarPAG_INSS_RET: TFMTBCdField;
    CdsPagarPAG_BASE_ISS: TFMTBCdField;
    CdsPagarPAG_BASE_INSS: TFMTBCdField;
    CdsPagarPAG_IRPJ_PERC: TFMTBCdField;
    CdsPagarPAG_PIS_PERC: TFMTBCdField;
    CdsPagarPAG_COFINS_PERC: TFMTBCdField;
    CdsPagarPAG_INSS_PERC: TFMTBCdField;
    CdsPagarPAG_CONTSOCIAL_PERC: TFMTBCdField;
    CdsPagarPAG_CONTSOCIAL_RET: TFMTBCdField;
    SqlPagarPAG_VL_RET: TFMTBCdField;
    CdsPagarPAG_VL_RET: TFMTBCdField;
    SqlReceberFAT_ISS_RET: TFMTBCdField;
    SqlReceberFAT_ISS_PERC: TFMTBCdField;
    CdsReceberFAT_ISS_RET: TFMTBCdField;
    CdsReceberFAT_ISS_PERC: TFMTBCdField;
    SqlReceberOPV_CODIGO: TSmallintField;
    CdsReceberOPV_CODIGO: TSmallintField;
    SqlPagarOPV_CODIGO: TSmallintField;
    CdsPagarOPV_CODIGO: TSmallintField;
    SqlPedidosPCL_CODIGO: TStringField;
    CdsPedidosPCL_CODIGO: TStringField;
    SqlOrdCompra: tsqlquery;
    DspOrdCompra: TDataSetProvider;
    CdsOrdCompra: TClientDataSet;
    DsOrdCompra: TDataSource;
    SqlItemCompra: tsqlquery;
    DspItemCompra: TDataSetProvider;
    CdsItemCompra: TClientDataSet;
    CdsItemCompraOCI_REGISTRO: TIntegerField;
    DsItemCompra: TDataSource;
    SqlItemCompraOCI_REGISTRO: TIntegerField;
    SqlItemCompraOCI_QTDES: TFMTBCdField;
    SqlItemCompraOCI_QTDER: TFMTBCdField;
    SqlItemCompraOCI_IPI: TFMTBCdField;
    SqlItemCompraOCI_SITUACAO: TStringField;
    SqlItemCompraEMP_CODIGO: TStringField;
    CdsItemCompraOCI_QTDES: TFMTBCdField;
    CdsItemCompraOCI_QTDER: TFMTBCdField;
    CdsItemCompraOCI_IPI: TFMTBCdField;
    CdsItemCompraOCI_SITUACAO: TStringField;
    CdsItemCompraEMP_CODIGO: TStringField;
    SqlCdsEnf: tsqlquery;
    DspEnf: TDataSetProvider;
    CdsEnf: TClientDataSet;
    DsEnf: TDataSource;
    SqlCdsEnfComp: tsqlquery;
    DspEnfComp: TDataSetProvider;
    CdsEnfComp: TClientDataSet;
    DsEnfComp: TDataSource;
    SqlCdsEnfCompENP_REGISTRO: TIntegerField;
    SqlCdsEnfCompENF_NOTANUMER: TStringField;
    SqlCdsEnfCompOCP_CODIGO: TStringField;
    CdsEnfCompENP_REGISTRO: TIntegerField;
    CdsEnfCompENF_NOTANUMER: TStringField;
    CdsEnfCompOCP_CODIGO: TStringField;
    SqlCdsEnfENF_REGISTRO: TIntegerField;
    CdsEnfENF_REGISTRO: TIntegerField;
    SqlItemCompraOCP_CODIGO: TStringField;
    CdsItemCompraOCP_CODIGO: TStringField;
    SqlCdsEnfENF_NOTANUMBER: TStringField;
    SqlCdsEnfENF_SERIE: TStringField;
    SqlCdsEnfOPV_CODIGO: TIntegerField;
    SqlCdsEnfENF_EMISSAO: TDateField;
    SqlCdsEnfENF_ENTRADA: TDateField;
    SqlCdsEnfPCL_CODIGO: TStringField;
    SqlCdsEnfOPE_NATUREZA: TStringField;
    SqlCdsEnfOCP_CODIGO: TStringField;
    SqlCdsEnfAMX_CODIGO: TStringField;
    SqlCdsEnfCCT_CODIGO: TStringField;
    SqlCdsEnfENF_VLFRETE: TFMTBCdField;
    SqlCdsEnfENF_VLSEGURO: TFMTBCdField;
    SqlCdsEnfENF_DESP_ACES: TFMTBCdField;
    SqlCdsEnfENF_ALIQ_ICMS: TFMTBCdField;
    SqlCdsEnfENF_BASEICMS: TFMTBCdField;
    SqlCdsEnfENF_VL_ICMS: TFMTBCdField;
    SqlCdsEnfENF_VLBASESUBTRIB: TFMTBCdField;
    SqlCdsEnfENF_VL_SUBTRIB: TFMTBCdField;
    SqlCdsEnfENF_TOT_CSUB: TFMTBCdField;
    SqlCdsEnfENF_VL_IPI: TFMTBCdField;
    SqlCdsEnfENF_BASE_IPI: TFMTBCdField;
    SqlCdsEnfENF_VL_DESCTO: TFMTBCdField;
    SqlCdsEnfENF_OBS_NOTA: TStringField;
    SqlCdsEnfENF_INTERNO: TStringField;
    SqlCdsEnfENF_CANCELADA: TStringField;
    SqlCdsEnfEMP_CODIGO: TStringField;
    CdsEnfENF_NOTANUMBER: TStringField;
    CdsEnfENF_SERIE: TStringField;
    CdsEnfOPV_CODIGO: TIntegerField;
    CdsEnfENF_EMISSAO: TDateField;
    CdsEnfENF_ENTRADA: TDateField;
    CdsEnfPCL_CODIGO: TStringField;
    CdsEnfOPE_NATUREZA: TStringField;
    CdsEnfOCP_CODIGO: TStringField;
    CdsEnfAMX_CODIGO: TStringField;
    CdsEnfCCT_CODIGO: TStringField;
    CdsEnfENF_VLFRETE: TFMTBCdField;
    CdsEnfENF_VLSEGURO: TFMTBCdField;
    CdsEnfENF_DESP_ACES: TFMTBCdField;
    CdsEnfENF_ALIQ_ICMS: TFMTBCdField;
    CdsEnfENF_BASEICMS: TFMTBCdField;
    CdsEnfENF_VL_ICMS: TFMTBCdField;
    CdsEnfENF_VLBASESUBTRIB: TFMTBCdField;
    CdsEnfENF_VL_SUBTRIB: TFMTBCdField;
    CdsEnfENF_TOT_CSUB: TFMTBCdField;
    CdsEnfENF_VL_IPI: TFMTBCdField;
    CdsEnfENF_BASE_IPI: TFMTBCdField;
    CdsEnfENF_VL_DESCTO: TFMTBCdField;
    CdsEnfENF_OBS_NOTA: TStringField;
    CdsEnfENF_INTERNO: TStringField;
    CdsEnfENF_CANCELADA: TStringField;
    CdsEnfEMP_CODIGO: TStringField;
    SqlCdsEnfFOR_CODIGO: TStringField;
    CdsEnfFOR_CODIGO: TStringField;
    SqlCdsEnfCompFOR_CODIGO: TStringField;
    CdsEnfCompFOR_CODIGO: TStringField;
    SqlOrdCompraOCP_CODIGO: TStringField;
    SqlOrdCompraCOT_CODIGO: TStringField;
    SqlOrdCompraOPV_CODIGO: TIntegerField;
    SqlOrdCompraFOR_CODIGO: TStringField;
    SqlOrdCompraOCP_DTEMIS: TSQLTimeStampField;
    SqlOrdCompraOCP_DTENTREGA: TSQLTimeStampField;
    SqlOrdCompraOCP_REQUERENTE: TStringField;
    SqlOrdCompraOCP_FRETE: TFMTBCdField;
    SqlOrdCompraOCP_DESPESAS: TFMTBCdField;
    SqlOrdCompraOCP_ICMS: TFMTBCdField;
    SqlOrdCompraOCP_IPI: TFMTBCdField;
    SqlOrdCompraTRP_CODIGO: TStringField;
    SqlOrdCompraOCP_TPPAGTO: TStringField;
    SqlOrdCompraOCP_OBS: TMemoField;
    SqlOrdCompraOCP_TOTAL: TFMTBCdField;
    SqlOrdCompraOCP_STATUS: TStringField;
    SqlOrdCompraEMP_CODIGO: TStringField;
    CdsOrdCompraOCP_CODIGO: TStringField;
    CdsOrdCompraCOT_CODIGO: TStringField;
    CdsOrdCompraOPV_CODIGO: TIntegerField;
    CdsOrdCompraFOR_CODIGO: TStringField;
    CdsOrdCompraOCP_DTEMIS: TSQLTimeStampField;
    CdsOrdCompraOCP_DTENTREGA: TSQLTimeStampField;
    CdsOrdCompraOCP_REQUERENTE: TStringField;
    CdsOrdCompraOCP_FRETE: TFMTBCdField;
    CdsOrdCompraOCP_DESPESAS: TFMTBCdField;
    CdsOrdCompraOCP_ICMS: TFMTBCdField;
    CdsOrdCompraOCP_IPI: TFMTBCdField;
    CdsOrdCompraTRP_CODIGO: TStringField;
    CdsOrdCompraOCP_TPPAGTO: TStringField;
    CdsOrdCompraOCP_OBS: TMemoField;
    CdsOrdCompraOCP_TOTAL: TFMTBCdField;
    CdsOrdCompraOCP_STATUS: TStringField;
    CdsOrdCompraEMP_CODIGO: TStringField;
    SqlPedItemPRD_DCVAR1: TStringField;
    SqlPedItemPRD_DCVAR2: TStringField;
    SqlPedItemPRD_DCVAR3: TStringField;
    SqlPedItemPRD_DCVAR4: TStringField;
    SqlPedItemPRD_DCVAR5: TStringField;
    SqlPedItemPRD_DCVAR6: TStringField;
    SqlPedItemPRD_DCVAR7: TStringField;
    SqlPedItemPRD_DCVAR8: TStringField;
    CdsPedItemPRD_DCVAR1: TStringField;
    CdsPedItemPRD_DCVAR2: TStringField;
    CdsPedItemPRD_DCVAR3: TStringField;
    CdsPedItemPRD_DCVAR4: TStringField;
    CdsPedItemPRD_DCVAR5: TStringField;
    CdsPedItemPRD_DCVAR6: TStringField;
    CdsPedItemPRD_DCVAR7: TStringField;
    CdsPedItemPRD_DCVAR8: TStringField;
    SqlPedidosPED_TPDESCTO: TStringField;
    CdsPedidosPED_TPDESCTO: TStringField;
    SqlPedidosPED_VLTOTAL_IPI: TFMTBCdField;
    CdsPedidosPED_VLTOTAL_IPI: TFMTBCdField;
    SqlPagarCCT_NOVO: TStringField;
    SqlPagarPAG_ISS_RET: TFMTBCdField;
    SqlPagarPAG_ISS_PERC: TFMTBCdField;
    CdsPagarCCT_NOVO: TStringField;
    CdsPagarPAG_ISS_RET: TFMTBCdField;
    CdsPagarPAG_ISS_PERC: TFMTBCdField;
    SqlReceberCCT_NOVO: TStringField;
    CdsReceberCCT_NOVO: TStringField;
    SqlCdsItemEnf: tsqlquery;
    DspItemEnf: TDataSetProvider;
    CdsItemEnf: TClientDataSet;
    DsItemEnf: TDataSource;
    SqlCdsItemEnfENF_REGISTRO: TIntegerField;
    SqlCdsItemEnfENF_IT_NOTANUMBER: TStringField;
    SqlCdsItemEnfOCP_CODIGO: TStringField;
    SqlCdsItemEnfENF_QTDE: TFMTBCdField;
    SqlCdsItemEnfENF_PRECO: TFMTBCdField;
    SqlCdsItemEnfENF_IPIALIQ: TFMTBCdField;
    SqlCdsItemEnfENF_VLSUBST: TFMTBCdField;
    SqlCdsItemEnfFOR_CODIGO: TStringField;
    CdsItemEnfENF_REGISTRO: TIntegerField;
    CdsItemEnfENF_IT_NOTANUMBER: TStringField;
    CdsItemEnfOCP_CODIGO: TStringField;
    CdsItemEnfENF_QTDE: TFMTBCdField;
    CdsItemEnfENF_PRECO: TFMTBCdField;
    CdsItemEnfENF_IPIALIQ: TFMTBCdField;
    CdsItemEnfENF_VLSUBST: TFMTBCdField;
    CdsItemEnfFOR_CODIGO: TStringField;
    SqlPagarParc: tsqlquery;
    DspPagarParc: TDataSetProvider;
    CdsPagarParc: TClientDataSet;
    DsPagarParc: TDataSource;
    SqlPagarParcPAG_CODIGO: TStringField;
    SqlPagarParcPPC_NUMER: TStringField;
    SqlPagarParcBAN_CODIGO: TStringField;
    SqlPagarParcPPC_BANCO: TStringField;
    SqlPagarParcCCT_CODIGO: TStringField;
    SqlPagarParcPCX_CODIGO: TStringField;
    SqlPagarParcPPC_NPARCELAS: TSmallintField;
    SqlPagarParcPPC_SITPAG: TStringField;
    SqlPagarParcPPC_STATUS: TStringField;
    SqlPagarParcPPC_DESCTO: TFMTBCdField;
    SqlPagarParcPPC_VLPARC: TFMTBCdField;
    SqlPagarParcPPC_VLPAGO: TFMTBCdField;
    SqlPagarParcPPC_OBS: TStringField;
    SqlPagarParcPPC_JUROS: TFMTBCdField;
    SqlPagarParcPPC_MULTA: TFMTBCdField;
    SqlPagarParcEMP_CODIGO: TStringField;
    SqlPagarParcPPC_NOSSONUM: TStringField;
    SqlPagarParcFOR_CODIGO: TStringField;
    SqlPagarParcPPC_FORMA: TStringField;
    SqlPagarParcCCT_NOVO: TStringField;
    SqlPagarParcBAN_APELIDO: TStringField;
    CdsPagarParcPAG_CODIGO: TStringField;
    CdsPagarParcPPC_NUMER: TStringField;
    CdsPagarParcBAN_CODIGO: TStringField;
    CdsPagarParcPPC_BANCO: TStringField;
    CdsPagarParcCCT_CODIGO: TStringField;
    CdsPagarParcPCX_CODIGO: TStringField;
    CdsPagarParcPPC_NPARCELAS: TSmallintField;
    CdsPagarParcPPC_SITPAG: TStringField;
    CdsPagarParcPPC_STATUS: TStringField;
    CdsPagarParcPPC_DESCTO: TFMTBCdField;
    CdsPagarParcPPC_VLPARC: TFMTBCdField;
    CdsPagarParcPPC_VLPAGO: TFMTBCdField;
    CdsPagarParcPPC_OBS: TStringField;
    CdsPagarParcPPC_JUROS: TFMTBCdField;
    CdsPagarParcPPC_MULTA: TFMTBCdField;
    CdsPagarParcEMP_CODIGO: TStringField;
    CdsPagarParcPPC_NOSSONUM: TStringField;
    CdsPagarParcFOR_CODIGO: TStringField;
    CdsPagarParcPPC_FORMA: TStringField;
    CdsPagarParcCCT_NOVO: TStringField;
    CdsPagarParcBAN_APELIDO: TStringField;
    SqlPagarParcPAG_REGISTRO: TIntegerField;
    CdsPagarParcPAG_REGISTRO: TIntegerField;
    SqlCdsItemEnfEMP_CODIGO: TStringField;
    CdsItemEnfEMP_CODIGO: TStringField;
    SqlPagarParcPPC_PREVISAO: TStringField;
    CdsPagarParcPPC_PREVISAO: TStringField;
    SqlRecParceCCT_NOVO: TStringField;
    SqlRecParceFPC_PREVISAO: TStringField;
    CdsRecParceCCT_NOVO: TStringField;
    CdsRecParceFPC_PREVISAO: TStringField;
    SqlPagarParcPPC_DTEMIS: TSQLTimeStampField;
    SqlPagarParcPPC_VENCTO: TSQLTimeStampField;
    SqlPagarParcPPC_PAGTO: TSQLTimeStampField;
    CdsPagarParcPPC_DTEMIS: TSQLTimeStampField;
    CdsPagarParcPPC_VENCTO: TSQLTimeStampField;
    CdsPagarParcPPC_PAGTO: TSQLTimeStampField;
    SqlCdsEnfCompEMP_CODIGO: TStringField;
    CdsEnfCompEMP_CODIGO: TStringField;
    SqlReceberFAT_REGISTRO: TIntegerField;
    CdsReceberFAT_REGISTRO: TIntegerField;
    SqlReceberOPE_CODIGO: TStringField;
    CdsReceberOPE_CODIGO: TStringField;
    CdsItemNotaNF_TOTAL_IPI_CC: TCurrencyField;
    SqlItemNotaNF_ICMSALIQ: TFMTBCdField;
    SqlItemNotaEMP_CODIGO: TStringField;
    CdsItemNotaNF_ICMSALIQ: TFMTBCdField;
    CdsItemNotaEMP_CODIGO: TStringField;
    SqlPagarPAG_REGISTRO: TIntegerField;
    CdsPagarPAG_REGISTRO: TIntegerField;
    SqlPedidosPED_REGISTRO: TIntegerField;
    CdsPedidosPED_REGISTRO: TIntegerField;
    SqlCdsItemEnfAMX_CODIGO: TStringField;
    CdsItemEnfAMX_CODIGO: TStringField;
    SqlRecParceFPC_STATUS_REMESSA: TStringField;
    SqlRecParceFPC_DATA_REMESSA: TDateField;
    SqlRecParceBAN_COD_APELIDO: TIntegerField;
    SqlRecParceFPC_STATUS_BAIXA: TStringField;
    CdsRecParceFPC_STATUS_REMESSA: TStringField;
    CdsRecParceFPC_DATA_REMESSA: TDateField;
    CdsRecParceBAN_COD_APELIDO: TIntegerField;
    CdsRecParceFPC_STATUS_BAIXA: TStringField;
    SQlNotaNF_NOTANUMBER: TStringField;
    SQlNotaNF_EMISSAO: TDateField;
    SQlNotaNF_SAIDA: TDateField;
    SQlNotaNF_HORASAIDA: TTimeField;
    SQlNotaNF_CONDPAGTO: TStringField;
    SQlNotaOPE_CODIGO: TStringField;
    SQlNotaOPE_NATUREZA: TStringField;
    SQlNotaOPE_AGRUPADO: TStringField;
    SQlNotaREP_CODIGO: TStringField;
    SQlNotaNF_ENTR_SAID: TStringField;
    SQlNotaNF_IMPRESS: TStringField;
    SQlNotaCLI_CODIGO: TStringField;
    SQlNotaNF_VLFRETE: TFMTBCdField;
    SQlNotaNF_VLSEGURO: TFMTBCdField;
    SQlNotaNF_DESP_ACES: TFMTBCdField;
    SQlNotaNF_ALIQ_ICMS: TFMTBCdField;
    SQlNotaNF_VL_DESCTO: TFMTBCdField;
    SQlNotaNF_PLACAVE: TStringField;
    SQlNotaNF_QTDE: TFMTBCdField;
    SQlNotaNF_PESOBRU: TFMTBCdField;
    SQlNotaNF_PESOLIQ: TFMTBCdField;
    SQlNotaNF_MARCA: TStringField;
    SQlNotaNF_NUMERO: TStringField;
    SQlNotaNF_INTERNO: TStringField;
    SQlNotaNF_CANCELADA: TStringField;
    SQlNotaPCL_CODIGO: TStringField;
    SQlNotaNF_AGRUPADO: TStringField;
    SQlNotaEMP_CODIGO: TStringField;
    SQlNotaNF_OBS_OPER: TStringField;
    SQlNotaNF_OBS_PEDI: TStringField;
    CdsNotaFiscalNF_NOTANUMBER: TStringField;
    CdsNotaFiscalNF_EMISSAO: TDateField;
    CdsNotaFiscalNF_SAIDA: TDateField;
    CdsNotaFiscalNF_HORASAIDA: TTimeField;
    CdsNotaFiscalNF_CONDPAGTO: TStringField;
    CdsNotaFiscalOPE_CODIGO: TStringField;
    CdsNotaFiscalOPE_NATUREZA: TStringField;
    CdsNotaFiscalOPE_AGRUPADO: TStringField;
    CdsNotaFiscalREP_CODIGO: TStringField;
    CdsNotaFiscalNF_ENTR_SAID: TStringField;
    CdsNotaFiscalNF_IMPRESS: TStringField;
    CdsNotaFiscalCLI_CODIGO: TStringField;
    CdsNotaFiscalNF_VLFRETE: TFMTBCdField;
    CdsNotaFiscalNF_VLSEGURO: TFMTBCdField;
    CdsNotaFiscalNF_DESP_ACES: TFMTBCdField;
    CdsNotaFiscalNF_ALIQ_ICMS: TFMTBCdField;
    CdsNotaFiscalNF_VL_DESCTO: TFMTBCdField;
    CdsNotaFiscalNF_PLACAVE: TStringField;
    CdsNotaFiscalNF_QTDE: TFMTBCdField;
    CdsNotaFiscalNF_PESOBRU: TFMTBCdField;
    CdsNotaFiscalNF_PESOLIQ: TFMTBCdField;
    CdsNotaFiscalNF_MARCA: TStringField;
    CdsNotaFiscalNF_NUMERO: TStringField;
    CdsNotaFiscalNF_INTERNO: TStringField;
    CdsNotaFiscalNF_CANCELADA: TStringField;
    CdsNotaFiscalPCL_CODIGO: TStringField;
    CdsNotaFiscalNF_AGRUPADO: TStringField;
    CdsNotaFiscalEMP_CODIGO: TStringField;
    CdsNotaFiscalNF_OBS_OPER: TStringField;
    CdsNotaFiscalNF_OBS_PEDI: TStringField;
    CdsNotaFiscalNF_TIPO_CC: TStringField;
    SQlNotaAMX_CODIGO: TStringField;
    CdsNotaFiscalAMX_CODIGO: TStringField;
    SqlPedidosPED_OBSG1: TStringField;
    SqlPedidosPED_OBSG2: TStringField;
    SqlPedidosPED_OBSG3: TStringField;
    SqlPedidosPED_OBSG4: TStringField;
    SqlPedidosPED_OBSG5: TStringField;
    SqlPedidosPED_OBSG6: TStringField;
    SqlPedidosPED_OBSG7: TStringField;
    CdsPedidosPED_OBSG1: TStringField;
    CdsPedidosPED_OBSG2: TStringField;
    CdsPedidosPED_OBSG3: TStringField;
    CdsPedidosPED_OBSG4: TStringField;
    CdsPedidosPED_OBSG5: TStringField;
    CdsPedidosPED_OBSG6: TStringField;
    CdsPedidosPED_OBSG7: TStringField;
    SqlPedidosPED_OBSGERAL: TMemoField;
    CdsPedidosPED_OBSGERAL: TMemoField;
    SQlNotaNF_OBSG1: TStringField;
    SQlNotaNF_OBSG2: TStringField;
    SQlNotaNF_OBSG3: TStringField;
    SQlNotaNF_OBSG4: TStringField;
    SQlNotaNF_OBSG5: TStringField;
    SQlNotaNF_OBSG6: TStringField;
    CdsNotaFiscalNF_OBSG1: TStringField;
    CdsNotaFiscalNF_OBSG2: TStringField;
    CdsNotaFiscalNF_OBSG3: TStringField;
    CdsNotaFiscalNF_OBSG4: TStringField;
    CdsNotaFiscalNF_OBSG5: TStringField;
    CdsNotaFiscalNF_OBSG6: TStringField;
    SQlNotaNF_TP_DESCTO: TStringField;
    SQlNotaNF_PC_DESCTO1: TFMTBCdField;
    SQlNotaNF_PC_DESCTO2: TFMTBCdField;
    CdsNotaFiscalNF_TP_DESCTO: TStringField;
    CdsNotaFiscalNF_PC_DESCTO1: TFMTBCdField;
    CdsNotaFiscalNF_PC_DESCTO2: TFMTBCdField;
    SQlNotaNF_BASE_ISS: TFMTBCdField;
    SQlNotaNF_VALOR_ISS: TFMTBCdField;
    CdsNotaFiscalNF_BASE_ISS: TFMTBCdField;
    CdsNotaFiscalNF_VALOR_ISS: TFMTBCdField;
    CdsNotaFiscalNF_STATUS_CC: TStringField;
    SQlNotaOPV_CODIGO: TIntegerField;
    CdsNotaFiscalOPV_CODIGO: TIntegerField;
    SqlItemNotaNF_PMATPRIMA: TFMTBCdField;
    CdsItemNotaNF_PMATPRIMA: TFMTBCdField;
    SQlNotaNF_ESPECIE: TStringField;
    CdsNotaFiscalNF_ESPECIE: TStringField;
    SqlPedidosPED_TOTUPS: TFMTBCdField;
    SqlPedidosPED_VLTUPS: TFMTBCdField;
    CdsPedidosPED_TOTUPS: TFMTBCdField;
    CdsPedidosPED_VLTUPS: TFMTBCdField;
    SqlPedItemPRF_OP: TStringField;
    CdsPedItemPRF_OP: TStringField;
    SqlPedItemPTI_CODIGO: TStringField;
    SqlPedItemPTI_SIGLA: TStringField;
    CdsPedItemPTI_CODIGO: TStringField;
    CdsPedItemPTI_SIGLA: TStringField;
    CdsReceberPED_CODIGO: TStringField;
    SqlPedidosPED_CODIGO: TStringField;
    SqlPedidosPED_PRODUCAO: TStringField;
    CdsPedidosPED_CODIGO: TStringField;
    CdsPedidosPED_PRODUCAO: TStringField;
    SqlPedItemPED_CODIGO: TStringField;
    CdsPedItemPED_CODIGO: TStringField;
    SQlNotaPED_CODIGO: TStringField;
    CdsNotaFiscalPED_CODIGO: TStringField;
    SqlItemNotaPED_CODIGO: TStringField;
    CdsItemNotaPED_CODIGO: TStringField;
    SqlNF_PEDNP_PED_CODIGO: TStringField;
    SqlNF_PEDEMP_CODIGO: TStringField;
    CdsNfPedNP_PED_CODIGO: TStringField;
    CdsNfPedEMP_CODIGO: TStringField;
    SqlEmbalagemPED_CODIGO: TStringField;
    CdsEmbalagemPED_CODIGO: TStringField;
    SqlReceberPED_CODIGO: TStringField;
    SqlCaixaFixoCCT_NOVO: TStringField;
    CdsCaixaFixoCCT_NOVO: TStringField;
    SqlItemEmbEBI_REGISTRO: TIntegerField;
    SqlItemEmbPEB_REGISTRO: TIntegerField;
    SqlItemEmbPRD_CODIGO: TStringField;
    SqlItemEmbEBI_QTDE: TIntegerField;
    SqlItemEmbEMP_CODIGO: TStringField;
    SqlItemEmbPRD_DESCRI: TStringField;
    CdsItemEmbEBI_REGISTRO: TIntegerField;
    CdsItemEmbPEB_REGISTRO: TIntegerField;
    CdsItemEmbPRD_CODIGO: TStringField;
    CdsItemEmbEBI_QTDE: TIntegerField;
    CdsItemEmbEMP_CODIGO: TStringField;
    CdsItemEmbPRD_DESCRI: TStringField;
    SqlRecParceFPC_FORMAPAGTO: TStringField;
    CdsRecParceFPC_FORMAPAGTO: TStringField;
    SqlPedidosPED_VLFRETE: TFMTBCdField;
    SqlPedidosPED_DESP_ACES: TFMTBCdField;
    SqlPedidosPED_VLSEGURO: TFMTBCdField;
    CdsPedidosPED_VLFRETE: TFMTBCdField;
    CdsPedidosPED_DESP_ACES: TFMTBCdField;
    CdsPedidosPED_VLSEGURO: TFMTBCdField;
    CdsPedItemCC_RECNO: TIntegerField;
    StpPedido: TSQLStoredProc;
    StpPedItem: TSQLStoredProc;
    SqlItemNotaNF_COMISSAO: TFMTBCdField;
    SqlItemNotaNF_QTDE_VAR1: TFMTBCdField;
    SqlItemNotaNF_QTDE_VAR2: TFMTBCdField;
    SqlItemNotaNF_QTDE_VAR3: TFMTBCdField;
    SqlItemNotaNF_QTDE_VAR4: TFMTBCdField;
    SqlItemNotaNF_QTDE_VAR5: TFMTBCdField;
    SqlItemNotaNF_QTDE_VAR6: TFMTBCdField;
    SqlItemNotaNF_QTDE_VAR7: TFMTBCdField;
    SqlItemNotaNF_QTDE_VAR8: TFMTBCdField;
    SqlItemNotaNF_FLAG_ATUALIZA_ESTOQUE: TStringField;
    CdsItemNotaNF_COMISSAO: TFMTBCdField;
    CdsItemNotaNF_QTDE_VAR1: TFMTBCdField;
    CdsItemNotaNF_QTDE_VAR2: TFMTBCdField;
    CdsItemNotaNF_QTDE_VAR3: TFMTBCdField;
    CdsItemNotaNF_QTDE_VAR4: TFMTBCdField;
    CdsItemNotaNF_QTDE_VAR5: TFMTBCdField;
    CdsItemNotaNF_QTDE_VAR6: TFMTBCdField;
    CdsItemNotaNF_QTDE_VAR7: TFMTBCdField;
    CdsItemNotaNF_QTDE_VAR8: TFMTBCdField;
    CdsItemNotaNF_FLAG_ATUALIZA_ESTOQUE: TStringField;
    SqlPedItemPRF_QTDE_FAT_VAR1: TFMTBCdField;
    SqlPedItemPRF_QTDE_FAT_VAR2: TFMTBCdField;
    SqlPedItemPRF_QTDE_FAT_VAR3: TFMTBCdField;
    SqlPedItemPRF_QTDE_FAT_VAR4: TFMTBCdField;
    SqlPedItemPRF_QTDE_FAT_VAR5: TFMTBCdField;
    SqlPedItemPRF_QTDE_FAT_VAR6: TFMTBCdField;
    SqlPedItemPRF_QTDE_FAT_VAR7: TFMTBCdField;
    SqlPedItemPRF_QTDE_FAT_VAR8: TFMTBCdField;
    SqlPedItemPRF_FLAG_ATUALIZA_ESTOQUE: TStringField;
    SqlPedItemPRF_ORIGEM_ITEM: TStringField;
    CdsPedItemPRF_QTDE_FAT_VAR1: TFMTBCdField;
    CdsPedItemPRF_QTDE_FAT_VAR2: TFMTBCdField;
    CdsPedItemPRF_QTDE_FAT_VAR3: TFMTBCdField;
    CdsPedItemPRF_QTDE_FAT_VAR4: TFMTBCdField;
    CdsPedItemPRF_QTDE_FAT_VAR5: TFMTBCdField;
    CdsPedItemPRF_QTDE_FAT_VAR6: TFMTBCdField;
    CdsPedItemPRF_QTDE_FAT_VAR7: TFMTBCdField;
    CdsPedItemPRF_QTDE_FAT_VAR8: TFMTBCdField;
    CdsPedItemPRF_FLAG_ATUALIZA_ESTOQUE: TStringField;
    CdsPedItemPRF_ORIGEM_ITEM: TStringField;
    SqlPedidosPED_FLAG_PED_DUPL: TStringField;
    CdsPedidosPED_FLAG_PED_DUPL: TStringField;
    SqlRecParceFPC_DESCONTADO: TStringField;
    SqlRecParceFPC_DATADESCTO: TDateField;
    SqlRecParceFPC_CONFIRMADESCTO: TStringField;
    SqlRecParceFPC_CONFIRMADEVOLUCAO: TStringField;
    SqlRecParceFPC_DATADEVOLUCAO: TDateField;
    SqlRecParceFPC_OBS_DESCTO: TStringField;
    SqlRecParceFPC_JUROS_DESCTO: TFMTBCdField;
    SqlRecParcePAG_CODIGO: TStringField;
    CdsRecParceFPC_DESCONTADO: TStringField;
    CdsRecParceFPC_DATADESCTO: TDateField;
    CdsRecParceFPC_CONFIRMADESCTO: TStringField;
    CdsRecParceFPC_CONFIRMADEVOLUCAO: TStringField;
    CdsRecParceFPC_DATADEVOLUCAO: TDateField;
    CdsRecParceFPC_OBS_DESCTO: TStringField;
    CdsRecParceFPC_JUROS_DESCTO: TFMTBCdField;
    CdsRecParcePAG_CODIGO: TStringField;
    CdsPagarParcN_PARC_CC: TStringField;
    CdsRecParceN_PARC_CC: TStringField;
    SQlNotaOPE_REDU_ICM: TFMTBCdField;
    CdsNotaFiscalOPE_REDU_ICM: TFMTBCdField;
    SQlNotaNF_OBS_OPER_AVISO2: TStringField;
    CdsNotaFiscalNF_OBS_OPER_AVISO2: TStringField;
    SqlItemCompraOCI_PRECO: TFMTBCdField;
    CdsItemCompraOCI_PRECO: TFMTBCdField;
    SqlCdsEnfENF_TIPO_FRETE: TIntegerField;
    CdsEnfENF_TIPO_FRETE: TIntegerField;
    SqlCdsEnfOPE_CODIGO: TStringField;
    CdsEnfOPE_CODIGO: TStringField;
    SqlCdsEnfENF_TIPO_NF_ENTRADA: TStringField;
    CdsEnfENF_TIPO_NF_ENTRADA: TStringField;
    SqlCdsEnfENF_MODELO_NF: TStringField;
    CdsEnfENF_MODELO_NF: TStringField;
    SqlRecParceFPC_BANCO_CHEQUE: TIntegerField;
    SqlRecParceFPC_NUM_CHEQUE: TStringField;
    SqlRecParceFPC_NUM_CHEQUE_DV: TStringField;
    CdsRecParceFPC_BANCO_CHEQUE: TIntegerField;
    CdsRecParceFPC_NUM_CHEQUE: TStringField;
    CdsRecParceFPC_NUM_CHEQUE_DV: TStringField;
    SqlRecParceFPC_CHEQUE_DATA: TDateField;
    CdsRecParceFPC_CHEQUE_DATA: TDateField;
    SqlRecParceFPC_SACADO_CHEQUE: TStringField;
    CdsRecParceFPC_SACADO_CHEQUE: TStringField;
    SqlPedItemPRF_PRODUTO_AGREGADO: TStringField;
    CdsPedItemPRF_PRODUTO_AGREGADO: TStringField;
    SqlItemNotaNF_PRODUTO_AGREGADO: TStringField;
    CdsItemNotaNF_PRODUTO_AGREGADO: TStringField;
    SqlReceberFAT_EXCLUSAO: TStringField;
    CdsReceberFAT_EXCLUSAO: TStringField;
    SqlRecParceFPC_EXCLUSAO: TStringField;
    CdsRecParceFPC_EXCLUSAO: TStringField;
    SqlPagarPAG_EXCLUSAO: TStringField;
    CdsPagarPAG_EXCLUSAO: TStringField;
    SqlPagarParcPPC_EXCLUSAO: TStringField;
    CdsPagarParcPPC_EXCLUSAO: TStringField;
    SqlReceberFAT_DATA_EXCLUSAO: TDateField;
    SqlReceberUSU_CODIGO: TIntegerField;
    SqlReceberUSU_LOGIN: TStringField;
    CdsReceberFAT_DATA_EXCLUSAO: TDateField;
    CdsReceberUSU_CODIGO: TIntegerField;
    CdsReceberUSU_LOGIN: TStringField;
    SqlPagarPAG_DATA_EXCLUSAO: TDateField;
    SqlPagarUSU_CODIGO: TIntegerField;
    SqlPagarUSU_LOGIN: TStringField;
    CdsPagarPAG_DATA_EXCLUSAO: TDateField;
    CdsPagarUSU_CODIGO: TIntegerField;
    CdsPagarUSU_LOGIN: TStringField;
    SqlPagarParcPPC_DATA_EXCLUSAO: TDateField;
    SqlPagarParcUSU_CODIGO: TIntegerField;
    SqlPagarParcUSU_LOGIN: TStringField;
    CdsPagarParcPPC_DATA_EXCLUSAO: TDateField;
    CdsPagarParcUSU_CODIGO: TIntegerField;
    CdsPagarParcUSU_LOGIN: TStringField;
    SqlRecParceFPC_DATA_EXCLUSAO: TDateField;
    SqlRecParceUSU_CODIGO: TIntegerField;
    SqlRecParceUSU_LOGIN: TStringField;
    CdsRecParceFPC_DATA_EXCLUSAO: TDateField;
    CdsRecParceUSU_CODIGO: TIntegerField;
    CdsRecParceUSU_LOGIN: TStringField;
    SqlReceberFAT_MOTIVO_EXCLUSAO: TStringField;
    CdsReceberFAT_MOTIVO_EXCLUSAO: TStringField;
    SqlRecParceFPC_MOTIVO_EXCLUSAO: TStringField;
    CdsRecParceFPC_MOTIVO_EXCLUSAO: TStringField;
    SqlPagarPAG_MOTIVO_EXCLUSAO: TStringField;
    SqlPagarParcPPC_MOTIVO_EXCLUSAO: TStringField;
    CdsPagarPAG_MOTIVO_EXCLUSAO: TStringField;
    CdsPagarParcPPC_MOTIVO_EXCLUSAO: TStringField;
    SqlReceberFAT_HORA_EXCLUSAO: TTimeField;
    CdsReceberFAT_HORA_EXCLUSAO: TTimeField;
    SqlRecParceFPC_HORA_EXCLUSAO: TTimeField;
    CdsRecParceFPC_HORA_EXCLUSAO: TTimeField;
    SqlPagarPAG_HORA_EXCLUSAO: TTimeField;
    SqlPagarParcPPC_HORA_EXCLUSAO: TTimeField;
    CdsPagarPAG_HORA_EXCLUSAO: TTimeField;
    CdsPagarParcPPC_HORA_EXCLUSAO: TTimeField;
    SQlNotaOPE_SEMVLCOM: TStringField;
    CdsNotaFiscalOPE_SEMVLCOM: TStringField;
    SqlItemNotaNF_HORA: TTimeField;
    CdsItemNotaNF_HORA: TTimeField;
    SqlPagarParcPPC_NUM_CHEQUE: TStringField;
    SqlPagarParcPPC_NUM_CHEQUE_DV: TStringField;
    CdsPagarParcPPC_NUM_CHEQUE: TStringField;
    CdsPagarParcPPC_NUM_CHEQUE_DV: TStringField;
    SqlPagarParcPPC_IMP_CHEQUE: TStringField;
    CdsPagarParcPPC_IMP_CHEQUE: TStringField;
    SQlNotaNF_TIPODOC: TStringField;
    CdsNotaFiscalNF_TIPODOC: TStringField;
    SqlItemNotaNF_IPIVALOR: TFMTBCdField;
    SqlItemNotaNF_ICMSVALOR: TFMTBCdField;
    SqlItemNotaNTP_CFOP: TIntegerField;
    CdsItemNotaNF_IPIVALOR: TFMTBCdField;
    CdsItemNotaNF_ICMSVALOR: TFMTBCdField;
    CdsItemNotaNTP_CFOP: TIntegerField;
    SQlNotaNF_MODELO_NF: TStringField;
    SQlNotaNF_SERIE: TStringField;
    CdsNotaFiscalNF_MODELO_NF: TStringField;
    CdsNotaFiscalNF_SERIE: TStringField;
    SqlPedItemPRD_PESOKG: TFMTBCdField;
    CdsPedItemPRD_PESOKG: TFMTBCdField;
    SQlNotaNF_CHAVE_NFE: TStringField;
    CdsNotaFiscalNF_CHAVE_NFE: TStringField;
    SQlNotaNF_NUM_NFE: TIntegerField;
    CdsNotaFiscalNF_NUM_NFE: TIntegerField;
    SqlPedidosPED_DESP_IMPOR: TFMTBCdField;
    CdsPedidosPED_DESP_IMPOR: TFMTBCdField;
    SQlNotaNF_DESP_IMPORT: TFMTBCdField;
    CdsNotaFiscalNF_DESP_IMPORT: TFMTBCdField;
    CdsNfeParce: TClientDataSet;
    DspNfeParce: TDataSetProvider;
    SqlNFeParce: tsqlquery;
    DsNfeParce: TDataSource;
    SqlNFeParceFAT_CODIGO: TStringField;
    SqlNFeParceFPC_NUMER: TStringField;
    SqlNFeParceREP_CODIGO: TStringField;
    SqlNFeParceBAN_CODIGO: TStringField;
    SqlNFeParceCCT_CODIGO: TStringField;
    SqlNFeParcePCX_CODIGO: TStringField;
    SqlNFeParceFPC_DTEMIS: TSQLTimeStampField;
    SqlNFeParceFPC_NPARCELAS: TSmallintField;
    SqlNFeParceFPC_COBNUM: TStringField;
    SqlNFeParceFPC_COBTIPO: TStringField;
    SqlNFeParceFPC_TIPODOC: TStringField;
    SqlNFeParceFPC_SITPAG: TStringField;
    SqlNFeParceFPC_STATUS: TStringField;
    SqlNFeParceFPC_DESCTO: TFMTBCdField;
    SqlNFeParceFPC_DTDESC: TSQLTimeStampField;
    SqlNFeParceFPC_VENCTO: TSQLTimeStampField;
    SqlNFeParceFPC_PAGTO: TSQLTimeStampField;
    SqlNFeParceFPC_OBS: TStringField;
    SqlNFeParceCLI_CODIGO: TStringField;
    SqlNFeParceFPC_IMPDUP: TStringField;
    SqlNFeParceFPC_JUROS: TFMTBCdField;
    SqlNFeParceFPC_MULTA: TFMTBCdField;
    SqlNFeParceFPC_VL_RET: TFMTBCdField;
    SqlNFeParceEMP_CODIGO: TStringField;
    SqlNFeParceCCT_NOVO: TStringField;
    SqlNFeParceFPC_PREVISAO: TStringField;
    SqlNFeParceFPC_STATUS_REMESSA: TStringField;
    SqlNFeParceFPC_DATA_REMESSA: TDateField;
    SqlNFeParceBAN_COD_APELIDO: TIntegerField;
    SqlNFeParceFPC_STATUS_BAIXA: TStringField;
    SqlNFeParceFPC_FORMAPAGTO: TStringField;
    SqlNFeParceFPC_DESCONTADO: TStringField;
    SqlNFeParceFPC_DATADESCTO: TDateField;
    SqlNFeParceFPC_CONFIRMADESCTO: TStringField;
    SqlNFeParceFPC_CONFIRMADEVOLUCAO: TStringField;
    SqlNFeParceFPC_DATADEVOLUCAO: TDateField;
    SqlNFeParceFPC_OBS_DESCTO: TStringField;
    SqlNFeParceFPC_JUROS_DESCTO: TFMTBCdField;
    SqlNFeParcePAG_CODIGO: TStringField;
    SqlNFeParceFPC_BANCO_CHEQUE: TIntegerField;
    SqlNFeParceFPC_NUM_CHEQUE: TStringField;
    SqlNFeParceFPC_NUM_CHEQUE_DV: TStringField;
    SqlNFeParceFPC_CHEQUE_DATA: TDateField;
    SqlNFeParceFPC_SACADO_CHEQUE: TStringField;
    SqlNFeParceFPC_EXCLUSAO: TStringField;
    SqlNFeParceFPC_DATA_EXCLUSAO: TDateField;
    SqlNFeParceFPC_HORA_EXCLUSAO: TTimeField;
    SqlNFeParceFPC_MOTIVO_EXCLUSAO: TStringField;
    SqlNFeParceUSU_CODIGO: TIntegerField;
    SqlNFeParceUSU_LOGIN: TStringField;
    CdsNfeParceFAT_CODIGO: TStringField;
    CdsNfeParceFPC_NUMER: TStringField;
    CdsNfeParceREP_CODIGO: TStringField;
    CdsNfeParceBAN_CODIGO: TStringField;
    CdsNfeParceCCT_CODIGO: TStringField;
    CdsNfeParcePCX_CODIGO: TStringField;
    CdsNfeParceFPC_DTEMIS: TSQLTimeStampField;
    CdsNfeParceFPC_NPARCELAS: TSmallintField;
    CdsNfeParceFPC_COBNUM: TStringField;
    CdsNfeParceFPC_COBTIPO: TStringField;
    CdsNfeParceFPC_TIPODOC: TStringField;
    CdsNfeParceFPC_SITPAG: TStringField;
    CdsNfeParceFPC_STATUS: TStringField;
    CdsNfeParceFPC_DESCTO: TFMTBCdField;
    CdsNfeParceFPC_DTDESC: TSQLTimeStampField;
    CdsNfeParceFPC_VENCTO: TSQLTimeStampField;
    CdsNfeParceFPC_OBS: TStringField;
    CdsNfeParceCLI_CODIGO: TStringField;
    CdsNfeParceFPC_IMPDUP: TStringField;
    CdsNfeParceFPC_JUROS: TFMTBCdField;
    CdsNfeParceFPC_MULTA: TFMTBCdField;
    CdsNfeParceFPC_VL_RET: TFMTBCdField;
    CdsNfeParceEMP_CODIGO: TStringField;
    CdsNfeParceCCT_NOVO: TStringField;
    CdsNfeParceFPC_PREVISAO: TStringField;
    CdsNfeParceFPC_STATUS_REMESSA: TStringField;
    CdsNfeParceFPC_DATA_REMESSA: TDateField;
    CdsNfeParceBAN_COD_APELIDO: TIntegerField;
    CdsNfeParceFPC_STATUS_BAIXA: TStringField;
    CdsNfeParceFPC_FORMAPAGTO: TStringField;
    CdsNfeParceFPC_DESCONTADO: TStringField;
    CdsNfeParceFPC_DATADESCTO: TDateField;
    CdsNfeParceFPC_CONFIRMADESCTO: TStringField;
    CdsNfeParceFPC_CONFIRMADEVOLUCAO: TStringField;
    CdsNfeParceFPC_DATADEVOLUCAO: TDateField;
    CdsNfeParceFPC_OBS_DESCTO: TStringField;
    CdsNfeParceFPC_JUROS_DESCTO: TFMTBCdField;
    CdsNfeParcePAG_CODIGO: TStringField;
    CdsNfeParceFPC_BANCO_CHEQUE: TIntegerField;
    CdsNfeParceFPC_NUM_CHEQUE: TStringField;
    CdsNfeParceFPC_NUM_CHEQUE_DV: TStringField;
    CdsNfeParceFPC_CHEQUE_DATA: TDateField;
    CdsNfeParceFPC_SACADO_CHEQUE: TStringField;
    CdsNfeParceFPC_EXCLUSAO: TStringField;
    CdsNfeParceFPC_DATA_EXCLUSAO: TDateField;
    CdsNfeParceFPC_HORA_EXCLUSAO: TTimeField;
    CdsNfeParceFPC_MOTIVO_EXCLUSAO: TStringField;
    CdsNfeParceUSU_CODIGO: TIntegerField;
    CdsNfeParceUSU_LOGIN: TStringField;
    SQLRecItemFIT_ICMALIQ: TFMTBCdField;
    CdsRecItemFIT_ICMALIQ: TFMTBCdField;
    SQLRecItemCLI_CODIGO: TStringField;
    CdsRecItemCLI_CODIGO: TStringField;
    SqlPedItemPRF_VALOR_ICMS: TFMTBCdField;
    CdsPedItemPRF_VALOR_ICMS: TFMTBCdField;
    SqlPedItemPRD_PESOLIQ2: TFMTBCdField;
    CdsPedItemPRD_PESOLIQ: TFMTBCdField;
    SqlCdsItemEnfPRD_DESCRI: TStringField;
    CdsItemEnfPRD_DESCRI: TStringField;
    SqlItemNotaNF_IPIBASE: TFMTBCdField;
    SqlItemNotaNF_ICMSBASE: TFMTBCdField;
    SqlItemNotaNF_SUBTRIBASE: TFMTBCdField;
    SqlItemNotaNF_ALIQSUBTRIB: TFMTBCdField;
    SqlItemNotaNF_MVAPERC: TFMTBCdField;
    CdsItemNotaNF_IPIBASE: TFMTBCdField;
    CdsItemNotaNF_ICMSBASE: TFMTBCdField;
    CdsItemNotaNF_SUBTRIBASE: TFMTBCdField;
    CdsItemNotaNF_ALIQSUBTRIB: TFMTBCdField;
    CdsItemNotaNF_MVAPERC: TFMTBCdField;
    SqlItemNotaNF_ICMSREDUCAOPERC: TFMTBCdField;
    CdsItemNotaNF_ICMSREDUCAOPERC: TFMTBCdField;
    SqlItemNotaNF_ALIQDOSIMPLES: TFMTBCdField;
    SqlItemNotaNF_CREDICMSDOSIMPLES: TFMTBCdField;
    CdsItemNotaNF_ALIQDOSIMPLES: TFMTBCdField;
    CdsItemNotaNF_CREDICMSDOSIMPLES: TFMTBCdField;
    SqlCdsEnfENF_CHAVE_NFE: TStringField;
    CdsEnfENF_CHAVE_NFE: TStringField;
    SQlNotaNF_STATUS_NFE: TStringField;
    SQlNotaNF_ENVIADO_NFE_EMAIL: TStringField;
    SQlNotaNF_EMAIL_ENVIO_NFE: TStringField;
    SQlNotaNF_LOTE_NFE: TIntegerField;
    SQlNotaNF_PROTOCOLO_NFE: TStringField;
    SQlNotaNF_PROTOCOLO_NFE_CANC: TStringField;
    SQlNotaNF_PROTOCOLO_AUTORIZACAO: TStringField;
    SQlNotaNF_DATA_AUTORIZACAO: TDateField;
    SQlNotaNF_HORA_AUTORIZACAO: TTimeField;
    SQlNotaNF_ALIQCREDSIMPLES: TFMTBCdField;
    SQlNotaNF_VLCREDSIMPLES: TFMTBCdField;
    SQlNotaNF_ALIQPIS: TFMTBCdField;
    SQlNotaNF_ALIQCOFINS: TFMTBCdField;
    CdsNotaFiscalNF_STATUS_NFE: TStringField;
    CdsNotaFiscalNF_ENVIADO_NFE_EMAIL: TStringField;
    CdsNotaFiscalNF_EMAIL_ENVIO_NFE: TStringField;
    CdsNotaFiscalNF_LOTE_NFE: TIntegerField;
    CdsNotaFiscalNF_PROTOCOLO_NFE: TStringField;
    CdsNotaFiscalNF_PROTOCOLO_NFE_CANC: TStringField;
    CdsNotaFiscalNF_PROTOCOLO_AUTORIZACAO: TStringField;
    CdsNotaFiscalNF_DATA_AUTORIZACAO: TDateField;
    CdsNotaFiscalNF_HORA_AUTORIZACAO: TTimeField;
    CdsNotaFiscalNF_ALIQCREDSIMPLES: TFMTBCdField;
    CdsNotaFiscalNF_VLCREDSIMPLES: TFMTBCdField;
    CdsNotaFiscalNF_ALIQPIS: TFMTBCdField;
    CdsNotaFiscalNF_ALIQCOFINS: TFMTBCdField;
    SqlItemNotaNF_IFRETE: TFMTBCdField;
    SqlItemNotaNF_ISEGURO: TFMTBCdField;
    SqlItemNotaNF_IDESP_ACES: TFMTBCdField;
    SqlItemNotaNF_IBASEISSQN: TFMTBCdField;
    SqlItemNotaNF_IALIQISSQN: TFMTBCdField;
    SqlItemNotaNF_IVLISSQN: TFMTBCdField;
    SqlItemNotaNF_CST_PIS: TFMTBCdField;
    SqlItemNotaNF_BASE_PIS: TFMTBCdField;
    SqlItemNotaNF_ALIQPIS: TFMTBCdField;
    SqlItemNotaNF_VLPIS: TFMTBCdField;
    SqlItemNotaNF_CST_COFINS: TFMTBCdField;
    SqlItemNotaNF_BASE_COFINS: TFMTBCdField;
    SqlItemNotaNF_ALIQCOFINS: TFMTBCdField;
    CdsItemNotaNF_IFRETE: TFMTBCdField;
    CdsItemNotaNF_ISEGURO: TFMTBCdField;
    CdsItemNotaNF_IDESP_ACES: TFMTBCdField;
    CdsItemNotaNF_IBASEISSQN: TFMTBCdField;
    CdsItemNotaNF_IALIQISSQN: TFMTBCdField;
    CdsItemNotaNF_IVLISSQN: TFMTBCdField;
    CdsItemNotaNF_CST_PIS: TFMTBCdField;
    CdsItemNotaNF_BASE_PIS: TFMTBCdField;
    CdsItemNotaNF_ALIQPIS: TFMTBCdField;
    CdsItemNotaNF_VLPIS: TFMTBCdField;
    CdsItemNotaNF_CST_COFINS: TFMTBCdField;
    CdsItemNotaNF_BASE_COFINS: TFMTBCdField;
    CdsItemNotaNF_ALIQCOFINS: TFMTBCdField;
    SqlCdsEnfENF_VLPIS: TFMTBCdField;
    SqlCdsEnfENF_VLCOFINS: TFMTBCdField;
    SqlCdsEnfENF_ALIQPIS: TFMTBCdField;
    SqlCdsEnfENF_CHAVE_NFESE: TStringField;
    CdsEnfENF_VLPIS: TFMTBCdField;
    CdsEnfENF_VLCOFINS: TFMTBCdField;
    CdsEnfENF_ALIQPIS: TFMTBCdField;
    CdsEnfENF_CHAVE_NFESE: TStringField;
    SqlCdsItemEnfENF_ICMSALIQ: TFMTBCdField;
    SqlCdsItemEnfENF_UNIDADE_TRABALHO: TFMTBCdField;
    SqlCdsItemEnfENF_LOTE: TStringField;
    SqlCdsItemEnfENF_ICMS: TFMTBCdField;
    SqlCdsItemEnfENF_CFOP: TStringField;
    SqlCdsItemEnfENF_IT_VLIPI: TFMTBCdField;
    SqlCdsItemEnfENF_IT_BASEIPI: TFMTBCdField;
    SqlCdsItemEnfENF_IT_NUM_DI: TFMTBCdField;
    SqlCdsItemEnfENF_IT_NCM: TIntegerField;
    SqlCdsItemEnfENF_IT_DESCTO: TFMTBCdField;
    SqlCdsItemEnfENF_IT_BASEICMS: TFMTBCdField;
    SqlCdsItemEnfENF_IT_BASESUBTRIB: TFMTBCdField;
    SqlCdsItemEnfENF_IT_VALFRETE: TFMTBCdField;
    SqlCdsItemEnfENF_IT_VLSEGURO: TFMTBCdField;
    SqlCdsItemEnfENF_IT_VLDESP_ACES: TFMTBCdField;
    SqlCdsItemEnfENF_IT_VLSUBTRIB: TFMTBCdField;
    SqlCdsItemEnfENF_IT_ALIQSUBTRIB: TFMTBCdField;
    SqlCdsItemEnfENF_IT_ISSQN: TFMTBCdField;
    SqlCdsItemEnfENF_IT_ALIQISSQN: TFMTBCdField;
    SqlCdsItemEnfENF_IT_VLISSQN: TFMTBCdField;
    SqlCdsItemEnfENF_IT_ALIQPIS: TFMTBCdField;
    SqlCdsItemEnfENF_IT_VLPIS: TFMTBCdField;
    SqlCdsItemEnfENF_IT_ALIQCOFINS: TFMTBCdField;
    SqlCdsItemEnfENF_IT_VLCOFINS: TFMTBCdField;
    SqlCdsItemEnfENF_CST_PIS: TFMTBCdField;
    SqlCdsItemEnfENF_BASEPIS: TFMTBCdField;
    SqlCdsItemEnfENF_CST_COFINS: TFMTBCdField;
    SqlCdsItemEnfENF_BASECOFINS: TFMTBCdField;
    CdsItemEnfENF_ICMSALIQ: TFMTBCdField;
    CdsItemEnfENF_UNIDADE_TRABALHO: TFMTBCdField;
    CdsItemEnfENF_LOTE: TStringField;
    CdsItemEnfENF_ICMS: TFMTBCdField;
    CdsItemEnfENF_CFOP: TStringField;
    CdsItemEnfENF_IT_VLIPI: TFMTBCdField;
    CdsItemEnfENF_IT_BASEIPI: TFMTBCdField;
    CdsItemEnfENF_IT_NUM_DI: TFMTBCdField;
    CdsItemEnfENF_IT_NCM: TIntegerField;
    CdsItemEnfENF_IT_DESCTO: TFMTBCdField;
    CdsItemEnfENF_IT_BASEICMS: TFMTBCdField;
    CdsItemEnfENF_IT_BASESUBTRIB: TFMTBCdField;
    CdsItemEnfENF_IT_VALFRETE: TFMTBCdField;
    CdsItemEnfENF_IT_VLSEGURO: TFMTBCdField;
    CdsItemEnfENF_IT_VLDESP_ACES: TFMTBCdField;
    CdsItemEnfENF_IT_VLSUBTRIB: TFMTBCdField;
    CdsItemEnfENF_IT_ALIQSUBTRIB: TFMTBCdField;
    CdsItemEnfENF_IT_ISSQN: TFMTBCdField;
    CdsItemEnfENF_IT_ALIQISSQN: TFMTBCdField;
    CdsItemEnfENF_IT_VLISSQN: TFMTBCdField;
    CdsItemEnfENF_IT_ALIQPIS: TFMTBCdField;
    CdsItemEnfENF_IT_VLPIS: TFMTBCdField;
    CdsItemEnfENF_IT_ALIQCOFINS: TFMTBCdField;
    CdsItemEnfENF_IT_VLCOFINS: TFMTBCdField;
    CdsItemEnfENF_CST_PIS: TFMTBCdField;
    CdsItemEnfENF_BASEPIS: TFMTBCdField;
    CdsItemEnfENF_CST_COFINS: TFMTBCdField;
    CdsItemEnfENF_BASECOFINS: TFMTBCdField;
    SqlItemNotaOPE_CODIGO: TStringField;
    CdsItemNotaOPE_CODIGO: TStringField;
    SqlPedItemAMX_CODIGO_DESTINO: TStringField;
    SqlPedItemAMX_CODIGO_ORIGEM: TStringField;
    SqlPedItemUSU_CODIGO: TIntegerField;
    SqlPedItemPRD_CODIGO: TStringField;
    CdsPedItemAMX_CODIGO_DESTINO: TStringField;
    CdsPedItemAMX_CODIGO_ORIGEM: TStringField;
    CdsPedItemUSU_CODIGO: TIntegerField;
    CdsPedItemPRD_CODIGO: TStringField;
    SqlItemNotaNF_VLCOFINS: TFMTBCdField;
    SqlItemNotaAMX_CODIGO_DESTINO: TStringField;
    SqlItemNotaAMX_CODIGO_ORIGEM: TStringField;
    SqlItemNotaUSU_CODIGO: TIntegerField;
    SqlItemNotaPRD_CODIGO: TStringField;
    CdsItemNotaNF_VLCOFINS: TFMTBCdField;
    CdsItemNotaAMX_CODIGO_DESTINO: TStringField;
    CdsItemNotaAMX_CODIGO_ORIGEM: TStringField;
    CdsItemNotaUSU_CODIGO: TIntegerField;
    CdsItemNotaPRD_CODIGO: TStringField;
    SqlPedidosAMX_CODIGO: TStringField;
    CdsPedidosAMX_CODIGO: TStringField;
    SqlPedidosPED_OS: TStringField;
    CdsPedidosPED_OS: TStringField;
    SQlNotaSRV_REGISTRO: TIntegerField;
    SQlNotaNF_NFSE_VLR_IR: TFMTBCdField;
    SQlNotaNF_NFSE_VLR_CSLL: TFMTBCdField;
    SQlNotaNF_NFSE_VLR_INSS: TFMTBCdField;
    SQlNotaNF_NFSE_VLR_COFINS: TFMTBCdField;
    SQlNotaNF_NFSE_VLR_PIS: TFMTBCdField;
    SQlNotaNF_NFSE_VLR_DEDUCOES: TFMTBCdField;
    SQlNotaNF_NFSE_VLR_ISS: TFMTBCdField;
    SQlNotaNF_NFSE_VLR_BASE_CALCULO: TFMTBCdField;
    SQlNotaNF_NFSE_DESCRICAO: TBlobField;
    CdsNotaFiscalSRV_REGISTRO: TIntegerField;
    CdsNotaFiscalNF_NFSE_VLR_IR: TFMTBCdField;
    CdsNotaFiscalNF_NFSE_VLR_CSLL: TFMTBCdField;
    CdsNotaFiscalNF_NFSE_VLR_INSS: TFMTBCdField;
    CdsNotaFiscalNF_NFSE_VLR_COFINS: TFMTBCdField;
    CdsNotaFiscalNF_NFSE_VLR_PIS: TFMTBCdField;
    CdsNotaFiscalNF_NFSE_VLR_DEDUCOES: TFMTBCdField;
    CdsNotaFiscalNF_NFSE_VLR_ISS: TFMTBCdField;
    CdsNotaFiscalNF_NFSE_VLR_BASE_CALCULO: TFMTBCdField;
    CdsNotaFiscalNF_NFSE_DESCRICAO: TBlobField;
    SQlNotaNF_STATUS_NFSE: TStringField;
    CdsNotaFiscalNF_STATUS_NFSE: TStringField;
    SqlReceberNF_NUM_NFE: TIntegerField;
    CdsReceberNF_NUM_NFE: TIntegerField;
    SQlNotaNF_NFSE_ALIQUOTA_ISS: TFMTBCdField;
    CdsNotaFiscalNF_NFSE_ALIQUOTA_ISS: TFMTBCdField;
    SqlRecParceFPC_COBNUM: TStringField;
    CdsRecParceFPC_COBNUM: TStringField;
    SqlItemNotaPRF_REGISTRO: TIntegerField;
    CdsItemNotaPRF_REGISTRO: TIntegerField;
    SQlNotaNF_EXPORT_UF_EMBARQUE: TStringField;
    SQlNotaNF_EXPORT_LOCAL_EMBARQUE: TStringField;
    CdsNotaFiscalNF_EXPORT_UF_EMBARQUE: TStringField;
    CdsNotaFiscalNF_EXPORT_LOCAL_EMBARQUE: TStringField;
    SqlCdsItemEnfREPETICAO_REFER: TIntegerField;
    CdsItemEnfREPETICAO_REFER: TIntegerField;
    SqlPedItemPRF_PRDDESCRI: TStringField;
    SqlPedItemPRF_COMPL_DESCRI: TStringField;
    CdsPedItemPRF_PRDDESCRI: TStringField;
    CdsPedItemPRF_COMPL_DESCRI: TStringField;
    SqlItemNotaPRD_DESCRI: TStringField;
    SqlItemNotaPRD_COMPL_DESCRI: TStringField;
    CdsItemNotaPRD_DESCRI: TStringField;
    CdsItemNotaPRD_COMPL_DESCRI: TStringField;
    SQlNotaNF_VALORTOT_PIS: TFMTBCdField;
    SQlNotaNF_VALORTOT_COFINS: TFMTBCdField;
    CdsNotaFiscalNF_VALORTOT_PIS: TFMTBCdField;
    CdsNotaFiscalNF_VALORTOT_COFINS: TFMTBCdField;
    SqlItemNotaIPI_CODIGO: TStringField;
    CdsItemNotaIPI_CODIGO: TStringField;
    SQlNotaNF_COMPLEMENTAR: TStringField;
    CdsNotaFiscalNF_COMPLEMENTAR: TStringField;
    SqlCdsEnfENF_ALIQCOFINS: TFMTBCdField;
    CdsEnfENF_ALIQCOFINS: TFMTBCdField;
    SqlCdsEnfENF_DADOS_ADICIONAIS: TMemoField;
    CdsEnfENF_DADOS_ADICIONAIS: TMemoField;
    SqlItemNotaSTB_TRIBUTACAO: TStringField;
    CdsItemNotaSTB_TRIBUTACAO: TStringField;
    SqlCdsEnfENF_FECHADO_PROJETO_OBRA: TStringField;
    CdsEnfENF_FECHADO_PROJETO_OBRA: TStringField;
    SqlItemNotaPRG_REGISTRO: TIntegerField;
    CdsItemNotaPRG_REGISTRO: TIntegerField;
    SQlNotaNFE_STATUS_PRODUCAO: TStringField;
    SQlNotaNF_OBSERVACAO: TBlobField;
    CdsNotaFiscalNFE_STATUS_PRODUCAO: TStringField;
    CdsNotaFiscalNF_OBSERVACAO: TBlobField;
    SqlItemNotaNF_PRECO: TFMTBCdField;
    CdsItemNotaNF_PRECO: TFMTBCdField;
    SqlCdsEnfENF_FRETEPARTICIPATOT: TStringField;
    CdsEnfENF_FRETEPARTICIPATOT: TStringField;
    SQlNotaNF_TIPO_FRETE: TStringField;
    CdsNotaFiscalNF_TIPO_FRETE: TStringField;
    SqlCdsEnfENF_XML: TBlobField;
    CdsEnfENF_XML: TBlobField;
    SqlItemNotaNF_CUSTO: TFMTBCdField;
    CdsItemNotaNF_CUSTO: TFMTBCdField;
    SqlItemNotaNF_MARGEM_PRODUTO: TFMTBCdField;
    CdsItemNotaNF_MARGEM_PRODUTO: TFMTBCdField;
    SqlItemNotaPRDL_REGISTRO: TIntegerField;
    CdsItemNotaPRDL_REGISTRO: TIntegerField;
    SQlNotaNF_BASEICMS: TFMTBCdField;
    SQlNotaNF_VL_ICMS: TFMTBCdField;
    SQlNotaNF_VLBASESUBTRIB: TFMTBCdField;
    SQlNotaNF_VL_SUBTRIB: TFMTBCdField;
    SQlNotaNF_TOT_CSUB: TFMTBCdField;
    SQlNotaNF_TOT_PROD: TFMTBCdField;
    SQlNotaNF_TOT_NOTA: TFMTBCdField;
    SQlNotaNF_VL_IPI: TFMTBCdField;
    SQlNotaNF_BASE_IPI: TFMTBCdField;
    CdsNotaFiscalNF_BASEICMS: TFMTBCdField;
    CdsNotaFiscalNF_VL_ICMS: TFMTBCdField;
    CdsNotaFiscalNF_VLBASESUBTRIB: TFMTBCdField;
    CdsNotaFiscalNF_VL_SUBTRIB: TFMTBCdField;
    CdsNotaFiscalNF_TOT_CSUB: TFMTBCdField;
    CdsNotaFiscalNF_TOT_PROD: TFMTBCdField;
    CdsNotaFiscalNF_TOT_NOTA: TFMTBCdField;
    CdsNotaFiscalNF_VL_IPI: TFMTBCdField;
    CdsNotaFiscalNF_BASE_IPI: TFMTBCdField;
    SqlReceberFAT_VL_LIQ: TFMTBCdField;
    SqlReceberFAT_VLFAT: TFMTBCdField;
    CdsReceberFAT_VL_LIQ: TFMTBCdField;
    CdsReceberFAT_VLFAT: TFMTBCdField;
    SqlRecParceFPC_VLPARC: TFMTBCdField;
    SqlRecParceFPC_VLPAGO: TFMTBCdField;
    CdsRecParceFPC_VLPARC: TFMTBCdField;
    CdsRecParceFPC_VLPAGO: TFMTBCdField;
    SqlNFeParceFPC_VLPARC: TFMTBCdField;
    SqlNFeParceFPC_VLPAGO: TFMTBCdField;
    CdsNfeParceFPC_PAGTO: TSQLTimeStampField;
    CdsNfeParceFPC_VLPARC: TFMTBCdField;
    CdsNfeParceFPC_VLPAGO: TFMTBCdField;
    SqlItemNotaNF_LEI_TRANSPARENCIA: TStringField;
    CdsItemNotaNF_LEI_TRANSPARENCIA: TStringField;
    SqlRecParcePCXPF_REGISTRO: TIntegerField;
    CdsRecParcePCXPF_REGISTRO: TIntegerField;
    SqlPagarParcPCXPF_REGISTRO: TIntegerField;
    CdsPagarParcPCXPF_REGISTRO: TIntegerField;
    SQlNotaNF_VENDA_FATURADA: TStringField;
    CdsNotaFiscalNF_VENDA_FATURADA: TStringField;
    SqlRecParceFPC_REEMBOLSO: TStringField;
    CdsRecParceFPC_REEMBOLSO: TStringField;
    SqlPagarParcPPC_REEMBOLSO: TStringField;
    CdsPagarParcPPC_REEMBOLSO: TStringField;
    SqlReceberFAT_REEMBOLSO: TStringField;
    CdsReceberFAT_REEMBOLSO: TStringField;
    SqlPagarPAG_REEMBOLSO: TStringField;
    CdsPagarPAG_REEMBOLSO: TStringField;
    SqlPedItemPRD_REFER: TStringField;
    CdsPedItemPRD_REFER: TStringField;
    SqlItemNotaPRD_REFER: TStringField;
    CdsItemNotaPRD_REFER: TStringField;
    SqlCdsItemEnfPRD_REFER: TStringField;
    CdsItemEnfPRD_REFER: TStringField;
    SqlItemEmbPRD_REFER: TStringField;
    CdsItemEmbPRD_REFER: TStringField;
    SqlItemCompraPRD_REFER: TStringField;
    CdsItemCompraPRD_REFER: TStringField;
    SqlPagarPAG_NUMDOC: TStringField;
    CdsPagarPAG_NUMDOC: TStringField;
    SqlPagarParcPAG_NUMDOC: TStringField;
    CdsPagarParcPAG_NUMDOC: TStringField;
    SqlItemNotaNF_IPI_POR_UNIDADE: TStringField;
    CdsItemNotaNF_IPI_POR_UNIDADE: TStringField;
    SqlPagarPAG_VALOR_N_RATEIA: TFMTBCdField;
    CdsPagarPAG_VALOR_N_RATEIA: TFMTBCdField;
    SqlPedItemPRG_REGISTRO: TIntegerField;
    CdsPedItemPRG_REGISTRO: TIntegerField;
    SqlCdsEnfPCX_CODIGO: TStringField;
    CdsEnfPCX_CODIGO: TStringField;
    SqlReceberFAT_LOTE: TStringField;
    CdsReceberFAT_LOTE: TStringField;
    SqlCdsEnfENF_INDUSTRIALIZACAO: TStringField;
    CdsEnfENF_INDUSTRIALIZACAO: TStringField;
    SQlNotaNF_CHAVE_NFE_REFERENCIADA: TStringField;
    CdsNotaFiscalNF_CHAVE_NFE_REFERENCIADA: TStringField;
    SqlPedItemPRF_PRECO: TFMTBCdField;
    SqlPedItemPRF_PRECO_BRUTO: TFMTBCdField;
    CdsPedItemPRF_PRECO: TFMTBCdField;
    CdsPedItemPRF_PRECO_BRUTO: TFMTBCdField;
    SqlItemNotaPRDCO_CODIGO_ORIGINAL: TStringField;
    CdsItemNotaPRDCO_CODIGO_ORIGINAL: TStringField;
    SqlPedItemPRDD_REGISTRO: TIntegerField;
    CdsPedItemPRDD_REGISTRO: TIntegerField;
    SqlItemNotaNF_VALOR_BCICMS_DESTINO: TFMTBCdField;
    SqlItemNotaNF_VALOR_FCP: TFMTBCdField;
    SqlItemNotaNF_VALOR_PARTILHA_DESTINO: TFMTBCdField;
    SqlItemNotaNF_VALOR_PARTILHA_ORIGEM: TFMTBCdField;
    CdsItemNotaNF_VALOR_BCICMS_DESTINO: TFMTBCdField;
    CdsItemNotaNF_VALOR_FCP: TFMTBCdField;
    CdsItemNotaNF_VALOR_PARTILHA_DESTINO: TFMTBCdField;
    CdsItemNotaNF_VALOR_PARTILHA_ORIGEM: TFMTBCdField;
    SQlNotaNF_VALOR_TOTAL_FCP: TFMTBCdField;
    SQlNotaNF_VALOR_TOTAL_PARTILHA_DEST: TFMTBCdField;
    SQlNotaNF_VALOR_TOTAL_PARTILHA_ORIG: TFMTBCdField;
    CdsNotaFiscalNF_VALOR_TOTAL_FCP: TFMTBCdField;
    CdsNotaFiscalNF_VALOR_TOTAL_PARTILHA_DEST: TFMTBCdField;
    CdsNotaFiscalNF_VALOR_TOTAL_PARTILHA_ORIG: TFMTBCdField;
    SqlItemNotaCEST_COD: TStringField;
    CdsItemNotaCEST_COD: TStringField;
    SqlItemNotaIBPT_VLAP: TFMTBCdField;
    CdsItemNotaIBPT_VLAP: TFMTBCdField;
    SQlNotaIBPT_VLAPROXTRIBUTOS: TFMTBCdField;
    CdsNotaFiscalIBPT_VLAPROXTRIBUTOS: TFMTBCdField;
    SqlPedItemID_DIRETIVAS: TIntegerField;
    CdsPedItemID_DIRETIVAS: TIntegerField;
    SQlNotaNF_UFVEICULO: TStringField;
    CdsNotaFiscalNF_UFVEICULO: TStringField;
    SqlPedItemPRF_IDESCTO1: TFloatField;
    SqlPedItemPRF_IDESCTO2: TFloatField;
    CdsPedItemPRF_IDESCTO1: TFloatField;
    CdsPedItemPRF_IDESCTO2: TFloatField;
    SqlPedItemPRDCO_CODIGO_ORIGINAL: TStringField;
    CdsPedItemPRDCO_CODIGO_ORIGINAL: TStringField;
    SqlItemNotaNF_PERC_FCP: TFMTBCdField;
    SqlItemNotaNF_ALIQ_ICMS_INTERNA_DESTINO: TFMTBCdField;
    CdsItemNotaNF_PERC_FCP: TFMTBCdField;
    CdsItemNotaNF_ALIQ_ICMS_INTERNA_DESTINO: TFMTBCdField;
    SqlItemNotaNF_CSOSN: TStringField;
    SqlItemNotaNF_ALIQ_ICMS_INTERESTADUAL: TFMTBCdField;
    SqlItemNotaNF_PERC_PARTILHA_DESTINO: TFMTBCdField;
    SqlItemNotaIBPT_ALIQFED: TFMTBCdField;
    SqlItemNotaIBPT_ALIQEST: TFMTBCdField;
    CdsItemNotaNF_CSOSN: TStringField;
    CdsItemNotaNF_ALIQ_ICMS_INTERESTADUAL: TFMTBCdField;
    CdsItemNotaNF_PERC_PARTILHA_DESTINO: TFMTBCdField;
    CdsItemNotaIBPT_ALIQFED: TFMTBCdField;
    CdsItemNotaIBPT_ALIQEST: TFMTBCdField;
    SqlOrdCompraOCP_PRAZO: TStringField;
    CdsOrdCompraOCP_PRAZO: TStringField;
    SqlReceberFAT_NUMSERIE: TStringField;
    CdsReceberFAT_NUMSERIE: TStringField;
    CdsRecParceFAT_NUMSERIE: TStringField;
    SqlRecParceFAT_NUMSERIE: TStringField;
    SqlRecParceFPC_DATABOLETO: TSQLTimeStampField;
    CdsRecParceFPC_DATABOLETO: TSQLTimeStampField;
    CdsEnfENF_ATUALIZA_ESTOQUE: TStringField;
    SqlCdsEnfENF_ATUALIZA_ESTOQUE: TStringField;
    CdsEnfENF_MODALIDADE: TStringField;
    CdsEnfENF_MODALIDADE_DESCR: TStringField;
    SqlCdsEnfENF_MODALIDADE: TStringField;
    SqlCdsEnfENF_MODALIDADE_DESCR: TStringField;
    CdsPedidosREP_CODIGO_INTERNO: TStringField;
    SqlPedidosREP_CODIGO_INTERNO: TStringField;
    SqlPedidosPED_COMISSAO_VEN: TFMTBCDField;
    CdsPedidosPED_COMISSAO_VEN: TFMTBCDField;
    CdsReceberFAT_COMISSAO_VEN: TFMTBCDField;
    SqlReceberFAT_COMISSAO_VEN: TFMTBCDField;
    CdsReceberREP_CODIGO_INTERNO: TStringField;
    SqlReceberREP_CODIGO_INTERNO: TStringField;
    CdsPedItemPRF_REGISTRO_VINCULADO: TIntegerField;
    SqlPedItemPRF_REGISTRO_VINCULADO: TIntegerField;
    CdsPedidosENDERECO_ENTREGA: TIntegerField;
    SqlPedidosENDERECO_ENTREGA: TIntegerField;
    CdsRecParcefpg_registro: TIntegerField;
    SqlRecParcefpg_registro: TIntegerField;
    CdsEnfENF_VLFRETEPORFORA: TFMTBCDField;
    CdsEnfENF_VLRDIFICMS: TFMTBCDField;
    CdsEnfENF_VLOUTROS: TFMTBCDField;
    SqlCdsEnfENF_VLFRETEPORFORA: TFMTBCDField;
    SqlCdsEnfENF_VLRDIFICMS: TFMTBCDField;
    SqlCdsEnfENF_VLOUTROS: TFMTBCDField;
    SqlPedItemPRF_PESOKG: TFMTBCDField;
    CdsPedItemPRF_PESOKG: TFMTBCDField;
    CdsOrdCompraOCP_ICMSST: TFMTBCDField;
    SqlOrdCompraOCP_ICMSST: TFMTBCDField;
    SqlPedItemPRF_PRODUTO_SEMVALOR: TStringField;
    CdsPedItemPRF_PRODUTO_SEMVALOR: TStringField;
    CdsReceberFAT_CID_CODIGO_PRESTACAO: TIntegerField;
    SqlReceberFAT_CID_CODIGO_PRESTACAO: TIntegerField;
    CdsPagarParcfpg_registro: TIntegerField;
    SqlPagarParcfpg_registro: TIntegerField;
    SqlPedidosPED_CONTATO_CLIENTE: TStringField;
    SqlPedidosPED_NUMERO_PED_CLIENTE: TStringField;
    SqlPedidosFPG_REGISTRO: TIntegerField;
    SqlPedidosCORI_CODIGO: TIntegerField;
    SqlPedidosPCX_CODIGO: TStringField;
    CdsPedidosPED_CONTATO_CLIENTE: TStringField;
    CdsPedidosPED_NUMERO_PED_CLIENTE: TStringField;
    CdsPedidosFPG_REGISTRO: TIntegerField;
    CdsPedidosCORI_CODIGO: TIntegerField;
    CdsPedidosPCX_CODIGO: TStringField;
    SqlPedItemPRF_PRAZO_ENTREGA: TDateField;
    CdsPedItemPRF_PRAZO_ENTREGA: TDateField;
    SqlCdsEnfENF_DADOS_ADICIONAIS_FISCO: TBlobField;
    CdsEnfENF_DADOS_ADICIONAIS_FISCO: TBlobField;
    SqlOrdCompraEMI_IE: TStringField;
    CdsOrdCompraEMI_IE: TStringField;
    SqlCdsEnfEMI_IE: TStringField;
    CdsEnfEMI_IE: TStringField;
    SqlPedidosEMI_IE: TStringField;
    CdsPedidosEMI_IE: TStringField;
    SqlOrdCompraEMI_CODIGO: TIntegerField;
    CdsOrdCompraEMI_CODIGO: TIntegerField;
    SqlCdsEnfEMI_CODIGO: TIntegerField;
    CdsEnfEMI_CODIGO: TIntegerField;
    SqlPedidosEMI_CODIGO: TIntegerField;
    CdsPedidosEMI_CODIGO: TIntegerField;
    SqlCdsEnfENF_TOT_PROD: TFMTBCDField;
    CdsEnfENF_TOT_PROD: TFMTBCDField;
    SqlCdsEnfENF_TOT_NOTA: TFMTBCDField;
    CdsEnfENF_TOT_NOTA: TFMTBCDField;
    SqlPedItemUNIDADE: TStringField;
    SqlPedItemPRF_PESO_COPIA: TFMTBCDField;
    CdsPedItemUNIDADE: TStringField;
    CdsPedItemPRF_PESO_COPIA: TFMTBCDField;
    SqlCdsEnfENF_PESO_L: TFMTBCDField;
    CdsEnfENF_PESO_L: TFMTBCDField;
    SqlPedItemCAP_CODIGO: TIntegerField;
    SqlPedItemACO_CODIGO: TIntegerField;
    CdsPedItemCAP_CODIGO: TIntegerField;
    CdsPedItemACO_CODIGO: TIntegerField;
    SqlPedItemPRF_VALOR_ST: TFMTBCDField;
    CdsPedItemPRF_VALOR_ST: TFMTBCDField;
    procedure CdsRecParceAfterEdit(DataSet: TDataSet);
    procedure CdsPagarParcCalcFields(DataSet: TDataSet);
    procedure CdsPedItemCalcFields(DataSet: TDataSet);
    procedure CdsPedItemAfterInsert(DataSet: TDataSet);
    procedure CdsCaixaFixoAfterScroll(DataSet: TDataSet);
    procedure CdsFechaCaixaCalcFields(DataSet: TDataSet);
    procedure CdsItemNotaCalcFields(DataSet: TDataSet);
    procedure CdsItemNotaBeforePost(DataSet: TDataSet);
    procedure CdsNotaFiscalAfterScroll(DataSet: TDataSet);
    procedure CdsEmbalagemBeforePost(DataSet: TDataSet);
    procedure CdsItemEmbBeforePost(DataSet: TDataSet);
    procedure CdsPedItemPRF_QTDE_FATURAR_CCChange(Sender: TField);
    procedure CdsNfPedBeforePost(DataSet: TDataSet);
    procedure CdsEnfBeforeEdit(DataSet: TDataSet);
    procedure CdsEnfBeforeCancel(DataSet: TDataSet);
    procedure CdsPagarBeforeEdit(DataSet: TDataSet);
    procedure CdsPagarParcBeforeEdit(DataSet: TDataSet);
    procedure CdsSaldoBancoBeforeEdit(DataSet: TDataSet);
    procedure CdsCaixaFixoBeforeEdit(DataSet: TDataSet);
    procedure CdsCaixaFixoBeforePost(DataSet: TDataSet);
    procedure CdsSaldoBancoBeforePost(DataSet: TDataSet);
    procedure CdsPedidosBeforeEdit(DataSet: TDataSet);
    procedure CdsPedItemAfterScroll(DataSet: TDataSet);
    procedure CdsPagarParcAfterEdit(DataSet: TDataSet);
    procedure CdsReceberBeforePost(DataSet: TDataSet);
    procedure CdsNotaFiscalCalcFields(DataSet: TDataSet);
    procedure CdsPagarBeforePost(DataSet: TDataSet);
    procedure CdsPedidosBeforePost(DataSet: TDataSet);
    procedure CdsPagarAfterEdit(DataSet: TDataSet);
    procedure CdsReceberAfterEdit(DataSet: TDataSet);
    procedure CdsRecParceCalcFields(DataSet: TDataSet);
    procedure CdsPedItemAfterPost(DataSet: TDataSet);
    procedure CdsRecItemBeforePost(DataSet: TDataSet);
    procedure CdsNotaFiscalBeforePost(DataSet: TDataSet);
    procedure CdsPagarParcBeforePost(DataSet: TDataSet);
    procedure CdsEnfBeforePost(DataSet: TDataSet);
    procedure CdsRecParceAfterInsert(DataSet: TDataSet);
    procedure CdsOrdCompraAfterEdit(DataSet: TDataSet);
  private
    wTransacao: TTransactionDesc;
    Procedure buscaItemNota;
    Procedure BuscaItemEmb;
    { Private declarations }
  public
    { Public declarations }
  end;

var
  DataMovimento: TDataMovimento;

implementation

uses DataCad, DataCad1, Rec0001, Rec0002, Pag0001, Pag0002, Sab0001,
  CAIXA001, Fat0000, OCP0001, Nfs0001, Men0001,
  Ped0009, uPedido, uteis, iniciodb;

{$R *.dfm}

procedure TDataMovimento.CdsRecParceAfterEdit(DataSet: TDataSet);
begin
    if assigned(FormContasRecParcelas) then
       FormContasRecParcelas.DesabilitaBotoes;
end;

procedure TDataMovimento.CdsRecParceAfterInsert(DataSet: TDataSet);
begin
     CdsRecParceFAT_REGISTRO.asinteger:=dbInicio.GetNextSequence( 'GEN_FAT_PC01_REGISTRO');
     CdsRecParceEMP_CODIGO.AsString := dbInicio.EMPRESA.EMP_CODIGO;
end;

procedure TDataMovimento.CdsPagarParcCalcFields(DataSet: TDataSet);
begin
    if (CdsPagarParcPPC_NPARCELAS.AsInteger = 1) then
       CdsPagarParcN_PARC_CC.AsString := '01/01'
    else
       CdsPagarParcN_PARC_CC.AsString := CdsPagarParcPPC_NUMER.AsString+'/'+StrZero(CdsPagarParcPPC_NPARCELAS.AsString,2);
end;

procedure TDataMovimento.CdsPedItemCalcFields(DataSet: TDataSet);
begin
    CdsPedItemPRF_TOTAL_CC.AsCurrency       := (CdsPedItemPRF_QTDE.AsCurrency * CdsPedItemPRF_PRECO.AsCurrency);
    CdsPedItemPRF_TOTAL_BRUTO_CC.AsCurrency := (CdsPedItemPRF_QTDE.AsCurrency * CdsPedItemPRF_PRECO_BRUTO.AsCurrency);
    CdsPedItemCC_RECNO.AsInteger            := CdsPedItem.RecNo;

end;

procedure TDataMovimento.CdsPedItemAfterInsert(DataSet: TDataSet);
begin
    DataCadastros.IncrementaRegistro('PED_IT01',CdsPedItemPRF_REGISTRO);
end;

procedure TDataMovimento.CdsCaixaFixoAfterScroll(DataSet: TDataSet);
begin
    if Assigned(FormCaixaFixo) then
       begin
           if FormCaixaFixo.SqlCdsCtaAnalise.Locate('CCT_CODIGO',FormCaixaFixo.DBEditCtaAnalise.Text,[]) = true then
              begin
                  if FormCaixaFixo.SqlCdsCtaAnaliseCCT_CONTA.AsString = 'S' then
                     // conta tipo despesa = Saída
                     FormCaixaFixo.CCxa_valor.Value := DataMovimento.CdsCaixaFixoCXA_SAIDA.AsCurrency
                  else
                     // conta tipo Receita = Enttrada
                     FormCaixaFixo.CCxa_valor.Value := DataMovimento.CdsCaixaFixoCXA_ENTRADA.AsCurrency;
                  FormCaixaFixo.CbCtaAnalise.Text   := FormCaixaFixo.SqlCdsCtaAnaliseCCT_DESCRI.AsString;
                  FormCaixaFixo.CbTipoDoc.ItemIndex := IIF(DataMovimento.CdsCaixaFixoCXA_TIPODOC.AsString = 'D',0,IIF(DataMovimento.CdsCaixaFixoCXA_TIPODOC.AsString = 'C',1,IIF(DataMovimento.CdsCaixaFixoCXA_TIPODOC.AsString = 'O',2,3)));
              end
           else
              begin
                  FormCaixaFixo.CbCtaAnalise.Text   := '';
                  if DataMovimento.CdsCaixaFixoCXA_TIPODOC.AsString = 'T' then
                     FormCaixaFixo.CCxa_valor.Value := DataMovimento.CdsCaixaFixoCXA_ENTRADA.AsCurrency;
              end;
       end;
end;

procedure TDataMovimento.CdsFechaCaixaCalcFields(DataSet: TDataSet);
begin
    CdsFechaCaixaCC_SALDOCAIXA.AsCurrency :=(CdsFechaCaixaCXF_ENTRADAS.AsCurrency-CdsFechaCaixaCXF_SAIDAS.AsCurrency)+CdsFechaCaixaCXF_ANTERIOR.AsCurrency;
end;

procedure TDataMovimento.CdsItemNotaCalcFields(DataSet: TDataSet);
begin
    CdsItemNotaNF_TOTAL_CC.AsCurrency     := (CdsItemNotaNF_QTDE.AsCurrency * CdsItemNotaNF_PRECO.AsCurrency);
    CdsItemNotaNF_TOTAL_IPI_CC.AsCurrency := (((CdsItemNotaNF_QTDE.AsCurrency * CdsItemNotaNF_PRECO.AsCurrency) * CdsItemNotaNF_IPIALIQ.AsCurrency)/100)+(CdsItemNotaNF_QTDE.AsCurrency * CdsItemNotaNF_PRECO.AsCurrency);
end;

procedure TDataMovimento.CdsItemNotaBeforePost(DataSet: TDataSet);
begin
  DataCadastros.IncrementaRegistro('NF_IT01',CdsItemNotaNF_REGISTRO);
end;

procedure TDataMovimento.CdsNotaFiscalAfterScroll(DataSet: TDataSet);
begin
    {if Assigned(FormPedidos) then
       begin
           FormPedidos.BuscaItensnota;
       end;}
    if Assigned(FrmPedido) then
       FrmPedido.BuscaItensNota;

end;

procedure TDataMovimento.buscaItemNota;
begin
    try
      if CdsNotaFiscal.Active then
        begin
         CdsItemNota.Close;
         SqlItemNota.sql.text := 'Select * from NF_IT01 where NF_IT_NOTANUMER = '''+CdsNotaFiscalNF_NOTANUMBER.AsString+'''';
         CdsItemNota.Open;
         CdsItemNota.RecordCount;
       end;
    except on E:EdatabaseError do
      uteis.erro  (pchar('Erro ao localizar itens !'+e.Message))
    end;
end;

procedure TDataMovimento.CdsEmbalagemBeforePost(DataSet: TDataSet);
begin
    DataCadastros.IncrementaRegistro('PED_EB02',CdsEmbalagemPEB_REGISTRO);
end;

procedure TDataMovimento.CdsItemEmbBeforePost(DataSet: TDataSet);
begin
    DataCadastros.IncrementaRegistro('PED_EB03',CdsItemEmbEBI_REGISTRO);
end;

procedure TDataMovimento.BuscaItemEmb;
begin
   {busca item ref a embalagem}
 try
   if CdsEmbalagem.Active then
      begin
         if CdsEmbalagem.IsEmpty = false then
            begin
               CdsItemEmb.Close;
               SqlItemEmb.sql.text := SQLDEF('PEDIDOS','select PED.* ,PRD_DESCRI from PED_EB03 PED left join PRD0000 on PRD0000.PRD_REFER = PED_EB03.PRD_REFER','where PEB_REGISTRO = '''+CdsEmbalagemPEB_REGISTRO.AsString+'''','PED.PEB_REGISTRO','PED.');
               CdsItemEmb.Open;
            end;
      end;
 except on E:EdatabaseError do
    uteis.erro  (Pchar('Erro ao localizar itens ref a embalagem !'+e.message));
 end;
end;

procedure TDataMovimento.CdsPedItemPRF_QTDE_FATURAR_CCChange(
  Sender: TField);
begin
 if Assigned(FormFaturamento) then
   begin
     If (DataMovimento.CdsPedItemPRF_QTDE.Ascurrency - DataMovimento.CdsPedItemPRF_QTDEFAT.AsCurrency ) < CdsPedItemPRF_QTDE_FATURAR_CC.AsCurrency then
        begin
            uteis.aviso('Quantidade selecionada maior que a quantidade pendente !');
            CdsPedItemPRF_QTDE_FATURAR_CC.AsCurrency := DataMovimento.CdsPedItemPRF_QTDE.Ascurrency - DataMovimento.CdsPedItemPRF_QTDEFAT.AsCurrency;
        end;
    end;
end;

procedure TDataMovimento.CdsNfPedBeforePost(DataSet: TDataSet);
begin
    DataCadastros.IncrementaRegistro('NF_PED',CdsNfPedNP_REGISTRO);
end;

procedure TDataMovimento.CdsEnfBeforeEdit(DataSet: TDataSet);
begin
    if Assigned(FormNfEntrada) then
       FormNfEntrada.DesabilitaBotoes;
end;

procedure TDataMovimento.CdsEnfBeforeCancel(DataSet: TDataSet);
begin
    DataCadastros.CancelaInsercao('ENF0001',DataMovimento.CdsEnfENF_REGISTRO,DataCadastros.CdsSysfileSYS_ENF);
end;

procedure TDataMovimento.CdsPagarBeforeEdit(DataSet: TDataSet);
begin
    if Assigned(FormContasPagar) then
       FormContasPagar.desabilitaBotoes;
end;

procedure TDataMovimento.CdsPagarParcBeforeEdit(DataSet: TDataSet);
begin
    if Assigned(FormContasPagParcelas) then
       FormContasPagParcelas.DesabilitaBotoes;
end;

procedure TDataMovimento.CdsSaldoBancoBeforeEdit(DataSet: TDataSet);
begin
    if Assigned(FormSaldoBanco) then
       FormSaldoBanco.DesabilitaBotoes;
end;

procedure TDataMovimento.CdsCaixaFixoBeforeEdit(DataSet: TDataSet);
begin
    If Assigned(FormCaixaFixo) then
       FormCaixaFixo.Desabilitabotoes;
end;

procedure TDataMovimento.CdsCaixaFixoBeforePost(DataSet: TDataSet);
begin
     CdsCaixaFixoCXA_LANCTO.asinteger:=dbInicio.GetNextSequence( 'gen_caixa001_lancto');
end;

procedure TDataMovimento.CdsSaldoBancoBeforePost(DataSet: TDataSet);
begin
    DataCadastros.IncrementaRegistro('SALDOBCO',CdsSaldoBancoSAB_CODIGO);
end;

procedure TDataMovimento.CdsPedidosBeforeEdit(DataSet: TDataSet);
begin
    {if Assigned(formPedidos) and (not assigned (FormPedidoDuplicar))then
       FormPedidos.DesabilitaBotoes;}
end;

procedure TDataMovimento.CdsPedItemAfterScroll(DataSet: TDataSet);
begin
   // Atualizar_Variacoes;
end;

procedure TDataMovimento.CdsPagarParcAfterEdit(DataSet: TDataSet);
begin
    if assigned(FormContasPagParcelas) then
       FormContasPagParcelas.DesabilitaBotoes;
end;

procedure TDataMovimento.CdsReceberBeforePost(DataSet: TDataSet);
begin
   CdsReceberFAT_REGISTRO.asInteger := dbInicio.GetNextSequence('GEN_FAT0000_REGISTRO');
end;

procedure TDataMovimento.CdsNotaFiscalCalcFields(DataSet: TDataSet);
begin
    CdsNotaFiscalNF_TIPO_CC.AsString := iif(CdsNotaFiscalNF_ENTR_SAID.AsString = 'S','SAIDA','ENTRADA');
    if CdsNotaFiscalNF_CANCELADA.AsString = 'S' then
       CdsNotaFiscalNF_STATUS_CC.AsString := 'SIM'
    else
       CdsNotaFiscalNF_STATUS_CC.AsString := 'NãO';
end;

procedure TDataMovimento.CdsOrdCompraAfterEdit(DataSet: TDataSet);
begin
    If Assigned(FormOrdCompra) then
       FormOrdCompra.desabilitaBotoes;
end;

procedure TDataMovimento.CdsPagarBeforePost(DataSet: TDataSet);
begin
    DataCadastros.IncrementaRegistro('PAG0000',CdsPagarPAG_REGISTRO);
end;

procedure TDataMovimento.CdsPedidosBeforePost(DataSet: TDataSet);
begin
  {executa store procedure script 3.0.0.151}
   StpPedido.ExecProc;
   CdsPedidosPED_REGISTRO.AsInteger := StpPedido.Params[0].AsInteger;
// DataCadastros.IncrementaRegistro('PED0000',CdsPedidosPED_REGISTRO);

end;

procedure TDataMovimento.CdsPagarAfterEdit(DataSet: TDataSet);
begin
    If Assigned(FormContasPagar) then
       FormContasPagar.desabilitaBotoes;
end;

procedure TDataMovimento.CdsReceberAfterEdit(DataSet: TDataSet);
begin
    if Assigned(formContasReceber) then
       FormContasReceber.desabilitaBotoes;
end;

procedure TDataMovimento.CdsRecParceCalcFields(DataSet: TDataSet);
begin
    if (CdsRecParceFPC_NPARCELAS.AsInteger = 1) then
       CdsRecParceN_PARC_CC.AsString := '01/01'
    else
       CdsRecParceN_PARC_CC.AsString := CdsRecParceFPC_NUMER.AsString+'/'+StrZero(CdsRecParceFPC_NPARCELAS.AsString,2);
end;


procedure TDataMovimento.CdsPedItemAfterPost(DataSet: TDataSet);
begin
    //Atualizar_Variacoes;
end;

procedure TDataMovimento.CdsRecItemBeforePost(DataSet: TDataSet);
begin
   DataCadastros.IncrementaRegistro('FAT_IT02',CdsRecItemREG);
end;

procedure TDataMovimento.CdsNotaFiscalBeforePost(DataSet: TDataSet);
begin
   DataCadastros.IncrementaRegistro('NF0001',CdsNotaFiscalNF_REGISTRO);
end;

procedure TDataMovimento.CdsPagarParcBeforePost(DataSet: TDataSet);
begin
   if CdsPagarParc.FieldByName('PAG_REGISTRO').AsInteger = 0 then
     CdsPagarParc.FieldByName('PAG_REGISTRO').AsInteger := DBInicio.GetNextSequence('gen_pag_pc01');

end;

procedure TDataMovimento.CdsEnfBeforePost(DataSet: TDataSet);
begin
   DataCadastros.IncrementaRegistro('ENF0001',DataMovimento.CdsEnfENF_REGISTRO);
   FormNfEntrada.DesabilitaBotoes;
end;

end.





