unit DmSysCfg;

interface

uses
  SysUtils, Classes, {{DBXpress,} DB, SqlExpr, FMTBCd, DBClient, Provider,
  DBLocal, DBLocalS, RwFunc, MIDASLIB;



type
  TDmCfg = class(TDataModule)
    SqlCdsNF: tsqlquery;
    DspNF: TDataSetProvider;
    CdsNF: TClientDataSet;
    DsNF: TDataSource;
    SqlCdsDupl: tsqlquery;
    SqlCdsEtiq: tsqlquery;
    DspDupl: TDataSetProvider;
    DspEtiq: TDataSetProvider;
    CdsDupl: TClientDataSet;
    CdsEtiq: TClientDataSet;
    DsDupl: TDataSource;
    DsEtiq: TDataSource;
    SqlCdsDuplCdU_CODIGO: TStringField;
    SqlCdsDuplCdU_DTCADA: TDateField;
    SqlCdsDuplCdU_ATIVO: TStringField;
    SqlCdsDuplCdU_FONTE: TStringField;
    SqlCdsDuplEMP_CODIGO: TStringField;
    SqlCdsDuplCdU_NATUREZA: TStringField;
    SqlCdsDuplCdU_DTEMISSAO: TStringField;
    SqlCdsDuplCdU_FATURA: TStringField;
    SqlCdsDuplCdU_VALORD: TStringField;
    SqlCdsDuplCdU_NORDEM: TStringField;
    SqlCdsDuplCdU_VENCTO: TStringField;
    SqlCdsDuplCdU_DESCTODE: TStringField;
    SqlCdsDuplCdU_DESCTOATE: TStringField;
    SqlCdsDuplCdU_DESCTOS: TStringField;
    SqlCdsDuplCdU_CONDESPECIAL: TStringField;
    SqlCdsDuplCdU_NOMESACADO: TStringField;
    SqlCdsDuplCdU_ENDERECO: TStringField;
    SqlCdsDuplCdU_BAIRRO: TStringField;
    SqlCdsDuplCdU_CIDADE: TStringField;
    SqlCdsDuplCdU_ESTADO: TStringField;
    SqlCdsDuplCdU_CEP: TStringField;
    SqlCdsDuplCdU_FONE: TStringField;
    SqlCdsDuplCdU_PRACA: TStringField;
    SqlCdsDuplCdU_ENDECOBRA: TStringField;
    SqlCdsDuplCdU_CEPCOBRA: TStringField;
    SqlCdsDuplCdU_CNPJ: TStringField;
    SqlCdsDuplCdU_INSCRESTADUAL: TStringField;
    SqlCdsDuplCdU_DATACEITE: TStringField;
    SqlCdsDuplCdU_VLEXTENSO: TStringField;
    SqlCdsDuplCdU_LINHAS: TStringField;
    CdsDuplCdU_CODIGO: TStringField;
    CdsDuplCdU_DTCADA: TDateField;
    CdsDuplCdU_ATIVO: TStringField;
    CdsDuplCdU_FONTE: TStringField;
    CdsDuplEMP_CODIGO: TStringField;
    CdsDuplCdU_NATUREZA: TStringField;
    CdsDuplCdU_DTEMISSAO: TStringField;
    CdsDuplCdU_FATURA: TStringField;
    CdsDuplCdU_VALORD: TStringField;
    CdsDuplCdU_NORDEM: TStringField;
    CdsDuplCdU_VENCTO: TStringField;
    CdsDuplCdU_DESCTODE: TStringField;
    CdsDuplCdU_DESCTOATE: TStringField;
    CdsDuplCdU_DESCTOS: TStringField;
    CdsDuplCdU_CONDESPECIAL: TStringField;
    CdsDuplCdU_NOMESACADO: TStringField;
    CdsDuplCdU_ENDERECO: TStringField;
    CdsDuplCdU_BAIRRO: TStringField;
    CdsDuplCdU_CIDADE: TStringField;
    CdsDuplCdU_ESTADO: TStringField;
    CdsDuplCdU_CEP: TStringField;
    CdsDuplCdU_FONE: TStringField;
    CdsDuplCdU_PRACA: TStringField;
    CdsDuplCdU_ENDECOBRA: TStringField;
    CdsDuplCdU_CEPCOBRA: TStringField;
    CdsDuplCdU_CNPJ: TStringField;
    CdsDuplCdU_INSCRESTADUAL: TStringField;
    CdsDuplCdU_DATACEITE: TStringField;
    CdsDuplCdU_VLEXTENSO: TStringField;
    CdsDuplCdU_LINHAS: TStringField;
    SqlCdsEtiqCET_CODIGO: TStringField;
    SqlCdsEtiqCET_DTCADA: TDateField;
    SqlCdsEtiqCET_ATIVO: TStringField;
    SqlCdsEtiqCET_TPIMP: TStringField;
    SqlCdsEtiqCET_QTDETIQ: TStringField;
    SqlCdsEtiqCET_INICOL1: TStringField;
    SqlCdsEtiqCET_INICOL2: TStringField;
    SqlCdsEtiqCET_INICOL3: TStringField;
    SqlCdsEtiqEMP_CODIGO: TStringField;
    SqlCdsEtiqCET_CLIENTE: TStringField;
    SqlCdsEtiqCET_ENDERECO: TStringField;
    SqlCdsEtiqCET_CIDADE: TStringField;
    SqlCdsEtiqCET_ESTADO: TStringField;
    SqlCdsEtiqCET_CEP: TStringField;
    SqlCdsEtiqCET_NFISCAL: TStringField;
    SqlCdsEtiqCET_QTDE: TStringField;
    SqlCdsEtiqCET_PESO: TStringField;
    SqlCdsEtiqCET_CODPRODUTO: TStringField;
    SqlCdsEtiqCET_PRODUTO: TStringField;
    SqlCdsEtiqCET_TRANSPORT: TStringField;
    SqlCdsEtiqCET_ENDTRANSP: TStringField;
    SqlCdsEtiqCET_CIDTRANSP: TStringField;
    SqlCdsEtiqCET_CEPTRANSP: TStringField;
    SqlCdsEtiqCET_LINHAS: TStringField;
    CdsEtiqCET_CODIGO: TStringField;
    CdsEtiqCET_DTCADA: TDateField;
    CdsEtiqCET_ATIVO: TStringField;
    CdsEtiqCET_TPIMP: TStringField;
    CdsEtiqCET_QTDETIQ: TStringField;
    CdsEtiqCET_INICOL1: TStringField;
    CdsEtiqCET_INICOL2: TStringField;
    CdsEtiqCET_INICOL3: TStringField;
    CdsEtiqEMP_CODIGO: TStringField;
    CdsEtiqCET_CLIENTE: TStringField;
    CdsEtiqCET_ENDERECO: TStringField;
    CdsEtiqCET_CIDADE: TStringField;
    CdsEtiqCET_ESTADO: TStringField;
    CdsEtiqCET_CEP: TStringField;
    CdsEtiqCET_NFISCAL: TStringField;
    CdsEtiqCET_QTDE: TStringField;
    CdsEtiqCET_PESO: TStringField;
    CdsEtiqCET_CODPRODUTO: TStringField;
    CdsEtiqCET_PRODUTO: TStringField;
    CdsEtiqCET_TRANSPORT: TStringField;
    CdsEtiqCET_ENDTRANSP: TStringField;
    CdsEtiqCET_CIDTRANSP: TStringField;
    CdsEtiqCET_CEPTRANSP: TStringField;
    CdsEtiqCET_LINHAS: TStringField;
    SqlCdsEtiqCET_DESCRIETIQ: TStringField;
    SqlCdsEtiqCET_ROTULO: TStringField;
    CdsEtiqCET_DESCRIETIQ: TStringField;
    CdsEtiqCET_ROTULO: TStringField;
    SqlCdsNFCNF_CODIGO: TStringField;
    SqlCdsNFCNF_DTCADA: TDateField;
    SqlCdsNFCNF_ATIVO: TStringField;
    SqlCdsNFCNF_FONTE: TStringField;
    SqlCdsNFCNF_SERIE: TStringField;
    SqlCdsNFEMP_CODIGO: TStringField;
    SqlCdsNFCNF_XSAIDA: TStringField;
    SqlCdsNFCNF_XENTRADA: TStringField;
    SqlCdsNFCNF_NUMERONF: TStringField;
    SqlCdsNFCNF_NATUREZA: TStringField;
    SqlCdsNFCNF_CFOP: TStringField;
    SqlCdsNFCNF_INSCSUBT: TStringField;
    SqlCdsNFCNF_RAZAO: TStringField;
    SqlCdsNFCNF_CNPJ: TStringField;
    SqlCdsNFCNF_DTEMISSAO: TStringField;
    SqlCdsNFCNF_ENDERECO: TStringField;
    SqlCdsNFCNF_BAIRRO: TStringField;
    SqlCdsNFCNF_CEP: TStringField;
    SqlCdsNFCNF_DTSAIDA: TStringField;
    SqlCdsNFCNF_CIDADE: TStringField;
    SqlCdsNFCNF_FONE: TStringField;
    SqlCdsNFCNF_ESTADO: TStringField;
    SqlCdsNFCNF_INSCRESTADUAL: TStringField;
    SqlCdsNFCNF_HORASAIDA: TStringField;
    SqlCdsNFCNF_FATURA1: TStringField;
    SqlCdsNFCNF_VENCTO1: TStringField;
    SqlCdsNFCNF_VALOR1: TStringField;
    SqlCdsNFCNF_FATURA2: TStringField;
    SqlCdsNFCNF_VENCTO2: TStringField;
    SqlCdsNFCNF_VALOR2: TStringField;
    SqlCdsNFCNF_FATURA3: TStringField;
    SqlCdsNFCNF_VENCTO3: TStringField;
    SqlCdsNFCNF_VALOR3: TStringField;
    SqlCdsNFCNF_FATURA4: TStringField;
    SqlCdsNFCNF_VENCTO4: TStringField;
    SqlCdsNFCNF_VALOR4: TStringField;
    SqlCdsNFCNF_FATURA5: TStringField;
    SqlCdsNFCNF_VENCTO5: TStringField;
    SqlCdsNFCNF_VALOR5: TStringField;
    SqlCdsNFCNF_FATURA6: TStringField;
    SqlCdsNFCNF_VENCTO6: TStringField;
    SqlCdsNFCNF_VALOR6: TStringField;
    SqlCdsNFCNF_CODPRODUTO: TStringField;
    SqlCdsNFCNF_DESPRODUTO: TStringField;
    SqlCdsNFCNF_CFCOD: TStringField;
    SqlCdsNFCNF_CFAPEL: TStringField;
    SqlCdsNFCNF_ST: TStringField;
    SqlCdsNFCNF_UNIDADE: TStringField;
    SqlCdsNFCNF_QTDE: TStringField;
    SqlCdsNFCNF_PRECOUNIT: TStringField;
    SqlCdsNFCNF_PRECOTOTAL: TStringField;
    SqlCdsNFCNF_ALIQIPI: TStringField;
    SqlCdsNFCNF_VALORIPI: TStringField;
    SqlCdsNFCNF_MENSAGE1: TStringField;
    SqlCdsNFCNF_MENSAGE2: TStringField;
    SqlCdsNFCNF_BASEICMS: TStringField;
    SqlCdsNFCNF_VLICMS: TStringField;
    SqlCdsNFCNF_BASESUBTRI: TStringField;
    SqlCdsNFCNF_VLBASESUBTRI: TStringField;
    SqlCdsNFCNF_VLTOTPRODU: TStringField;
    SqlCdsNFCNF_VLFRETE: TStringField;
    SqlCdsNFCNF_VLSEGURO: TStringField;
    SqlCdsNFCNF_DESPACESSO: TStringField;
    SqlCdsNFCNF_VLTOTIPI: TStringField;
    SqlCdsNFCNF_VLTOTNOTA: TStringField;
    SqlCdsNFCNF_TRANSP: TStringField;
    SqlCdsNFCNF_FRETEPORCONTA: TStringField;
    SqlCdsNFCNF_PLACAVEICULO: TStringField;
    SqlCdsNFCNF_PLACAESTADO: TStringField;
    SqlCdsNFCNF_CNPJTRANSP: TStringField;
    SqlCdsNFCNF_ENDERETRANSP: TStringField;
    SqlCdsNFCNF_CIDADETRANSP: TStringField;
    SqlCdsNFCNF_ESTADOTRANSP: TStringField;
    SqlCdsNFCNF_INSCESTRANSP: TStringField;
    SqlCdsNFCNF_QTDEVOTRANSP: TStringField;
    SqlCdsNFCNF_ESPECIETRANSP: TStringField;
    SqlCdsNFCNF_MARCA: TStringField;
    SqlCdsNFCNF_NUMERO: TStringField;
    SqlCdsNFCNF_PESOBRUTO: TStringField;
    SqlCdsNFCNF_PESOLIQUIDO: TStringField;
    SqlCdsNFCNF_REDESPTITULO: TStringField;
    SqlCdsNFCNF_TRANSPRED: TStringField;
    SqlCdsNFCNF_REDESPRUA: TStringField;
    SqlCdsNFCNF_REDESPCID: TStringField;
    SqlCdsNFCNF_ENTREGATITULO: TStringField;
    SqlCdsNFCNF_ENTREGARUA: TStringField;
    SqlCdsNFCNF_ENTREGACIDA: TStringField;
    SqlCdsNFCNF_COBRANCATITULO: TStringField;
    SqlCdsNFCNF_COBRANCARUA: TStringField;
    SqlCdsNFCNF_COBRANCACIDA: TStringField;
    SqlCdsNFCNF_DADOAD1: TStringField;
    SqlCdsNFCNF_DADOAD2: TStringField;
    SqlCdsNFCNF_DADOAD3: TStringField;
    SqlCdsNFCNF_DADOAD4: TStringField;
    SqlCdsNFCNF_DADOAD5: TStringField;
    SqlCdsNFCNF_DADOAD6: TStringField;
    SqlCdsNFCNF_DADOAD7: TStringField;
    SqlCdsNFCNF_DADOAD8: TStringField;
    SqlCdsNFCNF_DADOAD9: TStringField;
    SqlCdsNFCNF_DADOAD10: TStringField;
    SqlCdsNFCNF_DADOAD11: TStringField;
    SqlCdsNFCNF_DADOAD12: TStringField;
    SqlCdsNFCNF_NOTAFATURA: TStringField;
    SqlCdsNFCNF_ASSINTURA: TStringField;
    SqlCdsNFCNF_DATAREC: TStringField;
    SqlCdsNFCNF_LINHANOTA: TStringField;
    CdsNFCNF_CODIGO: TStringField;
    CdsNFCNF_DTCADA: TDateField;
    CdsNFCNF_ATIVO: TStringField;
    CdsNFCNF_FONTE: TStringField;
    CdsNFCNF_SERIE: TStringField;
    CdsNFEMP_CODIGO: TStringField;
    CdsNFCNF_XSAIDA: TStringField;
    CdsNFCNF_XENTRADA: TStringField;
    CdsNFCNF_NUMERONF: TStringField;
    CdsNFCNF_NATUREZA: TStringField;
    CdsNFCNF_CFOP: TStringField;
    CdsNFCNF_INSCSUBT: TStringField;
    CdsNFCNF_RAZAO: TStringField;
    CdsNFCNF_CNPJ: TStringField;
    CdsNFCNF_DTEMISSAO: TStringField;
    CdsNFCNF_ENDERECO: TStringField;
    CdsNFCNF_BAIRRO: TStringField;
    CdsNFCNF_CEP: TStringField;
    CdsNFCNF_DTSAIDA: TStringField;
    CdsNFCNF_CIDADE: TStringField;
    CdsNFCNF_FONE: TStringField;
    CdsNFCNF_ESTADO: TStringField;
    CdsNFCNF_INSCRESTADUAL: TStringField;
    CdsNFCNF_HORASAIDA: TStringField;
    CdsNFCNF_FATURA1: TStringField;
    CdsNFCNF_VENCTO1: TStringField;
    CdsNFCNF_VALOR1: TStringField;
    CdsNFCNF_FATURA2: TStringField;
    CdsNFCNF_VENCTO2: TStringField;
    CdsNFCNF_VALOR2: TStringField;
    CdsNFCNF_FATURA3: TStringField;
    CdsNFCNF_VENCTO3: TStringField;
    CdsNFCNF_VALOR3: TStringField;
    CdsNFCNF_FATURA4: TStringField;
    CdsNFCNF_VENCTO4: TStringField;
    CdsNFCNF_VALOR4: TStringField;
    CdsNFCNF_FATURA5: TStringField;
    CdsNFCNF_VENCTO5: TStringField;
    CdsNFCNF_VALOR5: TStringField;
    CdsNFCNF_FATURA6: TStringField;
    CdsNFCNF_VENCTO6: TStringField;
    CdsNFCNF_VALOR6: TStringField;
    CdsNFCNF_CODPRODUTO: TStringField;
    CdsNFCNF_DESPRODUTO: TStringField;
    CdsNFCNF_CFCOD: TStringField;
    CdsNFCNF_CFAPEL: TStringField;
    CdsNFCNF_ST: TStringField;
    CdsNFCNF_UNIDADE: TStringField;
    CdsNFCNF_QTDE: TStringField;
    CdsNFCNF_PRECOUNIT: TStringField;
    CdsNFCNF_PRECOTOTAL: TStringField;
    CdsNFCNF_ALIQIPI: TStringField;
    CdsNFCNF_VALORIPI: TStringField;
    CdsNFCNF_MENSAGE1: TStringField;
    CdsNFCNF_MENSAGE2: TStringField;
    CdsNFCNF_BASEICMS: TStringField;
    CdsNFCNF_VLICMS: TStringField;
    CdsNFCNF_BASESUBTRI: TStringField;
    CdsNFCNF_VLBASESUBTRI: TStringField;
    CdsNFCNF_VLTOTPRODU: TStringField;
    CdsNFCNF_VLFRETE: TStringField;
    CdsNFCNF_VLSEGURO: TStringField;
    CdsNFCNF_DESPACESSO: TStringField;
    CdsNFCNF_VLTOTIPI: TStringField;
    CdsNFCNF_VLTOTNOTA: TStringField;
    CdsNFCNF_TRANSP: TStringField;
    CdsNFCNF_FRETEPORCONTA: TStringField;
    CdsNFCNF_PLACAVEICULO: TStringField;
    CdsNFCNF_PLACAESTADO: TStringField;
    CdsNFCNF_CNPJTRANSP: TStringField;
    CdsNFCNF_ENDERETRANSP: TStringField;
    CdsNFCNF_CIDADETRANSP: TStringField;
    CdsNFCNF_ESTADOTRANSP: TStringField;
    CdsNFCNF_INSCESTRANSP: TStringField;
    CdsNFCNF_QTDEVOTRANSP: TStringField;
    CdsNFCNF_ESPECIETRANSP: TStringField;
    CdsNFCNF_MARCA: TStringField;
    CdsNFCNF_NUMERO: TStringField;
    CdsNFCNF_PESOBRUTO: TStringField;
    CdsNFCNF_PESOLIQUIDO: TStringField;
    CdsNFCNF_REDESPTITULO: TStringField;
    CdsNFCNF_TRANSPRED: TStringField;
    CdsNFCNF_REDESPRUA: TStringField;
    CdsNFCNF_REDESPCID: TStringField;
    CdsNFCNF_ENTREGATITULO: TStringField;
    CdsNFCNF_ENTREGARUA: TStringField;
    CdsNFCNF_ENTREGACIDA: TStringField;
    CdsNFCNF_COBRANCATITULO: TStringField;
    CdsNFCNF_COBRANCARUA: TStringField;
    CdsNFCNF_COBRANCACIDA: TStringField;
    CdsNFCNF_DADOAD1: TStringField;
    CdsNFCNF_DADOAD2: TStringField;
    CdsNFCNF_DADOAD3: TStringField;
    CdsNFCNF_DADOAD4: TStringField;
    CdsNFCNF_DADOAD5: TStringField;
    CdsNFCNF_DADOAD6: TStringField;
    CdsNFCNF_DADOAD7: TStringField;
    CdsNFCNF_DADOAD8: TStringField;
    CdsNFCNF_DADOAD9: TStringField;
    CdsNFCNF_DADOAD10: TStringField;
    CdsNFCNF_DADOAD11: TStringField;
    CdsNFCNF_DADOAD12: TStringField;
    CdsNFCNF_NOTAFATURA: TStringField;
    CdsNFCNF_ASSINTURA: TStringField;
    CdsNFCNF_DATAREC: TStringField;
    CdsNFCNF_LINHANOTA: TStringField;
    SqlCdsNFCNF_ALIQICMS: TStringField;
    CdsNFCNF_ALIQICMS: TStringField;
    SqlCdsBloq: tsqlquery;
    DspBloq: TDataSetProvider;
    CdsBloq: TClientDataSet;
    DsBloq: TDataSource;
    SqlCdsBloqBOL_CODBOL: TStringField;
    SqlCdsBloqBOL_ATIVO: TStringField;
    SqlCdsBloqBOL_CODBAN: TStringField;
    SqlCdsBloqBOL_NRLINHA: TStringField;
    SqlCdsBloqBOL_LOCAL: TStringField;
    SqlCdsBloqBOL_VENCTO: TStringField;
    SqlCdsBloqBOL_DTEMIS: TStringField;
    SqlCdsBloqBOL_CODFAT: TStringField;
    SqlCdsBloqBOL_ESPDOC: TStringField;
    SqlCdsBloqBOL_DESESPDOC: TStringField;
    SqlCdsBloqBOL_ACEITE: TStringField;
    SqlCdsBloqBOL_DESACEITE: TStringField;
    SqlCdsBloqBOL_DTPROCE: TStringField;
    SqlCdsBloqBOL_USOBCO: TStringField;
    SqlCdsBloqBOL_CARTEIRA: TStringField;
    SqlCdsBloqBOL_DESCARTEIRA: TStringField;
    SqlCdsBloqBOL_VLPARC: TStringField;
    SqlCdsBloqBOL_ESPECIE: TStringField;
    SqlCdsBloqBOL_DESPECIE: TStringField;
    SqlCdsBloqBOL_QUANTIDADE: TStringField;
    SqlCdsBloqBOL_VALOR: TStringField;
    SqlCdsBloqBOL_VLDOC: TStringField;
    SqlCdsBloqBOL_JUROMES: TStringField;
    SqlCdsBloqBOL_DESCABAT: TStringField;
    SqlCdsBloqBOL_OBSBOL1: TStringField;
    SqlCdsBloqBOL_OUTDEDU: TStringField;
    SqlCdsBloqBOL_OBSBOL2: TStringField;
    SqlCdsBloqBOL_MORAMULTA: TStringField;
    SqlCdsBloqBOL_OBSBOL3: TStringField;
    SqlCdsBloqBOL_OUTACRES: TStringField;
    SqlCdsBloqBOL_OBSBOL4: TStringField;
    SqlCdsBloqBOL_VLCOBRADO: TStringField;
    SqlCdsBloqBOL_RAZAO: TStringField;
    SqlCdsBloqBOL_END: TStringField;
    SqlCdsBloqBOL_CEP: TStringField;
    SqlCdsBloqBOL_CID: TStringField;
    SqlCdsBloqBOL_EST: TStringField;
    SqlCdsBloqBOL_CNPJ: TStringField;
    SqlCdsBloqEMP_CODIGO: TStringField;
    CdsBloqBOL_CODBOL: TStringField;
    CdsBloqBOL_ATIVO: TStringField;
    CdsBloqBOL_CODBAN: TStringField;
    CdsBloqBOL_NRLINHA: TStringField;
    CdsBloqBOL_LOCAL: TStringField;
    CdsBloqBOL_VENCTO: TStringField;
    CdsBloqBOL_DTEMIS: TStringField;
    CdsBloqBOL_CODFAT: TStringField;
    CdsBloqBOL_ESPDOC: TStringField;
    CdsBloqBOL_DESESPDOC: TStringField;
    CdsBloqBOL_ACEITE: TStringField;
    CdsBloqBOL_DESACEITE: TStringField;
    CdsBloqBOL_DTPROCE: TStringField;
    CdsBloqBOL_USOBCO: TStringField;
    CdsBloqBOL_CARTEIRA: TStringField;
    CdsBloqBOL_DESCARTEIRA: TStringField;
    CdsBloqBOL_VLPARC: TStringField;
    CdsBloqBOL_ESPECIE: TStringField;
    CdsBloqBOL_DESPECIE: TStringField;
    CdsBloqBOL_QUANTIDADE: TStringField;
    CdsBloqBOL_VALOR: TStringField;
    CdsBloqBOL_VLDOC: TStringField;
    CdsBloqBOL_JUROMES: TStringField;
    CdsBloqBOL_DESCABAT: TStringField;
    CdsBloqBOL_OBSBOL1: TStringField;
    CdsBloqBOL_OUTDEDU: TStringField;
    CdsBloqBOL_OBSBOL2: TStringField;
    CdsBloqBOL_MORAMULTA: TStringField;
    CdsBloqBOL_OBSBOL3: TStringField;
    CdsBloqBOL_OUTACRES: TStringField;
    CdsBloqBOL_OBSBOL4: TStringField;
    CdsBloqBOL_VLCOBRADO: TStringField;
    CdsBloqBOL_RAZAO: TStringField;
    CdsBloqBOL_END: TStringField;
    CdsBloqBOL_CEP: TStringField;
    CdsBloqBOL_CID: TStringField;
    CdsBloqBOL_EST: TStringField;
    CdsBloqBOL_CNPJ: TStringField;
    CdsBloqEMP_CODIGO: TStringField;
    SqlCdsBloqBOL_OBS1: TStringField;
    SqlCdsBloqBOL_OBS2: TStringField;
    SqlCdsBloqBOL_OBS3: TStringField;
    SqlCdsBloqBOL_OBS4: TStringField;
    CdsBloqBOL_OBS1: TStringField;
    CdsBloqBOL_OBS2: TStringField;
    CdsBloqBOL_OBS3: TStringField;
    CdsBloqBOL_OBS4: TStringField;
    SqlCdsBloqBOL_LOCPGTO: TStringField;
    CdsBloqBOL_LOCPGTO: TStringField;
    SqlCdsNFCNF_COMPDESCRI: TStringField;
    CdsNFCNF_COMPDESCRI: TStringField;
    SqlCdsNFCNF_MENSAPADRAO1: TStringField;
    CdsNFCNF_MENSAPADRAO1: TStringField;
    SqlSeq: tsqlquery;
    DspSeq: TDataSetProvider;
    CdsSeq: TClientDataSet;
    DsSeq: TDataSource;
    SqlSeqPed: tsqlquery;
    DspSeqPed: TDataSetProvider;
    CdsSeqPed: TClientDataSet;
    DsSeqPed: TDataSource;
    SqlSeqSEQUENCIA_TABELA: TStringField;
    SqlSeqSEQUENCIA_CAMPO: TStringField;
    SqlSeqSEQUENCIA_VALOR: TIntegerField;
    CdsSeqSEQUENCIA_TABELA: TStringField;
    CdsSeqSEQUENCIA_CAMPO: TStringField;
    CdsSeqSEQUENCIA_VALOR: TIntegerField;
    SqlSeqPedSEQUENCIA_TABELA: TStringField;
    SqlSeqPedSEQUENCIA_CAMPO: TStringField;
    SqlSeqPedPENDENCIA_VALOR: TIntegerField;
    CdsSeqPedSEQUENCIA_TABELA: TStringField;
    CdsSeqPedSEQUENCIA_CAMPO: TStringField;
    CdsSeqPedPENDENCIA_VALOR: TIntegerField;
    SqlSeqSEQUENCIA_REGISTRO: TIntegerField;
    CdsSeqSEQUENCIA_REGISTRO: TIntegerField;
    SqlSeqPedSEQUENCIA_REGISTRO: TIntegerField;
    CdsSeqPedSEQUENCIA_REGISTRO: TIntegerField;
    SqlSeqSEQUENCIA_EMPRESA: TStringField;
    CdsSeqSEQUENCIA_EMPRESA: TStringField;
    SqlSeqPedSEQUENCIA_EMPRESA: TStringField;
    CdsSeqPedSEQUENCIA_EMPRESA: TStringField;
    SqlCheque: tsqlquery;
    DspCheque: TDataSetProvider;
    CdsSysCheque: TClientDataSet;
    DsSysCheque: TDataSource;
    SqlCdsNFCNF_NFCONTINUA: TStringField;
    CdsNFCNF_NFCONTINUA: TStringField;
    SqlCdsNFCNF_QTDE_ITENS: TIntegerField;
    CdsNFCNF_QTDE_ITENS: TIntegerField;
    SqlCdsNFCNF_DEMOCALC: TStringField;
    CdsNFCNF_DEMOCALC: TStringField;
    SqlCdsDuplCdU_OBS: TStringField;
    CdsDuplCdU_OBS: TStringField;
    SqlChequeSCH_REGISTRO: TIntegerField;
    SqlChequeEMP_CODIGO: TStringField;
    SqlChequeBAN_CODIGO: TStringField;
    SqlChequeSCH_FONTE: TIntegerField;
    SqlChequeSCH_ENTRE_LINHAS: TIntegerField;
    SqlChequeSCH_QTDE_LINHAS: TIntegerField;
    SqlChequeSCH_VALOR: TStringField;
    SqlChequeSCH_LINHA1_EXT: TStringField;
    SqlChequeSCH_LINHA2_EXT: TStringField;
    SqlChequeSCH_QTDE_CARACTERES: TIntegerField;
    SqlChequeSCH_FAVORECIDO: TStringField;
    SqlChequeSCH_CIDADE: TStringField;
    SqlChequeSCH_DIA: TStringField;
    SqlChequeSCH_MES: TStringField;
    SqlChequeSCH_ANO: TStringField;
    SqlChequeSCH_TAM_ANO: TIntegerField;
    SqlChequeSCH_BOM_PARA: TStringField;
    CdsSysChequeSCH_REGISTRO: TIntegerField;
    CdsSysChequeEMP_CODIGO: TStringField;
    CdsSysChequeBAN_CODIGO: TStringField;
    CdsSysChequeSCH_FONTE: TIntegerField;
    CdsSysChequeSCH_ENTRE_LINHAS: TIntegerField;
    CdsSysChequeSCH_QTDE_LINHAS: TIntegerField;
    CdsSysChequeSCH_VALOR: TStringField;
    CdsSysChequeSCH_LINHA1_EXT: TStringField;
    CdsSysChequeSCH_LINHA2_EXT: TStringField;
    CdsSysChequeSCH_QTDE_CARACTERES: TIntegerField;
    CdsSysChequeSCH_FAVORECIDO: TStringField;
    CdsSysChequeSCH_CIDADE: TStringField;
    CdsSysChequeSCH_DIA: TStringField;
    CdsSysChequeSCH_MES: TStringField;
    CdsSysChequeSCH_ANO: TStringField;
    CdsSysChequeSCH_TAM_ANO: TIntegerField;
    CdsSysChequeSCH_BOM_PARA: TStringField;
    procedure CdsSeqAfterEdit(DataSet: TDataSet);
    procedure CdsSeqAfterScroll(DataSet: TDataSet);
    procedure CdsSysChequeBeforePost(DataSet: TDataSet);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  DmCfg: TDmCfg;

implementation

uses DataCad, Prmd0001, SEQ0000, Men0001, uteis, iniciodb;

{$R *.dfm}

procedure TDmCfg.CdsSeqAfterEdit(DataSet: TDataSet);
begin
    if Assigned(FrmSequenciador)then
       FrmSequenciador.HabilitaBotoes;
end;

procedure TDmCfg.CdsSeqAfterScroll(DataSet: TDataSet);
Var
  wSeleciona,wOrdem : String;
begin
    if (CdsSeq.State in [dsBrowse]) then
       begin
           try
             wSeleciona := ' WHERE S2.SEQUENCIA_TABELA = '''+Trim(CdsSeqSEQUENCIA_TABELA.AsString)+''' AND S2.SEQUENCIA_CAMPO = '''+Trim(CdsSeqSEQUENCIA_CAMPO.AsString)+'''';
             if SHARE('PARAMETROS')='E' then
                begin
                    wSeleciona := wSeleciona + ' AND S2.SEQUENCIA_EMPRESA = '''+Trim(CdsSeqSEQUENCIA_EMPRESA.AsString)+'''';
                end
             else
                begin
                    wSeleciona := '';
                end;
             wOrdem     := ' ORDER BY S2.SEQUENCIA_EMPRESA,S2.SEQUENCIA_TABELA,S2.SEQUENCIA_CAMPO';
             CdsSeqPed.Close;
             CdsSeqPed.CommandText := 'SELECT S2.* FROM SYS_SEQUENCIADOR_PENDENCIAS S2 '+wSeleciona+wOrdem;
             CdsSeqPed.Open;
           except on E:EdataBaseError do
              uteis.erro  (pchar('Erro ao localizar as pendencias ! '+e.Message));
           end;
       end;
end;

procedure TDmCfg.CdsSysChequeBeforePost(DataSet: TDataSet);
begin
 datacadastros.IncrementaRegistro('SYS_CHEQUE',CdsSysChequeSCH_REGISTRO);
end;

end.

