CREATE TABLE SETOR (
    CODIGO INTEGER NOT NULL,
    DESCRICAO VARCHAR(60));

COMMIT WORK;

ALTER TABLE SETOR
   ADD CONSTRAINT PK_SETOR
PRIMARY KEY (CODIGO)    ;
COMMIT WORK;

ALTER TABLE OCORRENCIA
ADD OCORRENCIATIPO CHAR(1);
COMMIT WORK;



UPDATE  VERSAOSISTEMA SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.0.488',
       VERSAOSISTEMA.DATA   = '12.06.2017'
 where VERSAOSISTEMA.CODIGO = 1;
 
COMMIT WORK;
