UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.570 patch 1',
    VERSAOSISTEMA.DATA   = '23.06.2022',
	VERSAO = '3.0.9.570'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE PRMT0001 ADD PMT_PEDIDO_IND_PLASTICA VARCHAR(1) DEFAULT 'N';
COMMENT ON COLUMN PRMT0001.PMT_PEDIDO_IND_PLASTICA is 'Tela de Pedido para Indústria Plástica';
ALTER TABLE PRMT0001 ADD PMT_GRADE_MEDIDA1 VARCHAR(50);
COMMENT ON COLUMN PRMT0001.PMT_GRADE_MEDIDA1 is 'Descrição para Medida1 da Grade';
ALTER TABLE PRMT0001 ADD PMT_GRADE_MEDIDA2 VARCHAR(50);
COMMENT ON COLUMN PRMT0001.PMT_GRADE_MEDIDA2 is 'Descrição para Medida2 da Grade';
ALTER TABLE PRMT0001 ADD PMT_GRADE_MEDIDA3 VARCHAR(50);
COMMENT ON COLUMN PRMT0001.PMT_GRADE_MEDIDA3 is 'Descrição para Medida3 da Grade';
UPDATE PRMT0001 SET PMT_GRADE_MEDIDA1 = 'Medida 1:' WHERE PMT_GRADE_MEDIDA1 IS NULL;
UPDATE PRMT0001 SET PMT_GRADE_MEDIDA2 = 'Medida 2:' WHERE PMT_GRADE_MEDIDA2 IS NULL;
UPDATE PRMT0001 SET PMT_GRADE_MEDIDA3 = 'Medida 3:' WHERE PMT_GRADE_MEDIDA3 IS NULL;

ALTER TABLE PED_IT01 ADD PRF_PESO NUMERIC(18,5);
COMMENT ON COLUMN PED_IT01.PRF_PESO is 'Peso do Item no Pedido';


ALTER TABLE PRD0000 ADD PRD_FATOR_PROD_TEMP NUMERIC(18,5);
UPDATE PRD0000 SET PRD_FATOR_PROD_TEMP = PRD_FATOR_PROD ;
ALTER TABLE PRD0000 DROP PRD_FATOR_PROD;
ALTER TABLE PRD0000 ALTER COLUMN PRD_FATOR_PROD_TEMP TO PRD_FATOR_PROD;
COMMENT ON COLUMN PRD0000.PRD_FATOR_PROD is 'Fator de Conversão do Produto';

ALTER TABLE ENF0001 ADD ENF_OBS_INDUST BLOB SUB_TYPE TEXT;
COMMENT ON COLUMN ENF0001.ENF_OBS_INDUST IS 'Observações para Indutrialização';



