UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.588 patch 1',
    VERSAOSISTEMA.DATA   = '17.01.2024',
	VERSAO = '3.0.9.588'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

/* issue 1760 */
CREATE TABLE LOTE_ESTORNADO  (
  PMT_LOTE_SEMENTE VARCHAR(50),   
  EMP_CODIGO VARCHAR(3)
);

/* issue 1780 */
ALTER TABLE TIPO_EMBALAGEM ADD TEM_CAPACIDADE DOUBLE PRECISION;
COMMENT ON COLUMN TIPO_EMBALAGEM.TEM_CAPACIDADE IS 'Capacidade da Embalagem';

/* issue 1788 */
ALTER TABLE PRMT0001 ADD PMT_BLOQ_PED_VENDA_FAT_ATRASO VARCHAR(1);
COMMENT ON COLUMN PRMT0001.PMT_BLOQ_PED_VENDA_FAT_ATRASO IS 'Bloqueio de pedido de venda para clientes com faturas em atraso maior que o prazo definido';
ALTER TABLE PRMT0001 ADD PMT_BLOQ_PED_VENDA_FAT_ATRASO_D INTEGER;
COMMENT ON COLUMN PRMT0001.PMT_BLOQ_PED_VENDA_FAT_ATRASO_D IS 'Quantidade de dias para bloqueio de pedido de venda para clientes com faturas em atraso maior que o prazo definido';
ALTER TABLE USUARIO_PARAMETRO ADD USP_PERMITE_VENDA_FATURA_ATRASO VARCHAR(1);
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_PERMITE_VENDA_FATURA_ATRASO IS 'Permite venda a cliente com faturas em atraso';

