SET TERM ^ ;

alter table opv0000 add OPV_SEMLOTE VARCHAR(1)^
COMMIT WORK^

Update VERSAOSISTEMA SET
       VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.0.459' ,
       VERSAOSISTEMA.DATA   = '20.09.2016'
 where VERSAOSISTEMA.CODIGO = 1^

COMMIT WORK^

SET TERM ; ^



