UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.593 patch 1',
    VERSAOSISTEMA.DATA   = '14.06.2024',
	VERSAO = '3.0.9.593'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

/* issue 1886 */
ALTER TABLE USUARIO_PARAMETRO ADD USP_BOTAO_DESVINCULAR_PEDIDO VARCHAR(1);
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_BOTAO_DESVINCULAR_PEDIDO IS 'Habilita (Mostra) o Botão Desvincular Pedido na Tela da Programação da Produção';
UPDATE USUARIO_PARAMETRO SET USP_BOTAO_DESVINCULAR_PEDIDO = 'N' WHERE USP_BOTAO_DESVINCULAR_PEDIDO IS NULL;  
COMMIT WORK;

/* issue 1890 */
ALTER TABLE  NF_IT01 ADD NF_ALIQCREDSIMPLES NUMERIC (18,5);
COMMENT ON COLUMN NF_IT01.NF_ALIQCREDSIMPLES IS 'Alíquota do aproveitamento de crédito de ICMS'; 
ALTER TABLE NF_IT01 ADD NF_VLCREDSIMPLES NUMERIC (18,5);
COMMENT ON COLUMN NF_IT01.NF_VLCREDSIMPLES IS 'Valor do aproveitamento de crédito de ICMS'; 

