
UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.535',
       VERSAOSISTEMA.DATA   = '31.07.2019',
	    VERSAO = '3.0.9.535'
 where VERSAOSISTEMA.CODIGO = 1;

COMMIT WORK;


ALTER TABLE ENTCTE ADD ecte_dataEntrada timestamp ;
COMMENT ON COLUMN ENTCTE.ECTE_DATAENTRADA IS 'DATA DE ENTRADA NO SISTEMA' ;


UPDATE ENTCTE
SET ecte_dataentrada = ecte_emissao+5;

commit work;