UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.608',
    VERSAOSISTEMA.DATA   = '15.10.2025',
	VERSAO = '3.0.9.608'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

/* ISSUE 2048 */
ALTER TABLE PRMT0001  ADD PMT_CADASTRA_PRODUTO_PEDIDO CHAR(1);
COMMENT ON COLUMN PRMT0001.PMT_CADASTRA_PRODUTO_PEDIDO is 'Apresenta o Painel de Importação (F12) de múltiplos XMLs na tela de Pedido';

/* ISSUE 2095 */
ALTER TABLE PRMT0001 ADD PMT_PRECO_LIQ_MENOR_TABELA_P CHAR(1) DEFAULT 'S';
COMMENT ON COLUMN PRMT0001.PMT_PRECO_LIQ_MENOR_TABELA_P IS 'Não Permite alterar o preço líquido menor que a tabela padrão';
UPDATE PRMT0001 SET PMT_PRECO_LIQ_MENOR_TABELA_P = 'N' WHERE PMT_PRECO_LIQ_MENOR_TABELA_P IS NULL;

