ALTER TABLE PRECOS0001
    ADD PERC_COMISSAO DECIMAL6,
    ADD PERC_VERBA DECIMAL6;

COMMIT WORK;

ALTER TABLE CONTA_CORRENTE
    ADD COD_PRODUTO VARCHAR(20),
    ADD DATA TIMESTAMP;

COMMIT WORK;


ALTER TABLE PCL0000
    ADD PERC_COMISSAO DECIMAL6,
    ADD PERC_VERBA DECIMAL6;

COMMIT WORK;
	
UPDATE  VERSAOSISTEMA SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.0.481',
       VERSAOSISTEMA.DATA   = '03.04.2017'
 where VERSAOSISTEMA.CODIGO = 1;
 
COMMIT WORK;

 