
UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.531 patch 4',
       VERSAOSISTEMA.DATA   = '24.04.2019',
	    VERSAO = '3.0.9.531'
 where VERSAOSISTEMA.CODIGO = 1;

commit work;
 
 
ALTER TABLE NF_IT01 ADD NF_ICMSSUBSTITUTO_ANT NUMERIC (18,5);
COMMENT ON COLUMN NF_IT01.NF_ICMSSUBSTITUTO_ANT IS 'VALOR DO ICMS PROPRIO DO SUBSTITUTO COBRADO EM OPERAÇÃO ANTERIOR';


ALTER TABLE PRMT0001 ADD PMT_RESPONSAVEL_TECNICO VARCHAR(1);
COMMENT ON COLUMN PRMT0001.PMT_RESPONSAVEL_TECNICO IS 'RESPONSAVEL TECNICO NO XML';

UPDATE PRMT0001 SET PMT_RESPONSAVEL_TECNICO = 'N';


