SET TERM ^ ;


alter table precos0001 add CODIGO_PRODUTO_CLIENTE  VARCHAR(25) CHARACTER SET WIN1252 COLLATE WIN_PTBR ^
alter table precos0001 add DESCRICAO_PRODUTO_CLIENTE  VARCHAR(60) CHARACTER SET WIN1252 COLLATE WIN_PTBR ^
--alter table precos0000 add pre_codigo integer^
--alter table precos0000 add  PRE_DTCADASTRO   DATE^
CREATE INDEX PRECOS0001_IDX3 ON PRECOS0001 (CODIGO_PRODUTO_CLIENTE)^
ALTER TABLE PRMT0001 ADD PMT_OBRIGAR_DIRETIVA_VENDA_ABA CHAR(1) CHARACTER SET WIN1252 COLLATE WIN_PTBR ^

ALTER TABLE PRD_CODIGOORIGINAL ADD CLI_CODIGO VARCHAR(5)^
ALTER TABLE PRD_CODIGOORIGINAL ADD PRDCO_DESCRICAO VARCHAR(60) CHARACTER SET WIN1252 COLLATE WIN_PTBR^

CREATE DOMAIN NUMEROSREAIS DOUBLE PRECISION^

update RDB$RELATION_FIELDS set RDB$FIELD_SOURCE = 'NUMEROSREAIS' where (RDB$FIELD_NAME = 'PRF_IDESCTO1') and (RDB$RELATION_NAME = 'PED_IT01')^
update RDB$RELATION_FIELDS set RDB$FIELD_SOURCE = 'NUMEROSREAIS' where (RDB$FIELD_NAME = 'PRF_IDESCTO2') and (RDB$RELATION_NAME = 'PED_IT01')^

COMMIT WORK^

Update VERSAOSISTEMA SET
       VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.0.448' ,
       VERSAOSISTEMA.DATA   = '15.04.2016'
 where VERSAOSISTEMA.CODIGO = 1^

COMMIT WORK^



SET TERM ; ^


