ALTER TABLE PED_IT01
    ADD OPE_CODIGO VARCHAR(3);
	
COMMIT WORK;

DELETE FROM FLUXOCX WHERE EMP_CODIGO = '1';

COMMIT WORK;

UPDATE  VERSAOSISTEMA SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.0.475',
       VERSAOSISTEMA.DATA   = '18.01.2017'
 where VERSAOSISTEMA.CODIGO = 1;
 
 COMMIT WORK;
