UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.592 patch 4',
    VERSAOSISTEMA.DATA   = '29.05.2024',
	VERSAO = '3.0.9.592'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

/* issue 1872 */
ALTER TABLE USUARIO_PARAMETRO ADD USP_ATIVAR_TROCA_CENTRO_CUSTO VARCHAR(1);
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_ATIVAR_TROCA_CENTRO_CUSTO IS 'Mostra o Botão Transferir na Tela de Cadastros -> Centro de Custo - [S]im | [N]ão';
UPDATE USUARIO_PARAMETRO SET USP_ATIVAR_TROCA_CENTRO_CUSTO = 'N' WHERE USP_ATIVAR_TROCA_CENTRO_CUSTO IS NULL;
COMMIT WORK;
