UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.556 patch 3',
    VERSAOSISTEMA.DATA   = '24.05.2021',
	VERSAO = '3.0.9.556'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE PARAMETROS_DA_QUALIDADE DROP PAR_VALOR_MIN;
ALTER TABLE PARAMETROS_DA_QUALIDADE DROP PAR_VALOR_MAX;
ALTER TABLE PARAMETROS_DA_QUALIDADE ADD PAR_OBSERVACAO VARCHAR(100);
ALTER TABLE CONTROLE_DE_QUALIDADE ADD PRD_REFER VARCHAR(20);

RECREATE TABLE CONTROLE_DE_QUALIDADE_PRODUTO (
	PRD_REFER VARCHAR(20) ,
	PAR_CODIGO INTEGER,
	CQP_ESPERADO VARCHAR(60),
	CQP_VALOR_MIN VARCHAR(60),
	CQP_VALOR_MAX VARCHAR(60),
	PRIMARY KEY (PRD_REFER, PAR_CODIGO)
);

DELETE FROM wsnovi;

INSERT INTO WSNOVI (WSLIC, SEQUENCIA) VALUES ('http://novinow.ddns.net:50122/ValidadorOnline/valida/validar', 1);
INSERT INTO WSNOVI (WSLIC, SEQUENCIA) VALUES ('http://novinow.dynu.net:50122/ValidadorOnline/valida/validar', 2);

