UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.541 patch 4',
       VERSAOSISTEMA.DATA   = '12.02.2020',
	    VERSAO = '3.0.9.541'
 where VERSAOSISTEMA.CODIGO = 1;

commit work;



INSERT INTO CLIENTE_ORIGEM (CORI_CODIGO, CORI_DESCRICAO) VALUES (1,'SITE');
INSERT INTO CLIENTE_ORIGEM (CORI_CODIGO, CORI_DESCRICAO) VALUES (2,'INTERNET/GOOGLE');
INSERT INTO CLIENTE_ORIGEM (CORI_CODIGO, CORI_DESCRICAO) VALUES (3,'REPRESENTANTES');
INSERT INTO CLIENTE_ORIGEM (CORI_CODIGO, CORI_DESCRICAO) VALUES (4,'INDICACAO');
INSERT INTO CLIENTE_ORIGEM (CORI_CODIGO, CORI_DESCRICAO) VALUES (5,'EMAIL MARKETING');
INSERT INTO CLIENTE_ORIGEM (CORI_CODIGO, CORI_DESCRICAO) VALUES (6,'MARKETPLACE');
INSERT INTO CLIENTE_ORIGEM (CORI_CODIGO, CORI_DESCRICAO) VALUES (7,'FEIRA');
INSERT INTO CLIENTE_ORIGEM (CORI_CODIGO, CORI_DESCRICAO) VALUES (8,'LICITACAO');
INSERT INTO CLIENTE_ORIGEM (CORI_CODIGO, CORI_DESCRICAO) VALUES (9,'ANUNCIOS');
INSERT INTO CLIENTE_ORIGEM (CORI_CODIGO, CORI_DESCRICAO) VALUES (10,'CLIENTE ANTIGO');
ALTER SEQUENCE GEN_CLIENTE_ORIGEM RESTART WITH 10;
commit work;


ALTER TABLE FOR0000 ADD FOR_DATAULTFORNECIMENTO DATE;
COMMENT ON COLUMN FOR0000.FOR_DATAULTFORNECIMENTO IS 'DATA DO ULTIMO FORNECIMENTO';


UPDATE FOR0000 F
SET FOR_DATAULTFORNECIMENTO = (SELECT MAX(ENF_EMISSAO) FROM ENF0001 EF WHERE EF.FOR_CODIGO = F.FOR_CODIGO)  ;


commit work;