UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.545 patch 5',
    VERSAOSISTEMA.DATA   = '09.06.2020',
	VERSAO = '3.0.9.545'
 where VERSAOSISTEMA.CODIGO = 1;

commit work;



ALTER TABLE kardex_almox_saldo ADD KAS_RESERVA NUMERIC(18,5); 


CREATE TABLE DEMANDA_PRODUCAO (
    DEP_CODIGO INTEGER NOT NULL,
    PED_CODIGO VARCHAR(7) NOT NULL,
    EMP_CODIGO VARCHAR(3) NOT NULL,
    PRF_REGISTRO INTEGER NOT NULL,
	PRD_CODIGO VARCHAR(5),
    DEP_DATA_ENTREGA DATE,
	DEP_QTDE_ESTOQUE NUMERIC(18,5),
	DEP_QTDE_PRODUCAO NUMERIC (18,5),
    DEP_SITUACAO VARCHAR(1),
	FTI_REGISTRO  INTEGER ,
	IOP_CODIGO INTEGER ,
	DEP_QTDE_PROGRA INTEGER
	);

ALTER TABLE DEMANDA_PRODUCAO
ADD CONSTRAINT PK_DEMANDA_PRODUCAO
PRIMARY KEY (DEP_CODIGO);

COMMENT ON COLUMN DEMANDA_PRODUCAO.PED_CODIGO IS 'REFERENCIA DO PEDIDO (PED0000)';
COMMENT ON COLUMN DEMANDA_PRODUCAO.EMP_CODIGO IS 'EMP0000';
COMMENT ON COLUMN DEMANDA_PRODUCAO.PRF_REGISTRO IS 'REFERENCIA DO ITEM DO PEDIDO';
COMMENT ON COLUMN DEMANDA_PRODUCAO.DEP_DATA_ENTREGA IS 'DATA DE ENTREGA DO ITEM';
COMMENT ON COLUMN DEMANDA_PRODUCAO.DEP_SITUACAO IS 'SITUACAO DA DEMANDA : N - NAO ENVIADO; R - RECEBIDA PEDIDO ; E - ENVIADO PRODUCAO I - INICIADA ; C -CONCLUIDA - A ATRASADO;  ESTORNADO';
COMMENT ON COLUMN DEMANDA_PRODUCAO.FTI_REGISTRO is 'item da ficha técnica';
COMMENT ON COLUMN DEMANDA_PRODUCAO.IOP_CODIGO IS 'CHAVE DE REFENCIA  ITEM DA ORDEM';
COMMENT ON COLUMN DEMANDA_PRODUCAO.DEP_QTDE_PROGRA IS 'QUANTIDADE PROGRAMADA PARA GERAR ORDEM';

CREATE SEQUENCE GEN_DEMANDA_PRODUCAO;

SET TERM ^ ;

create trigger demanda_producao_bi for demanda_producao
active before insert position 0
as
begin
  if (new.dep_codigo is null) then
    new.dep_codigo = gen_id(gen_demanda_producao,1);
end^

SET TERM ; ^

COMMENT ON TABLE DEMANDA_PRODUCAO IS 'demanda de producao';

CREATE TABLE DEMANDA_HISTORICO (
    HDE_CODIGO INTEGER NOT NULL,
    HDE_DATAMVTO TIMESTAMP NOT NULL,
    USU_CODIGO INTEGER NOT NULL,
    HDE_DESCRICAO VARCHAR(150),
    DEP_CODIGO INTEGER NOT NULL,
	PED_CODIGO VARCHAR(7) NOT NULL,
	PRD_CODIGO VARCHAR(5));

ALTER TABLE DEMANDA_HISTORICO
ADD CONSTRAINT PK_DEMANDA_HISTORICO
PRIMARY KEY (HDE_CODIGO);

COMMENT ON COLUMN DEMANDA_HISTORICO.HDE_DATAMVTO IS 'DATA DO MOVIMENTO REALIZADO';
COMMENT ON COLUMN DEMANDA_HISTORICO.USU_CODIGO IS 'REFERENCIA DO USUARIO';
COMMENT ON COLUMN DEMANDA_HISTORICO.HDE_DESCRICAO IS 'DESCRICAO DO QUE FOI MOVIMENTADO';
COMMENT ON COLUMN DEMANDA_HISTORICO.DEP_CODIGO IS 'REFERENCIA DA TABELA DE DEMANDA_PRODUCAO';

CREATE SEQUENCE GEN_DEMANDA_HISTORICO;

SET TERM ^ ;

create trigger demanda_historico_bi for demanda_historico
active before insert position 0
as
begin
  if (new.hde_codigo is null) then
    new.hde_codigo = gen_id(gen_demanda_historico,1);
end^

SET TERM ; ^

COMMENT ON TABLE DEMANDA_HISTORICO IS 'HISTORICO DE ACOES DA DEMANDA';

ALTER TABLE PRMT0001 ADD PMT_GERARSUBORDENS varchar(1);
COMMENT ON COLUMN PRMT0001.PMT_GERARSUBORDENS IS 'gerar subordens(PI/PA) DENTRO DA PRINCIPAL';

ALTER TABLE PRMT0001 ADD PMT_HABILITAR_MRP VARCHAR(1);
COMMENT ON COLUMN PRMT0001.PMT_HABILITAR_MRP IS 'HABILITAR MODULO PRODUCAO MRP  : S - SIM N NAO';

alter table PRMT0001 ADD PMT_COMPOSICAOORDEM VARCHAR(1);
COMMENT ON COLUMN PRMT0001.PMT_COMPOSICAOORDEM IS 'P - MESMO DO PEDIDO ; S - SEQUENCIAL';

ALTER TABLE PRMT0001 ADD PMT_COMSUMIRINSUMO VARCHAR(1);
COMMENT ON COLUMN PRMT0001.PMT_COMSUMIRINSUMO IS 'CONSUMIR PRODUTOS M - MANUAL ; E - ENVIO DA PRODUCAO ;  I  - INICIO DA PRODUCAO; A - EMPENHAR NO APONTAMENTO DA OPERACAO';

ALTER TABLE PRMT0001 ADD PMT_CUSTO_MATERIAPRIMA VARCHAR(1);
COMMENT ON COLUMN PRMT0001.PMT_CUSTO_MATERIAPRIMA IS 'CUSTO DE NA MP : L CUSTO LIQUIDO E CUSTO DE ENTRADA ; M - CUSTO MEDIO';


UPDATE PRMT0001
SET pmt_gerarsubordens = 'S', PMT_HABILITAR_MRP = 'N', PMT_COMPOSICAOORDEM = 'S' , PMT_COMSUMIRINSUMO = 'I' , PMT_CUSTO_MATERIAPRIMA = 'L' ;


CREATE TABLE MATERIAPRIMA_ORDEMPRODUCAO (
    MP_CODIGO INTEGER NOT NULL,
    PED_CODIGO VARCHAR(7) NOT NULL,
    IOP_CODIGO INTEGER NOT NULL,
    OPR_CODIGO INTEGER NOT NULL,
    PRD_CODIGO VARCHAR(5) NOT NULL,
    MP_UCONSUMO NUMERIC(18,5) NOT NULL,
    MP_BASECOMPOSICAO NUMERIC(18,5),
    MP_SITUACAO VARCHAR(1),
    MP_EMPENHADO NUMERIC(18,5),
    MP_CONSUMOTOTAL NUMERIC(18,5),
	MP_CODIGO_SUBST INTEGER,
	MP_CUSTO NUMERIC (18,5),
	OPE_CODIGO INTEGER
	);

ALTER TABLE MATERIAPRIMA_ORDEMPRODUCAO
ADD CONSTRAINT PK_MATERIAPRIMA_ORDEMPRODUCAO
PRIMARY KEY (MP_CODIGO);

COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.MP_CODIGO IS 'CHAVE IDENTIFICADORA';
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.PED_CODIGO IS 'CHAVE DA TABELA PEDIDO (PED0000)';
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.IOP_CODIGO IS 'CHAVE DE REFENCIA  ITEM DA ORDEM - REFERENTE AO PRODUTO DE COMPOSICAO';
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.OPR_CODIGO IS 'CHAVE DE REFERENCIA DA ORDEM';
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.PRD_CODIGO IS 'REFERENCIA DA CHAVE DO PRODUTO (PRD0000)';
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.MP_UCONSUMO IS 'CONSUMO UNITÁRIO';
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.MP_BASECOMPOSICAO IS 'BASE DE COMPOSICAO';
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.MP_SITUACAO IS 'SITUACAO';
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.MP_EMPENHADO IS 'QUANTIDADE DE CONSUMIDO';
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.MP_CODIGO_SUBST IS 'MATERIAL QUE SUBSTITUI';
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.MP_CUSTO is 'CUSTO TOTAL AO EMPENHAR';
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.OPE_CODIGO IS 'OPERACAO PADRAO (OPERACAO)';

CREATE SEQUENCE GEN_MATERIAPRIMA;

SET TERM ^ ;

create trigger materiaprima_ordemproducao_bi for materiaprima_ordemproducao
active before insert position 0
as
begin
  if (new.mp_codigo is null) then
    new.mp_codigo = gen_id(gen_materiaprima,1);
end^

SET TERM ; ^


ALTER TABLE ITEM_ORDEMPRODUCAO ADD FTI_REGISTRO INTEGER;
ALTER TABLE ITEM_ORDEMPRODUCAO ADD IOP_DATALIBERACAO TIMESTAMP;
ALTER TABLE ITEM_ORDEMPRODUCAO ADD IOP_QTDE_REFUGADA NUMERIC(18,5);
ALTER TABLE ITEM_ORDEMPRODUCAO ADD IOP_QTDE_CONCLUIDA NUMERIC(18,5);
ALTER TABLE ITEM_ORDEMPRODUCAO ADD IOP_QTDE_PRODUZINDO NUMERIC(18,5);
ALTER TABLE ITEM_ORDEMPRODUCAO ADD IOP_CUSTOMP NUMERIC (18,5);

COMMENT ON COLUMN ITEM_ORDEMPRODUCAO.FTI_REGISTRO IS 'ITEM DA FICHA TECNICA';
COMMENT ON COLUMN ITEM_ORDEMPRODUCAO.IOP_DATALIBERACAO IS ' DATA DE LIBERACAO DA DEMANDA';
COMMENT ON COLUMN ITEM_ORDEMPRODUCAO.IOP_QTDE_REFUGADA IS 'QUANTIDADE REFUGADA';
COMMENT ON COLUMN ITEM_ORDEMPRODUCAO.IOP_QTDE_CONCLUIDA IS 'QUANTIDADE CONCLUIDA';
COMMENT ON COLUMN ITEM_ORDEMPRODUCAO.IOP_QTDE_PRODUZINDO IS 'QUANTIDADE EM PRODUCAO';
COMMENT ON COLUMN ITEM_ORDEMPRODUCAO.IOP_CUSTOMP IS 'CUSTO DE MATERIA PRIMA';

 ALTER TABLE FTC0000 ADD FTC_ETAPAS  BLOB SUB_TYPE 0;
 
 UPDATE FTC0000 
 SET FTC_ETAPAS = FTC_PROC1 || FTC_PROC2 || FTC_PROC3 || FTC_PROC4 ||
 FTC_PROC5 || FTC_PROC6 || FTC_PROC7 || FTC_PROC8;
 
 COMMIT WORK;
 
 
 CREATE TABLE EMPENHO (
    EPE_CODIGO INTEGER NOT NULL,
    IOP_CODIGO INTEGER,
    MP_CODIGO INTEGER,
    PRD_CODIGO VARCHAR(5),
    EMP_QUANTIDADE NUMERIC(18,5),
    EMP_DATAEMPENHO TIMESTAMP,
    EMP_TIPO VARCHAR(1),
    PRDL_REGISTRO INTEGER,
	USU_CODIGO INTEGER NOT NULL,
    EPE_PRECO NUMERIC (18,5),
    EPE_CUSTO NUMERIC (18,5)
	);

ALTER TABLE EMPENHO
ADD CONSTRAINT PK_EMPENHO
PRIMARY KEY (EPE_CODIGO);

COMMENT ON COLUMN EMPENHO.EPE_CODIGO IS 'CHAVE PRIMARIA';
COMMENT ON COLUMN EMPENHO.IOP_CODIGO IS 'REFERENCIA DO ITEM DO ITEM DA ORDEM';
COMMENT ON COLUMN EMPENHO.MP_CODIGO IS 'REFERENCIA DA MATERIA PRIMA NO EMPENHO';
COMMENT ON COLUMN EMPENHO.PRD_CODIGO IS 'REFERENCIA DO PRODUTO';
COMMENT ON COLUMN EMPENHO.EMP_QUANTIDADE IS 'QUANTIDADE CONSUMIDA DO INSUMO';
COMMENT ON COLUMN EMPENHO.EMP_DATAEMPENHO IS 'DATA DO EMPENHO';
COMMENT ON COLUMN EMPENHO.EMP_TIPO IS 'A - AUTOMATICO - M : MANUAL E - ESORNADO';
COMMENT ON COLUMN EMPENHO.PRDL_REGISTRO IS 'LOTE';
COMMENT ON COLUMN EMPENHO.USU_CODIGO IS 'CHAVE REFERNCIA DO USUARIO';
COMMENT ON COLUMN EMPENHO.EPE_PRECO IS 'PRECO AO EMPENHAR ';
COMMENT ON COLUMN EMPENHO.EPE_CUSTO IS 'CUSTO AP EMPENHAR';
CREATE SEQUENCE GEN_EMPENHO_MATERIA_ID;

SET TERM ^ ;

create trigger empenho_bi for empenho
active before insert position 0
as
begin
  if (new.EPE_CODIGO is null) then
    new.EPE_CODIGO = gen_id(GEN_EMPENHO_MATERIA_ID,1);
end^

SET TERM ; ^

COMMENT ON TABLE EMPENHO IS 'CADASTRO DE EMPENHO';




CREATE TABLE HISTORICO_ORDEMPRODUCAO (
    HOP_CODIGO INTEGER NOT NULL,
    HOP_DATAMVTO TIMESTAMP NOT NULL,
    HOP_DESCRICAO VARCHAR(150) NOT NULL,
    USU_CODIGO INTEGER NOT NULL,
    IOP_CODIGO INTEGER NOT NULL,
	MP_CODIGO INTEGER);

COMMENT ON COLUMN HISTORICO_ORDEMPRODUCAO.HOP_CODIGO IS 'CODIGO IDENTIFICADOR';
COMMENT ON COLUMN HISTORICO_ORDEMPRODUCAO.HOP_DATAMVTO IS 'DATA DO MOVIMENTO DA PRODUCAO';
COMMENT ON COLUMN HISTORICO_ORDEMPRODUCAO.HOP_DESCRICAO IS 'DESCRICAO DO HISTORICO';
COMMENT ON COLUMN HISTORICO_ORDEMPRODUCAO.USU_CODIGO IS 'USUARIO DO SISTEMA QUE FEZ MOVIMENTO';
COMMENT ON COLUMN HISTORICO_ORDEMPRODUCAO.IOP_CODIGO IS 'CHAVE DE REFERENCIA DE ITEM DE ORDEM DE PRODUCAO';
COMMENT ON COLUMN HISTORICO_ORDEMPRODUCAO.MP_CODIGO IS 'CHAVE DE REFERENCIA DA MATERIA-PRIMA';

CREATE SEQUENCE GEN_HISTORICO_ORDEMPRODUCAO;

SET TERM ^ ;

create trigger historico_ordemproducao_bi for historico_ordemproducao
active before insert position 0
as
begin
  if (new.hop_codigo is null) then
    new.hop_codigo = gen_id(gen_historico_ordemproducao,1);
end^

SET TERM ; ^

COMMENT ON TABLE HISTORICO_ORDEMPRODUCAO IS 'HISTORICO debug ORDEM DE PRODUCAO, QUANDO FOI INICICIADO, APONTADO, SUSBSTITUIDO O PRODUTO';

 ALTER TABLE FABRICACAO ADD IOP_CODIGO INTEGER;
 COMMENT ON COLUMN FABRICACAO.IOP_CODIGO IS 'CHAVE REFERENCIA DO ITEM DE ORDEM DA PRODUCAO';
 
 CREATE TABLE ORDEM_PROGRAMADA (
    OPA_CODIGO INTEGER NOT NULL,
    OPA_SEQUENCIAL INTEGER NOT NULL,
    PED_CODIGO VARCHAR(7) NOT NULL,
    EMP_CODIGO VARCHAR(3) NOT NULL,
    DEP_CODIGO INTEGER NOT NULL,
    PRD_CODIGO VARCHAR(5) NOT NULL,
    OPA_DATA_ENTREGA TIMESTAMP NOT NULL,
    OPA_QTDE_PRODUZIR NUMERIC(18,5) NOT NULL,
    IOP_CODIGO INTEGER );

ALTER TABLE ORDEM_PROGRAMADA
ADD CONSTRAINT PK_ORDEM_PROGRAMADA
PRIMARY KEY (OPA_CODIGO);

COMMENT ON COLUMN ORDEM_PROGRAMADA.OPA_CODIGO IS 'CHAVE DA ORDEM PROGRAMADA';

COMMENT ON COLUMN ORDEM_PROGRAMADA.OPA_SEQUENCIAL IS 'SEQUENCIAL DA PRODUCAO';

COMMENT ON COLUMN ORDEM_PROGRAMADA.PED_CODIGO IS 'CODIGO CHAVE DO PEDIDO';

COMMENT ON COLUMN ORDEM_PROGRAMADA.EMP_CODIGO IS 'CODIGO DA EMPRESA';
COMMENT ON COLUMN ORDEM_PROGRAMADA.DEP_CODIGO IS 'CHAVE DA DEMANDA';
COMMENT ON COLUMN ORDEM_PROGRAMADA.PRD_CODIGO IS 'CODIGO DO PEDIDO';
COMMENT ON COLUMN ORDEM_PROGRAMADA.OPA_DATA_ENTREGA IS 'DATA DE ENTREGA';
COMMENT ON COLUMN ORDEM_PROGRAMADA.OPA_QTDE_PRODUZIR IS 'QUANTIDADE PRODUZIR';
COMMENT ON COLUMN ORDEM_PROGRAMADA.IOP_CODIGO IS 'ITEM DA ORDEM DE PRODUCAO GERADA';

CREATE SEQUENCE GEN_ORDEM_PROGRAMADA;

COMMENT ON TABLE ORDEM_PROGRAMADA IS 'PEDIDO COM QUANTIDADE QUE VAI SER PRODUZIR EM DIVERSAS ORDEM AO LONGO DE UM PERIODO';


 ALTER TABLE ITEM_ORDEMPRODUCAO ADD iop_seq_prg int;
comment ON COLUMN ITEM_ORDEMPRODUCAO.iop_seq_prg IS ' SEQUENCIA DE PROGRAMACAO, QUANDO NAO VAI PRODUZIR TUDO DE UMA VEZ';

ALTER TABLE ITEM_ORDEMPRODUCAO ADD IOP_DTENTREGA DATE;
COMMENT ON COLUMN ITEM_ORDEMPRODUCAO.IOP_DTENTREGA IS 'DATA DE ENTREGA ESPECIFICA';


ALTER TABLE PRMT0001 ADD PMT_CUSTOOPERACAO VARCHAR(1);
COMMENT ON COLUMN PRMT0001.PMT_CUSTOOPERACAO IS 'FORMACAO DE CUSTO DE OPERACAO: 1 TEMPO PADRAO (ENGENHARIA) X CUSTO/HORA OPERACAO 2 - TEMPO PADRAO (ENGENHARIA) X CUSTO/HORA OPERACAO +CUSTO COLABORADOR';

ALTER TABLE PRMT0001 ADD PMT_CUSTOCOLABORADOR VARCHAR(1);
ALTER TABLE PRMT0001 ADD PMT_CUSTOEQUIPAMENTO VARCHAR(1);

update PRMT0001
set PMT_CUSTOOPERACAO = '1', PMT_CUSTOCOLABORADOR = '1' , PMT_CUSTOEQUIPAMENTO  ='1';

commit work;

ALTER TABLE ITEM_ORDEMPRODUCAO ADD IOP_CUSTOOPERACAO NUMERIC (18,5);
COMMENT ON COLUMN ITEM_ORDEMPRODUCAO.IOP_CUSTOOPERACAO IS 'CUSTO DA OPERACAO';
ALTER TABLE ITEM_ORDEMPRODUCAO ADD IOP_CUSTOCOLABORADOR NUMERIC (18,5);
COMMENT ON COLUMN ITEM_ORDEMPRODUCAO.IOP_CUSTOCOLABORADOR IS 'CUSTO DE MAO DE OBRA';
ALTER TABLE ITEM_ORDEMPRODUCAO ADD IOP_CUSTOEQUIPAMENTO NUMERIC (18,5);
COMMENT ON COLUMN ITEM_ORDEMPRODUCAO.IOP_CUSTOEQUIPAMENTO IS 'CUSTO DE EQUIPAMENTO';
ALTER TABLE ITEM_ORDEMPRODUCAO ADD IOP_CUSTOSERVICOS NUMERIC (18,5);
COMMENT ON COLUMN ITEM_ORDEMPRODUCAO.IOP_CUSTOSERVICOS IS 'CUSTO DE SERVICOS';


ALTER TABLE USUARIO_PARAMETRO ADD USP_CUSTOPRODUCAO VARCHAR(1);
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_CUSTOPRODUCAO IS 'MOSTRA CUSTO DE PRODUCAO';
UPDATE USUARIO_PARAMETRO SET USP_CUSTOPRODUCAO = 'N';

 ALTER TABLE servico ADD SRV_CUSTO NUMERIC (18,5);
 ALTER TABLE SERVICO ADD SRV_UND VARCHAR (6);
 ALTER TABLE servico ADD SRV_TIPO INTEGER;
 COMMENT ON COLUMN SERVICO.srv_tipo IS 'TIPO DE SERVICO : 1 - INTERNO ; 2 - EXTERNO';
 
 

CREATE TABLE SERVICOS_ORDEM (
    SRO_CODIGO  INTEGER NOT NULL,
    IOP_CODIGO  INTEGER,
    SRO_QUATDE  NUMERIC(18,5),
    SRV_CUSTO   NUMERIC(18,5),
    SRV_CODIGO  INTEGER
);

ALTER TABLE SERVICOS_ORDEM
ADD CONSTRAINT PK_SERVICOS_ORDEM
PRIMARY KEY (SRO_CODIGO);

COMMENT ON COLUMN SERVICOS_ORDEM.SRO_CODIGO IS 'CHAVE PRINCIPAL';
COMMENT ON COLUMN SERVICOS_ORDEM.IOP_CODIGO IS 'ITEM ORDEM DE PRODUCAO';
COMMENT ON COLUMN SERVICOS_ORDEM.SRO_QUATDE IS 'QUANTIDADE DE SERVICOS';
COMMENT ON COLUMN SERVICOS_ORDEM.SRV_CUSTO IS 'CUSTO DO SERVICO COMO HISTORICO';

CREATE SEQUENCE GEN_SERVICOS_ORDEM;

SET TERM ^ ;

create trigger servicos_ordem_bi for servicos_ordem
active before insert position 0
as
begin
  if (new.sro_codigo is null) then
    new.sro_codigo = gen_id(gen_servicos_ordem,1);
end^

SET TERM ; ^

COMMENT ON TABLE SERVICOS_ORDEM IS 'SERVICOS VINCULADOS A ORDEM DE PRODUCAO';

ALTER TABLE SERVICOS_ORDEM
ADD CONSTRAINT FK_SERVICOS_ORDEM_ITEM
FOREIGN KEY (IOP_CODIGO)
REFERENCES ITEM_ORDEMPRODUCAO(IOP_CODIGO);


ALTER TABLE APONTAMENTO_FAB ADD APF_CUSTOEQUIPAMENTO NUMERIC(18,5);
ALTER TABLE APONTAMENTO_FAB ADD APF_CUSTOMAO NUMERIC(18,5);
COMMENT ON COLUMN APONTAMENTO_FAB.APF_CUSTOEQUIPAMENTO IS 'CUSTO DO EQUIPAMENTO DO APONTAMENTO';
COMMENT ON COLUMN APONTAMENTO_FAB.APF_CUSTOMAO IS 'CUSTO DO MAO-DE-OBRA DO APONTAMENTO';


ALTER TABLE FABRICACAO ALTER OSV_CODIGO TYPE VARCHAR(20);

ALTER TABLE EQUIPAMENTO ADD EQP_CUSTOHORA NUMERIC (18,5);

