UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.580 patch 3',
    VERSAOSISTEMA.DATA   = '24.05.2023',
	VERSAO = '3.0.9.580'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE PED0000 ADD CLI_CONSFINAL VARCHAR(1);
COMMENT ON COLUMN PED0000.CLI_CONSFINAL IS 'É Consumidor Final? [S]im | [N]ão';
UPDATE PED0000 p SET p.CLI_CONSFINAL = (SELECT c.CLI_CONSFINAL FROM CLI0000 c WHERE c.CLI_CODIGO = p.CLI_CODIGO) WHERE p.CLI_CONSFINAL IS NULL; 
ALTER TABLE PED0000 ADD CLI_CONSU_PROPRIO VARCHAR(1);
COMMENT ON COLUMN PED0000.CLI_CONSU_PROPRIO IS '[S] Comsumo Próprio | [N] Revenda';
UPDATE PED0000 p SET p.CLI_CONSU_PROPRIO = (SELECT c.CLI_CONSU_PROPRIO FROM CLI0000 c WHERE c.CLI_CODIGO = p.CLI_CODIGO) WHERE p.CLI_CONSU_PROPRIO IS NULL; 
COMMIT WORK;

ALTER TABLE PRMT0001 ADD PMT_FAT_NF_VALOR_ORIGINAL VARCHAR(1) DEFAULT 'L';
COMMENT ON COLUMN PRMT0001.PMT_FAT_NF_VALOR_ORIGINAL IS 'Composição do Valor Original da Fatura na Nota Fiscal - [T] Valor Total dos Produtos | [L] Valor Líquido da Fatura  | [N] Valor Total da Nota';
UPDATE PRMT0001 SET PMT_FAT_NF_VALOR_ORIGINAL = 'L' WHERE PMT_FAT_NF_VALOR_ORIGINAL IS NULL;
ALTER TABLE PRMT0001 ADD PMT_FAT_NF_FRETE_SEGURO_DESP VARCHAR(1) DEFAULT 'S';
COMMENT ON COLUMN PRMT0001.PMT_FAT_NF_FRETE_SEGURO_DESP IS 'Inclui Frete, Seguro e Despesas no Valor Original da Fatura na Nota Fiscal - [S]im | [N]ão ';
UPDATE PRMT0001 SET PMT_FAT_NF_FRETE_SEGURO_DESP = 'S' WHERE PMT_FAT_NF_FRETE_SEGURO_DESP IS NULL;
ALTER TABLE PRMT0001 ADD PMT_FAT_NF_VALOR_LIQ_DESC VARCHAR(1) DEFAULT 'S';
COMMENT ON COLUMN PRMT0001.PMT_FAT_NF_VALOR_LIQ_DESC IS 'Inclui os Descontos (Pedido e Faturamento) no Valor Original da Fatura na Nota Fiscal - [S]im | [N]ão ';
UPDATE PRMT0001 SET PMT_FAT_NF_VALOR_LIQ_DESC = 'S' WHERE PMT_FAT_NF_VALOR_LIQ_DESC IS NULL;
ALTER TABLE PRMT0001 ADD PMT_FAT_NF_VALOR_ANTECIPADO VARCHAR(1) DEFAULT 'S';
COMMENT ON COLUMN PRMT0001.PMT_FAT_NF_VALOR_ANTECIPADO IS 'Diminui o Valor Antecipado do Valor Original da Fatura na Nota Fiscal - [S]im | [N]ão ';
UPDATE PRMT0001 SET PMT_FAT_NF_VALOR_ANTECIPADO = 'S' WHERE PMT_FAT_NF_VALOR_ANTECIPADO IS NULL;
ALTER TABLE PRMT0001 ADD PMT_FAT_NF_SEM_VALOR_COMERCIAL VARCHAR(1) DEFAULT 'S';
COMMENT ON COLUMN PRMT0001.PMT_FAT_NF_SEM_VALOR_COMERCIAL IS 'Diminui CFOP Sem Valor Comercial do Valor Original da Fatura na Nota Fiscal - [S]im | [N]ão ';
UPDATE PRMT0001 SET PMT_FAT_NF_SEM_VALOR_COMERCIAL = 'S' WHERE PMT_FAT_NF_SEM_VALOR_COMERCIAL IS NULL;
ALTER TABLE PRMT0001 ADD PMT_FAT_NF_VL_LIQ_VALOR_ANTECIP VARCHAR(1) DEFAULT 'S';
COMMENT ON COLUMN PRMT0001.PMT_FAT_NF_VL_LIQ_VALOR_ANTECIP IS 'Diminui o Valor Antecipado do Valor Liquido da Fatura na Nota Fiscal - [S]im | [N]ão ';
UPDATE PRMT0001 SET PMT_FAT_NF_VL_LIQ_VALOR_ANTECIP = 'S' WHERE PMT_FAT_NF_VL_LIQ_VALOR_ANTECIP IS NULL;

