UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.537 patch 6',
       VERSAOSISTEMA.DATA   = '24.10.2019',
	    VERSAO = '3.0.9.537'
 where VERSAOSISTEMA.CODIGO = 1;

COMMIT WORK;

ALTER TABLE CLI0000 ADD CLI_LATITUDE DECIMAL(10, 8) ;
ALTER TABLE CLI0000 ADD CLI_LONGITUDE DECIMAL(11, 8) ;

COMMENT ON COLUMN CLI0000.CLI_LATITUDE IS 'LATITUDE DA LOCALIZACAO DO CLIENTE';
COMMENT ON COLUMN CLI0000.CLI_LONGITUDE IS 'LONGITUDE DA LOCALIZACAO DO CLIENTE';

alter table ope0000 alter column OPE_DESCRINATUREZA type varchar(60) ;

UPDATE OPE0000
SET OPE_DESCRINATUREZA = OPE_DESCRI;

commit work;
