UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.576 patch 1',
    VERSAOSISTEMA.DATA   = '13.01.2023',
	VERSAO = '3.0.9.576'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE PRMT0001 ADD PMT_RETORNO_POR_CORES VARCHAR(1) DEFAULT 'N';
UPDATE PRMT0001 SET PMT_RETORNO_POR_CORES = 'N' WHERE PMT_RETORNO_POR_CORES IS NULL;
COMMENT ON COLUMN PRMT0001.PMT_RETORNO_POR_CORES is 'Retorno por Cores';
ALTER TABLE PED_IT01_INDUST ADD ACO_CODIGO INTEGER DEFAULT 0;
UPDATE PED_IT01_INDUST SET ACO_CODIGO = '0' WHERE ACO_CODIGO IS NULL;
COMMENT ON COLUMN PED_IT01_INDUST.ACO_CODIGO is 'Código da Cor';
commit work;

ALTER TABLE NFSERVICO ALTER NFSE_DATAEMISSAO TYPE TIMESTAMP;

ALTER TABLE BAN0000 ADD BAN_DIAS_PARA_BAIXA INTEGER DEFAULT 0;

ALTER TABLE PRMT0001 ADD PMT_ALTERA_QUANT_ITEM_PED VARCHAR(1) DEFAULT 'N';
UPDATE PRMT0001 SET PMT_ALTERA_QUANT_ITEM_PED = 'N' WHERE PMT_ALTERA_QUANT_ITEM_PED IS NULL;
COMMENT ON COLUMN PRMT0001.PMT_ALTERA_QUANT_ITEM_PED  is 'Permite alteração da quantidade do item do pedido já enviado para a produção';

ALTER TABLE PED_IT01 ADD ACO_CODIGO_TEMP INTEGER DEFAULT 0;
UPDATE PED_IT01 SET ACO_CODIGO_TEMP = ACO_CODIGO;
ALTER TABLE PED_IT01 DROP ACO_CODIGO;
ALTER TABLE PED_IT01 ADD ACO_CODIGO INTEGER DEFAULT 0;
UPDATE PED_IT01 SET ACO_CODIGO = ACO_CODIGO_TEMP;
UPDATE PED_IT01 SET ACO_CODIGO = 0 WHERE ACO_CODIGO IS NULL;
ALTER TABLE PED_IT01 DROP ACO_CODIGO_TEMP;
commit work;
