UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.545 patch 12',
    VERSAOSISTEMA.DATA   = '30.06.2020',
	VERSAO = '3.0.9.545'
 where VERSAOSISTEMA.CODIGO = 1;
 
ALTER TABLE MATERIAPRIMA_ORDEMPRODUCAO ADD MP_EXTRA VARCHAR(1);
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.MP_EXTRA IS 'ADICIONADO A MATERIA PRIMA';
ALTER TABLE MATERIAPRIMA_ORDEMPRODUCAO ADD MP_ALTERACAOCONSUMO NUMERIC (18,5);
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.MP_ALTERACAOCONSUMO IS 'DE QUANTO FOI AUMENTO O CONSUMO TOTAL';

ALTER TABLE MATERIAPRIMA_ORDEMPRODUCAO ALTER PED_CODIGO DROP NOT NULL;
ALTER TABLE ITEM_ORDEMPRODUCAO ALTER PRD_CODIGO SET NOT NULL;
ALTER TABLE ITEM_ORDEMPRODUCAO ADD IOP_STATUS_ENVASE VARCHAR(1);
ALTER TABLE ITEM_ORDEMPRODUCAO ADD ORE_CODIGO INTEGER;
ALTER TABLE ITEM_ORDEMPRODUCAO ADD ORE_DATAENVASE TIMESTAMP;

COMMENT ON COLUMN ITEM_ORDEMPRODUCAO.IOP_STATUS_ENVASE IS  'STATUS ENVASE P PENDENTE ; I - INICIADO ; F -FINALIZADO';
COMMENT ON COLUMN ITEM_ORDEMPRODUCAO.ORE_CODIGO IS 'CODIGO DO ENVASE';
COMMENT ON COLUMN ITEM_ORDEMPRODUCAO.ORE_DATAENVASE IS 'DATA DO ENVASE';

CREATE SEQUENCE GEN_ORDEM_ENVASE;
CREATE GENERATOR GEN_ENVASE_ORDEM;

CREATE TABLE ENVASE_ORDEM (
    ENO_CODIGO  INTEGER NOT NULL,
    COL_CODIGO  INTEGER,
    EQP_CODIGO  INTEGER,
    ENO_TIPO    INTEGER,
    IOP_CODIGO  INTEGER
);

ALTER TABLE ENVASE_ORDEM ADD CONSTRAINT PK_ENVASE_ORDEM PRIMARY KEY (ENO_CODIGO);

SET TERM ^ ;

/* Trigger: ENVASE_ORDEM_BI */
CREATE OR ALTER TRIGGER ENVASE_ORDEM_BI FOR ENVASE_ORDEM
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.eno_codigo is null) then
    new.eno_codigo = gen_id(gen_envase_ordem,1);
end
^


SET TERM ; ^

COMMENT ON COLUMN ENVASE_ORDEM.ENO_CODIGO IS 'CODIGO CHAVE';
COMMENT ON COLUMN ENVASE_ORDEM.COL_CODIGO IS 'CHAVE ESTRANGEIRA COLABORADOR';
COMMENT ON COLUMN ENVASE_ORDEM.EQP_CODIGO IS 'CHAVE ESTRANGEIRO EQUIPAMENTO';
COMMENT ON COLUMN ENVASE_ORDEM.ENO_TIPO IS '1 GRAVIMETRICO , 2 POR SENSOR DE NIVEL,3 POR VOLUME ,4 DO FLUXO DE MASSA';
COMMENT ON COLUMN ENVASE_ORDEM.IOP_CODIGO IS 'CODIGO DO ITEM DA ORDEM';

ALTER TABLE ENVASE_ORDEM
ADD CONSTRAINT FK_ENVASE_ORDEM_1
FOREIGN KEY (COL_CODIGO)
REFERENCES COLABORADOR(COL_CODIGO)
ON DELETE SET NULL
ON UPDATE SET NULL;

ALTER TABLE ENVASE_ORDEM
ADD CONSTRAINT FK_ENVASE_ORDEM_EQUIP
FOREIGN KEY (EQP_CODIGO)
REFERENCES EQUIPAMENTO(EQP_CODIGO)
ON DELETE SET NULL
ON UPDATE SET NULL;

ALTER TABLE ENVASE_ORDEM
ADD CONSTRAINT FK_ENVASE_ORDEM_ITEM
FOREIGN KEY (IOP_CODIGO)
REFERENCES ITEM_ORDEMPRODUCAO(IOP_CODIGO)
ON DELETE SET NULL
ON UPDATE SET NULL;

CREATE INDEX ITEM_ORDEMPRODUCAO_NORDEM_IDX ON ITEM_ORDEMPRODUCAO (IOP_NORDEM);
CREATE INDEX ORDEMPRODUCAO_PEDIDO_IDX1 ON ORDEMPRODUCAO (PED_CODIGO, EMP_CODIGO);

CREATE INDEX DEMANDA_PRODUCAO_PEDIDO ON DEMANDA_PRODUCAO (EMP_CODIGO,PED_CODIGO);
CREATE INDEX ORDEMPRODUCAO_IDX1 ON ORDEMPRODUCAO (OPR_STATUS);
CREATE INDEX DEMANDA_PRODUCAO_ITEM_IDX1 ON DEMANDA_PRODUCAO (PRF_REGISTRO);


ALTER TABLE PEDIDO_WEB ADD UUID_SOVIS VARCHAR(50);
ALTER TABLE PEDIDO_WEB ADD IDPEDIDOSOVIS INTEGER; 
ALTER TABLE PEDIDO_WEB ADD IDPEDIDOERP VARCHAR (1);

ALTER TABLE PEDIDO_WEB_ITEM ADD IDITEMPEDIDOSOVIS INTEGER;
ALTER TABLE PEDIDO_WEB_ITEM ADD QTDEFATURADA NUMERIC(18,5);
ALTER TABLE PEDIDO_WEB_ITEM ADD VALORUNITFAT NUMERIC(18,5);
ALTER TABLE PEDIDO_WEB_ITEM ADD VALORTOTFAT NUMERIC(18,5);                            