
UPDATE  VERSAOSISTEMA SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.0.495',
       VERSAOSISTEMA.DATA   = '04.10.2017'
 where VERSAOSISTEMA.CODIGO = 1;
 
COMMIT WORK;

update prd_grade
SET PRG_DESCRICAO = '0' || TRIM(PRG_DESCRICAO) 
WHERE TRIM(PRG_DESCRICAO)  IN ('1','2','3','4','5','6','7','8','9');


COMMIT WORK;



ALTER TABLE IBPT0000 ALTER  IBPT_DESCRICAO TYPE VARCHAR(250);

