UPDATE  VERSAOSISTEMA 
SET    VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.527',
       VERSAOSISTEMA.DATA   = '24.01.2018',
       VERSAO = '3.0.9.527'
where VERSAOSISTEMA.CODIGO = 1;


ALTER TABLE IPI0000 ADD IPI_REDVLLIQ varchar (1);
COMMENT ON COLUMN IPI0000.IPI_REDVLLIQ IS 'DESCONTO NO VALOR LIQUIDO DE PIS E COFINS';

UPDATE  IPI0000
SET IPI_REDVLLIQ = 'N';

ALTER TABLE FAT_PC01 ALTER COLUMN FPC_COBNUM TYPE VARCHAR(20);

ALTER TABLE NF0001 ADD NF_VL_DESCTO_FAT NUMERIC(18,5);
COMMENT ON COLUMN NF0001.NF_VL_DESCTO_FAT IS 'DESCONTO NO VALOR LIQUIDO DE PIS E COFINS';
COMMENT ON COLUMN NF0001.NF_VL_DESCTO IS 'DESCONTO NA NOTA';