UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.580 patch 2',
    VERSAOSISTEMA.DATA   = '11.05.2023',
	VERSAO = '3.0.9.580'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE PRMT0001 ADD PMT_HABILITA_ICMS_PEDIDO VARCHAR(1) DEFAULT 'N';
COMMENT ON COLUMN PRMT0001.PMT_HABILITA_ICMS_PEDIDO is 'Habilita a Coluna ICMS no Pedido | [S] Sim [N] Não';
UPDATE PRMT0001 SET PMT_HABILITA_ICMS_PEDIDO = 'N' WHERE PMT_HABILITA_ICMS_PEDIDO IS NULL;
COMMIT WORK;



