UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.585 patch 1',
    VERSAOSISTEMA.DATA   = '06.10.2023',
	VERSAO = '3.0.9.585'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE PRMT0001 ADD PMT_GER_AVANC_ANTECIP_DESC VARCHAR(1);
COMMENT ON COLUMN PRMT0001.PMT_GER_AVANC_ANTECIP_DESC IS 'Utiliza Gerenciamento Avançado de Antecipação/Desconto'; 

ALTER TABLE FAT_PC01 ADD FPC_ANTECIPACAO_CONCLUIDA VARCHAR(1);
ALTER TABLE FAT_PC01 ADD FPC_USU_CODIGO_ANTECIPACAO INTEGER;
ALTER TABLE FAT_PC01 ADD FPC_DATA_ANTECIPACAO TIMESTAMP;