UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.556 patch 1',
    VERSAOSISTEMA.DATA   = '12.05.2021',
	VERSAO = '3.0.9.556'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE CONTROLE_DE_QUALIDADE ADD CQUA_DATA_INICIALIZACAO TIMESTAMP;
ALTER TABLE CONTROLE_DE_QUALIDADE ADD CQUA_DATA_CONCLUSAO TIMESTAMP;
ALTER TABLE CONTROLE_DE_QUALIDADE ADD CQUA_OBSERVACAO VARCHAR(100);
ALTER TABLE CONTROLE_DE_QUALIDADE ADD CQUA_RESULTADO_TEMP VARCHAR(60);
UPDATE CONTROLE_DE_QUALIDADE SET CQUA_RESULTADO_TEMP = CQUA_RESULTADO;
ALTER TABLE CONTROLE_DE_QUALIDADE DROP CQUA_RESULTADO;
ALTER TABLE CONTROLE_DE_QUALIDADE ADD CQUA_RESULTADO VARCHAR(60);
UPDATE CONTROLE_DE_QUALIDADE SET CQUA_RESULTADO = CQUA_RESULTADO_TEMP;
ALTER TABLE CONTROLE_DE_QUALIDADE DROP CQUA_RESULTADO_TEMP;

CREATE SEQUENCE GEN_HIST_CONTROLE_DE_QUALIDADE;
ALTER SEQUENCE GEN_HIST_CONTROLE_DE_QUALIDADE RESTART WITH 1;
COMMENT ON SEQUENCE GEN_HIST_CONTROLE_DE_QUALIDADE IS 'Gerador de Códigos para o Histórico do Controle de Qualidade';

RECREATE TABLE HIST_CONTROLE_DE_QUALIDADE(
	HCQ_CODIGO INT PRIMARY KEY,
	PRDL_LOTE VARCHAR(30),
	IOP_NORDEM VARCHAR(20),
	HCQ_DESCRICAO VARCHAR (255),
	HCQ_DATA_HORA TIMESTAMP,
	USU_CODIGO INT);
