SET TERM ^ ;

CREATE OR ALTER PROCEDURE ATUALIZACAO_CUSTOS (
    EMP_CODIGO VARCHAR(3)
)
AS
DECLARE VARIABLE PRD_REFER        VARCHAR(30);
DECLARE VARIABLE ENTRADA         NUMERIC(18,5);
DECLARE VARIABLE LIQUIDA         NUMERIC(18,5);
DECLARE VARIABLE IPI             NUMERIC(18,5);
DECLARE VARIABLE SUBSTRI         NUMERIC(18,5);
DECLARE VARIABLE FRETE           NUMERIC(18,5);
DECLARE VARIABLE DESPEACES       NUMERIC(18,5);
DECLARE VARIABLE SEGURO          NUMERIC(18,5);
DECLARE VARIABLE CUSTOADCIONAL   NUMERIC(18,5);
DECLARE VARIABLE CUSTOCREDITO    NUMERIC(18,5);
DECLARE VARIABLE CUSTO           NUMERIC(18,5);
DECLARE VARIABLE QTDE            NUMERIC(18,4);
DECLARE VARIABLE PMT_CALCULARPV  INTEGER;
DECLARE VARIABLE PMT_NAO_AUTO_PVENDA VARCHAR(1);
DECLARE VARIABLE PRD_PCUSTO       NUMERIC(18,5);
DECLARE VARIABLE PRD_PMEDIO       NUMERIC(18,5);
DECLARE VARIABLE PRD_CUSTOCOMIPI  NUMERIC(18,5);
DECLARE VARIABLE COMP            VARCHAR(2);
DECLARE VARIABLE SQLTXT          VARCHAR(1000);
DECLARE VARIABLE SQLPV           VARCHAR(500);

BEGIN

  /* pega o modo de compartilhamento (COMP) */
  SELECT PRODUTOS FROM SHAREDB INTO :COMP;

  /* parametros de controle por empresa */
  SELECT PMT_CALCULARPV, PMT_NAO_AUTO_PVENDA
    FROM PRMT0001 p
   WHERE p.EMP_CODIGO = :EMP_CODIGO
   INTO :PMT_CALCULARPV, :PMT_NAO_AUTO_PVENDA;

  /* itera produtos que têm entradas de compra válidas */
  FOR
    SELECT PR.PRD_REFER
      FROM PRD0000 PR
     WHERE EXISTS (
         SELECT 1
           FROM ENF0001 EF
           INNER JOIN ENF_IT01 E1
              ON (EF.ENF_NOTANUMBER = E1.ENF_IT_NOTANUMBER AND EF.FOR_CODIGO = E1.FOR_CODIGO)
           INNER JOIN OPE0000 OP1
              ON (E1.ENF_CFOP = OP1.OPE_NATUREZA AND OP1.OPE_TIPO_OPERACAO = 'C')
          WHERE PR.PRD_REFER = E1.PRD_REFER
            AND PR.PRD_STATUS = 'A'
            AND EF.EMP_CODIGO = :EMP_CODIGO
     )
    INTO :PRD_REFER
  DO
  BEGIN
    /* busca o último custo de entrada para o produto */
    SELECT FIRST 1
           (E1.ENF_IT_VLPIS + E1.ENF_IT_VLCOFINS + E1.ENF_ICMS) AS CUSTOCREDITO,
           (E1.ENF_IT_VLIPI + E1.ENF_VLSUBST + E1.ENF_IT_VALFRETE
            + E1.ENF_IT_VLDESP_ACES + E1.ENF_IT_VLSEGURO) AS ENTRADA,
           E1.ENF_IT_VLIPI AS IPI,
           E1.ENF_VLSUBST AS SUBSTRI,
           E1.ENF_IT_VALFRETE AS FRETE,
           E1.ENF_IT_VLDESP_ACES AS DESPEACES,
           E1.ENF_IT_VLSEGURO AS SEGURO,
           CAST(E1.ENF_QTDE AS NUMERIC(18,4)) AS QTDE,
           CAST(E1.ENF_CUSTO AS NUMERIC(18,5)) AS CUSTO
      FROM ENF0001 EF
      INNER JOIN ENF_IT01 E1
        ON (EF.ENF_NOTANUMBER = E1.ENF_IT_NOTANUMBER AND EF.FOR_CODIGO = E1.FOR_CODIGO)
      INNER JOIN OPE0000 OP1
        ON (E1.ENF_CFOP = OP1.OPE_NATUREZA AND OP1.OPE_TIPO_OPERACAO = 'C')
     WHERE E1.PRD_REFER = :PRD_REFER
       AND E1.EMP_CODIGO = :EMP_CODIGO
       AND E1.ENF_QTDE > 0
     ORDER BY EF.ENF_ENTRADA DESC, EF.ENF_REGISTRO DESC
     INTO :CUSTOCREDITO, :ENTRADA, :IPI, :SUBSTRI, :FRETE, :DESPEACES, :SEGURO, :QTDE, :CUSTO;

    /* proteção contra NULLS / divisão por zero */
    IF (:QTDE IS NULL OR :QTDE <= 0) THEN
    BEGIN
      QTDE = 0;
      SEGURO = 0;
      DESPEACES = 0;
      FRETE = 0;
      SUBSTRI = 0;
      IPI = 0;
      ENTRADA = COALESCE(:CUSTO, 0);
      CUSTOCREDITO = COALESCE(:CUSTO, 0);
    END
    ELSE
    BEGIN
      /* garante não-nulos antes da divisão */
      IF (:SEGURO IS NULL) THEN SEGURO = 0;
      IF (:DESPEACES IS NULL) THEN DESPEACES = 0;
      IF (:FRETE IS NULL) THEN FRETE = 0;
      IF (:SUBSTRI IS NULL) THEN SUBSTRI = 0;
      IF (:IPI IS NULL) THEN IPI = 0;
      IF (:CUSTOCREDITO IS NULL) THEN CUSTOCREDITO = 0;
      IF (:ENTRADA IS NULL) THEN ENTRADA = 0;
      IF (:CUSTO IS NULL) THEN CUSTO = 0;

      SEGURO    = CAST((:SEGURO / :QTDE) AS NUMERIC(18,5));
      DESPEACES = CAST((:DESPEACES / :QTDE) AS NUMERIC(18,5));
      FRETE     = CAST((:FRETE / :QTDE) AS NUMERIC(18,5));
      SUBSTRI   = CAST((:SUBSTRI / :QTDE) AS NUMERIC(18,5));
      IPI       = CAST((:IPI / :QTDE) AS NUMERIC(18,5));
      ENTRADA   = CAST((:CUSTO + (:ENTRADA / :QTDE)) AS NUMERIC(18,5));
      CUSTOCREDITO = CAST((:CUSTO - (:CUSTOCREDITO / :QTDE)) AS NUMERIC(18,5));
    END

    /* custo líquido */
    IF (:CUSTO IS NOT NULL AND :CUSTO > 0) THEN
      LIQUIDA = CAST(:CUSTO AS NUMERIC(18,5));
    ELSE
      LIQUIDA = 0;

    /* soma em variável para concatenar com segurança */
    CUSTOADCIONAL = COALESCE(:DESPEACES,0) + COALESCE(:SEGURO,0);

    /* monta e executa UPDATE conforme COMP (Firebird 2.5: sem USING) */
    IF (:COMP = 'C') THEN
    BEGIN
      SQLTXT =
        'UPDATE PRD0000 SET ' ||
        ' PRD_PCUSTO = ' || CAST(:LIQUIDA AS VARCHAR(20)) ||
        ' , PRD_CUSTOCOMIPI = ' || CAST(:ENTRADA AS VARCHAR(20)) ||
        ' , PRD_CUSTOFRETE = ' || CAST(:FRETE AS VARCHAR(20)) ||
        ' , PRD_CUSTOIPI = ' || CAST(:IPI AS VARCHAR(20)) ||
        ' , PRD_CUSTOSUBTRIB = ' || CAST(:SUBSTRI AS VARCHAR(20)) ||
        ' , PRD_CUSTOADCIONAL = (' || CAST(:DESPEACES AS VARCHAR(20)) || ' + ' || CAST(:SEGURO AS VARCHAR(20)) || ')' ||
        ' , PRD_CUSTO_CREDITO = ' || CAST(:CUSTOCREDITO AS VARCHAR(20)) ||
        ' WHERE PRD_REFER = ''' || :PRD_REFER || '''';
      EXECUTE STATEMENT :SQLTXT;
    END
    ELSE
    BEGIN
      SQLTXT =
        'UPDATE PRD0000 SET ' ||
        ' PRD_PCUSTO = ' || CAST(:LIQUIDA AS VARCHAR(20)) ||
        ' , PRD_CUSTOCOMIPI = ' || CAST(:ENTRADA AS VARCHAR(20)) ||
        ' , PRD_CUSTOFRETE = ' || CAST(:FRETE AS VARCHAR(20)) ||
        ' , PRD_CUSTOIPI = ' || CAST(:IPI AS VARCHAR(20)) ||
        ' , PRD_CUSTOSUBTRIB = ' || CAST(:SUBSTRI AS VARCHAR(20)) ||
        ' , PRD_CUSTOADCIONAL = (' || CAST(:DESPEACES AS VARCHAR(20)) || ' + ' || CAST(:SEGURO AS VARCHAR(20)) || ')' ||
        ' , PRD_CUSTO_CREDITO = ' || CAST(:CUSTOCREDITO AS VARCHAR(20)) ||
        ' WHERE PRD_REFER = ''' || :PRD_REFER || '''' ||
        ' AND EMP_CODIGO = ''' || :EMP_CODIGO || '''';
      EXECUTE STATEMENT :SQLTXT;
    END

    /* Atualiza preço de venda somente se permitido */
    IF (:PMT_NAO_AUTO_PVENDA = 'N') THEN
    BEGIN
      /* busca os custos atuais do produto, respeitando COMP */
      IF (:COMP = 'C') THEN
      BEGIN
        SELECT FIRST 1 PRD_PCUSTO, PRD_CUSTOCOMIPI, PRD_PMEDIO
          FROM PRD0000
         WHERE PRD_REFER = :PRD_REFER
         INTO :PRD_PCUSTO, :PRD_CUSTOCOMIPI, :PRD_PMEDIO;
      END
      ELSE
      BEGIN
        SELECT PRD_PCUSTO, PRD_CUSTOCOMIPI, PRD_PMEDIO
          FROM PRD0000 p
         WHERE p.PRD_REFER = :PRD_REFER
           AND p.EMP_CODIGO = :EMP_CODIGO
         INTO :PRD_PCUSTO, :PRD_CUSTOCOMIPI, :PRD_PMEDIO;
      END

      /* define e executa o UPDATE do PRD_PVENDA conforme PMT_CALCULARPV */
      IF ((:PRD_PCUSTO > 0) AND (:PMT_CALCULARPV = 0)) THEN
      BEGIN
        SQLPV =
          'UPDATE PRD0000 SET PRD_PVENDA = ' || CAST(:PRD_PCUSTO AS VARCHAR(20)) ||
          ' * ((PRD_MARGEMVENDA/100) + 1) WHERE PRD_REFER = ''' || :PRD_REFER || '''';
        IF (:COMP = 'C') THEN
          EXECUTE STATEMENT :SQLPV;
        ELSE
          EXECUTE STATEMENT (:SQLPV || ' AND EMP_CODIGO = ''' || :EMP_CODIGO || '''');
      END
      ELSE IF ((:PRD_CUSTOCOMIPI > 0) AND (:PMT_CALCULARPV = 1)) THEN
      BEGIN
        SQLPV =
          'UPDATE PRD0000 SET PRD_PVENDA = ' || CAST(:PRD_CUSTOCOMIPI AS VARCHAR(20)) ||
          ' * ((PRD_MARGEMVENDA/100) + 1) WHERE PRD_REFER = ''' || :PRD_REFER || '''';
        IF (:COMP = 'C') THEN
          EXECUTE STATEMENT :SQLPV;
        ELSE
          EXECUTE STATEMENT (:SQLPV || ' AND EMP_CODIGO = ''' || :EMP_CODIGO || '''');
      END
      ELSE IF ((:PRD_PMEDIO > 0) AND (:PMT_CALCULARPV = 2)) THEN
      BEGIN
        SQLPV =
          'UPDATE PRD0000 SET PRD_PVENDA = ' || CAST(:PRD_PMEDIO AS VARCHAR(20)) ||
          ' * ((PRD_MARGEMVENDA/100) + 1) WHERE PRD_REFER = ''' || :PRD_REFER || '''';
        IF (:COMP = 'C') THEN
          EXECUTE STATEMENT :SQLPV;
        ELSE
          EXECUTE STATEMENT (:SQLPV || ' AND EMP_CODIGO = ''' || :EMP_CODIGO || '''');
      END
      /* senão não altera PV */
    END

  END /* FOR PRD_REFER */

END
^

SET TERM ; ^
