UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.544 patch 1',
    VERSAOSISTEMA.DATA   = '08.05.2020',
	VERSAO = '3.0.9.544'
 where VERSAOSISTEMA.CODIGO = 1;

commit work;

ALTER TABLE CLI_CONTATO
ADD CC_TIPO CHAR(1);

