UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.562 patch 5',
    VERSAOSISTEMA.DATA   = '29.11.2021',
	VERSAO = '3.0.9.562'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE ITEM_ORDEMPRODUCAO ADD IOP_TEMCARGA CHAR(1);
UPDATE ITEM_ORDEMPRODUCAO a set a.IOP_TEMCARGA = 'S' WHERE a.IOP_CODIGO IN (SELECT b.IOP_CODIGO FROM PROCESSOS_PRODUCAO b WHERE b.CAR_CODIGO  IS NOT NULL) ;
UPDATE ITEM_ORDEMPRODUCAO a set a.IOP_TEMCARGA = 'N' WHERE a.IOP_TEMCARGA IS NULL;
commit work;
