update RDB$RELATION_FIELDS set
RDB$NULL_FLAG = 1
where (RDB$FIELD_NAME = 'CODIGO') and
(RDB$RELATION_NAME = 'CONTA_CORRENTE');

COMMIT WORK;

ALTER TABLE CONTA_CORRENTE
ADD CONSTRAINT PK_CONTA_CORRENTE
PRIMARY KEY (CODIGO); 
 
COMMIT WORK;
 
CREATE SEQUENCE GEN_CONTA_CORRENTE_CODIGO;

COMMIT WORK;

 ALTER TABLE PRMT0001
    ADD PMT_PAGAR_COMISSAO_VERBA CHAR(1);
	
COMMIT WORK;

ALTER TABLE OPV0000
    ADD OPV_COMISSAO_VERBA CHAR(1);

COMMIT WORK;
	
ALTER TABLE PRMT0001
    ADD PMT_COMIS_SIMPLES CHAR(1);
	
COMMIT WORK;

ALTER TABLE PRD0000
    ADD PRD_PERC_COMISSAO DECIMAL6,
    ADD PRD_PERC_VENDA DECIMAL6,
    ADD PRD_PERC_COMISSAO2 DECIMAL6,
    ADD PRD_PERC_VENDA2 DECIMAL6,	
    ADD PRD_PERC_COMISSAO3 DECIMAL6,
    ADD PRD_PERC_VENDA3 DECIMAL6,
    ADD PRD_PERC_COMISSAO4 DECIMAL6,
    ADD PRD_PERC_VENDA4 DECIMAL6,
    ADD PRD_PERC_COMISSAO5 DECIMAL6,
    ADD PRD_PERC_VENDA5 DECIMAL6,
    ADD PRD_PERC_COMISSAO6 DECIMAL6,
    ADD PRD_PERC_VENDA6 DECIMAL6;

COMMIT WORK;

ALTER TABLE PRMT0001
    ADD PMT_PERC_COMISSAO1 DECIMAL6,
    ADD PMT_PERC_VENDA1 DECIMAL6,
    ADD PMT_PERC_COMISSAO2 DECIMAL6,
    ADD PMT_PERC_VENDA2 DECIMAL6,	
    ADD PMT_PERC_COMISSAO3 DECIMAL6,
    ADD PMT_PERC_VENDA3 DECIMAL6,
    ADD PMT_PERC_COMISSAO4 DECIMAL6,
    ADD PMT_PERC_VENDA4 DECIMAL6,
    ADD PMT_PERC_COMISSAO5 DECIMAL6,
    ADD PMT_PERC_VENDA5 DECIMAL6,
    ADD PMT_PERC_COMISSAO6 DECIMAL6,
    ADD PMT_PERC_VENDA6 DECIMAL6;	

COMMIT WORK;

ALTER TABLE PED_IT01
    ADD USOU_VERBA CHAR(1);
	
COMMIT WORK;

ALTER TABLE PED_IT01
    ADD VALOR_VERBA DECIMAL6;
	
COMMIT WORK;

ALTER TABLE CONTA_CORRENTE
    ALTER DESCRICAO TYPE VARCHAR(100) CHARACTER SET NONE;
	
COMMIT WORK;	

UPDATE  VERSAOSISTEMA SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.0.480',
       VERSAOSISTEMA.DATA   = '23.03.2017'
 where VERSAOSISTEMA.CODIGO = 1;
 
COMMIT WORK;

 