UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.570 patch 2',
    VERSAOSISTEMA.DATA   = '20.07.2022',
	VERSAO = '3.0.9.570'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE USUARIO_PARAMETRO ADD USP_EXIBE_ABA_INFO_CLIENTE CHAR(1);
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_EXIBE_ABA_INFO_CLIENTE  IS 'Exibe/Oculta a aba de informações do cliente no pedido';
UPDATE USUARIO_PARAMETRO SET USP_EXIBE_ABA_INFO_CLIENTE = 'S';
commit work;


