UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.561 patch 1',
    VERSAOSISTEMA.DATA   = '13.10.2021',
	VERSAO = '3.0.9.561'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;


CREATE OR ALTER VIEW VW_SPED_NOTAS_FISCAIS_ITENS (DESP_ACESSORIA, FRETE, SEGURO, REGISTRO_NOTA, CODIGO_ITEM, DESCRICAO_ITEM, QUANTIDADE, UNIDADE, VALOR_ITEM, VALOR_DESCONTO, INDICADOR_MOVIMENTACAO, CST_ICMS, CFOP, CODIGO_CFOP, OPE_CODIGO, VALOR_BASE_ICMS, ALIQUOTA_ICMS, VALOR_ICMS, VALOR_BASE_ICMS_ST, ALIQUOTA_ICMS_ST, VALOR_ICMS_ST, INDICADOR_APURACAO_IPI, CST_IPI, CODIGO_ENQUAD_IPI, VALOR_BASE_IPI, ALIQUOTA_IPI, VALOR_IPI, CST_PIS, VALOR_BASE_PIS, ALIQ_PIS, QUANTIDADE_BASE_PIS, ALIQ_PIS_REAIS, VALOR_PIS, CST_COFINS, VALOR_BASE_COFINS, ALIQUOTA_COFINS, QUANTIDADE_BASE_COFINS, ALIQ_COFINS_REAIS, VALOR_COFINS, FOR_CODIGO)
AS
SELECT
T1.ENF_IT_VLDESP_ACES,
T1.ENF_IT_VALFRETE,
T1.ENF_IT_VLSEGURO,
CAST('E'||T1.ENF_IT_NOTANUMBER AS VARCHAR(30)),
T1.PRD_CODIGO,
CAST(T1.PRD_DESCRI AS VARCHAR(500)),
coalesce(t1.ENF_QTDE_ORIGINAL, T1.ENF_QTDE),
COALESCE(T1.ENF_UCOM,
	(SELECT FIRST 1 
		CASE PRD_PRODSERV    
			WHEN 'S' THEN COALESCE(T3.PRD_UND,'UN') 
			WHEN NULL THEN 'UN'
			WHEN '' THEN 'UN'
			ELSE T3.PRD_UND 
		END AS UNIDADE_MEDIDA  
	FROM PRD0000 T3 WHERE T3.PRD_REFER = T1.PRD_REFER)
	),
COALESCE(T1.ENF_PRECO_ORIGINAL,T1.ENF_PRECO),
T1.ENF_IT_DESCTO,
CAST((CASE WHEN (1=1) THEN
    'S'
END) AS VARCHAR(1)),
COALESCE(t1.STB_TRIBUTACAO,'00'),
t1.ENF_CFOP,
t1.ENF_CFOP,
T1.OPE_CODIGO AS OPE_CODIGO,
t1.ENF_IT_BASEICMS,
t1.ENF_ICMSALIQ,
t1.ENF_ICMS,
t1.ENF_IT_BASESUBTRIB AS VALOR_BASE_ICMS_ST,
t1.ENF_IT_ALIQSUBTRIB AS ALIQUOTA_ICMS_ST,
CAST(ENF_IT_VLSUBTRIB AS NUMERIC(18,2)) as VALOR_ICMS_ST,
CAST((CASE WHEN (1=1) THEN
    0
END) AS INTEGER),
t1.CST_IPI,
CAST(CASE WHEN (1=1) THEN
    'XXX'
END as varchar(3)),
COALESCE(T1.ENF_IT_BASEIPI,0) AS VALOR_BASE_IPI,
COALESCE(T1.ENF_IPIALIQ,0) AS ALIQUOTA_IPI,
COALESCE(T1.ENF_IT_VLIPI,0) AS VALOR_IPI ,
t1.CST_PIS,
COALESCE(T1.ENF_BASEPIS,0),
COALESCE(T1.ENF_IT_ALIQPIS,0),
CASE WHEN (1=1) THEN
    0.00
END,
CASE WHEN (1=1) THEN
    0.00
END,
COALESCE(T1.ENF_IT_VLPIS,0),
t1.CST_COFINS,
COALESCE(T1.ENF_BASECOFINS,0),
COALESCE(T1.ENF_IT_ALIQCOFINS,0),
CASE WHEN (1=1) THEN
    0.00
END,
CASE WHEN (1=1) THEN
    0.00
END,
COALESCE(T1.ENF_IT_VLCOFINS,0),
T1.FOR_CODIGO
FROM
ENF_IT01 T1
UNION ALL 
SELECT
T2.NF_IDESP_ACES,
T2.NF_IFRETE,
T2.NF_ISEGURO,
CAST('S'||T2.NF_IT_NOTANUMER AS VARCHAR(30)),
(SELECT FIRST 1 T3.PRD_CODIGO FROM PRD0000 T3 WHERE T3.PRD_REFER = T2.PRD_REFER),
T2.PRD_DESCRI,
T2.NF_QTDE,
(SELECT FIRST 1 T3.PRD_UND FROM PRD0000 T3 WHERE T3.PRD_REFER = T2.PRD_REFER),
T2.NF_PRECO,
T2.NF_IDESCTO1,
CAST((CASE WHEN (1=1) THEN
    'S'
END) AS VARCHAR(1)),
COALESCE((SELECT FIRST 1 cast(T3.PRD_ORIGEM as varchar(1)) FROM PRD0000 T3 WHERE T3.PRD_REFER = T2.PRD_REFER),'00')||t2.STB_TRIBUTACAO,
cast(t2.NTP_CFOP as varchar(4)),
cast(t2.NTP_CFOP as varchar(4)),
OPE_CODIGO,
t2.NF_ICMSBASE,
t2.NF_ICMSALIQ,
t2.NF_ICMSVALOR,
t2.NF_SUBTRIBASE,
t2.NF_ALIQSUBTRIB,
CAST(t2.NF_VLSUBST AS NUMERIC(18,2)) as VALOR_ICMS_ST,
CAST((CASE WHEN (1=1) THEN  0 END) AS INTEGER),
CST_IPI, 
CAST(CASE WHEN (1=1) THEN  'XXX' END as varchar(3)),
COALESCE(T2.NF_IPIBASE,0) AS VALOR_BASE_IPI,
COALESCE(T2.NF_IPIALIQ,0) AS ALIQUOTA_IPI,
COALESCE(T2.NF_IPIVALOR,0) AS VALOR_IPI,
CAST(CASE WHEN (T2.NF_BASE_PIS > 0) THEN
    coalesce(CST_PIS,'01')
    ELSE
    '99'
END as varchar(3)),
COALESCE(T2.NF_BASE_PIS,0),
COALESCE(T2.NF_ALIQPIS,0),
CASE WHEN (1=1) THEN
    0.00
END,
CASE WHEN (1=1) THEN
    0.00
END,
COALESCE(T2.NF_VLPIS,0),
cast(CASE WHEN (T2.NF_BASE_COFINS > 0) THEN
    coalesce(CST_COFINS, '01')
    ELSE
    '99'
END as varchar(3)),
COALESCE(T2.NF_BASE_COFINS,0),
COALESCE(T2.NF_ALIQCOFINS,0),
CASE WHEN (1=1) THEN
    0.00
END,
CASE WHEN (1=1) THEN
    0.00
END,
COALESCE(T2.NF_VLCOFINS,0),
NULL
FROM
NF_IT01 T2
WHERE
  EXISTS (SELECT 1 FROM PRD0000 T3 WHERE T3.PRD_REFER = T2.PRD_REFER)
  AND PRD_REFER IS NOT NULL;

CREATE INDEX PEDIDO_WEB_ITEM_IDX1 ON PEDIDO_WEB_ITEM (PW_REGISTRO);
CREATE INDEX PEDIDO_WEB_ITEM_IDX2 ON PEDIDO_WEB_ITEM (PWI_REFERENCIA);
CREATE INDEX PEDIDO_WEB_IDX3 ON PEDIDO_WEB (PEDIDO_ID_EXTERNO);
CREATE INDEX PEDIDO_WEB_IDX2 ON PEDIDO_WEB (CLI_CODIGO);
CREATE INDEX PEDIDO_WEB_IDX1 ON PEDIDO_WEB (EMP_CODIGO);

ALTER TABLE OPE0000 ADD OPE_REF_NFE_IND CHAR(1);
COMMENT ON COLUMN OPE0000.OPE_REF_NFE_IND IS 'Referencia NFe de Industrialização'; 

CREATE TABLE REF_NFE_IND(
	ENF_NOTANUMBER VARCHAR(10),
	NF_NOTANUMBER VARCHAR(6)	
);
COMMENT ON COLUMN REF_NFE_IND.ENF_NOTANUMBER IS 'Referencia NF de entrada de Industrialização'; 
COMMENT ON COLUMN REF_NFE_IND.NF_NOTANUMBER IS 'Referencia NFe de saída Industrialização'; 


ALTER TABLE PRMT0001 ADD PMT_PRD_REFER_SCO_REFER VARCHAR(20);
COMMENT ON COLUMN PRMT0001.PMT_PRD_REFER_SCO_REFER is 'Referência genérica de Produto para a Solicitação de Compra';
UPDATE PRMT0001 set PMT_PRD_REFER_SCO_REFER = '999999' WHERE PMT_PRD_REFER_SCO_REFER IS NULL;

ALTER TABLE USUARIO_PARAMETRO ADD USP_AUTORIZA_COTACAO_MATERIAL CHAR(1);
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_AUTORIZA_COTACAO_MATERIAL is 'Responsável pela autorização da cotação dos materiais';
UPDATE USUARIO_PARAMETRO SET USP_AUTORIZA_COTACAO_MATERIAL = 'N';
COMMIT WORK;
ALTER TABLE USUARIO_PARAMETRO ADD USP_AUTORIZA_COMPRA_MATERIAL CHAR(1);
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_AUTORIZA_COMPRA_MATERIAL is 'Responsável pela compra dos materiais';
UPDATE USUARIO_PARAMETRO SET USP_AUTORIZA_COMPRA_MATERIAL = 'N';
COMMIT WORK;

ALTER TABLE USUARIO_PARAMETRO ADD USP_REALIZA_COTACAO_MATERIAL CHAR(1);
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_REALIZA_COTACAO_MATERIAL is 'Responsável pela cotacao dos materiais';
UPDATE USUARIO_PARAMETRO SET USP_REALIZA_COTACAO_MATERIAL = 'N';
COMMIT WORK;


CREATE SEQUENCE GEN_SOLICITACAO_COMPRA;
ALTER SEQUENCE GEN_SOLICITACAO_COMPRA RESTART WITH 100;
COMMENT ON SEQUENCE GEN_SOLICITACAO_COMPRA IS 'Gerador de Códigos para as Solicitações de Compra';
CREATE TABLE SOLICITACAO_COMPRA (
	SCO_CODIGO INT PRIMARY KEY
);
COMMENT ON COLUMN SOLICITACAO_COMPRA.SCO_CODIGO is 'Chave Primária da Solicitação de Compra';
ALTER TABLE SOLICITACAO_COMPRA ADD SET_CODIGO INT;
COMMENT ON COLUMN SOLICITACAO_COMPRA.SET_CODIGO is 'Código do Setor';
ALTER TABLE SOLICITACAO_COMPRA ADD SCO_OBSERVACAO VARCHAR(70);
COMMENT ON COLUMN SOLICITACAO_COMPRA.SCO_OBSERVACAO is 'Observações da Solicitação de Compra';
ALTER TABLE SOLICITACAO_COMPRA ADD SCO_DATA_SOLICITACAO DATE;
COMMENT ON COLUMN SOLICITACAO_COMPRA.SCO_DATA_SOLICITACAO is 'Data da Solicitação de Compra';
ALTER TABLE SOLICITACAO_COMPRA ADD SCO_SOLICITANTE VARCHAR(30);
COMMENT ON COLUMN SOLICITACAO_COMPRA.SCO_SOLICITANTE is 'Nome da pessoa que fez a Solicitação de Compra';
ALTER TABLE SOLICITACAO_COMPRA ADD PRD_REFER VARCHAR(20);
COMMENT ON COLUMN SOLICITACAO_COMPRA.PRD_REFER is 'Referência do Produto';
ALTER TABLE SOLICITACAO_COMPRA ADD SCO_DESCRICAO_PRODUTO VARCHAR(100);
COMMENT ON COLUMN SOLICITACAO_COMPRA.SCO_DESCRICAO_PRODUTO is 'Descrição do Produto';
ALTER TABLE SOLICITACAO_COMPRA ADD UND_SIGLA VARCHAR(3);
COMMENT ON COLUMN SOLICITACAO_COMPRA.UND_SIGLA is 'Sigla (chave primária) da Unidade de Medida do Produto';
ALTER TABLE SOLICITACAO_COMPRA ADD SCO_QTDE_MIN NUMERIC(18,5);
COMMENT ON COLUMN SOLICITACAO_COMPRA.SCO_QTDE_MIN is 'Quantidade Mínima do Produto';
ALTER TABLE SOLICITACAO_COMPRA ADD SCO_QTDE_MAX NUMERIC(18,5);
COMMENT ON COLUMN SOLICITACAO_COMPRA.SCO_QTDE_MAX is 'Quantidade Máxima do Produto';
ALTER TABLE SOLICITACAO_COMPRA ADD SCO_STATUS_SOLICITACAO INT;
COMMENT ON COLUMN SOLICITACAO_COMPRA.SCO_STATUS_SOLICITACAO  is 'Status da Solicitação: 0: Não Definido / 1: Aberta / 2: Rejeitada / 3: Autorização de Cotação / 4: Cotação Finalizada / 5: Autorização de Compra / 6: Concluída / 7: Cancelada';
ALTER TABLE SOLICITACAO_COMPRA ADD SCO_STAT_SOLICIT_RESP VARCHAR(40);
COMMENT ON COLUMN SOLICITACAO_COMPRA.SCO_STAT_SOLICIT_RESP is 'Responsável pela Troca de Estado do Status da Solicitação';
ALTER TABLE SOLICITACAO_COMPRA ADD SCO_DATA_ENTREGA DATE;
COMMENT ON COLUMN SOLICITACAO_COMPRA.SCO_DATA_ENTREGA  is 'Data da entrega desejada';
ALTER TABLE SOLICITACAO_COMPRA ADD SCO_DATA_AUTORIZACAO_COTACAO DATE;
COMMENT ON COLUMN SOLICITACAO_COMPRA.SCO_DATA_AUTORIZACAO_COTACAO  is 'Data da Autorização da Cotação';
ALTER TABLE SOLICITACAO_COMPRA ADD SCO_OBSERVACAO_APROVACAO VARCHAR(100);
COMMENT ON COLUMN SOLICITACAO_COMPRA.SCO_OBSERVACAO_APROVACAO is 'Observação da Aprovação da Cotação';
ALTER TABLE SOLICITACAO_COMPRA ADD SCO_NRO_PEDIDO_VENDA VARCHAR(30);
COMMENT ON COLUMN SOLICITACAO_COMPRA.SCO_NRO_PEDIDO_VENDA  is 'Número do Pedido de Venda';

CREATE SEQUENCE GEN_SOLICITACAO_ITEM;
ALTER SEQUENCE GEN_SOLICITACAO_ITEM RESTART WITH 100;
COMMENT ON SEQUENCE GEN_SOLICITACAO_ITEM IS 'Gerador de Códigos para os Itens das Solicitações de Compra';
CREATE TABLE SOLICITACAO_ITEM (
	SIT_CODIGO INT PRIMARY KEY
);
COMMENT ON COLUMN SOLICITACAO_ITEM.SIT_CODIGO is 'Chave Primária do Item da Solicitação de Compra';
ALTER TABLE SOLICITACAO_ITEM ADD SCO_CODIGO INT;
COMMENT ON COLUMN SOLICITACAO_ITEM.SCO_CODIGO is 'Código da Solicitação de Compra';


ALTER TABLE SOLICITACAO_ITEM ADD FOR_CODIGO VARCHAR(4);
COMMENT ON COLUMN SOLICITACAO_ITEM.FOR_CODIGO is 'Código do Fornecedor do Produto';
ALTER TABLE SOLICITACAO_ITEM ADD FOR_RAZAO VARCHAR(70);
COMMENT ON COLUMN SOLICITACAO_ITEM.FOR_RAZAO is 'Razão Social do Fornecedor';
ALTER TABLE SOLICITACAO_ITEM ADD FOR_FONE VARCHAR(11);
COMMENT ON COLUMN SOLICITACAO_ITEM.FOR_FONE is 'Telefone do Fornecedor';
ALTER TABLE SOLICITACAO_ITEM ADD FOR_EMAIL VARCHAR(70);
COMMENT ON COLUMN SOLICITACAO_ITEM.FOR_EMAIL is 'e-mail do Fornecedor';
ALTER TABLE SOLICITACAO_ITEM ADD FOR_CGC VARCHAR(70);
COMMENT ON COLUMN SOLICITACAO_ITEM.FOR_CGC is 'CNPJ do Fornecedor';
ALTER TABLE SOLICITACAO_ITEM ADD SIT_COTACAO_APROVADA CHAR(1);
COMMENT ON COLUMN SOLICITACAO_ITEM.SIT_COTACAO_APROVADA is 'Cotação aprovada? Valores Válidos: S/N';
ALTER TABLE SOLICITACAO_ITEM ADD SIT_PEDIDO_COMPRA CHAR(1);
COMMENT ON COLUMN SOLICITACAO_ITEM.SIT_PEDIDO_COMPRA is 'Pedido de compra aprovado? Valores Válidos: S/N';
ALTER TABLE SOLICITACAO_ITEM ADD SIT_DATA_COTACAO DATE;
COMMENT ON COLUMN SOLICITACAO_ITEM.SIT_DATA_COTACAO  is 'Data da cotação';
ALTER TABLE SOLICITACAO_ITEM ADD SIT_PRECO_COTACAO NUMERIC(18,5);
COMMENT ON COLUMN SOLICITACAO_ITEM.SIT_PRECO_COTACAO is 'Preço do produto na cotação';
ALTER TABLE SOLICITACAO_ITEM ADD SIT_PRAZO_ENTREGA DATE;
COMMENT ON COLUMN SOLICITACAO_ITEM.SIT_PRAZO_ENTREGA is 'Prazao de entrega do produto cotado';
ALTER TABLE SOLICITACAO_ITEM ADD SIT_TIPO_FRETE VARCHAR(3);
COMMENT ON COLUMN SOLICITACAO_ITEM.SIT_TIPO_FRETE is 'Tipo do Frete (CIF-Pago / FOB-A pagar)';
ALTER TABLE SOLICITACAO_ITEM ADD SIT_NRO_PEDIDO_COMPRA VARCHAR(30);
COMMENT ON COLUMN SOLICITACAO_ITEM.SIT_NRO_PEDIDO_COMPRA  is 'Número do Pedido de Compra';
ALTER TABLE SOLICITACAO_ITEM ADD SIT_PRAZO_PAGAMENTO VARCHAR(30);
COMMENT ON COLUMN SOLICITACAO_ITEM.SIT_PRAZO_PAGAMENTO  is 'Prazo de pagamento em número de dias';
ALTER TABLE SOLICITACAO_ITEM ADD SIT_DATA_FINALIZACAO_COTACAO DATE;
COMMENT ON COLUMN SOLICITACAO_ITEM.SIT_DATA_FINALIZACAO_COTACAO  is 'Data da Finalização da Cotação';
ALTER TABLE SOLICITACAO_ITEM ADD SIT_DATA_AUTORIZACAO_COMPRA DATE;
COMMENT ON COLUMN SOLICITACAO_ITEM.SIT_DATA_AUTORIZACAO_COMPRA  is 'Data da Autorização da Compra';
ALTER TABLE SOLICITACAO_ITEM ADD SIT_CONCLUIDA VARCHAR(100);
COMMENT ON COLUMN SOLICITACAO_ITEM.SIT_CONCLUIDA is 'Cotação Concluída - Nº das OCs correspondentes';
ALTER TABLE SOLICITACAO_ITEM ADD SIT_STATUS_COMPRA INT;
COMMENT ON COLUMN SOLICITACAO_ITEM.SIT_STATUS_COMPRA  is 'Status da Compra: 0: Não definido / 1: Em Análise / 2: Em Aprovação / 3: Transmitir / 4: Em Acompanhamento / 5: Concluída / 6: Cancelada / 7: Revisar';
ALTER TABLE SOLICITACAO_ITEM ADD SIT_STATUS_COMPRA_OBS VARCHAR(100);
COMMENT ON COLUMN SOLICITACAO_ITEM.SIT_STATUS_COMPRA_OBS is 'Observação do Status da Compra Revisada (7)';
ALTER TABLE SOLICITACAO_ITEM ADD SIT_STAT_COMPRA_RESP VARCHAR(40);
COMMENT ON COLUMN SOLICITACAO_ITEM.SIT_STAT_COMPRA_RESP is 'Responsável pela Troca de Estado do Status da Compra';

CREATE SEQUENCE GEN_SOLICITACAO_ITEM_LOG;
ALTER SEQUENCE GEN_SOLICITACAO_ITEM_LOG RESTART WITH 1;
COMMENT ON SEQUENCE GEN_SOLICITACAO_ITEM_LOG IS 'Gerador de Códigos para o Log das Movimentações dos Itens Solicitados';
CREATE TABLE SOLICITACAO_ITEM_LOG (
	SIL_CODIGO INT PRIMARY KEY
);
COMMENT ON COLUMN SOLICITACAO_ITEM_LOG.SIL_CODIGO is 'Chave Primária do Log das Movimentações dos Itens Solicitados';
ALTER TABLE SOLICITACAO_ITEM_LOG ADD SIT_CODIGO INT;
COMMENT ON COLUMN SOLICITACAO_ITEM_LOG.SIT_CODIGO  is 'Código do Item da Silicitação';
ALTER TABLE SOLICITACAO_ITEM_LOG ADD SIT_STATUS_COMPRA INT;
COMMENT ON COLUMN SOLICITACAO_ITEM_LOG.SIT_STATUS_COMPRA  is 'Status da Compra: 0: Não definido / 1: Em Análise / 2: Em Aprovação / 3: Transmitir / 4: Em Acompanhamento / 5: Concluída / 6: Cancelada / 7: Revisar';
ALTER TABLE SOLICITACAO_ITEM_LOG ADD SIT_STATUS_SOLICITACAO INT;
COMMENT ON COLUMN SOLICITACAO_ITEM_LOG.SIT_STATUS_SOLICITACAO  is 'Status da Solicitação: 0: Não Definido / 1: Aberta / 2: Rejeitada / 3: Autorização de Cotação / 4: Cotação Finalizada / 5: Autorização de Compra / 6: Concluída / 7: Cancelada';
ALTER TABLE SOLICITACAO_ITEM_LOG ADD USU_NOME VARCHAR(40);
COMMENT ON COLUMN SOLICITACAO_ITEM_LOG.USU_NOME  is 'Usuário que fez a interação com o sistema';
ALTER TABLE SOLICITACAO_ITEM_LOG ADD SIL_DATA DATE;
COMMENT ON COLUMN SOLICITACAO_ITEM_LOG.SIL_DATA  is 'Data da Alteração';

ALTER TABLE PRMT0001 ADD PMT_MULTIPLAS_IE CHAR(1);
CREATE TABLE EMP_MULTIPLAS_IE (
	EMI_CODIGO INTEGER PRIMARY KEY,
	EMP_CODIGO VARCHAR(3),
	EMI_DESCRICAO VARCHAR(255),
	EMI_IE VARCHAR(20),
	EMI_SERIE_NF VARCHAR(20),
	EMI_SEQUENCIA_NF INTEGER
);
CREATE TABLE PEDIDO_IE (
	PED_CODIGO VARCHAR(7) PRIMARY KEY,
	EMI_IE VARCHAR(20)
);

