UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.540 patch 3',
       VERSAOSISTEMA.DATA   = '10.01.2020',
	    VERSAO = '3.0.9.540'
 where VERSAOSISTEMA.CODIGO = 1;

commit work;
 
ALTER TABLE NFSE_FATPC ADD EMP_CODIGO VARCHAR(3);
COMMENT ON COLUMN NFSE_FATPC.EMP_CODIGO IS 'CODIGO DE REFERENCIA DA EMPRESA';

UPDATE NFSE_FATPC S
SET EMP_CODIGO = (SELECT FIRST 1 EMP_CODIGO FROM FAT0000 FT WHERE FT.FAT_CODIGO = S.FAT_CODIGO);


commit work;


DELETE FROM NFSE_FATPC ft
WHERE NOT EXISTS (SELECT * FROM NFSERVICO se WHERE se.NFSE_CODIGO = ft.NFSE_CODIGO);

commit work;

DELETE FROM NFSE_FATPC ft
WHERE NOT EXISTS (SELECT * FROM FAT0000 fat WHERE fat.fat_codigo = ft.FAT_CODIGO);

commit work;