UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.610',
    VERSAOSISTEMA.DATA   = '09.01.2026',
	VERSAO = '3.0.9.610'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

/* ISSUE 2133 */
ALTER TABLE OPE0000 ADD OPE_MOSTRA_IBS_CBS CHAR(1);
COMMENT ON COLUMN OPE0000.OPE_MOSTRA_IBS_CBS is 'Insere as tags de IBS/CBS NO XML/DANFE da Nota Fiscal';

/* ISSUE 2137 */
ALTER TABLE PRMT0001 ADD PMT_SOMA_IBS_UF_BASE_CALCULO CHAR(1);
COMMENT ON COLUMN PRMT0001.PMT_SOMA_IBS_UF_BASE_CALCULO is 'Soma o IBS Estadual na Base de Cálculo <vBCIBSCBS>';


