DROP VIEW VW_SPED_INVENTARIO;
DROP VIEW VW_SPED_NOTAS_FISCAIS_ITENS;
DROP VIEW VW_SPED_PRODUTOS_SERVICOS;
DROP VIEW VW_SPED_REGISTRO_ANALITICO;
DROP VIEW VW_SPED_UNIDADE_MEDIDA;

commit work;

CREATE INDEX PRD0000_CODIGO_IDX1
ON PRD0000_CODIGO (PRD_CODIGO);



commit work;

CREATE TABLE PRD0000_TMP (
    PRD_CODIGO             VARCHAR(5) NOT NULL,
    PRD_REFER              VARCHAR(20),
    PRD_STATUS             VARCHAR(1) DEFAULT 'A',
    PRD_DTCADASTRO         DATE,
    PRD_DESCRI             VARCHAR(100),
    PRD_DESCRI_RES         VARCHAR(35),
    PRD_UND                VARCHAR(3),
    PRD_UND_GRADE_CALCULO  VARCHAR(3),
    PRD_EMBALA             VARCHAR(10),
    PGR_CODIGO             VARCHAR(3),
    PTI_CODIGO             VARCHAR(3),
    IPI_CODIGO             VARCHAR(8),
    PRD_ALIQICM            DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    LIN_CODIGO             VARCHAR(3),
    PRD_COMPL              VARCHAR(150),
    PRD_CARACT             BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    PRD_MINIMO             DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_PCUSTO             DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_PVENDA             DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_PMEDIO             DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_PMATPRI            DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_MAOOBRA            DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_ESTOQUE            DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_SAIDA              DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_PENDENTE           DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    FOR_CODIGO             VARCHAR(4),
    PRD_ENTRADA            DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_MAXIMO             DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_TEMSUB             VARCHAR(1),
    PRD_SITRIBUT           VARCHAR(2),
    PRD_ICMSUBS            DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_UTILCONV           VARCHAR(1),
    PRD_UNDCOMP            VARCHAR(3),
    PRD_PESOKG             DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_FATORC             DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_DIVMULT            VARCHAR(1),
    EMP_CODIGO             VARCHAR(3),
    PRD_DTPCUSTO           TIMESTAMP,
    PRD_TABPRECO           VARCHAR(1),
    PRD_GARANTIA           VARCHAR(10),
    PRD_FAMILIA            VARCHAR(5),
    PRD_CODBARRA           VARCHAR(13),
    PRD_VAR1               DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_VAR2               DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_VAR3               DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_VAR4               DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_VAR5               DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_VAR6               DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_VAR7               DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_VAR8               DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_DCVAR1             VARCHAR(12),
    PRD_DCVAR2             VARCHAR(12),
    PRD_DCVAR3             VARCHAR(12),
    PRD_DCVAR4             VARCHAR(12),
    PRD_DCVAR5             VARCHAR(12),
    PRD_DCVAR6             VARCHAR(12),
    PRD_DCVAR7             VARCHAR(12),
    PRD_DCVAR8             VARCHAR(12),
    PRD_CURVA              VARCHAR(1),
    PRD_CODORIGINAL        VARCHAR(50),
    PRD_CODMERCOSUL        VARCHAR(15),
    PRD_DTPVENDA           DATE,
    AMX_CODIGO             VARCHAR(3),
    PRD_PESOLIQ            DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_GRADE              VARCHAR(1),
    PRD_CUSTOCOMIPI        DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_RESERVA            DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_EMPENHO            DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_SALDOPRODUCAO      DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_SIMULACAO          DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_COMISSAO           VALOR_NUMERICO /* VALOR_NUMERICO = NUMERIC(10,4) DEFAULT 0 */,
    PRD_RESERVA_VAR1       DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_RESERVA_VAR2       DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_RESERVA_VAR3       DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_RESERVA_VAR4       DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_RESERVA_VAR5       DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_RESERVA_VAR6       DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_RESERVA_VAR7       DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_RESERVA_VAR8       DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_DT_ULT_COMPRA      DATE,
    PRD_VL_ULT_COMPRA      DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_NF_ULT_COMPRA      VARCHAR(10),
    FOR_CODIGO_ANT         VARCHAR(4),
    PRD_DT_ULT_COMPRA_ANT  DATE,
    PRD_VL_ULT_COMPRA_ANT  DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_NF_ULT_COMPRA_ANT  VARCHAR(10),
    PRD_LOTE               VARCHAR(15),
    PRD_FATOR_PROD         VALOR_NUMERICO /* VALOR_NUMERICO = NUMERIC(10,4) DEFAULT 0 */,
    PRD_DIV_MULT_PROD      CHAR(1) DEFAULT 'D',
    STB_TRIBUTACAO         VARCHAR(2),
    PRD_ORIGEM             INTEGER,
    PRD_CUSTO_CREDITO      DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_MARGEMVENDA        DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_MARGEMOFERTA       DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_PRECOOFERTA        DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_INICIOOFERTA       DATE,
    PRD_FIMOFERTA          DATE,
    PRD_PVENDA2            DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_PVENDA3            DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_PVENDA4            DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_PVENDA5            DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_PVENDA6            DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    USU_CODIGO_ATUAL_TAB   INTEGER,
    USU_LOGIN_ATUAL_TAB    VARCHAR(15),
    PRD_DATA_ATUAL_TAB     TIMESTAMP,
    SPED_GENCODIGO         VARCHAR(2),
    SPED_TIPCODIGO         VARCHAR(2),
    PRD_UNICODIGO          INTEGER,
    PRD_PRODSERV           VARCHAR(1) DEFAULT 'P',
    PRD_CUSTOFRETE         DECIMAL5 /* DECIMAL5 = DECIMAL(18,5) */,
    PRD_CUSTOIPI           DECIMAL5 /* DECIMAL5 = DECIMAL(18,5) */,
    PRD_CUSTOSUBTRIB       DECIMAL5 /* DECIMAL5 = DECIMAL(18,5) */,
    PRD_CUSTOADCIONAL      DECIMAL5 /* DECIMAL5 = DECIMAL(18,5) */,
    PRD_MGDESPFIXAS        DECIMAL5 /* DECIMAL5 = DECIMAL(18,5) */,
    PRD_INDICESOBMARGEM    DECIMAL5 /* DECIMAL5 = DECIMAL(18,5) */,
    SRV_REGISTRO           INTEGER,
    PRD_FOTO               BLOB SUB_TYPE 0 SEGMENT SIZE 80,
    PRD_GERENCIA_LOTE      VARCHAR(1) DEFAULT 'N'
);


commit work;

--------------------------------------------------------------------------------
INSERT INTO prd0000_tmp(PRD_CODIGO,
    PRD_REFER,
    PRD_STATUS,
    PRD_DTCADASTRO,
    PRD_DESCRI,
    PRD_DESCRI_RES,
    PRD_UND,
    PRD_UND_GRADE_CALCULO,
    PRD_EMBALA,
    PGR_CODIGO,
    PTI_CODIGO,
    IPI_CODIGO,
    PRD_ALIQICM,
    LIN_CODIGO,
    PRD_COMPL,
    PRD_CARACT,
    PRD_MINIMO,
    PRD_PCUSTO,
    PRD_PVENDA,
    PRD_PMEDIO,
    PRD_PMATPRI,
    PRD_MAOOBRA,
    PRD_ESTOQUE,
    PRD_SAIDA,
    PRD_PENDENTE,
    FOR_CODIGO,
    PRD_ENTRADA,
    PRD_MAXIMO,
    PRD_TEMSUB,
    PRD_SITRIBUT,
    PRD_ICMSUBS,
    PRD_UTILCONV,
    PRD_UNDCOMP,
    PRD_PESOKG,
    PRD_FATORC,
    PRD_DIVMULT,
    EMP_CODIGO,
    PRD_DTPCUSTO,
    PRD_TABPRECO,
    PRD_GARANTIA,
    PRD_FAMILIA,
    PRD_CODBARRA,
    PRD_VAR1,
    PRD_VAR2,
    PRD_VAR3,
    PRD_VAR4,
    PRD_VAR5,
    PRD_VAR6,
    PRD_VAR7,
    PRD_VAR8,
    PRD_DCVAR1,
    PRD_DCVAR2,
    PRD_DCVAR3,
    PRD_DCVAR4,
    PRD_DCVAR5,
    PRD_DCVAR6,
    PRD_DCVAR7,
    PRD_DCVAR8,
    PRD_CURVA,
    PRD_CODORIGINAL,
    PRD_CODMERCOSUL,
    PRD_DTPVENDA,
    AMX_CODIGO,
    PRD_PESOLIQ,
    PRD_GRADE,
    PRD_CUSTOCOMIPI,
    PRD_RESERVA,
    PRD_EMPENHO,
    PRD_SALDOPRODUCAO,
    PRD_SIMULACAO,
    PRD_COMISSAO,
    PRD_RESERVA_VAR1,
    PRD_RESERVA_VAR2,
    PRD_RESERVA_VAR3,
    PRD_RESERVA_VAR4,
    PRD_RESERVA_VAR5,
    PRD_RESERVA_VAR6,
    PRD_RESERVA_VAR7,
    PRD_RESERVA_VAR8,
    PRD_DT_ULT_COMPRA,
    PRD_VL_ULT_COMPRA,
    PRD_NF_ULT_COMPRA,
    FOR_CODIGO_ANT,
    PRD_DT_ULT_COMPRA_ANT,
    PRD_VL_ULT_COMPRA_ANT,
    PRD_NF_ULT_COMPRA_ANT,
    PRD_LOTE,
    PRD_FATOR_PROD,
    PRD_DIV_MULT_PROD,
    STB_TRIBUTACAO,
    PRD_ORIGEM,
    PRD_CUSTO_CREDITO,
    PRD_MARGEMVENDA,
    PRD_MARGEMOFERTA,
    PRD_PRECOOFERTA,
    PRD_INICIOOFERTA,
    PRD_FIMOFERTA,
    PRD_PVENDA2,
    PRD_PVENDA3,
    PRD_PVENDA4,
    PRD_PVENDA5,
    PRD_PVENDA6,
    USU_CODIGO_ATUAL_TAB,
    USU_LOGIN_ATUAL_TAB,
    PRD_DATA_ATUAL_TAB,
    SPED_GENCODIGO,
    SPED_TIPCODIGO,
    PRD_UNICODIGO,
    PRD_PRODSERV,
    PRD_CUSTOFRETE,
    PRD_CUSTOIPI,
    PRD_CUSTOSUBTRIB,
    PRD_CUSTOADCIONAL,
    PRD_MGDESPFIXAS,
    PRD_INDICESOBMARGEM,
    SRV_REGISTRO,
    PRD_FOTO,
    PRD_GERENCIA_LOTE)
SELECT PRD_CODIGO,
    PRD_REFER,
    PRD_STATUS,
    PRD_DTCADASTRO,
    PRD_DESCRI,
    PRD_DESCRI_RES,
    PRD_UND,
    PRD_UND_GRADE_CALCULO,
    PRD_EMBALA,
    PGR_CODIGO,
    PTI_CODIGO,
    IPI_CODIGO,
    PRD_ALIQICM,
    LIN_CODIGO,
    PRD_COMPL,
    PRD_CARACT,
    PRD_MINIMO,
    PRD_PCUSTO,
    PRD_PVENDA,
    PRD_PMEDIO,
    PRD_PMATPRI,
    PRD_MAOOBRA,
    PRD_ESTOQUE,
    PRD_SAIDA,
    PRD_PENDENTE,
    FOR_CODIGO,
    PRD_ENTRADA,
    PRD_MAXIMO,
    PRD_TEMSUB,
    PRD_SITRIBUT,
    PRD_ICMSUBS,
    PRD_UTILCONV,
    PRD_UNDCOMP,
    PRD_PESOKG,
    PRD_FATORC,
    PRD_DIVMULT,
    EMP_CODIGO,
    PRD_DTPCUSTO,
    PRD_TABPRECO,
    PRD_GARANTIA,
    PRD_FAMILIA,
    PRD_CODBARRA,
    PRD_VAR1,
    PRD_VAR2,
    PRD_VAR3,
    PRD_VAR4,
    PRD_VAR5,
    PRD_VAR6,
    PRD_VAR7,
    PRD_VAR8,
    PRD_DCVAR1,
    PRD_DCVAR2,
    PRD_DCVAR3,
    PRD_DCVAR4,
    PRD_DCVAR5,
    PRD_DCVAR6,
    PRD_DCVAR7,
    PRD_DCVAR8,
    PRD_CURVA,
    PRD_CODORIGINAL,
    PRD_CODMERCOSUL,
    PRD_DTPVENDA,
    AMX_CODIGO,
    PRD_PESOLIQ,
    PRD_GRADE,
    PRD_CUSTOCOMIPI,
    PRD_RESERVA,
    PRD_EMPENHO,
    PRD_SALDOPRODUCAO,
    PRD_SIMULACAO,
    PRD_COMISSAO,
    PRD_RESERVA_VAR1,
    PRD_RESERVA_VAR2,
    PRD_RESERVA_VAR3,
    PRD_RESERVA_VAR4,
    PRD_RESERVA_VAR5,
    PRD_RESERVA_VAR6,
    PRD_RESERVA_VAR7,
    PRD_RESERVA_VAR8,
    PRD_DT_ULT_COMPRA,
    PRD_VL_ULT_COMPRA,
    PRD_NF_ULT_COMPRA,
    FOR_CODIGO_ANT,
    PRD_DT_ULT_COMPRA_ANT,
    PRD_VL_ULT_COMPRA_ANT,
    PRD_NF_ULT_COMPRA_ANT,
    PRD_LOTE,
    PRD_FATOR_PROD,
    PRD_DIV_MULT_PROD,
    STB_TRIBUTACAO,
    PRD_ORIGEM,
    PRD_CUSTO_CREDITO,
    PRD_MARGEMVENDA,
    PRD_MARGEMOFERTA,
    PRD_PRECOOFERTA,
    PRD_INICIOOFERTA,
    PRD_FIMOFERTA,
    PRD_PVENDA2,
    PRD_PVENDA3,
    PRD_PVENDA4,
    PRD_PVENDA5,
    PRD_PVENDA6,
    USU_CODIGO_ATUAL_TAB,
    USU_LOGIN_ATUAL_TAB,
    PRD_DATA_ATUAL_TAB,
    SPED_GENCODIGO,
    SPED_TIPCODIGO,
    PRD_UNICODIGO,
    PRD_PRODSERV,
    PRD_CUSTOFRETE,
    PRD_CUSTOIPI,
    PRD_CUSTOSUBTRIB,
    PRD_CUSTOADCIONAL,
    PRD_MGDESPFIXAS,
    PRD_INDICESOBMARGEM,
    SRV_REGISTRO,
    PRD_FOTO,
    PRD_GERENCIA_LOTE
FROM prd0000;

COMMIT work;
--------------------------------------------------------------------------------
drop INDEX XPRD_DESR;
drop INDEX XPRD_REFE;

COMMIT work;

DROP TABLE PRD0000;

COMMIT work;

CREATE TABLE PRD0000 (
    PRD_CODIGO             VARCHAR(5) NOT NULL,
    PRD_REFER              VARCHAR(20),
    PRD_STATUS             VARCHAR(1) DEFAULT 'A',
    PRD_DTCADASTRO         DATE,
    PRD_DESCRI             VARCHAR(100),
    PRD_DESCRI_RES         VARCHAR(35),
    PRD_UND                VARCHAR(3),
    PRD_UND_GRADE_CALCULO  VARCHAR(3),
    PRD_EMBALA             VARCHAR(10),
    PGR_CODIGO             VARCHAR(3),
    PTI_CODIGO             VARCHAR(3),
    IPI_CODIGO             VARCHAR(8),
    PRD_ALIQICM            DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    LIN_CODIGO             VARCHAR(3),
    PRD_COMPL              VARCHAR(150),
    PRD_CARACT             BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    PRD_MINIMO             DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_PCUSTO             DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_PVENDA             DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_PMEDIO             DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_PMATPRI            DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_MAOOBRA            DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_ESTOQUE            DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_SAIDA              DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_PENDENTE           DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    FOR_CODIGO             VARCHAR(4),
    PRD_ENTRADA            DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_MAXIMO             DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_TEMSUB             VARCHAR(1),
    PRD_SITRIBUT           VARCHAR(2),
    PRD_ICMSUBS            DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_UTILCONV           VARCHAR(1),
    PRD_UNDCOMP            VARCHAR(3),
    PRD_PESOKG             DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_FATORC             DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_DIVMULT            VARCHAR(1),
    EMP_CODIGO             VARCHAR(3),
    PRD_DTPCUSTO           TIMESTAMP,
    PRD_TABPRECO           VARCHAR(1),
    PRD_GARANTIA           VARCHAR(10),
    PRD_FAMILIA            VARCHAR(5),
    PRD_CODBARRA           VARCHAR(13),
    PRD_VAR1               DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_VAR2               DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_VAR3               DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_VAR4               DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_VAR5               DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_VAR6               DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_VAR7               DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_VAR8               DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_DCVAR1             VARCHAR(12),
    PRD_DCVAR2             VARCHAR(12),
    PRD_DCVAR3             VARCHAR(12),
    PRD_DCVAR4             VARCHAR(12),
    PRD_DCVAR5             VARCHAR(12),
    PRD_DCVAR6             VARCHAR(12),
    PRD_DCVAR7             VARCHAR(12),
    PRD_DCVAR8             VARCHAR(12),
    PRD_CURVA              VARCHAR(1),
    PRD_CODORIGINAL        VARCHAR(50),
    PRD_CODMERCOSUL        VARCHAR(15),
    PRD_DTPVENDA           DATE,
    AMX_CODIGO             VARCHAR(3),
    PRD_PESOLIQ            DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_GRADE              VARCHAR(1),
    PRD_CUSTOCOMIPI        DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_RESERVA            DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_EMPENHO            DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_SALDOPRODUCAO      DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_SIMULACAO          DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_COMISSAO           VALOR_NUMERICO /* VALOR_NUMERICO = NUMERIC(10,4) DEFAULT 0 */,
    PRD_RESERVA_VAR1       DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_RESERVA_VAR2       DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_RESERVA_VAR3       DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_RESERVA_VAR4       DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_RESERVA_VAR5       DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_RESERVA_VAR6       DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_RESERVA_VAR7       DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_RESERVA_VAR8       DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_DT_ULT_COMPRA      DATE,
    PRD_VL_ULT_COMPRA      DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_NF_ULT_COMPRA      VARCHAR(10),
    FOR_CODIGO_ANT         VARCHAR(4),
    PRD_DT_ULT_COMPRA_ANT  DATE,
    PRD_VL_ULT_COMPRA_ANT  DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_NF_ULT_COMPRA_ANT  VARCHAR(10),
    PRD_LOTE               VARCHAR(15),
    PRD_FATOR_PROD         VALOR_NUMERICO /* VALOR_NUMERICO = NUMERIC(10,4) DEFAULT 0 */,
    PRD_DIV_MULT_PROD      CHAR(1) DEFAULT 'D',
    STB_TRIBUTACAO         VARCHAR(2),
    PRD_ORIGEM             INTEGER,
    PRD_CUSTO_CREDITO      DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_MARGEMVENDA        DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_MARGEMOFERTA       DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_PRECOOFERTA        DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_INICIOOFERTA       DATE,
    PRD_FIMOFERTA          DATE,
    PRD_PVENDA2            DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_PVENDA3            DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_PVENDA4            DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_PVENDA5            DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    PRD_PVENDA6            DECIMAL6 /* DECIMAL6 = NUMERIC(18,5) DEFAULT 0 */,
    USU_CODIGO_ATUAL_TAB   INTEGER,
    USU_LOGIN_ATUAL_TAB    VARCHAR(15),
    PRD_DATA_ATUAL_TAB     TIMESTAMP,
    SPED_GENCODIGO         VARCHAR(2),
    SPED_TIPCODIGO         VARCHAR(2),
    PRD_UNICODIGO          INTEGER,
    PRD_PRODSERV           VARCHAR(1) DEFAULT 'P',
    PRD_CUSTOFRETE         DECIMAL5 /* DECIMAL5 = DECIMAL(18,5) */,
    PRD_CUSTOIPI           DECIMAL5 /* DECIMAL5 = DECIMAL(18,5) */,
    PRD_CUSTOSUBTRIB       DECIMAL5 /* DECIMAL5 = DECIMAL(18,5) */,
    PRD_CUSTOADCIONAL      DECIMAL5 /* DECIMAL5 = DECIMAL(18,5) */,
    PRD_MGDESPFIXAS        DECIMAL5 /* DECIMAL5 = DECIMAL(18,5) */,
    PRD_INDICESOBMARGEM    DECIMAL5 /* DECIMAL5 = DECIMAL(18,5) */,
    SRV_REGISTRO           INTEGER,
    PRD_FOTO               BLOB SUB_TYPE 0 SEGMENT SIZE 80,
    PRD_GERENCIA_LOTE      VARCHAR(1) DEFAULT 'N'
);

commit work;

ALTER TABLE PRD0000 ADD CONSTRAINT PK_PRD0000 PRIMARY KEY (PRD_CODIGO);

commit work;

CREATE INDEX XPRD_DESR ON PRD0000 (PRD_DESCRI);
CREATE INDEX XPRD_REFE ON PRD0000 (PRD_REFER);

commit work;

COMMENT ON COLUMN PRD0000.PRD_FATOR_PROD IS
'FATOR DE CONVERSAO PARA A PRODUÇÃO';

COMMENT ON COLUMN PRD0000.PRD_DIV_MULT_PROD IS 
'D = DIVIDE
M = MULTIPLICA';

COMMENT ON COLUMN PRD0000.PRD_ORIGEM IS 
'0 = NACIONAL
1 = ESTRANGEIRA';

COMMENT ON COLUMN PRD0000.SRV_REGISTRO IS 
'REGISTRO DA TABELA DE SERVIÇOS';



commit work;

INSERT INTO prd0000(PRD_CODIGO,
    PRD_REFER,
    PRD_STATUS,
    PRD_DTCADASTRO,
    PRD_DESCRI,
    PRD_DESCRI_RES,
    PRD_UND,
    PRD_UND_GRADE_CALCULO,
    PRD_EMBALA,
    PGR_CODIGO,
    PTI_CODIGO,
    IPI_CODIGO,
    PRD_ALIQICM,
    LIN_CODIGO,
    PRD_COMPL,
    PRD_CARACT,
    PRD_MINIMO,
    PRD_PCUSTO,
    PRD_PVENDA,
    PRD_PMEDIO,
    PRD_PMATPRI,
    PRD_MAOOBRA,
    PRD_ESTOQUE,
    PRD_SAIDA,
    PRD_PENDENTE,
    FOR_CODIGO,
    PRD_ENTRADA,
    PRD_MAXIMO,
    PRD_TEMSUB,
    PRD_SITRIBUT,
    PRD_ICMSUBS,
    PRD_UTILCONV,
    PRD_UNDCOMP,
    PRD_PESOKG,
    PRD_FATORC,
    PRD_DIVMULT,
    EMP_CODIGO,
    PRD_DTPCUSTO,
    PRD_TABPRECO,
    PRD_GARANTIA,
    PRD_FAMILIA,
    PRD_CODBARRA,
    PRD_VAR1,
    PRD_VAR2,
    PRD_VAR3,
    PRD_VAR4,
    PRD_VAR5,
    PRD_VAR6,
    PRD_VAR7,
    PRD_VAR8,
    PRD_DCVAR1,
    PRD_DCVAR2,
    PRD_DCVAR3,
    PRD_DCVAR4,
    PRD_DCVAR5,
    PRD_DCVAR6,
    PRD_DCVAR7,
    PRD_DCVAR8,
    PRD_CURVA,
    PRD_CODORIGINAL,
    PRD_CODMERCOSUL,
    PRD_DTPVENDA,
    AMX_CODIGO,
    PRD_PESOLIQ,
    PRD_GRADE,
    PRD_CUSTOCOMIPI,
    PRD_RESERVA,
    PRD_EMPENHO,
    PRD_SALDOPRODUCAO,
    PRD_SIMULACAO,
    PRD_COMISSAO,
    PRD_RESERVA_VAR1,
    PRD_RESERVA_VAR2,
    PRD_RESERVA_VAR3,
    PRD_RESERVA_VAR4,
    PRD_RESERVA_VAR5,
    PRD_RESERVA_VAR6,
    PRD_RESERVA_VAR7,
    PRD_RESERVA_VAR8,
    PRD_DT_ULT_COMPRA,
    PRD_VL_ULT_COMPRA,
    PRD_NF_ULT_COMPRA,
    FOR_CODIGO_ANT,
    PRD_DT_ULT_COMPRA_ANT,
    PRD_VL_ULT_COMPRA_ANT,
    PRD_NF_ULT_COMPRA_ANT,
    PRD_LOTE,
    PRD_FATOR_PROD,
    PRD_DIV_MULT_PROD,
    STB_TRIBUTACAO,
    PRD_ORIGEM,
    PRD_CUSTO_CREDITO,
    PRD_MARGEMVENDA,
    PRD_MARGEMOFERTA,
    PRD_PRECOOFERTA,
    PRD_INICIOOFERTA,
    PRD_FIMOFERTA,
    PRD_PVENDA2,
    PRD_PVENDA3,
    PRD_PVENDA4,
    PRD_PVENDA5,
    PRD_PVENDA6,
    USU_CODIGO_ATUAL_TAB,
    USU_LOGIN_ATUAL_TAB,
    PRD_DATA_ATUAL_TAB,
    SPED_GENCODIGO,
    SPED_TIPCODIGO,
    PRD_UNICODIGO,
    PRD_PRODSERV,
    PRD_CUSTOFRETE,
    PRD_CUSTOIPI,
    PRD_CUSTOSUBTRIB,
    PRD_CUSTOADCIONAL,
    PRD_MGDESPFIXAS,
    PRD_INDICESOBMARGEM,
    SRV_REGISTRO,
    PRD_FOTO,
    PRD_GERENCIA_LOTE)
SELECT '0'||PRD_CODIGO,
    PRD_REFER,
    PRD_STATUS,
    PRD_DTCADASTRO,
    PRD_DESCRI,
    PRD_DESCRI_RES,
    PRD_UND,
    PRD_UND_GRADE_CALCULO,
    PRD_EMBALA,
    PGR_CODIGO,
    PTI_CODIGO,
    IPI_CODIGO,
    PRD_ALIQICM,
    LIN_CODIGO,
    PRD_COMPL,
    PRD_CARACT,
    PRD_MINIMO,
    PRD_PCUSTO,
    PRD_PVENDA,
    PRD_PMEDIO,
    PRD_PMATPRI,
    PRD_MAOOBRA,
    PRD_ESTOQUE,
    PRD_SAIDA,
    PRD_PENDENTE,
    FOR_CODIGO,
    PRD_ENTRADA,
    PRD_MAXIMO,
    PRD_TEMSUB,
    PRD_SITRIBUT,
    PRD_ICMSUBS,
    PRD_UTILCONV,
    PRD_UNDCOMP,
    PRD_PESOKG,
    PRD_FATORC,
    PRD_DIVMULT,
    EMP_CODIGO,
    PRD_DTPCUSTO,
    PRD_TABPRECO,
    PRD_GARANTIA,
    PRD_FAMILIA,
    PRD_CODBARRA,
    PRD_VAR1,
    PRD_VAR2,
    PRD_VAR3,
    PRD_VAR4,
    PRD_VAR5,
    PRD_VAR6,
    PRD_VAR7,
    PRD_VAR8,
    PRD_DCVAR1,
    PRD_DCVAR2,
    PRD_DCVAR3,
    PRD_DCVAR4,
    PRD_DCVAR5,
    PRD_DCVAR6,
    PRD_DCVAR7,
    PRD_DCVAR8,
    PRD_CURVA,
    PRD_CODORIGINAL,
    PRD_CODMERCOSUL,
    PRD_DTPVENDA,
    AMX_CODIGO,
    PRD_PESOLIQ,
    PRD_GRADE,
    PRD_CUSTOCOMIPI,
    PRD_RESERVA,
    PRD_EMPENHO,
    PRD_SALDOPRODUCAO,
    PRD_SIMULACAO,
    PRD_COMISSAO,
    PRD_RESERVA_VAR1,
    PRD_RESERVA_VAR2,
    PRD_RESERVA_VAR3,
    PRD_RESERVA_VAR4,
    PRD_RESERVA_VAR5,
    PRD_RESERVA_VAR6,
    PRD_RESERVA_VAR7,
    PRD_RESERVA_VAR8,
    PRD_DT_ULT_COMPRA,
    PRD_VL_ULT_COMPRA,
    PRD_NF_ULT_COMPRA,
    FOR_CODIGO_ANT,
    PRD_DT_ULT_COMPRA_ANT,
    PRD_VL_ULT_COMPRA_ANT,
    PRD_NF_ULT_COMPRA_ANT,
    PRD_LOTE,
    PRD_FATOR_PROD,
    PRD_DIV_MULT_PROD,
    STB_TRIBUTACAO,
    PRD_ORIGEM,
    PRD_CUSTO_CREDITO,
    PRD_MARGEMVENDA,
    PRD_MARGEMOFERTA,
    PRD_PRECOOFERTA,
    PRD_INICIOOFERTA,
    PRD_FIMOFERTA,
    PRD_PVENDA2,
    PRD_PVENDA3,
    PRD_PVENDA4,
    PRD_PVENDA5,
    PRD_PVENDA6,
    USU_CODIGO_ATUAL_TAB,
    USU_LOGIN_ATUAL_TAB,
    PRD_DATA_ATUAL_TAB,
    SPED_GENCODIGO,
    SPED_TIPCODIGO,
    PRD_UNICODIGO,
    PRD_PRODSERV,
    PRD_CUSTOFRETE,
    PRD_CUSTOIPI,
    PRD_CUSTOSUBTRIB,
    PRD_CUSTOADCIONAL,
    PRD_MGDESPFIXAS,
    PRD_INDICESOBMARGEM,
    SRV_REGISTRO,
    PRD_FOTO,
    PRD_GERENCIA_LOTE
FROM prd0000_tmp;

COMMIT work;
--------------------------------------------------------------------------------

CREATE OR ALTER VIEW VW_SPED_INVENTARIO(
    CODIGO_ITEM,
    UNIDADE_MEDIDA,
    QUANTIDADE,
    VALOR_UNITARIO,
    VALOR_ITEM,
    TIPO_PROPRIEDADE,
    DESCRICAO,
    CONTA_CONTABIL)
AS
SELECT
T1.PRD_REFER,
T1.PRD_UND,
COALESCE((select SUM(t2.KAS_SALDO) from KARDEX_ALMOX_SALDO t2 JOIN ALMOX0000 t3 on (t3.AMX_CODIGO = t2.AMX_CODIGO and t3.AMX_FISICO = 'S') where t2.PRD_CODIGO = t1.PRD_CODIGO),0),
CASE
    WHEN (T1.PRD_PMEDIO = 0) THEN
        T1.PRD_PCUSTO
    ELSE
        T1.PRD_PMEDIO
END,
CASE
    WHEN (T1.PRD_PMEDIO = 0) THEN
        T1.PRD_PCUSTO
    ELSE
        T1.PRD_PMEDIO
END,case when(1=1) then
    0
end,
t1.PRD_DESCRI,
case when(1=1) then
    ''
end
FROM
PRD0000 T1
WHERE T1.PRD_PRODSERV = 'P'
;

COMMIT work;
--------------------------------------------------------------------------------

CREATE OR ALTER VIEW VW_SPED_NOTAS_FISCAIS_ITENS(
    REGISTRO_NOTA,
    CODIGO_ITEM,
    DESCRICAO_ITEM,
    QUANTIDADE,
    UNIDADE,
    VALOR_ITEM,
    VALOR_DESCONTO,
    INDICADOR_MOVIMENTACAO,
    CST_ICMS,
    CFOP,
    CODIGO_CFOP, 
    VALOR_BASE_ICMS,
    ALIQUOTA_ICMS,
    VALOR_ICMS,
    VALOR_BASE_ICMS_ST,
    ALIQUOTA_ICMS_ST,
    VALOR_ICMS_ST,
    INDICADOR_APURACAO_IPI,
    CST_IPI,
    CODIGO_ENQUAD_IPI,
    VALOR_BASE_IPI,
    ALIQUOTA_IPI,
    VALOR_IPI,
    CST_PIS,
    VALOR_BASE_PIS,
    ALIQ_PIS,
    QUANTIDADE_BASE_PIS,
    ALIQ_PIS_REAIS,
    VALOR_PIS,
    CST_COFINS,
    VALOR_BASE_COFINS,
    ALIQUOTA_COFINS,
    QUANTIDADE_BASE_COFINS,
    ALIQ_COFINS_REAIS,
    VALOR_COFINS,
    CODIGO_CONTABIL)
AS
SELECT
CAST('E'||T1.ENF_IT_NOTANUMBER||T1.FOR_CODIGO AS VARCHAR(30)),
T1.PRD_REFER,
CAST(T1.PRD_DESCRI AS VARCHAR(500)),
T1.ENF_QTDE,
(SELECT FIRST 1 T3.PRD_UND FROM PRD0000 T3 WHERE T3.PRD_REFER = T1.PRD_REFER),
T1.ENF_PRECO,
T1.ENF_IT_DESCTO,
CAST((CASE WHEN (1=1) THEN
    'S'
END) AS VARCHAR(1)),
COALESCE((SELECT FIRST 1 cast(T3.PRD_ORIGEM as varchar(1)) FROM PRD0000 T3 WHERE T3.PRD_REFER = T1.PRD_REFER),'0')||t1.STB_TRIBUTACAO,
t1.ENF_CFOP,
t1.ENF_CFOP,
t1.ENF_IT_BASEICMS,
t1.ENF_ICMSALIQ,
t1.ENF_ICMS,
t1.ENF_IT_BASESUBTRIB,
t1.ENF_IT_ALIQSUBTRIB,
CAST(t1.ENF_IT_BASESUBTRIB * t1.ENF_IT_ALIQSUBTRIB AS NUMERIC(18,2)),
CAST((CASE WHEN (1=1) THEN
    0
END) AS INTEGER),
t1.CST_IPI,
CAST(CASE WHEN (1=1) THEN
    'XXX'
END as varchar(3)),
COALESCE(T1.ENF_IT_BASEIPI,0),
COALESCE(T1.ENF_IPIALIQ,0),
COALESCE(T1.ENF_IT_VLIPI,0),
t1.CST_PIS,
COALESCE(T1.ENF_BASEPIS,0),
COALESCE(T1.ENF_IT_ALIQPIS,0),
CASE WHEN (1=1) THEN
    0.00
END,
CASE WHEN (1=1) THEN
    0.00
END,
COALESCE(T1.ENF_IT_VLPIS,0),
t1.CST_COFINS,
COALESCE(T1.ENF_BASECOFINS,0),
COALESCE(T1.ENF_IT_ALIQCOFINS,0),
CASE WHEN (1=1) THEN
    0.00
END,
CASE WHEN (1=1) THEN
    0.00
END,
COALESCE(T1.ENF_IT_VLCOFINS,0),
CASE WHEN (1=1) THEN
    ''
END
FROM
ENF_IT01 T1
UNION ALL
SELECT
CAST('S'||T2.NF_IT_NOTANUMER AS VARCHAR(30)),
T2.PRD_REFER,
T2.PRD_DESCRI,
T2.NF_QTDE,
(SELECT FIRST 1 T3.PRD_UND FROM PRD0000 T3 WHERE T3.PRD_REFER = T2.PRD_REFER),
T2.NF_PRECO,
T2.NF_IDESCTO1,
CAST((CASE WHEN (1=1) THEN
    'S'
END) AS VARCHAR(1)),
COALESCE((SELECT FIRST 1 cast(T3.PRD_ORIGEM as varchar(1)) FROM PRD0000 T3 WHERE T3.PRD_REFER = T2.PRD_REFER),'0')||t2.STB_TRIBUTACAO,
cast(t2.NTP_CFOP as varchar(4)),
cast(t2.NTP_CFOP as varchar(4)),
t2.NF_ICMSBASE,
t2.NF_ICMSALIQ,
t2.NF_ICMSVALOR,
t2.NF_SUBTRIBASE,
t2.NF_ALIQSUBTRIB,
CAST(t2.NF_SUBTRIBASE * t2.NF_ALIQSUBTRIB AS NUMERIC(18,2)),
CAST((CASE WHEN (1=1) THEN
    0
END) AS INTEGER),
CAST(CASE WHEN (1=1) THEN
    'XXX'
END as varchar(3)),
CAST(CASE WHEN (1=1) THEN
    'XXX'
END as varchar(3)),
COALESCE(T2.NF_IPIBASE,0),
COALESCE(T2.NF_IPIALIQ,0),
COALESCE(T2.NF_IPIVALOR,0),
CAST(CASE WHEN (T2.NF_BASE_PIS > 0) THEN
    '01'
    ELSE
    '99'
END as varchar(3)),
COALESCE(T2.NF_BASE_PIS,0),
COALESCE(T2.NF_ALIQPIS,0),
CASE WHEN (1=1) THEN
    0.00
END,
CASE WHEN (1=1) THEN
    0.00
END,
COALESCE(T2.NF_VLPIS,0),
cast(CASE WHEN (T2.NF_BASE_COFINS > 0) THEN
    '01'
    ELSE
    '99'
END as varchar(3)),
COALESCE(T2.NF_BASE_COFINS,0),
COALESCE(T2.NF_ALIQCOFINS,0),
CASE WHEN (1=1) THEN
    0.00
END,
CASE WHEN (1=1) THEN
    0.00
END,
COALESCE(T2.NF_VLCOFINS,0),
CASE WHEN (1=1) THEN
    ''
END
FROM
NF_IT01 T2
;

COMMIT work;
--------------------------------------------------------------------------------
CREATE OR ALTER VIEW VW_SPED_PRODUTOS_SERVICOS(
    CODIGO_ITEM,
    DESCRICAO_ITEM,
    CODIGO_BARRAS,
    UNIDADE_MEDIDA,
    TIPO,
    CODIGO_NCM,
    CODIGO_GENERO,
    CODIGO_SERVICO,
    ALIQUOTA_ICMS)
AS
SELECT
T1.PRD_CODIGO,
T1.PRD_DESCRI,
T1.PRD_CODBARRA,
T1.PRD_UND,
T1.SPED_TIPCODIGO,
T1.IPI_CODIGO,
T1.SPED_GENCODIGO,
(SELECT T2.SRV_CODIGO FROM SRV0000 T2 WHERE T2.SRV_REGISTRO = T1.SRV_REGISTRO),
case
    when (T1.PRD_ALIQICM > 0) then
        T1.PRD_ALIQICM
    else
        (SELECT T3.ICM_ALIQ FROM ICM0000 T3 WHERE T3.ICM_DESTINO = (SELECT T4.EMP_UF FROM EMP0000 T4 WHERE T4.EMP_CODIGO = T1.EMP_CODIGO))
END
FROM
PRD0000 T1
;

COMMIT work;
--------------------------------------------------------------------------------
CREATE OR ALTER VIEW VW_SPED_REGISTRO_ANALITICO(
    EMISSAO,
    ENTRADA,
    CST_ICMS,
    CFOP,
    ALIQ_ICMS,
    VL_OPR,
    VL_BC_ICMS,
    VL_ICMS,
    VL_BC_ICMS_ST,
    VL_ICMS_ST,
    VL_RED_BC,
    VL_IPI,
    COD_OBS)
AS
SELECT
ENF.ENF_EMISSAO,
ENF.ENF_ENTRADA,
COALESCE(cast((PRD.PRD_ORIGEM) as varchar(1))||t1.STB_TRIBUTACAO,'000'),
COALESCE(CAST(T1.ENF_CFOP AS VARCHAR(30)),'0000'),
t1.ENF_ICMS,
COALESCE(sum(cast(t1.ENF_QTDE * t1.ENF_PRECO as numeric(18,2))+t1.ENF_IT_VLDESP_ACES+t1.ENF_IT_VALFRETE+t1.ENF_IT_VLSEGURO+t1.ENF_IT_VLSUBTRIB+t1.ENF_IT_VLIPI ),0),
COALESCE(SUM(cast(t1.ENF_IT_BASEICMS as numeric(18,2))),0),
COALESCE(SUM(cast(t1.ENF_ICMS as numeric(18,2))),0),
COALESCE(sum(t1.ENF_IT_BASESUBTRIB),0),
COALESCE(sum(t1.ENF_IT_VLSUBTRIB),0),
COALESCE(0,0),
COALESCE(sum(t1.ENF_IT_VLIPI),0),
CASE WHEN (1=1) THEN
    ''
END
FROM
ENF_IT01 T1
LEFT JOIN PRD0000 PRD ON (PRD.PRD_REFER = T1.PRD_REFER)
left JOIN ENF0001 ENF ON (ENF.ENF_NOTANUMBER = T1.ENF_IT_NOTANUMBER AND ENF.FOR_CODIGO = T1.FOR_CODIGO)
GROUP by  5,4, t1.STB_TRIBUTACAO, PRD.PRD_ORIGEM, ENF.ENF_EMISSAO,
ENF.ENF_ENTRADA
UNION ALL
SELECT
NF.NF_EMISSAO,
NF.NF_SAIDA,
COALESCE(cast(PRD.PRD_ORIGEM as varchar(1))||t2.STB_TRIBUTACAO,'000'),
COALESCE(CAST(T2.NTP_CFOP AS VARCHAR(30)),'000'),
COALESCE(t2.NF_ICMSALIQ,0),
COALESCE(sum(cast(t2.NF_QTDE * t2.NF_PRECO as numeric(18,2))+t2.NF_IDESP_ACES+t2.NF_IFRETE+t2.NF_ISEGURO+t2.NF_VLSUBST+t2.NF_IPIVALOR),0),
COALESCE(sum(t2.NF_ICMSBASE),0),
COALESCE(sum(t2.NF_ICMSVALOR),0),
COALESCE(sum(t2.NF_SUBTRIBASE),0),
COALESCE(sum(cast(t2.NF_VLSUBST as numeric(18,2))),0),
COALESCE(0,0),
COALESCE(sum(t2.NF_IPIVALOR),0),
CASE WHEN (1=1) THEN
    ''
END
FROM
NF_IT01 T2
LEFT JOIN PRD0000 PRD ON (PRD.PRD_REFER = T2.PRD_REFER)
LEFT JOIN NF0001 NF ON (NF.NF_NOTANUMBER = T2.NF_IT_NOTANUMER)
GROUP by  5,4, t2.STB_TRIBUTACAO, PRD.PRD_ORIGEM ,NF.NF_EMISSAO,
NF.NF_SAIDA
;
COMMIT work;
--------------------------------------------------------------------------------
CREATE OR ALTER VIEW VW_SPED_UNIDADE_MEDIDA(
    UNIDADE_SIGLA,
    UNIDADE_DESCRICAO)
AS
SELECT T1.PRD_UND,T1.PRD_UND FROM PRD0000 T1 WHERE T1.PRD_UND IS NOT NULL AND T1.PRD_UND <> '' GROUP BY T1.PRD_UND
;

COMMIT work;
--------------------------------------------------------------------------------
UPDATE PED_IT01 SET PRD_CODIGO = '0'||PRD_CODIGO;

COMMIT work;
--------------------------------------------------------------------------------

UPDATE PRD0000_CODIGO SET PRD_CODIGO = '0'||PRD_CODIGO;

COMMIT work;
--------------------------------------------------------------------------------

ALTER TABLE PRD_GRADE
    ALTER PRD_CODIGO TYPE VARCHAR(5) CHARACTER SET NONE;

    COMMIT work;
--------------------------------------------------------------------------------

UPDATE PRD_GRADE SET PRD_CODIGO = '0'||PRD_CODIGO;

COMMIT work;
--------------------------------------------------------------------------------

ALTER TABLE PED_VENDA_PERDIDA
    ALTER PRD_CODIGO TYPE VARCHAR(5) CHARACTER SET NONE;

    COMMIT work;
--------------------------------------------------------------------------------

UPDATE PED_VENDA_PERDIDA SET PRD_CODIGO = '0'||PRD_CODIGO;

COMMIT work;
--------------------------------------------------------------------------------

UPDATE PRD_LOTE SET PRD_CODIGO = '0'||PRD_CODIGO;

COMMIT work;
--------------------------------------------------------------------------------

ALTER TABLE ENF_IT01
    ALTER PRD_CODIGO TYPE VARCHAR(6) CHARACTER SET NONE;

    COMMIT work;
--------------------------------------------------------------------------------

UPDATE ENF_IT01 SET PRD_CODIGO = '0'||PRD_CODIGO;

COMMIT work;
--------------------------------------------------------------------------------

ALTER TABLE FAT_IT02
    ALTER PRD_CODIGO TYPE VARCHAR(5) CHARACTER SET NONE;

    COMMIT work;
--------------------------------------------------------------------------------

UPDATE FAT_IT02 SET PRD_CODIGO = '0'||PRD_CODIGO;

COMMIT work;
--------------------------------------------------------------------------------

UPDATE KARDEX SET PRD_CODIGO = '0'||PRD_CODIGO;

COMMIT work;
--------------------------------------------------------------------------------

UPDATE KARDEX_ALMOX_SALDO SET PRD_CODIGO = '0'||PRD_CODIGO;

COMMIT work;
--------------------------------------------------------------------------------

UPDATE NF_IT01 SET PRD_CODIGO = '0'||PRD_CODIGO;

COMMIT work;
--------------------------------------------------------------------------------

ALTER TABLE PAG_IT02
    ALTER PRD_CODIGO TYPE VARCHAR(5) CHARACTER SET NONE;

    COMMIT work;
--------------------------------------------------------------------------------

UPDATE PAG_IT02 SET PRD_CODIGO = '0'||PRD_CODIGO;

COMMIT work;
--------------------------------------------------------------------------------

ALTER TABLE PED_EB02
    ALTER PRD_CODIGO TYPE VARCHAR(5) CHARACTER SET NONE;

    COMMIT work;
--------------------------------------------------------------------------------

UPDATE PED_EB02 SET PRD_CODIGO = '0'||PRD_CODIGO;

COMMIT work;
--------------------------------------------------------------------------------

ALTER TABLE PED_EB03
    ALTER PRD_CODIGO TYPE VARCHAR(5) CHARACTER SET NONE;

    COMMIT work;
--------------------------------------------------------------------------------

UPDATE PED_EB03 SET PRD_CODIGO = '0'||PRD_CODIGO;

--------------------------------------------------------------------------------
Update VERSAOSISTEMA SET
       VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.0.404' ,
       VERSAOSISTEMA.DATA   = '15.09.2014'
 where VERSAOSISTEMA.CODIGO = 1;


commit work;
