
UPDATE  VERSAOSISTEMA SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.508',
       VERSAOSISTEMA.DATA   = '23.04.2018'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE PRMT0001 ALTER COLUMN PMT_MDL_OP TYPE VARCHAR(2); 
COMMENT ON COLUMN PRMT0001.PMT_MDL_OP IS 'TIPO DE RELATORIO DE PRODUCAO';

ALTER TABLE OPERACOES ADD OPE_OBSERVACAO BLOB SUB_TYPE 0;
COMMENT ON COLUMN OPERACOES.OPE_OBSERVACAO IS 'OBSERVACAO DA OPERACAO';
ALTER TABLE ENGENHARIA_PROCESSO ADD ENG_OBSERVACAO BLOB SUB_TYPE 0;
COMMENT ON COLUMN ENGENHARIA_PROCESSO.ENG_OBSERVACAO IS 'OBSERVACAO DA OPERACAO';
COMMENT ON COLUMN ENGENHARIA_PROCESSO.ESP_ESBOCO IS 'FOTO E ESBOCO DO PRODUTO COM AS MEDIDADAS';

COMMENT ON COLUMN FTC_IT01.PRD_REFER_ITENS IS 'CHAVE DO PRODUTO PARA MATERIAS PRIMAS';
COMMENT ON COLUMN FTC_IT01.PRG_REGISTRO IS 'REFERENCIA DA CHAVE DA GRADE DO PRODUTO (PRD_GRADE)';
COMMENT ON COLUMN FTC_IT01.FTI_UC IS 'QUANTIDADE DE MATERIA PRIMA NO PRODUTO PRD_REFER';


ALTER TABLE FABRICACAO ADD FAB_OBSERVACAO BLOB SUB_TYPE 0;
COMMENT ON COLUMN FABRICACAO.FAB_OBSERVACAO IS 'OBSERVACAO DA OPERACAO';