UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.564 patch 1',
    VERSAOSISTEMA.DATA   = '13.01.2022',
	VERSAO = '3.0.9.564'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE PRMT0001 ADD PMT_HABILITAR_DIFAL VARCHAR(1);
UPDATE PRMT0001 SET PMT_HABILITAR_DIFAL = 'S' WHERE PMT_HABILITAR_DIFAL IS NULL;
commit work;



