UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.559 patch 2',
    VERSAOSISTEMA.DATA   = '17.08.2021',
	VERSAO = '3.0.9.559'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE PRMT0001 ADD PMT_OS_CABECALHO VARCHAR(50);
ALTER TABLE PRMT0001 ADD PMT_OS_REV VARCHAR(10);
ALTER TABLE PRMT0001 ADD PMT_OS_DATA_EMISSAO DATE;

ALTER TABLE PRMT0001 ADD PMT_LIMITE_CREDITO_INICIAL DECIMAL (18,2);

ALTER TABLE PRMT0001 ADD PMT_REL_DATA_EXPEDICAO CHAR(1);

ALTER TABLE USUARIO_PARAMETRO ADD USP_FATURARSEMCONCLUSAO char(1);
ALTER TABLE USUARIO_PARAMETRO ADD USP_AUTORIZA_COTACAO_MATERIAL char(1);
ALTER TABLE USUARIO_PARAMETRO ADD USP_AUTORIZA_COMPRA_MATERIAL char(1);


