UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.587 patch 2',
    VERSAOSISTEMA.DATA   = '15.12.2023',
	VERSAO = '3.0.9.587'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE PRMT0001 ADD PMT_LAYOUT_BOLETO_FATURAMENTO VARCHAR(2);
UPDATE PRMT0001 SET PMT_LAYOUT_BOLETO_FATURAMENTO = '1' WHERE PMT_LAYOUT_BOLETO_FATURAMENTO IS NULL; 
COMMIT WORK;

ALTER TABLE USUARIO_PARAMETRO ADD USP_DASH_INTELIGENCIA VARCHAR(1);


