UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.539 patch 6',
       VERSAOSISTEMA.DATA   = '20.12.2019',
	    VERSAO = '3.0.9.539'
 where VERSAOSISTEMA.CODIGO = 1;
 
commit work;
 
UPDATE FAT0000 fat 
SET CCT_CODIGO = (SELECT FIRST 1 CCT_CODIGO FROM FAT_PC01 pc WHERE pc.FAT_CODIGO = fat.FAT_CODIGO AND fat.EMP_CODIGO = pc.EMP_CODIGO );


commit work;