UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.595 patch 1',
    VERSAOSISTEMA.DATA   = '16.08.2024',
	VERSAO = '3.0.9.595'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

/* issue 1937 */
CREATE TABLE FAT_AGRUPADO (
    EMP_CODIGO VARCHAR(3),
    FAT_CODIGO_ORI VARCHAR(6),
    FAT_CODIGO VARCHAR(6),
    FPC_NUMER VARCHAR(2),
    PRIMARY KEY (EMP_CODIGO, FAT_CODIGO_ORI, FAT_CODIGO, FPC_NUMER)
);

/* issue 1941 */
ALTER TABLE EMP0000 ADD EMP_APLICA_DIVISOR_SIMPLES VARCHAR(1);
COMMENT ON COLUMN EMP0000.EMP_APLICA_DIVISOR_SIMPLES IS 'Aplica divisor no valor de crédito do simples';


