
UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.536 patch 4',
       VERSAOSISTEMA.DATA   = '11.09.2019',
	    VERSAO = '3.0.9.536'
 where VERSAOSISTEMA.CODIGO = 1;

commit work;

Update CLI0000 
Set CLI_DTULTCOM = (SELECT FIRST 1 NF_EMISSAO FROM NF0001 nf WHERE nf_cancelada = 'N' AND nf.CLI_CODIGO = cli0000.CLI_CODIGO ORDER BY NF_EMISSAO DESC )
 ,CLI_VL_ULTCOMP = COALESCE(
                   (SELECT FIRST 1 NF_TOT_PROD + NF_VL_IPI+ NF_VLFRETE+NF_VLSEGURO+  NF_DESP_ACES+NF_VL_SUBTRIB - NF_VL_DESCTO
                    FROM NF0001 nf WHERE nf.CLI_CODIGO = cli0000.CLI_CODIGO ORDER BY NF_EMISSAO DESC ) ,0);
					
commit work;