UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.614',
    VERSAOSISTEMA.DATA   = '27.07.2026',
	VERSAO = '3.0.9.614'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;


/* issue 2246 */
ALTER TABLE BAN0000 ADD BAN_TIPO_DIAS_PROTESTO CHAR(1);
UPDATE BAN0000 SET BAN_TIPO_DIAS_PROTESTO = 'C' WHERE BAN_TIPO_DIAS_PROTESTO IS NULL;
commit work;

/* issue 2229 */
ALTER TABLE CLI0000 ALTER CLI_UND_CONSUMIDORA TYPE BIGINT;
ALTER TABLE PED0000 ALTER PED_UND_CONSUMIDORA TYPE BIGINT;
ALTER TABLE FAT_PC01 ALTER PED_UND_CONSUMIDORA TYPE BIGINT;

/* issue 2176 */
ALTER TABLE CLI0000 ADD CLI_RECORRENTE VARCHAR(1);
ALTER TABLE CLI0000 ADD CLI_DATA_ULTIMA_PARCELA TIMESTAMP;

