UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.576 patch 3',
    VERSAOSISTEMA.DATA   = '30.01.2023',
	VERSAO = '3.0.9.576'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;


COMMENT ON COLUMN TIPO_MOLA.MMO_TIPO  is '[C] Compressão | [R] Tração | [O] Torção | [D] Condutor';

ALTER TABLE TIPO_MOLA ADD MMO_DIAMETRO_MEDIO_MEIO VARCHAR(1) DEFAULT 'N';´
COMMENT ON COLUMN TIPO_MOLA.MMO_DIAMETRO_MEDIO_MEIO  is 'Diâmetro Médio do Meio';

ALTER TABLE MOLA_MATERIA ADD MMO_DIAMETRO_MEDIO_MEIO NUMERIC (18, 5);
ALTER TABLE MOLA_MATERIA ADD MMO_DIAMETRO_MEDIO_MEIO_MIN NUMERIC (18, 5);
ALTER TABLE MOLA_MATERIA ADD MMO_DIAMETRO_MEDIO_MEIO_MAX NUMERIC (18, 5);


CREATE GENERATOR GEN_HISTORICO_EMAIL;
CREATE TABLE HISTORICO_EMAIL (
	HEM_CODIGO INT PRIMARY KEY NOT NULL
);
COMMENT ON COLUMN HISTORICO_EMAIL.HEM_CODIGO is 'Chave primária do Histórico de eMail';
ALTER TABLE HISTORICO_EMAIL ADD HEM_MODULO VARCHAR(255);
COMMENT ON COLUMN HISTORICO_EMAIL.HEM_MODULO is 'Módulo proveniente do histórico';
ALTER TABLE HISTORICO_EMAIL ADD HEM_DESTINATARIO VARCHAR(255);
COMMENT ON COLUMN HISTORICO_EMAIL.HEM_DESTINATARIO is 'Destinatário do eMail';
ALTER TABLE HISTORICO_EMAIL ADD HEM_TITULO VARCHAR(255);
COMMENT ON COLUMN HISTORICO_EMAIL.HEM_TITULO is 'Descrição do Registro do Módulo ';
ALTER TABLE HISTORICO_EMAIL ADD HEM_CLI_FOR VARCHAR(1);
COMMENT ON COLUMN HISTORICO_EMAIL.HEM_CLI_FOR is 'Tipo: [C] Cliente ou [F] Fornecedor';
ALTER TABLE HISTORICO_EMAIL ADD CLI_FOR_CODIGO VARCHAR(5);
COMMENT ON COLUMN HISTORICO_EMAIL.CLI_FOR_CODIGO is 'Código do Cliente / Fornecedor';
ALTER TABLE HISTORICO_EMAIL ADD HEM_DATA_ENVIO TIMESTAMP;
COMMENT ON COLUMN HISTORICO_EMAIL.HEM_DATA_ENVIO is 'Data e Hora do Envio do eMail';
ALTER TABLE HISTORICO_EMAIL ADD USU_CODIGO INTEGER;
COMMENT ON COLUMN HISTORICO_EMAIL.USU_CODIGO is 'Usuário que enviou o eMail';
ALTER TABLE HISTORICO_EMAIL ADD EMP_CODIGO VARCHAR(3);
COMMENT ON COLUMN HISTORICO_EMAIL.EMP_CODIGO is 'Empresa que enviou o eMail';
ALTER TABLE HISTORICO_EMAIL ADD HEM_ANEXO VARCHAR(1024);
COMMENT ON COLUMN HISTORICO_EMAIL.HEM_ANEXO is 'Caminho do Anexo Enviado';
