UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.612',
    VERSAOSISTEMA.DATA   = '05.03.2026',
	VERSAO = '3.0.9.612'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

/* issues 2171*/

ALTER TABLE EMP0000 ADD PMT_VALIDA_VERSAO VARCHAR(1) DEFAULT 'S';
ALTER TABLE EMP0000 ADD PMT_CAMINHO_API VARCHAR(1000);
UPDATE EMP0000 SET PMT_VALIDA_VERSAO = 'S' WHERE PMT_VALIDA_VERSAO IS NULL;
UPDATE EMP0000 SET PMT_CAMINHO_API = 'https://api.compacta9.com.br' WHERE PMT_CAMINHO_API IS NULL;