UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.571 patch 4',
    VERSAOSISTEMA.DATA   = '26.08.2022',
	VERSAO = '3.0.9.571'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE PRD0000 ADD PRD_DESCONTO_TEMP NUMERIC(18,5);
UPDATE PRD0000 SET PRD_DESCONTO_TEMP = PRD_DESCONTO;
ALTER TABLE PRD0000 DROP PRD_DESCONTO; 
ALTER TABLE PRD0000 ALTER COLUMN PRD_DESCONTO_TEMP TO PRD_DESCONTO;
commit work;