
UPDATE  VERSAOSISTEMA SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.507',
       VERSAOSISTEMA.DATA   = '16.04.2018'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;


CREATE INDEX PED_IT01_IDX2 ON PED_IT01 (PRF_REGISTRO_VINCULADO);
COMMIT WORK;

ALTER TABLE PRMT0001 ADD PMT_HABILITAR_CODORIGINAL VARCHAR(1);
COMMENT ON COLUMN PRMT0001.PMT_UTILIZA_CODIGO_ORIG_VD_NF IS 'UTILIZAR CODIGO ORIGINAL NO PEDIDO E NA NOTA FISCAL';
COMMENT ON COLUMN PRMT0001.PMT_HABILITAR_CODORIGINAL IS  'HABILITAR DIGITACAO DE CODIGO ORIGINAL NO PEDIDO';
COMMIT WORK;

UPDATE PRMT0001 SET PMT_HABILITAR_CODORIGINAL = 'N';
COMMIT WORK;

ALTER TABLE PED_IT01 ADD PRF_PRAZO_DIAS INTEGER;
COMMIT WORK;
COMMENT ON COLUMN PED_IT01.PRF_PRAZO_DIAS IS 'PRAZO DE ENTREGAS DO ITEM EM DIAS';
COMMIT WORK;

ALTER TABLE PRMT0001 ADD PMT_PRAZO_ITEM  VARCHAR(1); 
COMMIT WORK;

COMMENT ON COLUMN PRMT0001.PMT_PRAZO_ITEM IS 'UTILIZA PRAZO POR ITEM';
COMMIT WORK;

UPDATE PRMT0001 SET PMT_PRAZO_ITEM = 'N';
COMMIT WORK;


ALTER TABLE USUARIO_PARAMETRO ADD USP_VIZUALIZAR_COMISSOES VARCHAR(1);
COMMIT WORK;

COMMENT ON COLUMN USUARIO_PARAMETRO.USP_VIZUALIZAR_COMISSOES IS 'VISUALIZAR COMISSOES DO PEDIDO';

COMMIT WORK;

UPDATE USUARIO_PARAMETRO SET USP_VIZUALIZAR_COMISSOES = 'S';


CREATE OR ALTER VIEW USUARIO_TUDO_VIEW (USP_REGISTRO, USP_COD_USUARIO, USP_STAT_PRECO_BRUTO_P, USP_STAT_PRECO_LIQUIDO_P, USP_STAT_DESC_AUTOMATICO_P, USP_DESCONTO_MAX_P, USP_REEMISSAO_PEDIDO_P, USP_EXCLUSAO_PEDIDO_P, USP_STAT_PRECO_BRUTO_T, USP_STAT_PRECO_LIQUIDO_T, USP_STAT_DESC_AUTOMATICO_T, USP_DESCONTO_MAX_T, USP_REEMISSAO_PEDIDO_T, USP_EXCLUSAO_PEDIDO_T, USP_STAT_COMISSAO, USP_STAT_CUSTO, USP_STAT_MARGEM, USP_STAT_PRECO_VENDA, USP_STAT_MARGEM_MINIMA, USP_STAT_PRECO_OFERTA, USP_ALTERA_DESCONTO_P, USP_ALTERA_DESCONTO_T, USP_DESCONTO_OFERTA_P, USP_DESCONTO_OFERTA_T, USP_ALTERA_NF_ENTRADA, USP_RELATORIOS_P, USP_VISUALIZA_PEDIDOS_P, USP_ALTERA_COMISSAO, USP_KARDEX_LANC_ENTRADA, USP_KARDEX_LANC_SAIDA, USP_KARDEX_LANC_BALANCO, USP_LIBERA_ANALISE_CREDITO, USP_LIBERA_ANALISE_PRODUCAO, USP_VENDA_CADASTRO_PRODUTO, USP_VENDA_REAJUSTE, USP_VISUALIZA_CLIENTES_P, USP_VISUALIZA_ANALISE_CREDITO_, USP_ALTERA_CUSTOS_PRODUTO, USP_VISUALIZA_MARKUP_PEDIDO, USP_VENDA_TRANSFERENCIA, USP_ALTERA_TABELA_PRECOS, USP_USAPRAZODESABILITADO, LIBERA_COLABORADOR, PERMITE_VER_CUSTO, PERMITE_VENDA_ABAIXO_CUSTO, USP_VIZUALIZAR_COMISSOES, USU_CODIGO, USU_DATA_CADASTRO, USU_DATA_ATUALIZACAO, USU_NOME, USU_SENHA, USU_TIPO_USUARIO, USU_LIBERA_CREDITO, USU_LIBERA_PRECO, USU_LIBERA_DESCONTO, USU_MENU01, USU_MENU02, USU_MENU03, USU_MENU04, USU_MENU05, USU_MENU06, USU_MENU07, USU_MENU08, USU_MENU09, USU_MENU010, USU_MENU011, USU_MENU012, USU_MENU013, USU_MENU014, USU_MENU015, USU_INCLUSAO, USU_ALTERACAO, USU_EXCLUSAO, USU_ESTATISTICA, USU_LOGIN, USU_EMAIL, USU_REEMISSAO_PED, REP_CODIGO, USU_RELATORIO)
AS
select USP_REGISTRO, USP_COD_USUARIO, USP_STAT_PRECO_BRUTO_P, USP_STAT_PRECO_LIQUIDO_P, USP_STAT_DESC_AUTOMATICO_P, USP_DESCONTO_MAX_P, USP_REEMISSAO_PEDIDO_P, USP_EXCLUSAO_PEDIDO_P, USP_STAT_PRECO_BRUTO_T, USP_STAT_PRECO_LIQUIDO_T, USP_STAT_DESC_AUTOMATICO_T, USP_DESCONTO_MAX_T, USP_REEMISSAO_PEDIDO_T, USP_EXCLUSAO_PEDIDO_T, USP_STAT_COMISSAO, USP_STAT_CUSTO, USP_STAT_MARGEM, USP_STAT_PRECO_VENDA, USP_STAT_MARGEM_MINIMA, USP_STAT_PRECO_OFERTA, USP_ALTERA_DESCONTO_P, USP_ALTERA_DESCONTO_T, USP_DESCONTO_OFERTA_P, USP_DESCONTO_OFERTA_T, USP_ALTERA_NF_ENTRADA, USP_RELATORIOS_P, USP_VISUALIZA_PEDIDOS_P, USP_ALTERA_COMISSAO, USP_KARDEX_LANC_ENTRADA, USP_KARDEX_LANC_SAIDA, USP_KARDEX_LANC_BALANCO, USP_LIBERA_ANALISE_CREDITO, USP_LIBERA_ANALISE_PRODUCAO, USP_VENDA_CADASTRO_PRODUTO, USP_VENDA_REAJUSTE, USP_VISUALIZA_CLIENTES_P, USP_VISUALIZA_ANALISE_CREDITO_, USP_ALTERA_CUSTOS_PRODUTO, USP_VISUALIZA_MARKUP_PEDIDO, USP_VENDA_TRANSFERENCIA, USP_ALTERA_TABELA_PRECOS, USP_USAPRAZODESABILITADO, LIBERA_COLABORADOR, PERMITE_VER_CUSTO, PERMITE_VENDA_ABAIXO_CUSTO, USP_VIZUALIZAR_COMISSOES, USU_CODIGO, USU_DATA_CADASTRO, USU_DATA_ATUALIZACAO, USU_NOME, USU_SENHA, USU_TIPO_USUARIO, USU_LIBERA_CREDITO, USU_LIBERA_PRECO, USU_LIBERA_DESCONTO, USU_MENU01, USU_MENU02, USU_MENU03, USU_MENU04, USU_MENU05, USU_MENU06, USU_MENU07, USU_MENU08, USU_MENU09, USU_MENU010, USU_MENU011, USU_MENU012, USU_MENU013, USU_MENU014, USU_MENU015, USU_INCLUSAO, USU_ALTERACAO, USU_EXCLUSAO, USU_ESTATISTICA, USU_LOGIN, USU_EMAIL, USU_REEMISSAO_PED, REP_CODIGO, USU_RELATORIO
from USUARIO_PARAMETRO a, usuario c
where c.usu_codigo = a.usp_cod_usuario;


COMMIT WORK;


ALTER TABLE CLI0000 ADD FPG_REGISTRO INTEGER;
COMMIT WORK;

COMMENT ON COLUMN CLI0000.FPG_REGISTRO IS 'CHAVE REFERENCIA A FORMA PAGAMENTO';
COMMIT WORK;

COMMENT ON COLUMN PED0000.FPG_REGISTRO IS 'CHAVE REFERENCIA A FORMA PAGAMENTO';                        
COMMENT ON COLUMN FORMA_PAGAMENTO.FPG_REGISTRO IS 'CHAVE REFERENCIA A FORMA PAGAMENTO';
COMMENT ON COLUMN PAG_PAGAMENTO.FPG_REGISTRO IS 'CHAVE REFERENCIA A FORMA PAGAMENTO';                  


COMMIT WORK;

/* ATUALIZAR TODAS OS ITENS CUJO PRD_CODIGO ESTÁ NULO, FAZENDO UM PESQUISA NA BSC, jupter A MAIOR É ANTES DE MAIO DE 2017, PODE TER SIDO ALGUM PROBLEMA NO PASSADO QUE JA FOI AJUSTADO  */
UPDATE PED_IT01
SET PRD_CODIGO = (SELECT MAX(PRD_CODIGO)  FROM PRD0000 PR  WHERE PR.PRD_REFER = PED_IT01.PRD_REFER)
WHERE PRD_CODIGO IS NULL
AND PRD_REFER IS NOT NULL AND PRD_REFER <> '0';

COMMIT WORK;


UPDATE PED_IT01
SET PRD_REFER = (SELECT MAX(PRD_REFER)  FROM PRD0000 PR  WHERE PR.PRD_CODIGO = PED_IT01.PRD_CODIGO)
WHERE ( PRD_REFER IS NULL OR PRD_REFER = '')
AND PRD_CODIGO IS NOT NULL AND PRF_REGISTRO_VINCULADO > 0 ;


COMMIT WORK;