UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.580 patch 1',
    VERSAOSISTEMA.DATA   = '04.05.2023',
	VERSAO = '3.0.9.580'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE PED_IND_KIT ADD ENF_REGISTRO INTEGER DEFAULT 0;

