UPDATE  VERSAOSISTEMA 
SET    VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.525 PATCH 4 ',
       VERSAOSISTEMA.DATA   = '07.01.2019',
       VERSAO = '3.0.9.525'
where VERSAOSISTEMA.CODIGO = 1;

ALTER TABLE USUARIO_PARAMETRO ADD usp_permite_excluir_itens VARCHAR(1);

UPDATE USUARIO_PARAMETRO
SET USP_PERMITE_EXCLUIR_ITENS = 'S';


CREATE OR ALTER VIEW USUARIO_TUDO_VIEW (USP_REGISTRO, USP_COD_USUARIO, USP_STAT_PRECO_BRUTO_P, USP_STAT_PRECO_LIQUIDO_P, USP_STAT_DESC_AUTOMATICO_P, USP_DESCONTO_MAX_P, USP_REEMISSAO_PEDIDO_P, USP_EXCLUSAO_PEDIDO_P, USP_STAT_PRECO_BRUTO_T, USP_STAT_PRECO_LIQUIDO_T, USP_STAT_DESC_AUTOMATICO_T, USP_DESCONTO_MAX_T, USP_REEMISSAO_PEDIDO_T, USP_EXCLUSAO_PEDIDO_T, USP_STAT_COMISSAO, USP_STAT_CUSTO, USP_STAT_MARGEM, USP_STAT_PRECO_VENDA, USP_STAT_MARGEM_MINIMA, USP_STAT_PRECO_OFERTA, USP_ALTERA_DESCONTO_P, USP_ALTERA_DESCONTO_T, USP_DESCONTO_OFERTA_P, USP_DESCONTO_OFERTA_T, USP_ALTERA_NF_ENTRADA, USP_RELATORIOS_P, USP_VISUALIZA_PEDIDOS_P, USP_ALTERA_COMISSAO, USP_KARDEX_LANC_ENTRADA, USP_KARDEX_LANC_SAIDA, USP_KARDEX_LANC_BALANCO, USP_LIBERA_ANALISE_CREDITO, USP_LIBERA_ANALISE_PRODUCAO, USP_VENDA_CADASTRO_PRODUTO, USP_VENDA_REAJUSTE, USP_VISUALIZA_CLIENTES_P, USP_VISUALIZA_ANALISE_CREDITO_, USP_ALTERA_CUSTOS_PRODUTO, USP_VISUALIZA_MARKUP_PEDIDO, USP_VENDA_TRANSFERENCIA, USP_ALTERA_TABELA_PRECOS, USP_USAPRAZODESABILITADO, LIBERA_COLABORADOR, PERMITE_VER_CUSTO, PERMITE_VENDA_ABAIXO_CUSTO, USP_VIZUALIZAR_COMISSOES, USU_CODIGO, USU_DATA_CADASTRO, USU_DATA_ATUALIZACAO, USU_NOME, USU_SENHA, USU_TIPO_USUARIO, USU_LIBERA_CREDITO, USU_LIBERA_PRECO, USU_LIBERA_DESCONTO, USU_MENU01, USU_MENU02, USU_MENU03, USU_MENU04, USU_MENU05, USU_MENU06, USU_MENU07, USU_MENU08, USU_MENU09, USU_MENU010, USU_MENU011, USU_MENU012, USU_MENU013, USU_MENU014, USU_MENU015, USU_INCLUSAO, USU_ALTERACAO, USU_EXCLUSAO, USU_ESTATISTICA, USU_LOGIN, USU_EMAIL, USU_REEMISSAO_PED, REP_CODIGO, USU_RELATORIO,usp_permite_excluir_itens)
AS
select USP_REGISTRO, USP_COD_USUARIO, USP_STAT_PRECO_BRUTO_P, USP_STAT_PRECO_LIQUIDO_P, USP_STAT_DESC_AUTOMATICO_P, USP_DESCONTO_MAX_P, USP_REEMISSAO_PEDIDO_P, USP_EXCLUSAO_PEDIDO_P, USP_STAT_PRECO_BRUTO_T, USP_STAT_PRECO_LIQUIDO_T, USP_STAT_DESC_AUTOMATICO_T, USP_DESCONTO_MAX_T, USP_REEMISSAO_PEDIDO_T, USP_EXCLUSAO_PEDIDO_T, USP_STAT_COMISSAO, USP_STAT_CUSTO, USP_STAT_MARGEM, USP_STAT_PRECO_VENDA, USP_STAT_MARGEM_MINIMA, USP_STAT_PRECO_OFERTA, USP_ALTERA_DESCONTO_P, USP_ALTERA_DESCONTO_T, USP_DESCONTO_OFERTA_P, USP_DESCONTO_OFERTA_T, USP_ALTERA_NF_ENTRADA, USP_RELATORIOS_P, USP_VISUALIZA_PEDIDOS_P, USP_ALTERA_COMISSAO, USP_KARDEX_LANC_ENTRADA, USP_KARDEX_LANC_SAIDA, USP_KARDEX_LANC_BALANCO, USP_LIBERA_ANALISE_CREDITO, USP_LIBERA_ANALISE_PRODUCAO, USP_VENDA_CADASTRO_PRODUTO, USP_VENDA_REAJUSTE, USP_VISUALIZA_CLIENTES_P, USP_VISUALIZA_ANALISE_CREDITO_, USP_ALTERA_CUSTOS_PRODUTO, USP_VISUALIZA_MARKUP_PEDIDO, USP_VENDA_TRANSFERENCIA, USP_ALTERA_TABELA_PRECOS, USP_USAPRAZODESABILITADO, LIBERA_COLABORADOR, PERMITE_VER_CUSTO, PERMITE_VENDA_ABAIXO_CUSTO, USP_VIZUALIZAR_COMISSOES, USU_CODIGO, USU_DATA_CADASTRO, USU_DATA_ATUALIZACAO, USU_NOME, USU_SENHA, USU_TIPO_USUARIO, USU_LIBERA_CREDITO, USU_LIBERA_PRECO, USU_LIBERA_DESCONTO, USU_MENU01, USU_MENU02, USU_MENU03, USU_MENU04, USU_MENU05, USU_MENU06, USU_MENU07, USU_MENU08, USU_MENU09, USU_MENU010, USU_MENU011, USU_MENU012, USU_MENU013, USU_MENU014, USU_MENU015, USU_INCLUSAO, USU_ALTERACAO, USU_EXCLUSAO, USU_ESTATISTICA, USU_LOGIN, USU_EMAIL, USU_REEMISSAO_PED, REP_CODIGO, USU_RELATORIO,usp_permite_excluir_itens
from USUARIO_PARAMETRO a, usuario c
where c.usu_codigo = a.usp_cod_usuario;


ALTER TABLE FAT_PC01 ADD FPC_TARIFA NUMERIC (18,5);
COMMENT ON COLUMN FAT_PC01.FPC_TARIFA IS 'TARIFA BANCARIA';

-- ATUALIZAÇÃO DO CAMPO TARIFA
UPDATE FAT_PC01
SET FPC_TARIFA = COALESCE((SELECT FIRST 1 DCN_TARIFA FROM  DUPLICAT_CNAB DU JOIN ARQUIVO_CNAB AC ON (AC.CNAB_REGISTRO = DCN_COD_REMESSA AND CNAB_LITERAL_ARQUIVO = 'RETORNO') 
                            WHERE DU.DCN_DUPLICATA = FAT_CODIGO AND FPC_NUMER = DU.DCN_DUP_PARCELA),0);

							
UPDATE FAT_PC01
SET FPC_VLPAGO = FPC_VLPAGO + FPC_TARIFA
WHERE FPC_STATUS = 'Liquidada'
AND (FPC_VLPARC +  FPC_JUROS +  FPC_MULTA - FPC_DESCTO ) = (FPC_VLPAGO + FPC_TARIFA )
AND FPC_TARIFA > 0 ;


