UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.613 patch 2',
    VERSAOSISTEMA.DATA   = '30.06.2026',
	VERSAO = '3.0.9.613'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

/* issue 2231 */
ALTER TABLE OPE_REGRA ADD OPR_TIPO_CALCULO_MVA VARCHAR(1) DEFAULT 'F';
COMMENT ON COLUMN OPE_REGRA.OPR_TIPO_CALCULO_MVA IS 'Tipo de calculo da base ST: D = Por Dentro, F = Por Fora';
UPDATE OPE_REGRA SET OPR_TIPO_CALCULO_MVA = 'F' WHERE OPR_TIPO_CALCULO_MVA IS NULL; 
commit work;
