UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.568 patch 4',
    VERSAOSISTEMA.DATA   = '31.05.2022',
	VERSAO = '3.0.9.568'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE ITEM_ORDEMPRODUCAO ADD IOP_OBSERVACAO_PED BLOB SUB_TYPE TEXT;
ALTER TABLE ITEM_ORDEMPRODUCAO ADD IOP_OBSERVACAO_PRD BLOB SUB_TYPE TEXT;



