UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.586 patch 3',
    VERSAOSISTEMA.DATA   = '22.11.2023',
	VERSAO = '3.0.9.586'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE USUARIO_PARAMETRO ADD USP_INCLUI_ITEM_PED_OP_GERADA VARCHAR(1);
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_INCLUI_ITEM_PED_OP_GERADA IS 'Permite incluir itens em pedidos com OP gerada';

ALTER TABLE PED_IT01 ADD PRD_ORIGEM INTEGER;
COMMENT ON COLUMN PED_IT01.PRD_ORIGEM IS 'Origem da Mercadoria, Nacional ou Importada';
UPDATE PED_IT01 pi2 SET PRD_ORIGEM = (SELECT PRD_ORIGEM FROM PRD0000 p WHERE pi2.PRD_CODIGO = p.PRD_CODIGO) WHERE pi2.PRD_ORIGEM IS NULL;
COMMIT WORK;

ALTER TABLE COTACAO_ITEM ADD PCX_CODIGO VARCHAR(3);
COMMENT ON COLUMN COTACAO_ITEM.PCX_CODIGO IS 'Centro de Custo';

INSERT INTO BANCOS VALUES (133, 'CRESOL', '001', 'N');
COMMIT WORK;

ALTER TABLE PRMT0001 ADD PMT_INFORMA_LOTE_NOTA_ENTRADA VARCHAR(1) DEFAULT 'N';

	