
UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.530',
       VERSAOSISTEMA.DATA   = '28.02.2019',
	    VERSAO = '3.0.9.530'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;


ALTER TABLE EMP0000 ALTER column emp_razao TYPE varchar(60);
ALTER TABLE EMP0000 ALTER COLUMN EMP_FANTASIA TYPE VARCHAR(60);
COMMENT ON COLUMN EMP0000.EMP_RAZAO IS 'RAZAO SOCIAL DA EMPRESA/COLOGADA'; 
COMMENT ON COLUMN EMP0000.EMP_BAIRRO IS 'BAIRRO LOCAL DA EMPRESA';
COMMENT ON COLUMN EMP0000.EMP_FANTASIA IS 'NOME FANTASIA DA EMPRESA';
COMMENT ON COLUMN EMP0000.EMP_CEP IS 'CEP DA EMPRESA';
COMMENT ON COLUMN EMP0000.EMP_ENDERE IS 'ENDERECO DA EMPRESA COM NUMERO';
COMMENT ON COLUMN EMP0000.EMP_PERCENT_ISS IS 'ALIQUOTA DE ISS - SERVICO';
COMMENT ON COLUMN EMP0000.EMP_PERCENT_IR IS 'ALIQUOTA DE IR - IMPOSTO DE RENDA - SERVICO';
COMMENT ON COLUMN EMP0000.EMP_PERCENT_COFINS IS 'ALIQUOTA DE CONFINS';
COMMENT ON COLUMN EMP0000.EMP_PERCENT_PIS IS 'ALIQUOTA DE PIS- SERVICO';
COMMENT ON COLUMN EMP0000.EMP_PERCENT_CSLL IS 'ALIQUOTA DE CSLL - SERVICO'; 
COMMENT ON COLUMN EMP0000.EMP_PERCENT_INSS IS 'ALIQUOTA DE INSS - SERVICO';


ALTER TABLE EMP0000 ADD EMP_LOGO_nfe BLOB sub_type 0;
COMMENT ON COLUMN EMP0000.EMP_LOGO_nfe IS 'LOGO SOMENTE DA NFE';
ALTER TABLE EMP0000 ADD EMP_LOGONFE_PROPRIO VARCHAR(1);
COMMENT ON COLUMN EMP0000.EMP_LOGONFE_PROPRIO IS 'INDICADOR DE LOGO PROPRIO';

UPDATE EMP0000
SET EMP_LOGONFE_PROPRIO = 'N';

commit work;


CREATE OR ALTER VIEW LISTA_QTDE_VENDAS_MESANO (PRD_REFER, prd_codigo, MES, ANO, QTD, "REF")
AS
select
    prd.prd_refer,
    prd.prd_codigo,
    extract( month from nf.nf_emissao ) as mes,
    extract( year from nf.nf_emissao ) as ano,
    SUM( itnf.nf_qtde ) as Qtd,
    (extract( year from nf.nf_emissao )*12)+extract( month from nf.nf_emissao ) as Ref
from nf0001 nf
    join nf_it01 itnf on itnf.nf_it_notanumer = nf.nf_notanumber
    join prd0000 prd on prd.prd_codigo=itnf.prd_codigo
    WHERE NF_VENDA_FATURADA = 'S'
group by 1,2,3,4;


CREATE INDEX OSV0001_IDX3 ON OSV0001 (OSV_EMISSAO);



ALTER TABLE USUARIO_PARAMETRO ADD USP_INCLUIR_CLIENTES VARCHAR(1);
ALTER TABLE USUARIO_PARAMETRO ADD USP_ALTERAR_CLIENTES VARCHAR(1);

UPDATE USUARIO_PARAMETRO
SET USP_INCLUIR_CLIENTES = 'S', USP_ALTERAR_CLIENTES = 'S';
COMMIT WORK;

COMMENT ON COLUMN USUARIO_PARAMETRO.USP_INCLUIR_CLIENTES IS 'PERMITE INCLUIR CLIENTES PELA TELA DE CONSULTA: SIM OU NAO';
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_ALTERAR_CLIENTES IS 'PERMITE ALTERAR CLIENTES PELA TELA DE CONSULTA: SIM OU NAO';
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_STAT_PRECO_BRUTO_P IS 'PERMITE ALTERAR PRECO BRUTO';
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_STAT_PRECO_LIQUIDO_P IS 'PERMITE ALTERAR PRECO LIQUIDO: SIM OU NAO';
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_RELATORIOS_P IS 'ACESSO AOS RELATORIOS DO PEDIDO: SIM NAO';
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_REEMISSAO_PEDIDO_P IS 'PERMITE REEMISSAO DO PEDIDO DE VENDA: SIM OU NAO';
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_EXCLUSAO_PEDIDO_P IS 'PERMITE A EXCLUSAO DO PEDIDO DE VENDA: SIM OU NAO';
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_ALTERA_DESCONTO_P IS 'PERMITE ALTERAR DESCONTO NO PEDIDO DE VENDA : SIM OU NAO';
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_VENDA_CADASTRO_PRODUTO IS 'PERMITE CADASTRA PRODUTO NO PEDIDO DE VENDA: SIM OU NAO';
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_VENDA_REAJUSTE IS 'HABILITA FUNCAO REAJUSTE NO PEDIDO: SIM OU NAO';
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_ALTERA_TABELA_PRECOS IS 'ALTERAR TABELA DE PRECOS: SIM OU NAO';
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_DESCONTO_MAX_P IS 'PERCENTUAL DE DESCONTO MAXIMO NO ITEM DO PEDIDO DE VENDA';
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_VISUALIZA_PEDIDOS_P IS 'VISUALIZA SOMENTE PEDIDOS DO USUARIO: SIM OU NAO';
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_ALTERA_COMISSAO IS 'PERMITE ALTERAR COMISSAO NO ITEM DO PEDIDO: SIM OU NAO';
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_LIBERA_ANALISE_CREDITO IS 'GERENCIAL: LIBERA ANALISE DE CREDITO: SIM OU NAO';
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_LIBERA_ANALISE_PRODUCAO IS 'GERENCIAL : LIBERA ANALISE DE PRODUCAO: SIM OU NAO';
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_VISUALIZA_CLIENTES_P IS 'VISUALIZA CLIENTE SOMENTE DO USUARIO : SIM OU NAO';
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_VISUALIZA_ANALISE_CREDITO_ IS 'PERMITE VISUALIZAR ANALISE DE CREDITO : SIM OU NAO';
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_VENDA_TRANSFERENCIA IS 'PERMITE FAZER TRANSFERENCIAS DE MERCADORIAS: SIM OU NAO';
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_VIZUALIZAR_COMISSOES IS 'PERMITE VER COMISSOES DO PEDIDO : SIM OU NAO';
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_PERMITE_EXCLUIR_ITENS IS 'PERMITE EXCLUIR ITEM DO PEDIDO DE VENDA: SIM OU NAO';
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_STAT_COMISSAO IS 'PERMITE ALTERAR COMISSAO NO CADASTRO DE PRODUTO: SIM OU NAO';
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_STAT_CUSTO IS 'PERMITE ALTERAR CUSTO LIQUIDO NO CADASTRO DE PRODUTO: SIM OU NAO';
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_STAT_MARGEM IS 'PERMITE ALTERAR A MARGEM NO CADASTRO DE PRODUTO: SIM OU NAO';
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_STAT_PRECO_VENDA IS 'PERMITE ALTERAR O PRECO DE VENDA NO CADASTRO DE PRODUTOS : SIM OU NAO';
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_STAT_MARGEM_MINIMA IS 'PERMITE ALTERAR A MARGEM MINIMA NO CADASTRO DE PRODUTOS : SIM OU NAO'; 
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_STAT_PRECO_OFERTA IS 'PERMITE ALTERAR O PRECO DE OFERTA NO CADASTRO DE PRODUTOS';
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_ALTERA_NF_ENTRADA IS 'PERMITE ALTERAR A NF DE ENTRATADA : SIM OU NAO';
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_KARDEX_LANC_ENTRADA IS 'PERMITE A ENTRADA MANUAL NO KARDEX: SIM OU NAO';
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_KARDEX_LANC_SAIDA IS 'PERMITE A SAIDA MANUAL DO KARDEX: SIM OU NAO'; 
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_KARDEX_LANC_BALANCO IS 'PERMITE O BALANCO MANUAL NO KARDEX';
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_VISUALIZA_MARKUP_PEDIDO IS 'PERMITE VISUALIZAR O MARKUP NO PEDIDO';
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_USAPRAZODESABILITADO IS 'PODE USAR PRAZOS DESABILITADO';
COMMENT ON COLUMN USUARIO_PARAMETRO.LIBERA_COLABORADOR IS  'PERMITE VER OS DADOS DO COLABORADOR NO CADASTRO DE FORNECEDOR';
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_ALTERA_CUSTOS_PRODUTO IS 'PERMITE ALTERAR CUSTOS CALCULADOS PELO SISTEMA: SIM OU NAO';
COMMENT ON COLUMN USUARIO_PARAMETRO.PERMITE_VER_CUSTO IS 'PERMITE VISUALIZAR PRECOS DE CUSTOS: SIM OU NAO';
COMMENT ON COLUMN USUARIO_PARAMETRO.PERMITE_VENDA_ABAIXO_CUSTO IS 'PERMITE VENDER ABAIXO DO CUSTO DE VENDA: SIM OU NAO';


CREATE OR ALTER VIEW USUARIO_TUDO_VIEW (USP_REGISTRO, USP_COD_USUARIO, USP_STAT_PRECO_BRUTO_P, USP_STAT_PRECO_LIQUIDO_P, USP_STAT_DESC_AUTOMATICO_P, USP_DESCONTO_MAX_P, USP_REEMISSAO_PEDIDO_P, 
USP_EXCLUSAO_PEDIDO_P, USP_STAT_PRECO_BRUTO_T, USP_STAT_PRECO_LIQUIDO_T, USP_STAT_DESC_AUTOMATICO_T, USP_DESCONTO_MAX_T, USP_REEMISSAO_PEDIDO_T, USP_EXCLUSAO_PEDIDO_T, USP_STAT_COMISSAO, 
USP_STAT_CUSTO, USP_STAT_MARGEM, USP_STAT_PRECO_VENDA, USP_STAT_MARGEM_MINIMA, USP_STAT_PRECO_OFERTA, USP_ALTERA_DESCONTO_P, USP_ALTERA_DESCONTO_T, USP_DESCONTO_OFERTA_P, USP_DESCONTO_OFERTA_T, 
USP_ALTERA_NF_ENTRADA, USP_RELATORIOS_P, USP_VISUALIZA_PEDIDOS_P, USP_ALTERA_COMISSAO, USP_KARDEX_LANC_ENTRADA, USP_KARDEX_LANC_SAIDA, USP_KARDEX_LANC_BALANCO, USP_LIBERA_ANALISE_CREDITO, 
USP_LIBERA_ANALISE_PRODUCAO, USP_VENDA_CADASTRO_PRODUTO, USP_VENDA_REAJUSTE, USP_VISUALIZA_CLIENTES_P, USP_VISUALIZA_ANALISE_CREDITO_, USP_ALTERA_CUSTOS_PRODUTO, USP_VISUALIZA_MARKUP_PEDIDO, 
USP_VENDA_TRANSFERENCIA, USP_ALTERA_TABELA_PRECOS, USP_USAPRAZODESABILITADO, LIBERA_COLABORADOR, PERMITE_VER_CUSTO, PERMITE_VENDA_ABAIXO_CUSTO, USP_VIZUALIZAR_COMISSOES, USU_CODIGO, 
USU_DATA_CADASTRO, USU_DATA_ATUALIZACAO, USU_NOME, USU_SENHA, USU_TIPO_USUARIO, USU_LIBERA_CREDITO, USU_LIBERA_PRECO, USU_LIBERA_DESCONTO, USU_MENU01, USU_MENU02, USU_MENU03, 
USU_MENU04, USU_MENU05, USU_MENU06, USU_MENU07, USU_MENU08, USU_MENU09, USU_MENU010, USU_MENU011, USU_MENU012, USU_MENU013, USU_MENU014, USU_MENU015, USU_INCLUSAO, USU_ALTERACAO, 
USU_EXCLUSAO, USU_ESTATISTICA,
USU_LOGIN, USU_EMAIL, USU_REEMISSAO_PED, REP_CODIGO, USU_RELATORIO, USP_PERMITE_EXCLUIR_ITENS,USP_INCLUIR_CLIENTES,USP_ALTERAR_CLIENTES)
AS
select USP_REGISTRO, USP_COD_USUARIO, USP_STAT_PRECO_BRUTO_P, USP_STAT_PRECO_LIQUIDO_P, USP_STAT_DESC_AUTOMATICO_P, USP_DESCONTO_MAX_P, USP_REEMISSAO_PEDIDO_P, USP_EXCLUSAO_PEDIDO_P, USP_STAT_PRECO_BRUTO_T,
USP_STAT_PRECO_LIQUIDO_T, USP_STAT_DESC_AUTOMATICO_T, USP_DESCONTO_MAX_T, USP_REEMISSAO_PEDIDO_T, USP_EXCLUSAO_PEDIDO_T, USP_STAT_COMISSAO, USP_STAT_CUSTO, USP_STAT_MARGEM, USP_STAT_PRECO_VENDA,
USP_STAT_MARGEM_MINIMA, USP_STAT_PRECO_OFERTA, USP_ALTERA_DESCONTO_P, USP_ALTERA_DESCONTO_T, USP_DESCONTO_OFERTA_P, USP_DESCONTO_OFERTA_T, USP_ALTERA_NF_ENTRADA, USP_RELATORIOS_P, USP_VISUALIZA_PEDIDOS_P,
USP_ALTERA_COMISSAO, USP_KARDEX_LANC_ENTRADA, USP_KARDEX_LANC_SAIDA, USP_KARDEX_LANC_BALANCO, USP_LIBERA_ANALISE_CREDITO, USP_LIBERA_ANALISE_PRODUCAO, USP_VENDA_CADASTRO_PRODUTO, USP_VENDA_REAJUSTE, 
USP_VISUALIZA_CLIENTES_P, USP_VISUALIZA_ANALISE_CREDITO_, USP_ALTERA_CUSTOS_PRODUTO, USP_VISUALIZA_MARKUP_PEDIDO, USP_VENDA_TRANSFERENCIA, USP_ALTERA_TABELA_PRECOS, USP_USAPRAZODESABILITADO, 
LIBERA_COLABORADOR, PERMITE_VER_CUSTO, PERMITE_VENDA_ABAIXO_CUSTO, USP_VIZUALIZAR_COMISSOES, USU_CODIGO, USU_DATA_CADASTRO, USU_DATA_ATUALIZACAO, USU_NOME, USU_SENHA, USU_TIPO_USUARIO, 
USU_LIBERA_CREDITO, USU_LIBERA_PRECO, USU_LIBERA_DESCONTO, USU_MENU01, USU_MENU02, USU_MENU03, USU_MENU04, USU_MENU05, USU_MENU06, USU_MENU07, USU_MENU08, USU_MENU09, USU_MENU010, 
USU_MENU011, USU_MENU012, USU_MENU013, USU_MENU014, USU_MENU015, USU_INCLUSAO, USU_ALTERACAO, USU_EXCLUSAO, USU_ESTATISTICA, USU_LOGIN, USU_EMAIL, USU_REEMISSAO_PED, REP_CODIGO, 
USU_RELATORIO,usp_permite_excluir_itens, USP_INCLUIR_CLIENTES,USP_ALTERAR_CLIENTES
from USUARIO_PARAMETRO a, usuario c
where c.usu_codigo = a.usp_cod_usuario;



ALTER TABLE OPE_REGRA ADD OPR_ORIGEM VARCHAR(1);
COMMENT ON COLUMN OPE_REGRA.OPR_ORIGEM IS 'ORIGEM DA MERCADORIA : N - NACIONAL; E  - ESTRANGEIRA ; I - INDIFERENTE ';
UPDATE OPE_REGRA SET OPR_ORIGEM = 'I'; 

commit work;

CREATE INDEX NF0001_IDX3 ON NF0001 (NF_VENDA_FATURADA);
CREATE INDEX NF_IT01_IDX2 ON NF_IT01 (PRD_CODIGO);
CREATE INDEX ENF_IT01_IDX4 ON ENF_IT01 (PRD_CODIGO);

