SET TERM ^ ;

ALTER TABLE EMP0000 ADD EMP_REQUER_CONEXAO_TLS CHAR(1)^
alter table ban0000 add ban_convenio varchar(15) ^
COMMIT WORK^

Update VERSAOSISTEMA SET
       VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.0.462' ,
       VERSAOSISTEMA.DATA   = '10.10.2016'
 where VERSAOSISTEMA.CODIGO = 1^

COMMIT WORK^

SET TERM ; ^





