UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.575 patch 2',
    VERSAOSISTEMA.DATA   = '08.12.2022',
	VERSAO = '3.0.9.575'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

CREATE TABLE IOP_RESERVA_PREFIXO (IOP_PREFIXO VARCHAR(20));

ALTER TABLE PRMT0001 ADD PMT_LANCA_PERC_MATERIA_PRIMA VARCHAR(1);
COMMENT ON COLUMN PRMT0001.PMT_LANCA_PERC_MATERIA_PRIMA  is 'Permite fazer lançamento na ficha técnica em percentual de consumo por matéria-prima';
UPDATE PRMT0001 SET PMT_LANCA_PERC_MATERIA_PRIMA = 'N' WHERE PMT_LANCA_PERC_MATERIA_PRIMA IS NULL;
COMMIT WORK;
ALTER TABLE FTC_IT01 ADD FTI_PERCENTUAL NUMERIC(18,5) DEFAULT 0;
COMMENT ON COLUMN FTC_IT01.FTI_PERCENTUAL  is 'Lançamento na ficha técnica em percentual de consumo por matéria-prima';
UPDATE FTC_IT01 SET FTI_PERCENTUAL = 0;
COMMIT WORK;

ALTER TABLE BAN0000 ADD BAN_TIPO_JUROS CHAR(1) DEFAULT '1';
COMMENT ON COLUMN BAN0000.BAN_TIPO_JUROS  is '1 - Valor Por Dia | 2 - Taxa Mensal | 3 - Isento';
UPDATE BAN0000 SET BAN_TIPO_JUROS = '1';


