UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.546 patch 7',
    VERSAOSISTEMA.DATA   = '30.07.2020',
	VERSAO = '3.0.9.546'
 where VERSAOSISTEMA.CODIGO = 1;

COMMIT WORK;

ALTER TABLE PRECOS0001 ADD PRE_DATAAJUSTE TIMESTAMP;
COMMENT ON COLUMN PRECOS0001.PRE_DATAAJUSTE IS 'DATA DE AJUSTE';
 
ALTER TABLE ORDEM_PROGRAMADA ADD OPA_DATA_FABRICACAO TIMESTAMP; 
ALTER TABLE ORDEM_PROGRAMADA ADD OPA_DATA_AJUSTADA TIMESTAMP;   
ALTER TABLE ORDEM_PROGRAMADA ADD OPA_DIAS_CORRIDOS INTEGER;
ALTER TABLE ORDEM_PROGRAMADA ADD OPA_STATUS VARCHAR(1);

COMMENT ON COLUMN ORDEM_PROGRAMADA.OPA_DATA_FABRICACAO IS 'DATA DE CONCLUSAO; FABRICACAO';
COMMENT ON COLUMN ORDEM_PROGRAMADA.OPA_DATA_AJUSTADA IS 'DATA DE AJUSTE DE ENTREGA';
COMMENT ON COLUMN ORDEM_PROGRAMADA.OPA_DIAS_CORRIDOS IS 'DIAS QUE DEMOROU PARA ENTREGAR';
COMMENT ON COLUMN ORDEM_PROGRAMADA.OPA_STATUS IS 'A - ATRASADO;  T - ANTECIPADO ; P - NO PRAZO';


UPDATE ORDEM_PROGRAMADA
SET OPA_DATA_AJUSTADA = OPA_DATA_ENTREGA;

COMMIT WORK;

UPDATE ORDEM_PROGRAMADA orp
SET IOP_CODIGO = (SELECT IOP_CODIGO 
                    FROM ITEM_ORDEMPRODUCAO iop 
                    JOIN ORDEMPRODUCAO opr ON (opr.OPR_CODIGO = iop.OPR_CODIGO)
                   WHERE iop.PRD_CODIGO = orp.PRD_CODIGO 
                     AND opr.PED_CODIGO = orp.PED_CODIGO
                     AND OPA_SEQUENCIAL = iop_seq_prg );
COMMIT WORK;


UPDATE ORDEM_PROGRAMADA orp
SET OPA_DATA_FABRICACAO = (SELECT IOP_DATA_CONCLUSAO 
                             FROM ITEM_ORDEMPRODUCAO iop
                             WHERE iop.IOP_CODIGO = orp.IOP_CODIGO AND iop.IOP_STATUS = 'F'); 
COMMIT WORK;


ALTER TABLE ITEM_ORDEMPRODUCAO ADD IOP_DATA_AJUSTADA TIMESTAMP;   
ALTER TABLE ITEM_ORDEMPRODUCAO ADD IOP_DIAS_CORRIDOS INTEGER;
ALTER TABLE ITEM_ORDEMPRODUCAO ADD IOP_STATUS_ENTREGA VARCHAR(1);

COMMENT ON COLUMN ITEM_ORDEMPRODUCAO.IOP_DATA_AJUSTADA IS 'DATA DE AJUSTE DE ENTREGA';
COMMENT ON COLUMN ITEM_ORDEMPRODUCAO.IOP_DIAS_CORRIDOS IS 'DIAS QUE DEMOROU PARA ENTREGAR';
COMMENT ON COLUMN ITEM_ORDEMPRODUCAO.IOP_STATUS_ENTREGA IS 'A - ATRASADO;   P - NO PRAZO';


UPDATE ITEM_ORDEMPRODUCAO
SET   iop_data_ajustada = coalesce(iop_data_ajustada, CAST(IOP_DTENTREGA AS TIMESTAMP) ) ;
commit work;

UPDATE ITEM_ORDEMPRODUCAO
SET  iop_dias_corridos = datediff(DAY FROM iop_data_conclusao TO iop_data_ajustada )
    , iop_status_entrega =  IIF ( datediff(DAY FROM iop_data_conclusao TO iop_data_ajustada ) >= 0,'P','A')					       
WHERE iop_status = 'F'
AND  iop_data_conclusao IS NOT NULL;

commit work;    


ALTER TABLE PRMT0001 ADD PMT_ENVASE_SBAIXA VARCHAR(1);
COMMENT ON COLUMN PRMT0001.PMT_ENVASE_SBAIXA IS 'AUTORIZA CONCLUIR ENVASE SEM ESTOQUE';

UPDATE PRMT0001
SET PMT_ENVASE_SBAIXA = 'N';

commit work;

ALTER TABLE PRD0000 ADD PRD_ENVASE VARCHAR(1);
COMMENT ON COLUMN PRD0000.PRD_ENVASE IS 'PRODUTO VAI PARA ENVASE';

UPDATE PRD0000
SET prd_envase = 'N';

commit work;

ALTER TABLE DEMANDA_PRODUCAO ADD DEP_DATA_AJUSTADA TIMESTAMP;
COMMENT ON COLUMN DEMANDA_PRODUCAO.DEP_DATA_AJUSTADA IS 'DATA DE ENTREGA AJUSTADA';


UPDATE ITEM_ORDEMPRODUCAO
SET iop_seq_prg = 0 
WHERE IOP_SEQ_PRG IS null;


commit work;

UPDATE ITEM_ORDEMPRODUCAO
SET IOP_PREFIXO = IOP_NORDEM 
  WHERE ORE_CODIGO IS NULL
  AND (IOP_PREFIXO = ''  OR IOP_PREFIXO IS NULL);
  
commit work;