UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.604',
    VERSAOSISTEMA.DATA   = '15.05.2025',
	VERSAO = '3.0.9.604'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

/* issue 2039 */
ALTER TABLE PRMT0001 ADD PMT_CALCULAR_ITENS_NO_FINAL CHAR(1) DEFAULT 'N';
COMMENT ON COLUMN PRMT0001.PMT_CALCULAR_ITENS_NO_FINAL IS 'Fazer os cáculos de tributos e outros do pedido/orcamento ao final do pedido';
UPDATE PRMT0001 SET PMT_CALCULAR_ITENS_NO_FINAL = 'N' WHERE PMT_CALCULAR_ITENS_NO_FINAL IS NULL;
