UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.575 patch 3',
    VERSAOSISTEMA.DATA   = '14.12.2022',
	VERSAO = '3.0.9.575'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE FOR0000 ADD TRP_CODIGO VARCHAR(3);

UPDATE PCL0000 SET PCL_MODALIDADE = '1' WHERE PCL_MODALIDADE <> '0' AND PCL_MODALIDADE <> '1' AND PCL_MODALIDADE <> '2';
COMMIT WORK;

