UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.563 patch 2',
    VERSAOSISTEMA.DATA   = '07.12.2021',
	VERSAO = '3.0.9.563'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE ALMOX0000 ADD AMX_NUM_ATO_DECLARATORIO VARCHAR(20);
ALTER TABLE ALMOX0000 ADD AMX_VALIDADE_ATO_DECLARATORIO DATE;
ALTER TABLE OPE0000 ADD OPE_VENDA_SAIDA_ARMAZEM CHAR(1);


