UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.577 patch 3',
    VERSAOSISTEMA.DATA   = '16.02.2023',
	VERSAO = '3.0.9.577'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE PRMT0001 ADD PMT_ENVIA_COPIA_PEDIDO_INDUST VARCHAR(1024);
COMMENT ON COLUMN PRMT0001.PMT_ENVIA_COPIA_PEDIDO_INDUST is 'Enviar Cópia do Pedido de Industrialização para o eMail';

CREATE TABLE CLI_ATV1_2 (RCL_CODIGO VARCHAR(3) PRIMARY KEY NOT NULL);
ALTER TABLE CLI_ATV1_2 ADD RCL_ATIVIDADE VARCHAR(20);
ALTER TABLE CLI_ATV1_2 ADD EMP_CODIGO VARCHAR(3);
INSERT INTO CLI_ATV1_2 SELECT * FROM CLI_ATV1 ;
DROP TABLE CLI_ATV1;
CREATE VIEW CLI_ATV1 (RCL_CODIGO, RCL_ATIVIDADE, EMP_CODIGO) AS SELECT * FROM CLI_ATV1_2;  
ALTER TABLE CLI0000 ALTER CLI_ATIVIDADE TYPE VARCHAR(3);
UPDATE CLI_ATV1 SET RCL_CODIGO = '0' || TRIM(RCL_CODIGO);
UPDATE CLI0000 SET CLI_ATIVIDADE = '0' || TRIM(CLI_ATIVIDADE);




