UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.543 patch 3',
       VERSAOSISTEMA.DATA   = '16.04.2020',
	    VERSAO = '3.0.9.543'
 where VERSAOSISTEMA.CODIGO = 1;

commit work; 

ALTER TABLE PRMT0001 ADD PMT_CONTROLE_CONTASPAGAR VARCHAR(1);
COMMENT ON COLUMN PRMT0001.PMT_CONTROLE_CONTASPAGAR IS 'HABILTAR APROVACAO PARA PAGAMENTO NO CONTAS A PAGAR';

ALTER TABLE USUARIO_PARAMETRO ADD USP_APROVAR_PAG VARCHAR(1);
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_APROVAR_PAG IS 'APROVAR PAGAMENTO DE CONTAS A PAGAR';
ALTER TABLE USUARIO_PARAMETRO ADD USP_REPROVAR_PAG VARCHAR(1);
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_REPROVAR_PAG IS 'REPROVAR PAGAMENTO DE CONTAS A PAGAR';

ALTER TABLE USUARIO_PARAMETRO ADD USP_APROVAR_EST VARCHAR(1);
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_APROVAR_EST IS 'ESTORNAR APROVACAO PARA PAGAMENTOS DE CONTAS A PAGAR';
ALTER TABLE USUARIO_PARAMETRO ADD USP_REPROVAR_EST VARCHAR(1);
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_REPROVAR_EST IS 'ESTORNAR REPROVACAO PARA PAGAMENTOS DE CONTAS A PAGAR';

ALTER TABLE USUARIO_PARAMETRO ADD USP_APONTAR_EST VARCHAR(1);
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_APONTAR_EST IS 'ESTORNAR SOLICITACAO PARA PAGAMENTOS DE CONTAS A PAGAR';

ALTER TABLE USUARIO_PARAMETRO ADD USP_APONTAR VARCHAR(1);
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_APONTAR IS 'APONTAR LIBERACAO DE PAGAMENTO PARA SER APROVADO';

UPDATE PRMT0001 
SET PMT_CONTROLE_CONTASPAGAR = 'N';

commit work;
UPDATE USUARIO_PARAMETRO
SET USP_APROVAR_PAG = 'N', USP_REPROVAR_PAG = 'N', USP_APROVAR_EST = 'N', USP_REPROVAR_EST = 'N', USP_APONTAR = 'N' , USP_APONTAR_EST = 'N';

commit work;

ALTER TABLE PAG_PC01 ADD PPC_SIT_LIBERACAO VARCHAR(1);
ALTER TABLE PAG_PC01 ADD PPC_VALOR_APONTADO NUMERIC(18,5);
COMMENT ON COLUMN PAG_PC01.PPC_VALOR_APONTADO IS 'VALOR APONTADO';
COMMENT ON COLUMN PAG_PC01.PPC_SIT_LIBERACAO IS 'A - APROVADO L - LIBERADO ,R - REPROVADO S - SEM LIBERACAO, ';

CREATE TABLE CONTROLE_TIT_PAGAR (
    CTP_CODIGO INTEGER NOT NULL,
    CTP_DATA_MOV TIMESTAMP NOT NULL,
    CTP_DESCRI VARCHAR(100) NOT NULL,
    COD_USU INTEGER NOT NULL,
    PAG_REGISTRO INTEGER NOT NULL,
    PAG_CODIGO VARCHAR(15) NOT NULL,
    PPC_NUMER VARCHAR(2) NOT NULL);

COMMENT ON TABLE CONTROLE_TIT_PAGAR IS 'CONTROLE DE TITULOS A PAGAR';

ALTER TABLE CONTROLE_TIT_PAGAR
ADD CONSTRAINT PK_CONTROLE_TIT_PAGAR
PRIMARY KEY (CTP_CODIGO);

COMMENT ON COLUMN CONTROLE_TIT_PAGAR.CTP_CODIGO IS 'CODIGO IDENTIFICADOR DO CONTROLE';
COMMENT ON COLUMN CONTROLE_TIT_PAGAR.CTP_DATA_MOV IS 'DATA DA MOVIMENTACAO';
COMMENT ON COLUMN CONTROLE_TIT_PAGAR.CTP_DESCRI IS 'DESCRICAO DO MOVIMENTO : APONTOU, APROVOU, ESTORNOU, REPROVOU';
COMMENT ON COLUMN CONTROLE_TIT_PAGAR.COD_USU IS 'IDENTIFICADOR DA TABELA DE USUARIO';
COMMENT ON COLUMN CONTROLE_TIT_PAGAR.PAG_REGISTRO IS 'IDENTIFICADOR DO TITULO (PAG_PC01)';
COMMENT ON COLUMN CONTROLE_TIT_PAGAR.PAG_CODIGO IS 'IDENTIFICADOR DO TÍTULO REDUNDANTE (PAG0000) - FACILITA AS QUERYS';
COMMENT ON COLUMN CONTROLE_TIT_PAGAR.PPC_NUMER IS 'PARCELA DO TÍTULO REDUNDANTE PARA TAB (PAG0000)';

CREATE SEQUENCE GEN_CONTROLE_TIT_PAGAR;

SET TERM ^ ;

create trigger controle_tit_pagar_bi for controle_tit_pagar
active before insert position 0
as
begin
  if (new.ctp_codigo is null) then
    new.ctp_codigo = gen_id(gen_controle_tit_pagar,1);
end^

SET TERM ; ^


UPDATE ORDEMPRODUCAO OPR
SET OPR_DATAFATURA = (SELECT FIRST 1 NF_SAIDA+ NF_HORASAIDA FROM NF0001 NF WHERE NF.PED_CODIGO = OPR.PED_CODIGO ORDER BY NF_EMISSAO DESC );

COMMIT WORK ;

UPDATE ORDEMPRODUCAO opr 
SET OPR_CONCLUSAO = (SELECT MAX(PCP_DATAFIM) 
					FROM ITEM_ORDEMPRODUCAO IOP 
					 LEFT JOIN PROCESSOS_PRODUCAO PCP ON (PCP.IOP_CODIGO = IOP.IOP_CODIGO)
					 WHERE (IOP.OPR_CODIGO = OPR.OPR_CODIGO) 
					 AND 
					 (SELECT  count(*)
					   FROM PRD0000 PR  
					    JOIN PROCESSOS_OPERACOES POP ON (POP.PRO_CODIGO = PR.PRO_CODIGO) 
					    WHERE  (PR.PRD_CODIGO = IOP.PRD_CODIGO)
					    AND NOT EXISTS (SELECT * FROM  PROCESSOS_PRODUCAO PCP                
					                    WHERE PCP.PCP_STATUS  = 'F' AND  PCP.IOP_CODIGO = IOP.IOP_CODIGO AND PCP.OPE_CODIGO = POP.OPE_CODIGO) ) = 0 
					 );
COMMIT WORK;



COMMENT ON COLUMN ORDEMPRODUCAO.OPR_LEADTIME IS 'TEMPO GASTO DO PEDIDO ATE ENTREGA';

UPDATE ORDEMPRODUCAO
SET OPR_LEADTIME =  OPR_CONCLUSAO- OPR_EMISSAO
WHERE OPR_CONCLUSAO IS NOT NULL;

COMMIT WORK;


UPDATE ORDEMPRODUCAO
SET OPR_STATUS = 'F'
WHERE OPR_CONCLUSAO IS NOT NULL ;

COMMIT WORK;


UPDATE PROCESSOS_PRODUCAO pcp
SET PCP_DATAINI = (SELECT MIN(app_dataini) FROM APONTAMENTO_PROCESSO ap WHERE ap.PCP_CODIGO = pcp.PCP_CODIGO)  ;

COMMIT WORK;

UPDATE PROCESSOS_PRODUCAO pcp
SET PCP_DATAFIM = (SELECT MAX(app_dataini) FROM APONTAMENTO_PROCESSO ap WHERE ap.PCP_CODIGO = pcp.PCP_CODIGO)  ; 

COMMIT WORK;

UPDATE CARGA CAR
SET CAR_DATAINI = (SELECT MIN(app_dataini) FROM APONTAMENTO_PROCESSO ap WHERE ap.CAR_CODIGO = car.CAR_CODIGO) ;  

COMMIT WORK;

UPDATE CARGA CAR
SET CAR_DATAFIM = (SELECT MAX(app_dataini) FROM APONTAMENTO_PROCESSO ap WHERE ap.CAR_CODIGO = car.CAR_CODIGO) ;  


COMMIT WORK;

