SET TERM ^ ;

ALTER TABLE ope_regra ADD opr_aliq_interestadual DECIMAL5^
COMMIT WORK^

Update VERSAOSISTEMA SET
       VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.0.463' ,
       VERSAOSISTEMA.DATA   = '19.10.2016'
 where VERSAOSISTEMA.CODIGO = 1^

COMMIT WORK^

SET TERM ; ^





