UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.568 patch 1',
    VERSAOSISTEMA.DATA   = '17.05.2022',
	VERSAO = '3.0.9.568'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;


ALTER TABLE BAN0000 ADD FPG_REGISTRO INTEGER;
COMMENT ON COLUMN BAN0000.FPG_REGISTRO is 'Forma de pagamento padrão para o banco';

ALTER TABLE ENF_IT01 ADD OPE_CODIGO_RETORNO VARCHAR(3);
COMMENT ON COLUMN ENF_IT01.OPE_CODIGO_RETORNO is 'Código de Retorno da CFOP';
ALTER TABLE PED_IT01 ADD OPE_CODIGO_RETORNO VARCHAR(3);
COMMENT ON COLUMN PED_IT01.OPE_CODIGO_RETORNO is 'Código de Retorno da CFOP';
ALTER TABLE PRMT0001 ADD PMT_NAT_OPER_RETORNO VARCHAR(1) DEFAULT 'N';
COMMENT ON COLUMN PRMT0001.PMT_NAT_OPER_RETORNO is 'Natureza da Operação de Retorno na Entrada de Notas Fiscais por XML';




