UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.536 patch 11',
       VERSAOSISTEMA.DATA   = '13.09.2019',
	    VERSAO = '3.0.9.536'
 where VERSAOSISTEMA.CODIGO = 1;

commit work;


ALTER TABLE USUARIO_PARAMETRO ADD USP_ABRICHAMADO VARCHAR(1);
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_ABRICHAMADO IS 'HABILITA BOTAO DE ABRI CHAMADO NO SUPORTE ';


 UPDATE USUARIO_PARAMETRO
 SET USP_ABRICHAMADO = 'N';
 
 COMMIT WORK;