UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.582',
    VERSAOSISTEMA.DATA   = '03.07.2023',
	VERSAO = '3.0.9.582'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

SELECT GEN_ID( GEN_INSTCNAB, (SELECT MAX(IST_REGISTRO) FROM INSTRUCAO_CNAB) - GEN_ID(GEN_INSTCNAB, 0)) FROM RDB$DATABASE;
INSERT INTO INSTRUCAO_CNAB ( IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (756, '01','ENTRADA DE TÍTULOS',1);
INSERT INTO INSTRUCAO_CNAB ( IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (756, '02','PEDIDO DE BAIXA',1);
INSERT INTO INSTRUCAO_CNAB ( IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (756, '03','PROTESTO PARA FINS FALIMENTARES',1);
INSERT INTO INSTRUCAO_CNAB ( IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (756, '04','CONCESSÃO DE ABATIMENTO',1);
INSERT INTO INSTRUCAO_CNAB ( IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (756, '05','CANCELAMENTO DE ABATIMENTO',1);
INSERT INTO INSTRUCAO_CNAB ( IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (756, '06','ALTERAÇÃO DE VENCIMENTO',1);
INSERT INTO INSTRUCAO_CNAB ( IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (756, '07' ,'CONCESSÃO DE DESCONTO',1);
INSERT INTO INSTRUCAO_CNAB ( IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (756, '09','PROTESTAR',1);
INSERT INTO INSTRUCAO_CNAB ( IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (756, '10','SUSTAR PROTESTO E BAIXAR TÍTULO',1);
INSERT INTO INSTRUCAO_CNAB ( IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (756, '11','SUSTAR PROTESTO E MANTER EM CARTEIRA',1);
INSERT INTO INSTRUCAO_CNAB ( IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (756, '12','ALTERAÇÃO DE JUROS DE MORA',1);
INSERT INTO INSTRUCAO_CNAB ( IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (756, '13','DISPENSAR COBRANÇA DE JUROS DE MORA',1);
INSERT INTO INSTRUCAO_CNAB ( IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (756, '14','ALTERAÇÃO DE VALOR/PERCENTUAL DE MULTA',1);
INSERT INTO INSTRUCAO_CNAB ( IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (756, '15','DISPENSAR COBRANÇA DE MULTA',1);
INSERT INTO INSTRUCAO_CNAB ( IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (756, '16','ALTERAÇÃO DO VALOR DE DESCONTO',1);
INSERT INTO INSTRUCAO_CNAB ( IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (756, '18','ALTERAÇÃO DO VALOR DE ABATIMENTO',1);
INSERT INTO INSTRUCAO_CNAB ( IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (756, '21','ALTERAR NÚMERO DO TÍTULO DADO PELO BENEFICIARIO',1);
INSERT INTO INSTRUCAO_CNAB ( IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (756, '22','ALTERAR NÚMERO CONTROLE DO PARTICIPANTE',1);
INSERT INTO INSTRUCAO_CNAB ( IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (756, '23','ALTERAR DADOS DO PAGADOR',1);
INSERT INTO INSTRUCAO_CNAB ( IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (756, '24','ALTERAR DADOS DO SACADOR/AVALISTA',1);
INSERT INTO INSTRUCAO_CNAB ( IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (756, '31','ALTERAÇÃO DE OUTROS DADOS',1);
INSERT INTO INSTRUCAO_CNAB ( IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (756, '33','ALTERAÇÃO DOS DADOS DO RATEIO DE CRÉDITO',1);
INSERT INTO INSTRUCAO_CNAB ( IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (756, '34','PEDIDO DE CANCELAMENTO DOS DADOS DO RATEIO DE CRÉDITO',1);
INSERT INTO INSTRUCAO_CNAB ( IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (756, '35','PEDIDO DE DESAGENDAMENTO DO DÉBITO AUTOMÁTICO',1);
INSERT INTO INSTRUCAO_CNAB ( IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (756, '42','ALTERAÇÃO DE ESPÉCIE DE TÍTULO',1);
INSERT INTO INSTRUCAO_CNAB ( IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (756, '45','NEGATIVAÇÃO SEM PROTESTO',1);
INSERT INTO INSTRUCAO_CNAB ( IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (756, '46','SOLICITAÇÃO DE BAIXA DE TÍTULO NEGATIVADO SEM PROTESTO',1);
INSERT INTO INSTRUCAO_CNAB ( IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (756, '47','SOLICITAÇÃO EXCLUIR NEGATIVAÇÃO E MANTER PENDENTE',1);
DELETE FROM INSTRUCAO_CNAB T1 
  WHERE EXISTS 
   (SELECT IST_COD_BANCO, IST_CODIGO,BAN_LEIAUTE FROM INSTRUCAO_CNAB T2 
    WHERE T1.IST_COD_BANCO = IST_COD_BANCO AND T1.IST_CODIGO  = T2.IST_CODIGO AND T1.BAN_LEIAUTE = T2.BAN_LEIAUTE AND  
          T1.RDB$DB_KEY != T2.RDB$DB_KEY);
COMMIT WORK;

