UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.575 patch 4',
    VERSAOSISTEMA.DATA   = '21.12.2022',
	VERSAO = '3.0.9.575'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

/* issue 993 */
ALTER TABLE CLI0000 ADD CLI_FONE_TEMP VARCHAR(12);
UPDATE CLI0000 SET CLI_FONE_TEMP = REPLACE(CLI_FONE, ' ', '');
UPDATE CLI0000 SET CLI_FONE_TEMP = NULL WHERE CLI_FONE_TEMP = '';
UPDATE CLI0000 SET CLI_FONE_TEMP = CAST(CAST(COALESCE(CLI_FONE_TEMP, '0') AS DECIMAL(18,0)) AS VARCHAR(12));
UPDATE CLI0000 SET CLI_FONE_TEMP = NULL WHERE CLI_FONE_TEMP = '0';
UPDATE CLI0000 SET CLI_FONE_TEMP =
	CASE 
		WHEN CHARACTER_LENGTH(CLI_FONE_TEMP) = 10 THEN SUBSTRING (CLI_FONE_TEMP FROM 1 FOR 2)||' '||SUBSTRING (CLI_FONE_TEMP FROM 3 FOR 10)
		WHEN CHARACTER_LENGTH(CLI_FONE_TEMP) = 11 THEN CLI_FONE_TEMP
		ELSE CLI_FONE_TEMP		
	END;
ALTER TABLE CLI0000 ALTER CLI_FONE TYPE VARCHAR(12);
UPDATE CLI0000 SET CLI_FONE = CLI_FONE_TEMP;
ALTER TABLE CLI0000 DROP CLI_FONE_TEMP;

ALTER TABLE CLI0000 ADD CLI_FAX_TEMP VARCHAR(12);
UPDATE CLI0000 SET CLI_FAX_TEMP = REPLACE(CLI_FAX, ' ', '');
UPDATE CLI0000 SET CLI_FAX_TEMP = NULL WHERE CLI_FAX_TEMP = '';
UPDATE CLI0000 SET CLI_FAX_TEMP = CAST(CAST(COALESCE(CLI_FAX_TEMP, '0') AS DECIMAL(18,0)) AS VARCHAR(12));
UPDATE CLI0000 SET CLI_FAX_TEMP = NULL WHERE CLI_FAX_TEMP = '0';
UPDATE CLI0000 SET CLI_FAX_TEMP =
	CASE 
		WHEN CHARACTER_LENGTH(CLI_FAX_TEMP) = 10 THEN SUBSTRING (CLI_FAX_TEMP FROM 1 FOR 2)||' '||SUBSTRING (CLI_FAX_TEMP FROM 3 FOR 10)
		WHEN CHARACTER_LENGTH(CLI_FAX_TEMP) = 11 THEN CLI_FAX_TEMP
		ELSE CLI_FAX_TEMP		
	END;
ALTER TABLE CLI0000 ALTER CLI_FAX TYPE VARCHAR(12);
UPDATE CLI0000 SET CLI_FAX = CLI_FAX_TEMP;
ALTER TABLE CLI0000 DROP CLI_FAX_TEMP;
COMMIT WORK;

/* issue 1058 */
ALTER TABLE IPI0000 ADD NCM_DESC_FAMILIA_TEMP BLOB SUB_TYPE TEXT;
UPDATE IPI0000 SET NCM_DESC_FAMILIA_TEMP = NCM_DESC_FAMILIA; 
ALTER TABLE IPI0000 DROP NCM_DESC_FAMILIA;
ALTER TABLE IPI0000 ALTER COLUMN NCM_DESC_FAMILIA_TEMP TO NCM_DESC_FAMILIA; 

/* issue 1102 */
INSERT INTO BANCOS (BCO_CODIGO, BCO_DESCRICAO, EMP_CODIGO, BCO_UNIDADE_CONSUMIDORA ) VALUES (85, 'VIACREDI', '001', 'N');

