UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.588 patch 2',
    VERSAOSISTEMA.DATA   = '30.01.2024',
	VERSAO = '3.0.9.588'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

/* issue 1794 */
ALTER TABLE USUARIO ADD USU_ATIVO VARCHAR(1);
COMMENT ON COLUMN USUARIO.USU_ATIVO IS 'Usuário está Ativo? S/N';
UPDATE USUARIO SET USU_ATIVO = 'S' WHERE USU_ATIVO IS NULL;
COMMIT WORK;

/* issue 1796 */
UPDATE CLI0000 SET CLI_BAIRRO = UPPER(CLI_BAIRRO);  
COMMIT WORK;

