UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.560 patch 1',
    VERSAOSISTEMA.DATA   = '09.09.2021',
	VERSAO = '3.0.9.560'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE PRMT0001 ADD PMT_AMX_ENVASE_SAIDA VARCHAR(4);
ALTER TABLE FTC0000 ADD AMX_CODIGO VARCHAR(4);

CREATE INDEX HISTORICO_ORDEMPRODUCAO_IDX2 ON HISTORICO_ORDEMPRODUCAO (IOP_CODIGO);
CREATE INDEX HISTORICO_ORDEMPRODUCAO_IDX1 ON HISTORICO_ORDEMPRODUCAO (HOP_CODIGO);
CREATE INDEX MATERIAPRIMA_ORDEMPRODUCAO_IDX3 ON MATERIAPRIMA_ORDEMPRODUCAO (PRD_CODIGO);
CREATE INDEX MATERIAPRIMA_ORDEMPRODUCAO_IDX2 ON MATERIAPRIMA_ORDEMPRODUCAO (OPR_CODIGO);
CREATE INDEX MATERIAPRIMA_ORDEMPRODUCAO_IDX1 ON MATERIAPRIMA_ORDEMPRODUCAO (IOP_CODIGO);

