SET TERM ^ ;

CREATE OR ALTER PROCEDURE ATUALIZACAO_CUSTOS (EMP_CODIGO VARCHAR(3))
AS
declare variable PRD_REFER varchar(20);
declare variable ENTRADA numeric(18,5);
declare variable LIQUIDA numeric(18,5);
declare variable IPI numeric(18,5);
declare variable SUBSTRI numeric(18,5);
declare variable FRETE numeric(18,5);
declare variable DESPEACES numeric(18,5);
declare variable SEGURO numeric(18,5);
declare variable CUSTOCREDITO numeric(18,5);
declare variable CUSTO numeric(18,5);
declare variable CUSTO_BASE numeric(18,5);
declare variable QTDE numeric(18,4);
declare variable QTDE_TOTAL_NOTA numeric(18,4);
declare variable FRETE_POR_FORA numeric(18,5);
declare variable DIF_ICMS_POR_FORA numeric(18,5);
declare variable OUTROS_POR_FORA numeric(18,5);
declare variable PMT_CALCULARPV integer;
declare variable PMT_NAO_AUTO_PVENDA varchar(1);
declare variable PRD_PCUSTO numeric(18,5);
declare variable PRD_PMEDIO numeric(18,5);
declare variable PRD_CUSTOCOMIPI numeric(18,5);
declare variable COMP varchar(2);
BEGIN

  SELECT PRODUTOS FROM SHAREDB INTO :COMP;

  SELECT PMT_CALCULARPV, PMT_NAO_AUTO_PVENDA
  FROM PRMT0001
  WHERE EMP_CODIGO = :EMP_CODIGO
  INTO :PMT_CALCULARPV, :PMT_NAO_AUTO_PVENDA;

  FOR
    SELECT PRD_REFER
    FROM PRD0000 PR
    WHERE PR.PRD_STATUS = 'A'
      AND EXISTS (
        SELECT 1
        FROM ENF0001 EF
        JOIN ENF_IT01 E1
          ON EF.ENF_NOTANUMBER = E1.ENF_IT_NOTANUMBER
         AND EF.FOR_CODIGO = E1.FOR_CODIGO
        JOIN OPE0000 OP
          ON OP.OPE_NATUREZA = E1.ENF_CFOP
         AND OP.OPE_TIPO_OPERACAO = 'C'
        WHERE E1.PRD_REFER = PR.PRD_REFER
          AND EF.EMP_CODIGO = :EMP_CODIGO
      )
    INTO :PRD_REFER
  DO
  BEGIN

    SELECT FIRST 1
        (E1.ENF_IT_VLPIS + E1.ENF_IT_VLCOFINS + E1.ENF_ICMS),
        E1.ENF_IT_VLIPI,
        E1.ENF_VLSUBST,
        E1.ENF_IT_VALFRETE,
        E1.ENF_IT_VLDESP_ACES,
        E1.ENF_IT_VLSEGURO,
        CAST(E1.ENF_QTDE AS NUMERIC(18,4)),
        CAST(E1.ENF_CUSTO AS NUMERIC(18,5)),
        COALESCE(EF.ENF_VLFRETEPORFORA,0),
        COALESCE(EF.ENF_VLRDIFICMS,0),        
        COALESCE(EF.ENF_VLOUTROS,0),
        (SELECT SUM(E2.ENF_QTDE)
         FROM ENF_IT01 E2
         WHERE E2.ENF_IT_NOTANUMBER = E1.ENF_IT_NOTANUMBER
           AND E2.FOR_CODIGO = E1.FOR_CODIGO)
    FROM ENF0001 EF
    JOIN ENF_IT01 E1
      ON EF.ENF_NOTANUMBER = E1.ENF_IT_NOTANUMBER
     AND EF.FOR_CODIGO = E1.FOR_CODIGO
    JOIN OPE0000 OP
      ON OP.OPE_NATUREZA = E1.ENF_CFOP
     AND OP.OPE_TIPO_OPERACAO = 'C'
    WHERE E1.PRD_REFER = :PRD_REFER
      AND E1.EMP_CODIGO = :EMP_CODIGO
      AND E1.ENF_QTDE > 0
    ORDER BY EF.ENF_EMISSAO DESC, EF.ENF_REGISTRO DESC
    INTO :CUSTOCREDITO, :IPI, :SUBSTRI, :FRETE,
         :DESPEACES, :SEGURO, :QTDE, :CUSTO_BASE,
         :FRETE_POR_FORA, :DIF_ICMS_POR_FORA, :OUTROS_POR_FORA, :QTDE_TOTAL_NOTA;

    CUSTO = CUSTO_BASE;
    LIQUIDA = CUSTO_BASE;

    
    /* rateio correto dos por fora */
    IF (QTDE_TOTAL_NOTA > 0 AND FRETE_POR_FORA > 0) THEN
        FRETE = FRETE + ((FRETE_POR_FORA / QTDE_TOTAL_NOTA) * QTDE);

    IF (QTDE_TOTAL_NOTA > 0 AND DIF_ICMS_POR_FORA > 0) THEN
        SUBSTRI = SUBSTRI + ((DIF_ICMS_POR_FORA / QTDE_TOTAL_NOTA) * QTDE);

    IF (QTDE_TOTAL_NOTA > 0 AND OUTROS_POR_FORA > 0) THEN
        DESPEACES = DESPEACES + ((OUTROS_POR_FORA / QTDE_TOTAL_NOTA) * QTDE);

    
    
    
    
    /* rateios unitários */
    FRETE     = FRETE / QTDE;
    IPI       = IPI / QTDE;
    SUBSTRI   = SUBSTRI / QTDE;
    DESPEACES = DESPEACES / QTDE;
    SEGURO    = SEGURO / QTDE;

    /* custos */
    LIQUIDA = CUSTO;
    ENTRADA = CUSTO + FRETE + IPI + SUBSTRI + DESPEACES + SEGURO;
    CUSTOCREDITO = (CUSTO_BASE - (CUSTOCREDITO / QTDE));

    /* update do produto */
IF (COMP = 'C') THEN
  EXECUTE STATEMENT
    'UPDATE PRD0000 SET '||
    'PRD_PCUSTO='||REPLACE(CAST(LIQUIDA AS VARCHAR(20)),',','.')||
    ',PRD_CUSTOCOMIPI='||REPLACE(CAST(ENTRADA AS VARCHAR(20)),',','.')||
    ',PRD_CUSTOFRETE='||REPLACE(CAST(FRETE AS VARCHAR(20)),',','.')||
    ',PRD_CUSTOIPI='||REPLACE(CAST(IPI AS VARCHAR(20)),',','.')||
    ',PRD_CUSTOSUBTRIB='||REPLACE(CAST(SUBSTRI AS VARCHAR(20)),',','.')||
    ',PRD_CUSTOADCIONAL='||REPLACE(CAST((DESPEACES+SEGURO) AS VARCHAR(20)),',','.')||
    ',PRD_CUSTO_CREDITO='||REPLACE(CAST(CUSTOCREDITO AS VARCHAR(20)),',','.')||
    ' WHERE PRD_REFER='''||PRD_REFER||'''';
ELSE
  EXECUTE STATEMENT
    'UPDATE PRD0000 SET '||
    'PRD_PCUSTO='||REPLACE(CAST(LIQUIDA AS VARCHAR(20)),',','.')||
    ',PRD_CUSTOCOMIPI='||REPLACE(CAST(ENTRADA AS VARCHAR(20)),',','.')||
    ',PRD_CUSTOFRETE='||REPLACE(CAST(FRETE AS VARCHAR(20)),',','.')||
    ',PRD_CUSTOIPI='||REPLACE(CAST(IPI AS VARCHAR(20)),',','.')||
    ',PRD_CUSTOSUBTRIB='||REPLACE(CAST(SUBSTRI AS VARCHAR(20)),',','.')||
    ',PRD_CUSTOADCIONAL='||REPLACE(CAST((DESPEACES+SEGURO) AS VARCHAR(20)),',','.')||
    ',PRD_CUSTO_CREDITO='||REPLACE(CAST(CUSTOCREDITO AS VARCHAR(20)),',','.')||
    ' WHERE PRD_REFER='''||PRD_REFER||
    ''' AND EMP_CODIGO='''||EMP_CODIGO||'''';

  END
END^

SET TERM ; ^
