UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.532',
       VERSAOSISTEMA.DATA   = '08.05.2019',
	    VERSAO = '3.0.9.532'
 where VERSAOSISTEMA.CODIGO = 1;

 
commit work;
 
ALTER TABLE PRMT0001 ADD PMT_GerarTagICMSSubsPagaAnter VARCHAR (1);
COMMENT ON COLUMN PRMT0001.PMT_GerarTagICMSSubsPagaAnter IS 
'N -> SE O VALOR FOR ZERO, NAO VAI FORÇAR A GERACAO DA TAG NUNCA;
P -> FORÇA A TAG SER GERADA NO AMBIENTE DE PRODUCAO MESMO QUE O VALOR SEJA ZERO;
H -> FORÇA A TAG SER﻿ GERADA NO AMBIENTE DE HOMOLOGACAO MESMO QUE﻿ O VALOR SEJA ZERO;
S -> MESMO QUE O VALOR SEJA ZERO, A TAG SERA GERADA SEMPRE;﻿';

UPDATE PRMT0001 SET PMT_GerarTagICMSSubsPagaAnter = 'N';

commit work;

COMMENT ON TABLE PAIS0000 IS 'TABELA DE PAISES';


ALTER TABLE PRD0000 ADD PRD_CBENEF VARCHAR(8);
COMMENT ON COLUMN PRD0000.PRD_CBENEF IS 'CODIGO DO BENEFICIO FISCAL';


-- linhas orfãs
DELETE FROM FAT_RECEBIMENTO
WHERE NOT EXISTS (SELECT 1 FROM FAT_PC01 fat WHERE FAT_RECEBIMENTO.FAT_REGISTRO = fat.FAT_REGISTRO);

commit work;


ALTER TABLE FAT0000 ADD FAT_VALORANTECIPADO NUMERIC(18,5);
COMMENT ON COLUMN FAT0000.FAT_VALORANTECIPADO IS 'VALORES ANTECIPADOS CREDITO , ESTE VALOR NAO SAI NA FATURA SOMENTE NA NOTA';

COMMENT ON TABLE CONTA_CORRENTE IS 'CONTA CORRENTE CREDITO AO CLIENTE, FORNECEDOR';

CREATE TABLE CONTA_FATURA (
    CFA_CODCONTAFAT INTEGER NOT NULL,
    CODIGO_CONTA VARCHAR(5) NOT null,
    FAT_REGISTRO INTEGER NOT NULL,
    CFA_DATAREGISTRO TIMESTAMP DEFAULT CURRENT_DATE NOT NULL,
    CFA_VALOR NUMERIC(18,5) NOT NULL  );

ALTER TABLE CONTA_FATURA ADD CONSTRAINT PK_CONTA_FATURA PRIMARY KEY (CFA_CODCONTAFAT);

COMMENT ON COLUMN CONTA_FATURA.CFA_CODCONTAFAT IS  'IDENTIFICADOR DO CREDITO DA FATURA';
COMMENT ON COLUMN CONTA_FATURA.CODIGO_CONTA IS 'CONTA CORRENTE';
COMMENT ON COLUMN CONTA_FATURA.FAT_REGISTRO IS 'IDENTIFICADOR REGISTRO';
COMMENT ON COLUMN CONTA_FATURA.CFA_VALOR IS 'VALOR USADO';
CREATE SEQUENCE GEN_CONTA_FATURA_ID;

SET TERM ^ ;

create trigger conta_fatura_bi for conta_fatura
active before insert position 0
as
begin
  if (new.cfa_codcontafat is null) then
    new.cfa_codcontafat = gen_id(gen_conta_fatura_id,1);
end^

SET TERM ; ^

ALTER TABLE USUARIO_PARAMETRO ADD USP_USA_CREDITO_CC varchar(1);

UPDATE USUARIO_PARAMETRO SET USP_USA_CREDITO_CC = 'N';

COMMIT WORK;

COMMENT ON COLUMN USUARIO_PARAMETRO.USP_USA_CREDITO_CC IS 'USA CREDITO DA CONTA CORRENTE DO CLIENTE PARA ABATER NA FATURA' ;

ALTER TABLE PRMT0001 ADD PMT_NAO_ATUALIZAR_BANCO VARCHAR (1);
COMMENT ON COLUMN PRMT0001.PMT_NAO_ATUALIZAR_BANCO IS 'NÃO ATUALIZAR BANCO NA PARCELA AO LIQUIDAR POR OUTRO BANCO';


UPDATE PRMT0001 SET PMT_NAO_ATUALIZAR_BANCO = 'S';
COMMIT WORK;