
UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.535 patch 3',
       VERSAOSISTEMA.DATA   = '07.08.2019',
	    VERSAO = '3.0.9.535'
 where VERSAOSISTEMA.CODIGO = 1;

COMMIT WORK;


UPDATE PRD0000 PR 
SET PRD_PENDENTE = (SELECT SUM(OCI_QTDES) - SUM( OCI_QTDER)
					FROM OCP_IT01 IT
 					WHERE OCI_SITUACAO = 'P'
 					AND it.PRD_REFER = pr.PRD_REFER
 					AND ((SELECT PRODUTOS FROM SHAREDB) = 'C' OR PR.EMP_CODIGO = IT.EMP_CODIGO))  ;


COMMIT WORK;
 				
				
				
ALTER TABLE USUARIO_PARAMETRO ADD USP_TRANSFERENCIATITULOS VARCHAR(1);
COMMENT ON COLUMN  USUARIO_PARAMETRO.USP_TRANSFERENCIATITULOS IS 'PERMITIR TRANSFERENCIA DE TITULOS';

UPDATE USUARIO_PARAMETRO
SET USP_TRANSFERENCIATITULOS = 'N';
 
 
 COMMIT WORK;				