UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.537 patch 4',
       VERSAOSISTEMA.DATA   = '10.10.2019',
	    VERSAO = '3.0.9.537'
 where VERSAOSISTEMA.CODIGO = 1;

COMMIT WORK;

ALTER TABLE PRD0000 ADD PRD_UND_TRIB VARCHAR(6);
COMMENT ON COLUMN PRD0000.PRD_UND_TRIB IS ' UNIDADE TRIBUTARIA QUE VAI NA NFE';
 
ALTER TABLE PED_IT01 ADD PRF_QUANT_TRIB NUMERIC(18,5);
COMMENT ON COLUMN PED_IT01.PRF_QUANT_TRIB IS 'QUANTIDADE RELACIONADO A UNIDADE TRIBUTARIA - EXPORTACAO';