UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.585',
    VERSAOSISTEMA.DATA   = '04.10.2023',
	VERSAO = '3.0.9.585'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE PRD_LOTE ADD AMX_CODIGO VARCHAR(4);


