CREATE TABLE ENDERECO (
    CODIGO INTEGER NOT NULL,
    COD_CLIENTE INTEGER,
    COD_CIDADE INTEGER,
    COD_PAIS INTEGER,
    DESCRICAO VARCHAR(150),
    NUMERO INTEGER,
    COMPLEMENTO VARCHAR(10),
    BAIRRO VARCHAR(30),
    CXPOSTAL VARCHAR(6),
    CEP VARCHAR(8),
	ESTADO VARCHAR(2),
    TIPO VARCHAR(1),
    PADRAO VARCHAR(1));
	
COMMIT WORK;

ALTER TABLE ENDERECO
ADD CONSTRAINT PK_ENDERECO
PRIMARY KEY (CODIGO);

CREATE SEQUENCE GEN_ENDERECO_ID;

COMMIT WORK;

ALTER SEQUENCE GEN_ENDERECO_ID RESTART WITH 0;

COMMIT WORK;

COMMENT ON COLUMN ENDERECO.TIPO IS
'0 - Cobraça 1 - Entrega';

COMMIT WORK;

COMMENT ON COLUMN ENDERECO.PADRAO IS
'0 - NAO 1 - SIM';

COMMIT WORK;

UPDATE  VERSAOSISTEMA SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.0.469',
       VERSAOSISTEMA.DATA   = '01.12.2016'
 where VERSAOSISTEMA.CODIGO = 1;
 
 COMMIT WORK;