UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.564',
    VERSAOSISTEMA.DATA   = '10.01.2022',
	VERSAO = '3.0.9.564'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE OPERACOES ADD EQP_CODIGO INT;

