UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.584',
    VERSAOSISTEMA.DATA   = '05.09.2023',
	VERSAO = '3.0.9.584'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE EMP0000 ADD EMP_CLAS_ESTAB_IND VARCHAR(2);
COMMENT ON COLUMN EMP0000.EMP_CLAS_ESTAB_IND IS 'Classificação do Estabelecimento';
