UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.607 patch 3',
    VERSAOSISTEMA.DATA   = '19.09.2025',
	VERSAO = '3.0.9.607'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

/* ISSUE 2048 */
ALTER TABLE PRMT0001  ADD PMT_CADASTRA_PRODUTO_PEDIDO CHAR(1);
COMMENT ON COLUMN PRMT0001.PMT_CADASTRA_PRODUTO_PEDIDO is 'Apresenta o Painel de Importação (F12) de múltiplos XMLs na tela de Pedido';
