UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.545 patch 8',
    VERSAOSISTEMA.DATA   = '12.06.2020',
	VERSAO = '3.0.9.545'
 where VERSAOSISTEMA.CODIGO = 1;

commit work;


ALTER TABLE DEMANDA_PRODUCAO ADD DEP_GERASUBORDENS VARCHAR(1);
COMMENT ON COLUMN DEMANDA_PRODUCAO.DEP_GERASUBORDENS IS 'SE MESMO NÃO GERA SUBORDENS, POSSIBILITA GERAR SUBORNDES MANUAL';

