UPDATE  VERSAOSISTEMA 
SET    VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.517',
       VERSAOSISTEMA.DATA   = '07.07.2018',
	   VERSAO = '3.0.9.517'
 where VERSAOSISTEMA.CODIGO = 1;
 
commit work;



ALTER TABLE CLI0000 ADD CLI_FRETE VARCHAR(1);
COMMENT ON COLUMN CLI0000.CLI_FRETE IS 'TIPO DE FRETE : 0- (CIF),1 (FOB),2-TERCEIROS, 3-PROPRIO POR CONTA DO REMETENTE, 4-PROPRIO POR CONTA DO DESTINATARIO,9-SEM FRETE';

ALTER TABLE EMP0000 ADD EMP_USERNAME_FIN VARCHAR(50);
COMMENT ON COLUMN EMP0000.EMP_USERNAME_FIN IS 'USUARIO QUE ENVIARA EMAIL PELO FINANCEIRO - CRIPTOGRAFADA';

ALTER TABLE EMP0000 ADD EMP_PASSWORD_FIN  VARCHAR(50);
COMMENT ON COLUMN EMP0000.EMP_PASSWORD_FIN IS 'SENHA DO EMAIL DO FINANCEIRO - CRIPTOGRAFADA';


