UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.609',
    VERSAOSISTEMA.DATA   = '27.11.2025',
	VERSAO = '3.0.9.609'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

/* issue 2066*/
UPDATE PRMT0001 p 
	SET PMT_ATIVAR_IBS_CBS = 'S', 
	PMT_IBS_ALIQUOTA_MUNICIPAL = 0, 
	PMT_IBS_ALIQUOTA_ESTADUAL = 0.1,
	PMT_CBS_ALIQUOTA = 0.9,
	PMT_CST_IBS_CBS = '000'
WHERE p.PMT_CST_IBS_CBS IS NULL;

