
UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.536 patch 2',
       VERSAOSISTEMA.DATA   = '02.09.2019',
	    VERSAO = '3.0.9.536'
 where VERSAOSISTEMA.CODIGO = 1;

commit work;

-- EMBRATERM 
delete from custoindust;

CREATE SEQUENCE GEN_SETOR;


CREATE TABLE SETOR (
    SET_CODIGO INTEGER NOT NULL,
    SET_DESCRICAO VARCHAR(60),
    EMP_CODIGO VARCHAR(3));

COMMENT ON COLUMN SETOR.SET_CODIGO IS 'IDENTIFICADOR DE SETORES';
COMMENT ON COLUMN SETOR.SET_DESCRICAO IS 'DESCRIÇÃO';
COMMENT ON COLUMN SETOR.EMP_CODIGO IS 'CHAVE DE REFENCIA (EMP0001)';

ALTER TABLE SETOR ADD CONSTRAINT PK_SETOR PRIMARY KEY (SET_CODIGO);



SET TERM ^ ;

create trigger setor_bi for setor
active before insert position 0
as
begin
  if (new.set_codigo is null) then
    new.set_codigo = gen_id(gen_setor,1);
end^

SET TERM ; ^


COMMENT ON TABLE SETOR IS 'CADASTRO DE SETORES';


ALTER TABLE CUSTOINDUST ADD SET_CODIGO INTEGER;

COMMENT ON COLUMN CUSTOINDUST.SET_CODIGO IS 'REFERENCIA DO SETOR';

ALTER TABLE CUSTOINDUST ADD CONSTRAINT FK_CUSTOINDUST_SETOR
FOREIGN KEY (SET_CODIGO) REFERENCES SETOR(SET_CODIGO) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE SERVICO ADD SET_CODIGO INTEGER; 
ALTER TABLE SERVICO ADD CONSTRAINT SET_CODIGO FOREIGN KEY (SET_CODIGO) REFERENCES SETOR(SET_CODIGO);

