UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.541 patch 8',
       VERSAOSISTEMA.DATA   = '27.02.2020',
	    VERSAO = '3.0.9.541'
 where VERSAOSISTEMA.CODIGO = 1;

commit work;

ALTER TABLE USUARIO_PARAMETRO ADD USP_ALTERA_FORMA_PAG_FAT VARCHAR(1);
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_ALTERA_FORMA_PAG_FAT IS 'BLOQUEIA ALTERAÇÃO FORMA DE PAGAMENTO NAS PARCELAS S - PERMITE ALTERAR N - BLOQUEIA';
  
   
UPDATE  USUARIO_PARAMETRO
SET USP_ALTERA_FORMA_PAG_FAT = 'S';