UPDATE  VERSAOSISTEMA 
SET    VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.518',
       VERSAOSISTEMA.DATA   = '02.08.2018',
	   VERSAO = '3.0.9.518'
 where VERSAOSISTEMA.CODIGO = 1;
 
commit work;


ALTER TABLE PRD0000 ADD PRD_PER_ICMS NUMERIC(18,5);
ALTER TABLE PRD0000 ADD PRD_PER_PISCONFINS NUMERIC(18,5);
ALTER TABLE PRD0000 ADD PRD_PER_IPI NUMERIC(18,5);
ALTER TABLE PRD0000 ADD PRD_PER_FRETE NUMERIC(18,5);
ALTER TABLE PRD0000 ADD PRD_PER_OUTROS NUMERIC(18,5);
ALTER TABLE PRD0000 ADD PRD_PER_LUCRO NUMERIC(18,5);

COMMENT ON COLUMN PRD0000.PRD_PER_ICMS IS 'PERCENTUAL DE ICMS QUE COMPOE A MARGEM DE VENDA';
COMMENT ON COLUMN PRD0000.PRD_PER_PISCONFINS IS 'PERCENTUAL DE PIS E CONFINS QUE COMPOE A MARGEM DE VENDA';
COMMENT ON COLUMN PRD0000.PRD_PER_IPI IS 'PERCENTUAL DE IPI QUE COMPOE A MARGEM DE VENDA';
COMMENT ON COLUMN PRD0000.PRD_PER_FRETE IS 'PERCENTUAL DE FRETE QUE COMPOE A MARGEM DE VENDA';
COMMENT ON COLUMN PRD0000.PRD_PER_OUTROS IS 'PERCENTUAL DE OUTROS QUE COMPOE A MARGEM DE VENDA';
COMMENT ON COLUMN PRD0000.PRD_PER_LUCRO IS 'PERCENTUAL DE MARGEM DE LUCRO ICMS QUE COMPOE A MARGEM DE VENDA';


ALTER TABLE PRD_GRUPO ADD PGR_PER_ICMS NUMERIC(18,5);
ALTER TABLE PRD_GRUPO ADD PGR_PER_PISCONFINS NUMERIC(18,5);
ALTER TABLE PRD_GRUPO ADD PGR_PER_IPI NUMERIC(18,5);
ALTER TABLE PRD_GRUPO ADD PGR_PER_FRETE NUMERIC(18,5);
ALTER TABLE PRD_GRUPO ADD PGR_PER_OUTROS NUMERIC(18,5);
ALTER TABLE PRD_GRUPO ADD PGR_PER_LUCRO NUMERIC(18,5);
ALTER TABLE PRD_GRUPO ADD PGR_MARGEMVENDA NUMERIC(18,5);
ALTER TABLE PRD_GRUPO ADD PGR_MARGEMOFERTA NUMERIC(18,5);

COMMENT ON COLUMN PRD_GRUPO.PGR_PER_ICMS IS 'PERCENTUAL DE ICMS QUE COMPOE A MARGEM DE VENDA';
COMMENT ON COLUMN PRD_GRUPO.PGR_PER_PISCONFINS IS 'PERCENTUAL DE PIS E CONFINS QUE COMPOE A MARGEM DE VENDA';
COMMENT ON COLUMN PRD_GRUPO.PGR_PER_IPI IS 'PERCENTUAL DE IPI QUE COMPOE A MARGEM DE VENDA';
COMMENT ON COLUMN PRD_GRUPO.PGR_PER_FRETE IS 'PERCENTUAL DE FRETE QUE COMPOE A MARGEM DE VENDA';
COMMENT ON COLUMN PRD_GRUPO.PGR_PER_OUTROS IS 'PERCENTUAL DE OUTROS QUE COMPOE A MARGEM DE VENDA';
COMMENT ON COLUMN PRD_GRUPO.PGR_PER_LUCRO IS 'PERCENTUAL DE MARGEM DE LUCRO ICMS QUE COMPOE A MARGEM DE VENDA';
COMMENT ON COLUMN PRD_GRUPO.PGR_MARGEMVENDA IS 'MARGEM DE VENDA - CALCULADO';
COMMENT ON COLUMN PRD_GRUPO.PGR_MARGEMOFERTA IS 'MARGEM DE OFERTA';


ALTER TABLE PRD_TIPO ADD PTI_PER_ICMS NUMERIC(18,5);
ALTER TABLE PRD_TIPO ADD PTI_PER_PISCONFINS NUMERIC(18,5);
ALTER TABLE PRD_TIPO ADD PTI_PER_IPI NUMERIC(18,5);
ALTER TABLE PRD_TIPO ADD PTI_PER_FRETE NUMERIC(18,5);
ALTER TABLE PRD_TIPO ADD PTI_PER_OUTROS NUMERIC(18,5);
ALTER TABLE PRD_TIPO ADD PTI_PER_LUCRO NUMERIC(18,5);


COMMENT ON COLUMN PRD_TIPO.PTI_PER_ICMS IS 'PERCENTUAL DE ICMS QUE COMPOE A MARGEM DE VENDA';
COMMENT ON COLUMN PRD_TIPO.PTI_PER_PISCONFINS IS 'PERCENTUAL DE PIS E CONFINS QUE COMPOE A MARGEM DE VENDA';
COMMENT ON COLUMN PRD_TIPO.PTI_PER_IPI IS 'PERCENTUAL DE IPI QUE COMPOE A MARGEM DE VENDA';
COMMENT ON COLUMN PRD_TIPO.PTI_PER_FRETE IS 'PERCENTUAL DE FRETE QUE COMPOE A MARGEM DE VENDA';
COMMENT ON COLUMN PRD_TIPO.PTI_PER_OUTROS IS 'PERCENTUAL DE OUTROS QUE COMPOE A MARGEM DE VENDA';
COMMENT ON COLUMN PRD_TIPO.PTI_PER_LUCRO IS 'PERCENTUAL DE MARGEM DE LUCRO ICMS QUE COMPOE A MARGEM DE VENDA';
COMMENT ON COLUMN PRD_TIPO.PTI_MARGEM IS 'MARGEM DE VENDA - CALCULADO';
COMMENT ON COLUMN PRD_TIPO.PTI_MARGEMOF IS 'MARGEM DE OFERTA';
COMMENT ON COLUMN PRD_TIPO.PTI_ATUALIZAR_ESTOQUE IS 'PRODUTOS DESSE TIPO ATUALIZA ESTOQUE';



UPDATE PRD0000
SET PRD_PER_LUCRO = PRD_MARGEMVENDA
	,PRD_PER_ICMS = 0 
	,PRD_PER_PISCONFINS = 0  
	,PRD_PER_IPI =0
	,PRD_PER_FRETE  = 0 
	,PRD_PER_OUTROS  = 0 ;

commit work;

CREATE OR ALTER VIEW TABELAPRECOS (tab_registro, seq , EMP_CODIGO, EMP_CODIGOPRD,prd_refer, prd_codigo, NOME ,PRD_PVENDA, PRD_PERC_COMISSAO, PRD_PERC_VENDA )
AS 
SELECT  pm.emp_codigo||prd_codigo ||  1 AS tab_registro, 1, pm.emp_codigo,PR.EMP_CODIGO, prd_refer, prd_codigo, PMT_TABNOME1,CAST(PRD_PVENDA AS NUMERIC(18,5)), PRD_PERC_COMISSAO, PRD_PERC_VENDA
FROM PRMT0001 pm , PRD0000 pr
UNION ALL
SELECT pm.emp_codigo||prd_codigo || 2,2, pm.emp_codigo,PR.EMP_CODIGO, prd_refer, prd_codigo, PMT_TABNOME2,CAST(PRD_PVENDA2 AS NUMERIC(18,5)), PRD_PERC_COMISSAO2, PRD_PERC_VENDA2
FROM PRMT0001 pm , PRD0000 pr
UNION ALL 
SELECT pm.emp_codigo||prd_codigo || 3, 3, pm.emp_codigo,PR.EMP_CODIGO, prd_refer, prd_codigo, PMT_TABNOME3,CAST(PRD_PVENDA3 AS NUMERIC(18,5)), PRD_PERC_COMISSAO3, PRD_PERC_VENDA3
FROM PRMT0001 pm , PRD0000 pr
UNION all
SELECT pm.emp_codigo||prd_codigo || 4, 4, pm.emp_codigo,PR.EMP_CODIGO, prd_refer, prd_codigo, PMT_TABNOME4,CAST(PRD_PVENDA4 AS NUMERIC(18,5)), PRD_PERC_COMISSAO4, PRD_PERC_VENDA4
FROM PRMT0001 pm , PRD0000 pr
UNION ALL
SELECT pm.emp_codigo||prd_codigo || 5,5, pm.emp_codigo,PR.EMP_CODIGO, prd_refer, prd_codigo, PMT_TABNOME5,CAST(PRD_PVENDA5 AS NUMERIC(18,5)), PRD_PERC_COMISSAO5, PRD_PERC_VENDA5
FROM PRMT0001 pm , PRD0000 pr
UNION ALL 
SELECT pm.emp_codigo||prd_codigo || 6, 6, pm.emp_codigo,PR.EMP_CODIGO, prd_refer, prd_codigo, PMT_TABNOME6,CAST(PRD_PVENDA6 AS NUMERIC(18,5)), PRD_PERC_COMISSAO6, PRD_PERC_VENDA6
FROM PRMT0001 pm , PRD0000 pr;


ALTER TABLE OCP_IT01 ADD PRD_UND varchar(3);
comment ON COLUMN OCP_IT01.prd_und IS 'UNIDADE DE MEDIDA DO PRODUTO NA COMPRA';


COMMENT ON COLUMN PRMT0001.PMT_COMIS_REP IS 'COMISSAO PADRAO DO REPRESENTANTE'; 
COMMENT ON COLUMN PRMT0001.PMT_COMIS_SUP IS 'COMISSAO PADRAO DO SUPERVISOR';
COMMENT ON COLUMN PRMT0001.PMT_COMIS_GER IS 'COMISSAO PADRAO DO GERENTE';
COMMENT ON COLUMN PRMT0001.PMT_COMIS_PROD IS 'UTILIZAR SISTEMA DE COMISSAO POR PRODUTO (PRODUTO/TIPO/GRUPO)';
COMMENT ON COLUMN PRMT0001.PMT_COMIS_ESCALA IS 'UTILIZAR SISTEMA DE COMISSAO POR PRODUTO (TABELA ESCALONADA)';
COMMENT ON COLUMN PRMT0001.PMT_COMIS_SIMPLES IS 'UTILIZAR SISTEMA DE COMISSAO POR PRODUTO (TABELA SIMPLES)';
COMMENT ON COLUMN PRMT0001.PMT_PAGAR_COMISSAO_VERBA IS 'PAGAR COMISSAO / VERBA POR MULTIPLAS TABELAS E PRAZO';
COMMENT ON COLUMN PRMT0001.PMT_COMIS_GRP IS  'UTILIZAR SISTEMA DE COMISSAO POR GRUPO PADRAO';
COMMENT ON COLUMN PRMT0001.PMT_PERC_COMISSAO1 IS 'COMISSAO 1 PADRAO DO PRODUTO NA TABELA ESCALONADA';
COMMENT ON COLUMN PRMT0001.PMT_PERC_COMISSAO2 IS 'COMISSAO 2 PADRAO DO PRODUTO NA TABELA ESCALONADA';
COMMENT ON COLUMN PRMT0001.PMT_PERC_COMISSAO3 IS 'COMISSAO 3 PADRAO DO PRODUTO NA TABELA ESCALONADA';
COMMENT ON COLUMN PRMT0001.PMT_PERC_COMISSAO4 IS 'COMISSAO 4 PADRAO DO PRODUTO NA TABELA ESCALONADA';
COMMENT ON COLUMN PRMT0001.PMT_PERC_COMISSAO5 IS 'COMISSAO 5 PADRAO DO PRODUTO NA TABELA ESCALONADA';
COMMENT ON COLUMN PRMT0001.PMT_PERC_COMISSAO6 IS 'COMISSAO 6 PADRAO DO PRODUTO NA TABELA ESCALONADA';

/*
ALTER TABLE PRD0000_ALTER ALTER COLUMN PRDA_VALOR_ANTERIOR TYPE VARCHAR(100);
ALTER TABLE PRD0000_ALTER ALTER COLUMN PRDA_VALOR_NOVO TYPE VARCHAR(100);

*/


-- AJUSTAR ERRO DE KIT E AGRUPAMENTO
UPDATE PED_IT01
SET PRF_PRODUTO_AGREGADO = 'S'
WHERE PRF_REGISTRO_VINCULADO > 0 
AND (PRF_PRODUTO_AGREGADO = 'N' OR PRF_PRODUTO_AGREGADO ='' OR PRF_PRODUTO_AGREGADO IS NULL);
