UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.540 patch 1',
       VERSAOSISTEMA.DATA   = '08.01.2020',
	    VERSAO = '3.0.9.540'
 where VERSAOSISTEMA.CODIGO = 1;

 commit work;

-- ERRO ACONTECE SOMENTE NA DOAÇÃO
UPDATE PED0000 p
  SET PED_VLFATURADO = PED_VLTOTAL_BRUTO
  WHERE (EXISTS (SELECT * FROM FAT0000 f WHERE p.PED_CODIGO = f.PED_CODIGO AND p.EMP_CODIGO = f.EMP_CODIGO)   OR PED_SITUACAO = 'T')
  AND (SELECT  PMT_PEDIDO_DOACAO FROM PRMT0001 WHERE PRMT0001.EMP_CODIGO = P.EMP_CODIGO) = 'S' ;
  
  
  COMMIT WORK;
  
  
ALTER TABLE NF0001 ALTER COLUMN NF_OBS_OPER TYPE VARCHAR(200);
ALTER TABLE NF0001 ALTER COLUMN  NF_OBS_OPER_AVISO2 TYPE VARCHAR(200);