UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.538 patch 3',
       VERSAOSISTEMA.DATA   = '12.11.2019',
	    VERSAO = '3.0.9.538'
 where VERSAOSISTEMA.CODIGO = 1;


commit work;

  
CREATE INDEX NF0001_HISTORICO_IDX1
ON NF0001_HISTORICO (EMP_CODIGO,NF_REGITRO,NFM_REGISTRO);


ALTER TABLE NF0001 ADD NF_DENEGADA_CANCELADA VARCHAR(1);
COMMENT ON COLUMN ENF0001.ENF_MODALIDADE IS 'TIPO DE PAGAMENTO 0 - A VISTA, 1 - PRAZO, 2 - OUTROS, 3 - CARTAO DE CREDITO , 4 - CARTÃO DEBITO, 9 - SEM PAGAMENTO';