UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.565',
    VERSAOSISTEMA.DATA   = '31.01.2022',
	VERSAO = '3.0.9.565'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE EMP0000 ADD EMP_UTILIZAR_API_ACBR CHAR(1) DEFAULT 'N';
ALTER TABLE EMP0000 ADD EMP_USUARIO_API_ACBR VARCHAR(50) ;
ALTER TABLE EMP0000 ADD EMP_TOKEN_API_ACBR VARCHAR(60);
commit work;

ALTER TABLE CUSTOINDUST ADD CIO_PV_TEMP NUMERIC(15,4);
UPDATE CUSTOINDUST SET CIO_PV_TEMP = CIO_PV ;
ALTER TABLE CUSTOINDUST DROP CIO_PV;
ALTER TABLE CUSTOINDUST ALTER COLUMN CIO_PV_TEMP TO CIO_PV;
commit work;


