UPDATE  VERSAOSISTEMA SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.502', VERSAO = '3.0.9.502',
       VERSAOSISTEMA.DATA   = '31.01.2017'
 where VERSAOSISTEMA.CODIGO = 1;
 
COMMIT WORK;

ALTER TABLE ENF0001 ADD ENF_ATUALIZA_ESTOQUE VARCHAR(1);
ALTER TABLE precos0001 ALTER COLUMN PRE_MARGEM type NUMERIC(18,2);

UPDATE ENF0001 
SET ENF_ATUALIZA_ESTOQUE = (SELECT FIRST 1 ENF_ATUALIZA_ESTOQUE FROM ENF_IT01 WHERE ENF_IT01.ENF_IT_NOTANUMBER = ENF0001.ENF_NOTANUMBER );

SET TERM ^ ;
execute block as
  declare variable v_MARGEM NUMERIC(18,5);
  declare variable v_PRECO NUMERIC(18,6);
  DECLARE VARIABLE v_PCUSTO NUMERIC(18,5);
  DECLARE VARIABLE vid integer; 
BEGIN
    
  FOR
    select a.id,PRE_PRECO,  b.PRD_PCUSTO
    From precos0001 A
         join prd0000 b on b.prd_codigo=a.prd_codigo
    WHERE PRE_PRECO <> 0 
    AND PRE_PRECO IS NOT NULL 
    AND b.PRD_PCUSTO  <> 0 
    and b.PRD_PCUSTO is not null
    INTO vid,v_preco,v_pcusto
    DO
    BEGIN
      v_margem = (v_preco/v_pcusto)-1 ;
      v_margem = round(v_margem,4) ;
      if (v_margem< 100000) then
          v_margem = v_margem * 100 ;
      execute STATEMENT 'update precos0001 set pre_margem = '|| cast(v_margem AS varchar(20)) || ' where id = '||cast(vid as varchar(20));
    END
    
end
^
SET TERM ; ^

COMMIT WORK;


 ALTER TABLE prd_tipo ADD PTI_DISPONIVEL_VENDAS VARCHAR(1);
 COMMENT ON COLUMN PRD_TIPO.PTI_DISPONIVEL_VENDAS IS 'DISPONIBILIZAR PARA VENDAS';
 COMMENT ON COLUMN ENF0001.ENF_ATUALIZA_ESTOQUE IS 'NOTA ATUALIZA ESTOQUE';
  
 UPDATE PRD_TIPO
    SET PTI_DISPONIVEL_VENDAS = 'S';
	

ALTER TABLE PRMT0001 ADD PMT_PRODUZIR_MAIS_OP VARCHAR(1);

COMMENT ON COLUMN PRMT0001.PMT_PRECOCOMIPI IS 'USAR O PRECO DE CUSTO COM IPI';  
COMMENT ON COLUMN PRMT0001.PMT_PRODUZIR_MAIS_OP IS 'APONTAMENTO ACEITA CONCLUIR QTDE MAIOR QUE SOLICITADA NA OP';
COMMENT ON COLUMN PRMT0001.PMT_OPS_CONCLUIR IS 'GRAVAR SAIDAS NO KARDEX SEM CONTROLAR EMPENHO DO ESTOQUE';
comment ON COLUMN PRMT0001.PMT_OPSPRODUZIR IS 'GERAR CONSUMO DE  OPS DIRETO PARA PRODUCAO';
comment ON COLUMN PRMT0001.PMT_CELULAPROD IS  'UTILIZAR SISTEMA DE PRODUCAO POR CELULAS';
COMMENT ON COLUMN PRMT0001.PMT_PA IS 'CODIGO DO PRODUTO ACABADO';
COMMENT ON COLUMN PRMT0001.PMT_PI IS 'CODIGO DO PRODUTO INTERMEDIARIO';

UPDATE PRMT0001
SET PMT_PRODUZIR_MAIS_OP = 'N';	

CREATE OR ALTER VIEW OPE0000_VIEW_PESQUISA (OPE_CODIGO, CFOP, OPE_NATUREZA, OPE_DESCRI, OPE_TIPO, OPE_DENTRO, OPE_ATIVA, EMP_CODIGO, OPE_SERVICO)
AS
select  ope_codigo,
        ope_natureza||' - '||ope_descri as Cfop,
        ope_natureza,
        ope_descri, ope_tipo, OPE_DENTRO, OPE_ATIVA, emp_codigo, OPE_SERVICO
from ope0000
WHERE OPE_ATIVA = 'S';

COMMENT ON VIEW OPE0000_VIEW_PESQUISA IS 'PESQUISA COMBO DAS OPERACOES - CFOP';