UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.546 patch 2',
    VERSAOSISTEMA.DATA   = '14.07.2020',
	VERSAO = '3.0.9.546'
 where VERSAOSISTEMA.CODIGO = 1;
 
commit work;

ALTER TABLE ITEM_ORDEMPRODUCAO ADD IOP_PREFIXO VARCHAR(20); 


UPDATE ITEM_ORDEMPRODUCAO
SET IOP_PREFIXO = replace ( SUBSTRING(IOP_NORDEM FROM 1 for POSITION('-' IN IOP_NORDEM)),'-','') 
  WHERE ORE_CODIGO IS null;

COMMIT WORK;  
 
CREATE INDEX ITEM_ORDEMPRODUCAO_NORDEM_IDX ON ITEM_ORDEMPRODUCAO (IOP_NORDEM);
CREATE INDEX ITEM_ORDEMPRODUCAO_PREFIXO_IDX ON ITEM_ORDEMPRODUCAO (IOP_PREFIXO);  


UPDATE DEMANDA_PRODUCAO DEP 
SET DEP_SITUACAO  ='C'
WHERE EXISTS 
 (SELECT 1 FROM ITEM_ORDEMPRODUCAO IOP WHERE DEP.IOP_CODIGO = IOP.IOP_CODIGO AND IOP_STATUS ='F');

UPDATE DEMANDA_PRODUCAO DEP 
SET DEP_SITUACAO  ='I'
WHERE EXISTS 
 (SELECT 1 FROM ITEM_ORDEMPRODUCAO IOP WHERE DEP.IOP_CODIGO = IOP.IOP_CODIGO AND IOP_STATUS ='I');


UPDATE DEMANDA_PRODUCAO DEP 
SET DEP_SITUACAO  ='E'
WHERE EXISTS 
 (SELECT 1 FROM ITEM_ORDEMPRODUCAO IOP WHERE DEP.IOP_CODIGO = IOP.IOP_CODIGO AND IOP_STATUS ='L');
 
 COMMIT WORK;