ALTER TABLE OPV0000
    ADD OPV_BONIFICACAO CHAR(1);

COMMIT WORK;	
	
ALTER TABLE REP0000
    ADD GERAR_VERBA VARCHAR(1) DEFAULT '1';
	
COMMIT WORK;	

update rep0000 set gerar_verba = '1';

COMMIT WORK;		
	
ALTER TABLE CONTA_CORRENTE
    ALTER VALOR TYPE DECIMAL6,
    ALTER VALOR_UTILIZADO TYPE DECIMAL6;
 
COMMIT WORK;	
	
UPDATE  VERSAOSISTEMA SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.0.482',
       VERSAOSISTEMA.DATA   = '03.04.2017'
 where VERSAOSISTEMA.CODIGO = 1;
 
COMMIT WORK;

 