UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.567 patch 2',
    VERSAOSISTEMA.DATA   = '18.04.2022',
	VERSAO = '3.0.9.567'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;


ALTER TABLE USUARIO_PARAMETRO ADD USP_AUTORIZA_RETIRADA_MATERIAL CHAR(1);
ALTER TABLE USUARIO_PARAMETRO ADD USP_REALIZA_RETIRADA_MATERIAL CHAR(1);

CREATE SEQUENCE GEN_REQUISICAO_MATERIAL;
  ALTER SEQUENCE GEN_REQUISICAO_MATERIAL RESTART WITH 100;
  COMMENT ON SEQUENCE GEN_REQUISICAO_MATERIAL IS 'Gerador de Códigos para as Requisições de Materiais para retirada do Estoque';
  
CREATE SEQUENCE GEN_REQUISICAO_MATERIAL_ITEM;
  ALTER SEQUENCE GEN_REQUISICAO_MATERIAL_ITEM RESTART WITH 100;
  COMMENT ON SEQUENCE GEN_REQUISICAO_MATERIAL_ITEM IS 'Gerador de Códigos para os Itens das Requisições de Materiais para retirada do Estoque';

 CREATE SEQUENCE GEN_REQUISICAO_MATERIAL_AUT;
  ALTER SEQUENCE GEN_REQUISICAO_MATERIAL_AUT RESTART WITH 100;
  COMMENT ON SEQUENCE GEN_REQUISICAO_MATERIAL_AUT IS 'Gerador de Códigos para as Autorizações dos Itens das Requisições de Materiais para retirada do Estoque';

CREATE TABLE REQUISICAO_MATERIAL (
	REM_CODIGO INT PRIMARY KEY
);
  COMMENT ON TABLE REQUISICAO_MATERIAL IS 'Requisições de Materiais para retirada do Estoque';
  COMMENT ON COLUMN REQUISICAO_MATERIAL.REM_CODIGO is 'Chave Primária da Requisição de Material';
ALTER TABLE REQUISICAO_MATERIAL ADD EMP_CODIGO VARCHAR(3);
  COMMENT ON COLUMN REQUISICAO_MATERIAL.EMP_CODIGO is 'Empresa do Produto Requisitado';
ALTER TABLE REQUISICAO_MATERIAL ADD AMX_CODIGO VARCHAR(4);
  COMMENT ON COLUMN REQUISICAO_MATERIAL.AMX_CODIGO is 'Código do Almoxarifado';
ALTER TABLE REQUISICAO_MATERIAL ADD REM_DATA DATE;
  COMMENT ON COLUMN REQUISICAO_MATERIAL.REM_DATA is 'Data da Requisição';
ALTER TABLE REQUISICAO_MATERIAL ADD REM_REQUISITANTE VARCHAR(255);
  COMMENT ON COLUMN REQUISICAO_MATERIAL.REM_REQUISITANTE is 'Código do Almoxarifado';
ALTER TABLE REQUISICAO_MATERIAL ADD SET_CODIGO INT;
  COMMENT ON COLUMN REQUISICAO_MATERIAL.SET_CODIGO is 'Código do Setor';
ALTER TABLE REQUISICAO_MATERIAL ADD REM_OBSERVACAO BLOB SUB_TYPE TEXT ;
  COMMENT ON COLUMN REQUISICAO_MATERIAL.REM_OBSERVACAO is 'Observações da Requisição de Material';
ALTER TABLE REQUISICAO_MATERIAL ADD REM_STATUS VARCHAR(1) DEFAULT 'P';
  COMMENT ON COLUMN REQUISICAO_MATERIAL.REM_STATUS is '[P] Pendente / [A] Atendido / [R] Parcial';
 
CREATE TABLE REQUISICAO_MATERIAL_ITEM (
	RMI_CODIGO INT PRIMARY KEY
);
  COMMENT ON TABLE REQUISICAO_MATERIAL_ITEM IS 'Itens das Requisições de Materiais para retirada do Estoque';
  COMMENT ON COLUMN REQUISICAO_MATERIAL_ITEM.RMI_CODIGO is 'Chave Primária do Item da Requisição de Material';
ALTER TABLE REQUISICAO_MATERIAL_ITEM ADD REM_CODIGO INT;
  COMMENT ON COLUMN REQUISICAO_MATERIAL_ITEM.REM_CODIGO is 'Chave primária do cabeçalho da Requisição de Material';
ALTER TABLE REQUISICAO_MATERIAL_ITEM ADD PRD_REFER VARCHAR(20);
  COMMENT ON COLUMN REQUISICAO_MATERIAL_ITEM.PRD_REFER is 'Referência do Produto Requisitado';
ALTER TABLE REQUISICAO_MATERIAL_ITEM ADD RMI_QUANTIDADE NUMERIC (18,5);
  COMMENT ON COLUMN REQUISICAO_MATERIAL_ITEM.RMI_QUANTIDADE IS 'Quantidade Requisitada';


 CREATE TABLE REQUISICAO_MATERIAL_AUT (
	RMA_CODIGO INT PRIMARY KEY
);
  COMMENT ON TABLE REQUISICAO_MATERIAL_AUT IS 'Autorização dos Itens das Requisições de Materiais para retirada do Estoque';
  COMMENT ON COLUMN REQUISICAO_MATERIAL_AUT.RMA_CODIGO is 'Chave Primária da Autorização do Item da Requisição de Material';
ALTER TABLE REQUISICAO_MATERIAL_AUT ADD RMI_CODIGO INT;
  COMMENT ON COLUMN REQUISICAO_MATERIAL_AUT.RMI_CODIGO is 'Código do item do Material Requisitado';
ALTER TABLE REQUISICAO_MATERIAL_AUT ADD USU_NOME VARCHAR(40);
  COMMENT ON COLUMN REQUISICAO_MATERIAL_AUT.USU_NOME is 'Nome do Usuário que autorizou o Material Requisitado';
ALTER TABLE REQUISICAO_MATERIAL_AUT ADD RMA_SITUACAO VARCHAR(1) DEFAULT 'N';
  COMMENT ON COLUMN REQUISICAO_MATERIAL_AUT.RMA_SITUACAO is 'Situação da Autorização do Material Requisitado [A] = Autorizado / [N] = Não Autorizado';
ALTER TABLE REQUISICAO_MATERIAL_AUT ADD RMA_STATUS VARCHAR(1) DEFAULT 'P';
  COMMENT ON COLUMN REQUISICAO_MATERIAL_AUT.RMA_STATUS is 'Status da Autorização do Material Requisitado [C] = Concluído / [P] = Pendente';
ALTER TABLE REQUISICAO_MATERIAL_AUT ADD RMA_DATA DATE;
  COMMENT ON COLUMN REQUISICAO_MATERIAL_AUT.RMA_DATA is 'Data da Autorização';
 
