UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.572 patch 1',
    VERSAOSISTEMA.DATA   = '16.09.2022',
	VERSAO = '3.0.9.572'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE PRMT0001 ADD PMT_FATURA_SEM_PESO VARCHAR(1) DEFAULT 'S';
COMMENT ON COLUMN PRMT0001.PMT_FATURA_SEM_PESO is ' Permitir Faturamento sem Informar Peso na Nota Fiscal';
UPDATE PRMT0001 SET PMT_FATURA_SEM_PESO = 'S' WHERE PMT_FATURA_SEM_PESO IS NULL;
COMMIT WORK; 

CREATE GENERATOR GEN_REGRA_FISCAL_PROD_CAP;
CREATE TABLE REGRA_FISCAL_PROD_CAP (
	RFP_CODIGO INT PRIMARY KEY NOT NULL
);
COMMENT ON TABLE REGRA_FISCAL_PROD_CAP is 'Tabela Auxiliar da Regra Fiscal do Produto e Capacidade';
COMMENT ON COLUMN REGRA_FISCAL_PROD_CAP.RFP_CODIGO  is 'Chave primária da Regra Fiscal do Produto e Capacidade';
ALTER TABLE REGRA_FISCAL_PROD_CAP ADD OPR_REGISTRO INTEGER;
COMMENT ON COLUMN REGRA_FISCAL_PROD_CAP.OPR_REGISTRO  is 'Chave Primária das Regras Fiscais para CFOP e NCM';
ALTER TABLE REGRA_FISCAL_PROD_CAP ADD PRD_REFER VARCHAR(20);
COMMENT ON COLUMN REGRA_FISCAL_PROD_CAP.PRD_REFER  is 'Referência do Produto';
ALTER TABLE REGRA_FISCAL_PROD_CAP ADD CAP_CODIGO INTEGER;
COMMENT ON COLUMN REGRA_FISCAL_PROD_CAP.CAP_CODIGO  is 'Chave primária da Capacidade';

