UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.567 patch 5',
    VERSAOSISTEMA.DATA   = '28.04.2022',
	VERSAO = '3.0.9.567'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE ENF_IT01 ADD ENF_ORIGEM_MERCADORIA INTEGER;

