UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.545 patch 6',
    VERSAOSISTEMA.DATA   = '09.06.2020',
	VERSAO = '3.0.9.545'
 where VERSAOSISTEMA.CODIGO = 1;

commit work;



UPDATE ITEM_ORDEMPRODUCAO IOP  
SET IOP_DATA_CONCLUSAO = 
          (SELECT MAX(PCP_DATAFIM)  FROM PROCESSOS_PRODUCAO POP
			WHERE OPE_CODIGO = ( 
								SELECT OPE_CODIGO FROM PROCESSOS_OPERACOES PO
								WHERE PRO_CODIGO = IOP.PRO_CODIGO
								AND POP_SEQ = (SELECT MAX(POP_SEQ) FROM PROCESSOS_OPERACOES PRO
								                WHERE PRO.PRO_CODIGO = PO.PRO_CODIGO))
			AND IOP.IOP_CODIGO = POP.IOP_CODIGO);
			
COMMIT WORK;			

UPDATE ITEM_ORDEMPRODUCAO IOP
SET IOP_LEADTIME =  IOP_DATA_CONCLUSAO-(SELECT OPR_EMISSAO FROM ORDEMPRODUCAO OPR  WHERE IOP.OPR_CODIGO = OPR.OPR_CODIGO)
WHERE IOP_DATA_CONCLUSAO IS NOT NULL;


COMMIT WORK;	



ALTER TABLE EMP0000 ADD EMP_TIPOCERTIFICADO INTEGER; 
COMMENT ON COLUMN EMP0000.EMP_TIPOCERTIFICADO IS 'TIPO DE CERTIFICADO 1: A1 ; 3 : A3 ';

UPDATE EMP0000 
SET EMP_TIPOCERTIFICADO = 1 ;

COMMIT WORK;