UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.555 patch 4',
    VERSAOSISTEMA.DATA   = '27.04.2021',
	VERSAO = '3.0.9.555'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;


ALTER TABLE MOLA_MATERIA
ALTER COLUMN MMO_DIAMETRO_ARAME TYPE VARCHAR(50);

ALTER TABLE OPV0000 ADD OPV_INATIVAR_TIPO_PEDIDO VARCHAR(1);
UPDATE OPV0000 SET OPV_INATIVAR_TIPO_PEDIDO = 'N';
commit work;

ALTER TABLE TAREFAS_CRM ALTER COLUMN TRF_EMAILCONTATO TYPE VARCHAR(255);

