UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.564 patch 2',
    VERSAOSISTEMA.DATA   = '19.01.2022',
	VERSAO = '3.0.9.564'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE EMP0000 ADD EMP_USAR_MAIL_ACBR VARCHAR(1);
UPDATE EMP0000 SET EMP_USAR_MAIL_ACBR = 'S';
commit work;

ALTER TABLE USUARIO_PARAMETRO ADD USP_VISUALIZA_PEDIDOS_CRM VARCHAR(1);

ALTER TABLE FABRICACAO ADD FAB_DIAS NUMERIC(15, 5) DEFAULT 0;
UPDATE FABRICACAO SET FAB_DIAS = 0;
ALTER TABLE PRMT0001 ADD PMT_HABILITA_MEDIDAPRD_DESC1 VARCHAR(15);
ALTER TABLE PRMT0001 ADD PMT_HABILITA_MEDIDAPRD_DESC2 VARCHAR(15);
ALTER TABLE PRMT0001 ADD PMT_HABILITA_MEDIDAPRD_DESC3 VARCHAR(15);
ALTER TABLE PRMT0001 ADD PMT_HABILITA_MEDIDAPRD_DESC4 VARCHAR(15);
UPDATE PRMT0001 SET PMT_HABILITA_MEDIDAPRD_DESC1 = 'Interno:' WHERE PMT_HABILITA_MEDIDAPRD_DESC1 IS NULL;
UPDATE PRMT0001 SET PMT_HABILITA_MEDIDAPRD_DESC2 = 'Externo:' WHERE PMT_HABILITA_MEDIDAPRD_DESC2 IS NULL;
UPDATE PRMT0001 SET PMT_HABILITA_MEDIDAPRD_DESC3 = 'Altura 1:' WHERE PMT_HABILITA_MEDIDAPRD_DESC3 IS NULL;
UPDATE PRMT0001 SET PMT_HABILITA_MEDIDAPRD_DESC4 = 'Altura 2:' WHERE PMT_HABILITA_MEDIDAPRD_DESC4 IS NULL;
COMMIT;
CREATE GENERATOR GEN_HIST_OPER_PROC_FAB;
CREATE TABLE HIST_OPER_PROC_FAB (
  OPF_CODIGO INT NOT NULL PRIMARY KEY,
  FAB_CODIGO INT,
  OPF_DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  OPF_DESCRICAO VARCHAR(255),
  USU_LOGIN VARCHAR(15)
);
CREATE INDEX IDX_HIST_OPER_PROC_FAB ON HIST_OPER_PROC_FAB COMPUTED BY (FAB_CODIGO);




