UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.582 patch 2',
    VERSAOSISTEMA.DATA   = '13.07.2023',
	VERSAO = '3.0.9.582'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE FORMA_PAGAMENTO ADD FPG_BOLETO VARCHAR(1) DEFAULT 'S';
UPDATE FORMA_PAGAMENTO SET FPG_BOLETO = 'S' WHERE FPG_BOLETO IS NULL;
COMMIT WORK;


