-- estoque antigo, nao usamos mais
DELETE FROM PRD_ENSA;
COMMIT WORK;


update RDB$RELATION_FIELDS set
RDB$FIELD_SOURCE = 'DECIMAL8'
where (RDB$FIELD_NAME = 'FIR_INDICE_REAL') and
(RDB$RELATION_NAME = 'FIN_RATEIO');
COMMIT WORK;

update RDB$RELATION_FIELDS set
RDB$FIELD_SOURCE = 'DECIMAL8'
where (RDB$FIELD_NAME = 'FIR_INDICE') and
(RDB$RELATION_NAME = 'FIN_RATEIO');
COMMIT WORK;


ALTER TABLE OSV0001
ADD OSV_DTENTREGA TIMESTAMP;
COMMIT WORK;

ALTER TABLE PSV_IT02
ADD PS2_DTENTREGA TIMESTAMP;
COMMIT WORK;


UPDATE  VERSAOSISTEMA SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.0.489',
       VERSAOSISTEMA.DATA   = '20.06.2017'
 where VERSAOSISTEMA.CODIGO = 1;
 
COMMIT WORK;
