UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.583',
    VERSAOSISTEMA.DATA   = '08.08.2023',
	VERSAO = '3.0.9.583'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE PRD0000 ADD PRD_CAPACIDADE_OBRIGATORIA VARCHAR(1) DEFAULT 'N';
COMMENT ON COLUMN PRD0000.PRD_CAPACIDADE_OBRIGATORIA IS 'Obriga a escolha da capacidade do produto no item do pedido de venda';
UPDATE PRD0000 SET PRD_CAPACIDADE_OBRIGATORIA = 'N' WHERE PRD_CAPACIDADE_OBRIGATORIA IS NULL;
commit work;

