
UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.535 patch 5',
       VERSAOSISTEMA.DATA   = '17.08.2019',
	    VERSAO = '3.0.9.535'
 where VERSAOSISTEMA.CODIGO = 1;
 
 commit work;

 

ALTER TABLE PRMT0001 ADD PMT_FATURA_MULTIEMPRESA VARCHAR(1);
COMMENT ON COLUMN PRMT0001.PMT_FATURA_MULTIEMPRESA IS 'FATURAMENTO MULTIEMPRESA';

UPDATE PRMT0001
SET PMT_FATURA_MULTIEMPRESA = 'N';  


commit work;