SET TERM ^ ;

CREATE TRIGGER TRG_IBS_ID FOR IBS
BEFORE INSERT
AS
BEGIN
  IF (NEW.IBS_ID IS NULL) THEN
    NEW.IBS_ID = NEXT VALUE FOR GEN_IBS_ID;
END^

CREATE TRIGGER TRG_CBS_ID FOR CBS
BEFORE INSERT
AS
BEGIN
  IF (NEW.CBS_ID IS NULL) THEN
    NEW.CBS_ID = NEXT VALUE FOR GEN_CBS_ID;
END^

SET TERM ; ^
