ALTER TABLE for0000
    ADD COLABORADOR VARCHAR(50) ,
    ADD ENDERECO_COL VARCHAR(100) ,
    ADD DATA_NASC TIMESTAMP ,
    ADD LOCAL_NASC VARCHAR(50) ,
    ADD NACIONALIDADE VARCHAR(30) ,
    ADD ESTADO_CIVIL VARCHAR(15) ,
    ADD PAI VARCHAR(50) ,
    ADD MAE VARCHAR(50) ,
    ADD RG VARCHAR(12) ,
    ADD RG_EMISSAO TIMESTAMP ,
    ADD ORGAO_UF VARCHAR(10) ,
    ADD TITULO_ELEITORAL VARCHAR(15) ,
    ADD ZONA INTEGER ,
    ADD SECAO INTEGER ,
    ADD ORGAO_CLASSE VARCHAR(10) ,
    ADD CTPS INTEGER ,
    ADD SERIE VARCHAR(10) ,
    ADD CTPS_EXPEDICAO TIMESTAMP ,
    ADD CTPS_UF VARCHAR(3) ,
    ADD CPF VARCHAR(14) ,
    ADD HABILITACAO VARCHAR(15) ,
    ADD HABILITACAO_CATEG VARCHAR(2) ,
    ADD DOC_MILITAR VARCHAR(15) ,
    ADD DOC_MILITAR_CATEG VARCHAR(5) ,
    ADD COR VARCHAR(10) ,
    ADD SEXO VARCHAR(9) ,
    ADD GRAU_INSTRUCAO VARCHAR(50) ,
    ADD DEFICIENCIA CHAR(1) ,
    ADD FONE_RESIDENCIAL VARCHAR(10) ,
    ADD FONE_CELULAR VARCHAR(15) ,
    ADD CARGO VARCHAR(50) ,
    ADD FUNCAO VARCHAR(50) ,
    ADD CBO INTEGER ,
    ADD ADMISSAO TIMESTAMP ,
    ADD SALARIO DECIMAL6 ,
    ADD SALARIO_POR VARCHAR(10) ,
    ADD HORA_ENTRADA TIME ,
    ADD HORA_SAIDA TIME ,
    ADD SAIDA_INTERVALO TIME ,
    ADD ENTRADA_INTERVALO TIME ,
    ADD FGTS_DATA_OPCAO TIMESTAMP ,
    ADD FGTS_CONTA_BANCO VARCHAR(50) ,
    ADD FGTS_DATA_RETIFICACAO TIMESTAMP ,
    ADD PIS_DATA TIMESTAMP ,
    ADD PIS_NUMERO VARCHAR(20) ,
    ADD PIS_DOMINIO_BANCARIO VARCHAR(50) ,
    ADD PIS_NUM_BANCO INTEGER ,
    ADD PIS_AGENCIA INTEGER ,
    ADD PIS_END_AGENCIA VARCHAR(50) ,
    ADD BENEFICIARIOS VARCHAR(500) ,
    ADD SALARIO_ALTERACOES VARCHAR(500) ,
    ADD FERIAS_PERIODO_AQUISITIVO VARCHAR(500) ,
    ADD FERIAS_PERIODO_GOZO VARCHAR(500) ,
    ADD ACIDENTE_TRABALHO VARCHAR(500) ,
    ADD DOENCA_PROFISSIONAL VARCHAR(500) ,
    ADD CONTRIBUICAO_SINDICATO VARCHAR(500) ,
    ADD RESCISAO_DATA TIMESTAMP ,
    ADD RESCISAO_TIPO VARCHAR(50) ;

COMMIT WORK;

ALTER TABLE PED0000
    ADD PED_PLACA VARCHAR(7);
    
COMMIT WORK;
    
UPDATE  VERSAOSISTEMA SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.0.484',
       VERSAOSISTEMA.DATA   = '26.04.2017'
 where VERSAOSISTEMA.CODIGO = 1;
 
COMMIT WORK;