UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.567 patch 1',
    VERSAOSISTEMA.DATA   = '08.04.2022',
	VERSAO = '3.0.9.567'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE PRMT0001 ADD PMT_NAT_OPER_PADRAO VARCHAR(1) DEFAULT 'S';
UPDATE PRMT0001 SET PMT_NAT_OPER_PADRAO ='S' WHERE PMT_NAT_OPER_PADRAO IS NULL;
COMMIT WORK;


