UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.547 patch 2',
    VERSAOSISTEMA.DATA   = '19.08.2020',
	VERSAO = '3.0.9.547'
 where VERSAOSISTEMA.CODIGO = 1;
 
commit work;


 UPDATE PRMT0001
 SET PMT_BTN_ALT_REFER = 'N';


commit work;


ALTER TABLE PRMT0001 ADD PMT_HABILITA_ENVASE VARCHAR(2);
COMMENT ON COLUMN PRMT0001.PMT_HABILITA_ENVASE IS 'HABILITA ENVASE';

UPDATE PRMT0001
SET PMT_HABILITA_ENVASE = 'N';

COMMIT;

