SET TERM ^ ;

CREATE OR ALTER TRIGGER NF_IT01_BI0
FOR NF_IT01
ACTIVE BEFORE INSERT
AS
    DECLARE VARIABLE cst CHAR(2);
BEGIN
    /* Geração automática do registro */
    IF (NEW.NF_REGISTRO IS NULL) THEN
        NEW.NF_REGISTRO = GEN_ID(GEN_NF_IT01, 1);
END^

SET TERM ; ^
