UPDATE  VERSAOSISTEMA
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.536',
    VERSAOSISTEMA.DATA   = '03.08.2019',
    VERSAO = '3.0.9.536'
where VERSAOSISTEMA.CODIGO = 1;

commit work;

CREATE INDEX EXPEDICAO_IDX1 ON EXPEDICAO (PED_REGISTRO);

CREATE UNIQUE INDEX EMP0000_IDX1 ON EMP0000 (EMP_CODIGO);
CREATE INDEX HISTORICO_EXPE_IDX1 ON HISTORICO_EXPE (PED_CODIGO,SITEXP);

CREATE INDEX HISTORICO_EXPE_IDX2 ON HISTORICO_EXPE (DATASIT);
CREATE INDEX PED0000_IDX2 ON PED0000 (PCX_CODIGO);
CREATE INDEX HISTORICO_EXPE_IDX3 ON HISTORICO_EXPE (USU_CODIGO);

CREATE INDEX PED0000_IDX3 ON PED0000 (ped_dtsaida);
