UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.579 patch 2',
    VERSAOSISTEMA.DATA   = '24.04.2023',
	VERSAO = '3.0.9.579'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE TIPO_MOLA  ADD MMO_PERDA_PADRAO NUMERIC(18,5);
COMMENT ON COLUMN TIPO_MOLA.MMO_PERDA_PADRAO IS 'Perda padrão (mm)';

UPDATE PRMT0001 SET PMT_DESCRICAO_99_OUTROS = 'NÃO IDENTIFICADO' WHERE PMT_DESCRICAO_99_OUTROS = '' ;
UPDATE PRMT0001 SET PMT_DESCRICAO_99_OUTROS = 'NÃO IDENTIFICADO' WHERE PMT_DESCRICAO_99_OUTROS IS NULL;
COMMIT;

