UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.532 patch 1',
       VERSAOSISTEMA.DATA   = '26.04.2019',
	    VERSAO = '3.0.9.532'
 where VERSAOSISTEMA.CODIGO = 1;

 
commit work;

ALTER TABLE PED0000 ADD PED_FATURAR_LIBERADO VARCHAR(1);
ALTER TABLE PED0000 ADD PED_USU_LIBEROU_FATURAMENTO  INTEGER ;
ALTER TABLE PED0000 ADD PED_DATA_LIBERACAO  DATE ;

COMMENT ON COLUMN PED0000.PED_FATURAR_LIBERADO IS 'PEDIDO LIBERADO PARA FATURAR NÃO PODE MAIS ALTERAR';
COMMENT ON COLUMN PED0000.PED_USU_LIBEROU_FATURAMENTO IS 'USUARIO QUE LIBEROU PARA FATURAMENTO';
COMMENT ON COLUMN PED0000.PED_DATA_LIBERACAO  IS 'DATA DA LIBERACAO ';

UPDATE PED0000 SET PED_FATURAR_LIBERADO = 'S';

commit work;

ALTER TABLE PRMT0001 ADD PMT_LIBERAR_FATURA VARCHAR(1);
COMMENT ON COLUMN PRMT0001.PMT_LIBERAR_FATURA  IS 'LIBERAR PEDIDO PARA FATURAMENTO A- AUTOMATICO M - MANUAL' ;


ALTER TABLE PRMT0001 ADD PMT_LIBERAR_EXPEDICAO VARCHAR(1);
COMMENT ON COLUMN PRMT0001.PMT_LIBERAR_EXPEDICAO IS 'LIBERAR PARA EXPEDICAO : P  - PEDIDO ; F PELO FATURAMENTO ';


UPDATE PRMT0001 
SET PMT_LIBERAR_FATURA = 'A', PMT_LIBERAR_EXPEDICAO = 'P';

COMMIT WORK;


ALTER TABLE NF0001 ADD NF_SITEXPEDICAO VARCHAR(1);
COMMENT ON COLUMN NF0001.NF_SITEXPEDICAO IS 'SITUACAO DA EXPEDICAO NA NOTA F - FATURADO ; L LIBERADO C- CANCELADO';

UPDATE NF0001
SET NF_SITEXPEDICAO = 'C'
WHERE NF_STATUS_NFE = 'C';
COMMIT WORK;

UPDATE NF0001
SET NF_SITEXPEDICAO = 'F'
WHERE NF_STATUS_NFE <> 'C'
AND NF_SITEXPEDICAO IS NULL;

COMMIT WORK;

UPDATE TAREFAS_CRM
SET TRF_DATAABERTURA = COALESCE((SELECT MIN(TAH_DATA_REGISTRO) FROM TAREFAS_HISTORICO HI WHERE HI.TRF_REGISTRO = TAREFAS_CRM.TRF_REGISTRO),TRF_DATA_REGISTRO);

COMMIT WORK;