UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.536 patch 3',
       VERSAOSISTEMA.DATA   = '02.09.2019',
	    VERSAO = '3.0.9.536'
 where VERSAOSISTEMA.CODIGO = 1;

commit work;

UPDATE BAN0000 SET BAN_CARTEIRA_REGISTRO = 'S';

COMMIT WORK;

ALTER TABLE OPV0000 ADD OPV_ESTOQUE_REMESSAINDUS VARCHAR(2);
COMMENT ON COLUMN OPV0000.OPV_ESTOQUE_REMESSAINDUS IS 'SAIDA DE UM ESTOQUE EENTRADA EM OUTRA EM REMESSA DE INDUSTRIALIZACAO';

UPDATE OPV0000 SET OPV_ESTOQUE_REMESSAINDUS = 'N';

COMMIT WORK;

UPDATE OPV0000 SET OPV_VENDA = 'N' WHERE OPV_CODIGO <> 15;

UPDATE OPV0000 SET OPV_VENDA = 'S' WHERE OPV_CODIGO = 15;

COMMIT;