UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.535 patch 4',
       VERSAOSISTEMA.DATA   = '15.08.2019',
	    VERSAO = '3.0.9.535'
 where VERSAOSISTEMA.CODIGO = 1;

COMMIT WORK;

delete FROM OCP_IT01 it
WHERE NOT EXISTS (SELECT 1 FROM OCP0000 oc WHERE oc.OCP_CODIGO = it.OCP_CODIGO);

commit work;

UPDATE PRD0000 PR 
SET PRD_PENDENTE = (SELECT SUM(OCI_QTDES) - SUM( OCI_QTDER)
					FROM OCP_IT01 IT
 					WHERE OCI_SITUACAO = 'P'
 					AND it.PRD_REFER = pr.PRD_REFER
 					AND ((SELECT PRODUTOS FROM SHAREDB) = 'C' OR PR.EMP_CODIGO = IT.EMP_CODIGO))  ;


COMMIT WORK;


ALTER TABLE OPV0000 ADD OPV_FATURAMENTO VARCHAR(1);
COMMENT ON COLUMN OPV0000.OPV_FATURAMENTO IS 'TIPO DE PEDIDO FATURA';
COMMENT ON COLUMN OPV0000.OPV_VENDA IS 'TIPO VENDA. AUTORIZA TIPO DE PEDIDO PARA VENDA' ;

UPDATE OPV0000
SET OPV_FATURAMENTO = OPV0000.OPV_VENDA;

UPDATE OPV0000 SET OPV_VENDA = 'N' WHERE OPV_CODIGO <> 15;

UPDATE OPV0000 SET OPV_VENDA = 'S' WHERE OPV_CODIGO = 15;


COMMIT WORK;


ALTER TABLE BAN0000 ADD BAN_ATIVO VARCHAR(1);
UPDATE BAN0000
SET BAN_ATIVO = 'S';

COMMIT WORK;

COMMENT ON COLUMN BAN0000.BAN_ATIVO IS 'BANCO ESTA ATIVO S OU N ';