UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.594 patch 4',
    VERSAOSISTEMA.DATA   = '31.07.2024',
	VERSAO = '3.0.9.594'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

/* issues 1926 */
ALTER TABLE PRD_GRADE ADD PRG_METRO_CUBICO NUMERIC(18,5);
COMMENT ON COLUMN PRD_GRADE.PRG_METRO_CUBICO IS 'Metros Cúbicos';

ALTER TABLE PRMT0001 ADD PMT_ATIVA_METRO_CUBICO VARCHAR(1);
COMMENT ON COLUMN PRMT0001.PMT_ATIVA_METRO_CUBICO IS 'Cálculo de Metros Cúbicos e Mostra no Grid de Pedidos';

/* issues 1928 */
ALTER TABLE PRD0000 ADD PRD_LANCA_VALOR_ZERADO VARCHAR(1);
COMMENT ON COLUMN PRD0000.PRD_LANCA_VALOR_ZERADO IS 'Na inserção do Item no Pedido, Permite alterar o Valor se Preço de Venda estiver Zerado';