UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.590 patch 1',
    VERSAOSISTEMA.DATA   = '20.03.2024',
	VERSAO = '3.0.9.590'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;


/* issues 1816-1817 */
ALTER TABLE CLI0000 ADD CLI_AGRONEGOCIO VARCHAR(1) DEFAULT 'N';
ALTER TABLE PRD0000 ADD PRD_AGRONEGOCIO VARCHAR(1) DEFAULT 'N';
UPDATE CLI0000 SET CLI_AGRONEGOCIO = 'N' WHERE CLI_AGRONEGOCIO IS NULL;
UPDATE PRD0000 SET PRD_AGRONEGOCIO = 'N' WHERE PRD_AGRONEGOCIO IS NULL;
COMMIT WORK;

