UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.569',
    VERSAOSISTEMA.DATA   = '09.06.2022',
	VERSAO = '3.0.9.569'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE OCP_IT01 ADD OCI_DESCONTO NUMERIC(18,4);
COMMENT ON COLUMN OCP_IT01.OCI_DESCONTO is 'Desconto do item da Ordem de Compra';
ALTER TABLE OCP_IT01 ADD OCI_TIPO_DESCONTO CHAR(1);
COMMENT ON COLUMN OCP_IT01.OCI_TIPO_DESCONTO is 'Tipo do Desconto do item da Ordem de Compra (P)Percentual ou (V)Valor';
COMMENT ON COLUMN OCP_IT01.OCI_ICMS is 'ICMS do item da Ordem de Compra';
