SET TERM ^ ;

create table PRD_DIRETIVA_ITEM (
PDI_REGISTRO INTEGER NOT NULL,
PRF_REGISTRO INTEGER NOT NULL,
PRDD_REGISTRO INTEGER NOT null )^
CREATE GENERATOR GEN_PRD_DIRETIVA_ITEM_ID^

COMMENT ON COLUMN PRD_DIRETIVA_ITEM.PDI_REGISTRO IS 'Meu ID'^
COMMENT ON COLUMN PRD_DIRETIVA_ITEM.PRF_REGISTRO IS 'id item pedido'^
COMMENT ON COLUMN PRD_DIRETIVA_ITEM.PRDD_REGISTRO IS 'id registro diretiva'^

CREATE OR ALTER TRIGGER PRD_DIRETIVA_ITEM_BI FOR PRD_DIRETIVA_ITEM
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.prdd_registro is null) then
    new.prdd_registro = gen_id(GEN_PRD_DIRETIVA_ITEM_ID,1);
end^

ALTER TABLE PRD_DIRETIVA_ITEM  ADD CONSTRAINT PK_PRD_DIRETIVA_ITEM PRIMARY KEY (PDI_REGISTRO)^
CREATE INDEX PRD_DIRETIVA_ITEM_IDX1 ON PRD_DIRETIVA_ITEM (PRF_REGISTRO, PRDD_REGISTRO)^
COMMIT WORK^

alter table PRMT0001 ADD PMT_FORM_DANFE CHAR(1)^
alter table ped_it01 add id_diretivas integer^
COMMIT WORK^

UPDATE PED_IT01 SET ID_DIRETIVAS = GEN_ID(GEN_ITEM_PEDIDO,1)^
COMMIT WORK^

insert into PRD_DIRETIVA_ITEM (PDI_REGISTRO, PRF_REGISTRO, PRDD_REGISTRO)
Select  GEN_ID(GEN_PRD_DIRETIVA_ITEM_ID,1), B.id_diretivas, B.PRDD_REGISTRO
from ped_it01 B
where Coalesce(B.prdd_registro,0)>0^
COMMIT WORK^

update PRMT0001 set PMT_FORM_DANFE = '1'^
COMMIT WORK^

Update VERSAOSISTEMA SET
       VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.0.446' ,
       VERSAOSISTEMA.DATA   = '25.02.2016'
 where VERSAOSISTEMA.CODIGO = 1^
COMMIT WORK^



SET TERM ; ^


