ALTER TABLE TRP0000
    ADD CLIENTE_RETIRA CHAR(1);
COMMIT WORK;

UPDATE trp0000
    SET trp0000.cliente_retira = 'N';
COMMIT WORK;

ALTER TABLE PRMT0001
    ADD PMT_TRIB_NF CHAR(1);
COMMIT WORK;

ALTER TABLE PRMT0001
    ADD PMT_ITENS_KIT CHAR(1);
COMMIT WORK;

ALTER TABLE TRP0000
    ADD FRETE CHAR(1);
COMMIT WORK;

UPDATE  VERSAOSISTEMA SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.0.477',
       VERSAOSISTEMA.DATA   = '16.02.2017'
 where VERSAOSISTEMA.CODIGO = 1;
 
 COMMIT WORK;

 