UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.532 patch 2',
       VERSAOSISTEMA.DATA   = '14.05.2019',
	    VERSAO = '3.0.9.532'
 where VERSAOSISTEMA.CODIGO = 1;

COMMIT WORK;
 
 -- linhas orfãs
delete FROM PAG_PAGAMENTO
WHERE NOT EXISTS (SELECT 1 FROM PAG_PC01 PAG WHERE PAG_PAGAMENTO.PAG_REGISTRO = PAG.PAG_REGISTRO);

COMMIT WORK;

--ATUALIZA FORNECEDORES DAS PARCELAS
UPDATE PAG_PC01
SET for_codigo = (SELECT FOR_CODIGO FROM PAG0000 pag 
				     WHERE pag.PAG_CODIGO =  PAG_PC01.PAG_CODIGO
					AND (pag.EMP_CODIGO = pag_pc01.EMP_CODIGO OR (SELECT pagar FROM SHAREDB) = 'C'))
WHERE FOR_CODIGO <> (SELECT FOR_CODIGO FROM PAG0000 pag 
				     WHERE pag.PAG_CODIGO =  PAG_PC01.PAG_CODIGO
					AND (pag.EMP_CODIGO = pag_pc01.EMP_CODIGO OR (SELECT pagar FROM SHAREDB) = 'C') );
					
					
COMMIT WORK;					
					
					
--- atualizando forma de pagamento em branco na parcela que tem recebimento já preenchido
UPDATE FAT_PC01
SET FPG_REGISTRO =  (SELECT first 1 FPG_REGISTRO FROM FAT_RECEBIMENTO REC 
    				 WHERE REC.FAT_REGISTRO =  FAT_PC01.FAT_REGISTRO	)
WHERE FPG_REGISTRO IS NULL
AND 
 (SELECT first 1 FPG_REGISTRO FROM FAT_RECEBIMENTO REC 
     WHERE REC.FAT_REGISTRO =  FAT_PC01.FAT_REGISTRO	) IS NOT NULL;

COMMIT WORK;	

--- atualizando banco em branco ou inválido na parcela que tem recebimento já preenchido
UPDATE FAT_PC01
SET BAN_CODIGO =  (SELECT first 1 BAN_CODIGO FROM FAT_RECEBIMENTO REC 
    				 WHERE REC.FAT_REGISTRO =  FAT_PC01.FAT_REGISTRO	)
WHERE  (BAN_CODIGO IS NULL
 OR BAN_CODIGO NOT IN (SELECT BAN_CODIGO FROM BAN0000))
 AND 
 (SELECT first 1 BAN_CODIGO FROM FAT_RECEBIMENTO REC 
     WHERE REC.FAT_REGISTRO =  FAT_PC01.FAT_REGISTRO	) IS NOT NULL;
	 
COMMIT WORK;	

	 