UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.546 patch 3',
    VERSAOSISTEMA.DATA   = '16.07.2020',
	VERSAO = '3.0.9.546'
 where VERSAOSISTEMA.CODIGO = 1;
 
ALTER TABLE PRMT0001 ADD PMT_MULTIPLICADOR_P VARCHAR(1);
COMMENT ON COLUMN PRMT0001.PMT_MULTIPLICADOR_P IS 'HABILITAR MULTIPLICADOR P';

UPDATE PRMT0001
SET PMT_MULTIPLICADOR_P = 'N'

COMMIT WORK;