UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.573',
    VERSAOSISTEMA.DATA   = '06.10.2022',
	VERSAO = '3.0.9.573'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

CREATE TABLE PEDIDO_EM_EDICAO (
	PED_CODIGO VARCHAR(7),
	EMP_CODIGO VARCHAR(3),
	USU_LOGIN VARCHAR(15)
);

INSERT INTO CAPACIDADE VALUES (0, '');
commit work;

ALTER TABLE ENF0001 ADD ENF_ENVIADO_PCP_DEMANDA VARCHAR(1);


