UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.573 patch 4',
    VERSAOSISTEMA.DATA   = '28.10.2022',
	VERSAO = '3.0.9.573'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE MATERIAPRIMA_ORDEMPRODUCAO ADD FOR_CODIGO VARCHAR(4);
ALTER TABLE MATERIAPRIMA_ORDEMPRODUCAO ADD ENF_NOTANUMBER VARCHAR(10);
ALTER TABLE MATERIAPRIMA_ORDEMPRODUCAO ADD MP_DATA_COMPRA DATE;

