
UPDATE  VERSAOSISTEMA SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.511',
       VERSAOSISTEMA.DATA   = '16.05.2018'
 where VERSAOSISTEMA.CODIGO = 1;

 commit work;


ALTER TABLE PED0000 ADD BAN_CODIGO varchar(4);
ALTER TABLE PED0000 ADD PED_PARCELA INTEGER;
ALTER TABLE PED0000 ADD PED_INICIOPAG DATE;
ALTER TABLE PED0000 ADD PED_TIPOPARCELA VARCHAR(10);
ALTER TABLE PED0000 ADD  PED_VLPARCELA NUMERIC(18,5);

COMMENT ON COLUMN PED0000.BAN_CODIGO IS 'CHAVE DA TABELA DE BANCOS (BANC000)';
COMMENT ON COLUMN CLI0000.BAN_CODIGO IS 'CHAVE DA TABELA DE BANCOS (BANC000)';
COMMENT ON COLUMN PED0000.PED_PARCELA IS 'PARCELAS DO PEDIDO ';
COMMENT ON COLUMN PED0000.PED_INICIOPAG IS 'INICIO DE PAGEMENTO DAS PARCELAS';
COMMENT ON COLUMN PED0000.PED_TIPOPARCELA IS 'TIPO DE PARCELA : BIMESTRAL , TRIMESTRAL, SEMESTRALM ANUAL, UNICA';
COMMENT ON COLUMN PED0000.PED_VLPARCELA IS 'VALOR PARCELA';

ALTER TABLE PED0000 ADD  PED_UND_CONSUMIDORA INTEGER;
ALTER TABLE FAT_PC01 ADD  PED_UND_CONSUMIDORA INTEGER;

COMMENT ON COLUMN PED0000.PED_UND_CONSUMIDORA IS 'UNIDADE CONSUMIDORA - COPEL';
COMMENT ON COLUMN FAT_PC01.PED_UND_CONSUMIDORA IS 'UNIDADE CONSUMIDORA - COPEL';

ALTER TABLE BANCOS ADD BCO_UNIDADE_CONSUMIDORA VARCHAR(1);
COMMENT ON COLUMN BANCOS.BCO_UNIDADE_CONSUMIDORA IS 'TEM UNIDADE CONSUMIDORA OBRIGATORIA';


UPDATE BANCOS
SET BCO_UNIDADE_CONSUMIDORA = 'N';

INSERT INTO BANCOS VALUES (900, 'COPEL','001','S'); 

commit work;

ALTER TABLE PRMT0001 ADD pmt_Pedido_Doacao VARCHAR(1);
COMMENT ON COLUMN PRMT0001.pmt_Pedido_Doacao IS 'TELA DE PEDIDO TIPO DOACAO S: SIM N:NAO';

update PRMT0001 
set pmt_Pedido_Doacao = 'N';

COMMIT WORK;

ALTER TABLE PED_IT01 ADD PRF_PESOKG NUMERIC (18,5);
comment ON COLUMN PED_IT01.prf_pesokg  IS 'PESO LIQUIDO DO ITEM EM KG';


CREATE OR ALTER PROCEDURE PRD_AJUSTA_SITUACAO_PEDIDO (VCOD_PEDIDO CHAR(7), VCOD_EMP CHAR(3))
RETURNS (
    VSIT CHAR(1)
)
AS
declare variable VQTDFAT float;
declare variable VQTD float;
declare variable vDoacao varchar(1);
begin
  select pmt_Pedido_Doacao from PRMT0001
  where emp_codigo = :VCOD_EMP
  into :vDoacao;
  if (:vDoacao <> 'S') then
  begin 
      select sum(PRF_QTDE), sum(PRF_QTDEFAT)
      from PED_IT01
      where PED_CODIGO = :VCOD_PEDIDO and
            EMP_CODIGO = :VCOD_EMP and
            PRF_PRODUTO_AGREGADO = 'N'
      into :VQTD, :VQTDFAT;
      if (VQTDFAT >= VQTD) then
        VSIT = 'T';
      else
      if (VQTDFAT > 0) then
        VSIT = 'P';
      else
        VSIT = 'F';
  end
 else 
   vsit = 'T';
  suspend;
end;




