UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.586 patch 1',
    VERSAOSISTEMA.DATA   = '07.11.2023',
	VERSAO = '3.0.9.586'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE FOR0000 ADD FOR_FONE_TEMP VARCHAR(12);
UPDATE FOR0000 SET FOR_FONE_TEMP = REPLACE(FOR_FONE, ' ', '');
UPDATE FOR0000 SET FOR_FONE_TEMP = NULL WHERE FOR_FONE_TEMP = '';
UPDATE FOR0000 SET FOR_FONE_TEMP = CAST(CAST(COALESCE(FOR_FONE_TEMP, '0') AS DECIMAL(18,0)) AS VARCHAR(12));
UPDATE FOR0000 SET FOR_FONE_TEMP = NULL WHERE FOR_FONE_TEMP = '0';
UPDATE FOR0000 SET FOR_FONE_TEMP =
	CASE 
		WHEN CHARACTER_LENGTH(FOR_FONE_TEMP) = 10 THEN SUBSTRING (FOR_FONE_TEMP FROM 1 FOR 2)||' '||SUBSTRING (FOR_FONE_TEMP FROM 3 FOR 10)
		WHEN CHARACTER_LENGTH(FOR_FONE_TEMP) = 11 THEN FOR_FONE_TEMP
		ELSE FOR_FONE_TEMP		
	END;
ALTER TABLE FOR0000 ALTER FOR_FONE TYPE VARCHAR(12);
UPDATE FOR0000 SET FOR_FONE = FOR_FONE_TEMP;
ALTER TABLE FOR0000 DROP FOR_FONE_TEMP;

ALTER TABLE FOR0000 ADD FOR_FAX_TEMP VARCHAR(12);
UPDATE FOR0000 SET FOR_FAX_TEMP = REPLACE(FOR_FAX, ' ', '');
UPDATE FOR0000 SET FOR_FAX_TEMP = NULL WHERE FOR_FAX_TEMP = '';
UPDATE FOR0000 SET FOR_FAX_TEMP = CAST(CAST(COALESCE(FOR_FAX_TEMP, '0') AS DECIMAL(18,0)) AS VARCHAR(12));
UPDATE FOR0000 SET FOR_FAX_TEMP = NULL WHERE FOR_FAX_TEMP = '0';
UPDATE FOR0000 SET FOR_FAX_TEMP =
	CASE 
		WHEN CHARACTER_LENGTH(FOR_FAX_TEMP) = 10 THEN SUBSTRING (FOR_FAX_TEMP FROM 1 FOR 2)||' '||SUBSTRING (FOR_FAX_TEMP FROM 3 FOR 10)
		WHEN CHARACTER_LENGTH(FOR_FAX_TEMP) = 11 THEN FOR_FAX_TEMP
		ELSE FOR_FAX_TEMP		
	END;
ALTER TABLE FOR0000 ALTER FOR_FAX TYPE VARCHAR(12);
UPDATE FOR0000 SET FOR_FAX = FOR_FAX_TEMP;
ALTER TABLE FOR0000 DROP FOR_FAX_TEMP;

CREATE INDEX PRD_EMP01 ON PRD0000_ENDERECAMENTO_EMPRESA (EMP_CODIGO);
CREATE INDEX PRD_PRDE ON PRD0000_ENDERECAMENTO_EMPRESA (PRDE_REGISTRO);
CREATE INDEX PRD_REFER01 ON PRD0000_ENDERECAMENTO_EMPRESA (PRD_REFER);
