UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.546',
    VERSAOSISTEMA.DATA   = '01.07.2020',
	VERSAO = '3.0.9.546'
 where VERSAOSISTEMA.CODIGO = 1;
 
 
 UPDATE PED0000 p
  SET PED_VLFATURADO = PED_VLTOTAL_BRUTO
  WHERE PED_SITUACAO = 'T';