UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.545 patch 7',
    VERSAOSISTEMA.DATA   = '11.06.2020',
	VERSAO = '3.0.9.545'
 where VERSAOSISTEMA.CODIGO = 1;

commit work;

ALTER TABLE PRMT0001 ADD PMT_VINCULAR_VENDEDOR VARCHAR(1);
COMMENT ON COLUMN PRMT0001.PMT_VINCULAR_VENDEDOR IS 'VINCULA O USARIO AO VENDEDOR NO PEDIDO';
UPDATE PRMT0001 SET PMT_VINCULAR_VENDEDOR = 'N';

ALTER TABLE EMP0000 ADD PRD_SPEDVALIDA VARCHAR(1);
UPDATE EMP0000 SET PRD_SPEDVALIDA = 'N';
COMMENT ON COLUMN EMP0000.PRD_SPEDVALIDA IS 'ATIVAR VALIDACAO DO SPED S - SIM N - NAO';

ALTER TABLE PRD0000 ADD PRD_VAIXML VARCHAR(1);
UPDATE PRD0000 SET PRD_VAIXML = 'S';
COMMENT ON COLUMN PRD0000.PRD_VAIXML IS 'CODIGO DE BARRAS VAI NO EAN DO XML NFE';