UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.561 patch 5',
    VERSAOSISTEMA.DATA   = '29.10.2021',
	VERSAO = '3.0.9.561'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE APONTAMENTO_FAB ADD APF_REBARBA DECIMAL (18,5);
ALTER TABLE FABRICACAO ADD FAB_REBARBA DECIMAL (18,5);
UPDATE FABRICACAO SET FAB_REBARBA = 0;
commit work;