ALTER TABLE PED_IT01 ALTER COLUMN PRF_COMPL_DESCRI TYPE VARCHAR(500);

 COMMIT WORK;   
 
ALTER TABLE PRD0000 ALTER COLUMN PRD_COMPL TYPE VARCHAR(500);

 COMMIT WORK;	 
 
ALTER TABLE NF_IT01 ALTER COLUMN PRD_COMPL_DESCRI TYPE VARCHAR(500);
 
 COMMIT WORK;	

ALTER TABLE USUARIO_ACESSO
    ADD USA_RELATORIO CHAR(1); 

 COMMIT WORK;	

UPDATE  VERSAOSISTEMA SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.0.476',
       VERSAOSISTEMA.DATA   = '19.01.2017'
 where VERSAOSISTEMA.CODIGO = 1;
 
 COMMIT WORK;
