UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.560 patch 3',
    VERSAOSISTEMA.DATA   = '17.09.2021',
	VERSAO = '3.0.9.560'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

INSERT INTO PRD_LINHA VALUES ('999', 'TODAS AS LINHAS', '001');
commit work;

UPDATE PRMT0001 x SET x.PMT_LIMITE_CREDITO_INICIAL =0 WHERE x.PMT_LIMITE_CREDITO_INICIAL IS NULL;
commit work;