SET TERM ^ ;

CREATE INDEX OSV0001_IDX2 ON OSV0001 (OSV_CODIGO)^

Update VERSAOSISTEMA SET
       VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.0.453' ,
       VERSAOSISTEMA.DATA   = '06.06.2016'
 where VERSAOSISTEMA.CODIGO = 1^

COMMIT WORK^



SET TERM ; ^


