UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.584 patch 1',
    VERSAOSISTEMA.DATA   = '25.09.2023',
	VERSAO = '3.0.9.584'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE PRMT0001 ADD PMT_BAIXA_ESTOQUE_AVANCADO VARCHAR(1) DEFAULT 'N';
COMMENT ON COLUMN PRMT0001.PMT_BAIXA_ESTOQUE_AVANCADO IS 'Permite informar o almoxarifado antes de produzir - [S]im | [N]ão ';
UPDATE PRMT0001 SET PMT_BAIXA_ESTOQUE_AVANCADO = 'N' WHERE PMT_BAIXA_ESTOQUE_AVANCADO IS NULL;
COMMIT WORK;

ALTER TABLE MATERIAPRIMA_ORDEMPRODUCAO ADD AMX_CODIGO VARCHAR(4);

ALTER TABLE MOLA_MATERIA ADD MMO_ARQUIVO_FICHA_TECNICA VARCHAR(1024) DEFAULT '';
UPDATE MOLA_MATERIA SET MMO_ARQUIVO_FICHA_TECNICA = '' WHERE MMO_ARQUIVO_FICHA_TECNICA IS NULL;

ALTER TABLE EMP0000 ADD EMP_CLAS_ESTAB_IND VARCHAR(2);
COMMENT ON COLUMN EMP0000.EMP_CLAS_ESTAB_IND IS 'Classificação do Estabelecimento';

ALTER TABLE ENF_IT01 ADD ENF_IT_DET_NITEM INTEGER;

