UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.562 patch 3',
    VERSAOSISTEMA.DATA   = '17.11.2021',
	VERSAO = '3.0.9.562'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE PRMT0001 ADD PMT_LOTE_RASTREABILIDADE CHAR(1);
UPDATE PRMT0001 SET PMT_LOTE_RASTREABILIDADE = 'S' WHERE PMT_LOTE_RASTREABILIDADE IS NULL;
commit work;
