UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.563 patch 1',
    VERSAOSISTEMA.DATA   = '07.12.2021',
	VERSAO = '3.0.9.563'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE OPERACOES ALTER COLUMN OPE_TEMRESULTADO SET DEFAULT 'N';
UPDATE OPERACOES  ope SET ope.OPE_TEMRESULTADO = 'N' WHERE ope.OPE_TEMRESULTADO  IS NULL;
DELETE FROM ITEM_ORDEMPRODUCAO a WHERE a.IOP_NORDEM = '';

CREATE OR ALTER VIEW VW_SPED_NOTAS_FISCAIS_ITENS (DESP_ACESSORIA, FRETE, SEGURO, REGISTRO_NOTA, CODIGO_ITEM, DESCRICAO_ITEM, QUANTIDADE, UNIDADE, VALOR_ITEM, VALOR_DESCONTO, INDICADOR_MOVIMENTACAO, CST_ICMS, CFOP, CODIGO_CFOP, OPE_CODIGO, VALOR_BASE_ICMS, ALIQUOTA_ICMS, VALOR_ICMS, VALOR_BASE_ICMS_ST, ALIQUOTA_ICMS_ST, VALOR_ICMS_ST, INDICADOR_APURACAO_IPI, CST_IPI, CODIGO_ENQUAD_IPI, VALOR_BASE_IPI, ALIQUOTA_IPI, VALOR_IPI, CST_PIS, VALOR_BASE_PIS, ALIQ_PIS, QUANTIDADE_BASE_PIS, ALIQ_PIS_REAIS, VALOR_PIS, CST_COFINS, VALOR_BASE_COFINS, ALIQUOTA_COFINS, QUANTIDADE_BASE_COFINS, ALIQ_COFINS_REAIS, VALOR_COFINS, FOR_CODIGO)
AS
SELECT
T1.ENF_IT_VLDESP_ACES,
T1.ENF_IT_VALFRETE,
T1.ENF_IT_VLSEGURO,
CAST('E'||T1.ENF_IT_NOTANUMBER AS VARCHAR(30)),
T1.PRD_REFER,
CAST(T1.PRD_DESCRI AS VARCHAR(500)),
coalesce(t1.ENF_QTDE_ORIGINAL, T1.ENF_QTDE),
COALESCE(T1.ENF_UCOM,
	(SELECT FIRST 1 
		CASE PRD_PRODSERV    
			WHEN 'S' THEN COALESCE(T3.PRD_UND,'UN') 
			WHEN NULL THEN 'UN'
			WHEN '' THEN 'UN'
			ELSE T3.PRD_UND 
		END AS UNIDADE_MEDIDA  
	FROM PRD0000 T3 WHERE T3.PRD_REFER = T1.PRD_REFER)
	),
COALESCE(T1.ENF_PRECO_ORIGINAL,T1.ENF_PRECO),
T1.ENF_IT_DESCTO,
CAST((CASE WHEN (1=1) THEN
    'S'
END) AS VARCHAR(1)),
COALESCE(t1.STB_TRIBUTACAO,'00'),
t1.ENF_CFOP,
t1.ENF_CFOP,
T1.OPE_CODIGO AS OPE_CODIGO,
t1.ENF_IT_BASEICMS,
t1.ENF_ICMSALIQ,
t1.ENF_ICMS,
t1.ENF_IT_BASESUBTRIB AS VALOR_BASE_ICMS_ST,
t1.ENF_IT_ALIQSUBTRIB AS ALIQUOTA_ICMS_ST,
CAST(ENF_IT_VLSUBTRIB AS NUMERIC(18,2)) as VALOR_ICMS_ST,
CAST((CASE WHEN (1=1) THEN
    0
END) AS INTEGER),
t1.CST_IPI,
CAST(CASE WHEN (1=1) THEN
    'XXX'
END as varchar(3)),
COALESCE(T1.ENF_IT_BASEIPI,0) AS VALOR_BASE_IPI,
COALESCE(T1.ENF_IPIALIQ,0) AS ALIQUOTA_IPI,
COALESCE(T1.ENF_IT_VLIPI,0) AS VALOR_IPI ,
t1.CST_PIS,
COALESCE(T1.ENF_BASEPIS,0),
COALESCE(T1.ENF_IT_ALIQPIS,0),
CASE WHEN (1=1) THEN
    0.00
END,
CASE WHEN (1=1) THEN
    0.00
END,
COALESCE(T1.ENF_IT_VLPIS,0),
t1.CST_COFINS,
COALESCE(T1.ENF_BASECOFINS,0),
COALESCE(T1.ENF_IT_ALIQCOFINS,0),
CASE WHEN (1=1) THEN
    0.00
END,
CASE WHEN (1=1) THEN
    0.00
END,
COALESCE(T1.ENF_IT_VLCOFINS,0),
T1.FOR_CODIGO
FROM
ENF_IT01 T1
UNION ALL 
SELECT
T2.NF_IDESP_ACES,
T2.NF_IFRETE,
T2.NF_ISEGURO,
CAST('S'||T2.NF_IT_NOTANUMER AS VARCHAR(30)),
(SELECT FIRST 1 T3.PRD_REFER FROM PRD0000 T3 WHERE T3.PRD_REFER = T2.PRD_REFER),
T2.PRD_DESCRI,
T2.NF_QTDE,
(SELECT FIRST 1 T3.PRD_UND FROM PRD0000 T3 WHERE T3.PRD_REFER = T2.PRD_REFER),
T2.NF_PRECO,
T2.NF_IDESCTO1,
CAST((CASE WHEN (1=1) THEN
    'S'
END) AS VARCHAR(1)),
COALESCE((SELECT FIRST 1 cast(T3.PRD_ORIGEM as varchar(1)) FROM PRD0000 T3 WHERE T3.PRD_REFER = T2.PRD_REFER),'00')||t2.STB_TRIBUTACAO,
cast(t2.NTP_CFOP as varchar(4)),
cast(t2.NTP_CFOP as varchar(4)),
OPE_CODIGO,
t2.NF_ICMSBASE,
t2.NF_ICMSALIQ,
t2.NF_ICMSVALOR,
t2.NF_SUBTRIBASE,
t2.NF_ALIQSUBTRIB,
CAST(t2.NF_VLSUBST AS NUMERIC(18,2)) as VALOR_ICMS_ST,
CAST((CASE WHEN (1=1) THEN  0 END) AS INTEGER),
CST_IPI, 
CAST(CASE WHEN (1=1) THEN  'XXX' END as varchar(3)),
COALESCE(T2.NF_IPIBASE,0) AS VALOR_BASE_IPI,
COALESCE(T2.NF_IPIALIQ,0) AS ALIQUOTA_IPI,
COALESCE(T2.NF_IPIVALOR,0) AS VALOR_IPI,
CAST(CASE WHEN (T2.NF_BASE_PIS > 0) THEN
    coalesce(CST_PIS,'01')
    ELSE
    '99'
END as varchar(3)),
COALESCE(T2.NF_BASE_PIS,0),
COALESCE(T2.NF_ALIQPIS,0),
CASE WHEN (1=1) THEN
    0.00
END,
CASE WHEN (1=1) THEN
    0.00
END,
COALESCE(T2.NF_VLPIS,0),
cast(CASE WHEN (T2.NF_BASE_COFINS > 0) THEN
    coalesce(CST_COFINS, '01')
    ELSE
    '99'
END as varchar(3)),
COALESCE(T2.NF_BASE_COFINS,0),
COALESCE(T2.NF_ALIQCOFINS,0),
CASE WHEN (1=1) THEN
    0.00
END,
CASE WHEN (1=1) THEN
    0.00
END,
COALESCE(T2.NF_VLCOFINS,0),
NULL
FROM
NF_IT01 T2
WHERE
  EXISTS (SELECT 1 FROM PRD0000 T3 WHERE T3.PRD_REFER = T2.PRD_REFER)
  AND PRD_REFER IS NOT NULL;
  
