UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.586',
    VERSAOSISTEMA.DATA   = '01.11.2023',
	VERSAO = '3.0.9.586'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE NFSE_IT ADD NFSI_JUSTIFICATIVA_DEDUCAO VARCHAR(255);

ALTER TABLE SHAREDB ADD ENDERECO_ESTOQUE VARCHAR(1)  DEFAULT 'C';
UPDATE SHAREDB SET ENDERECO_ESTOQUE = 'C' WHERE ENDERECO_ESTOQUE IS NULL;
ALTER TABLE PRD0000_ENDERECAMENTO ADD AMX_CODIGO VARCHAR(4);
UPDATE PRD0000_ENDERECAMENTO pe SET AMX_CODIGO = 
(
   SELECT DISTINCT pm.PMT_AMX_FATURAMENTO 
     FROM  PRD0000 pr 
       JOIN PRMT0001 pm ON (pm.EMP_CODIGO = pr.EMP_CODIGO  )
     WHERE pr.EMP_CODIGO = pe.EMP_CODIGO AND pr.PRDE_REGISTRO = pe.PRDE_REGISTRO 
)
WHERE pe.AMX_CODIGO IS NULL;
CREATE TABLE PRD0000_ENDERECAMENTO_EMPRESA (
  PRD_REFER VARCHAR(20),
  EMP_CODIGO VARCHAR(3),
  PRDE_REGISTRO INTEGER
);
INSERT INTO PRD0000_ENDERECAMENTO_EMPRESA(PRD_REFER, EMP_CODIGO, PRDE_REGISTRO)
  SELECT PRD_REFER, EMP_CODIGO, PRDE_REGISTRO FROM PRD0000 
    WHERE NOT EXISTS (SELECT 1 FROM PRD0000_ENDERECAMENTO_EMPRESA);
COMMIT WORK;


