ALTER TABLE PRD_LOTE
    ADD PRDL_QTDELOTE DECIMAL6;
COMMIT WORK;


    
UPDATE  VERSAOSISTEMA SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.0.486',
       VERSAOSISTEMA.DATA   = '29.05.2017'
 where VERSAOSISTEMA.CODIGO = 1;
 
COMMIT WORK;
