UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.557 patch 3',
    VERSAOSISTEMA.DATA   = '29.06.2021',
	VERSAO = '3.0.9.557'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE PCX0000 ADD PCX_PARTICIPA_CUSTO_OPERACIONAL CHAR(1) DEFAULT 'N';
UPDATE PCX0000 SET PCX_PARTICIPA_CUSTO_OPERACIONAL = 'N' WHERE PCX_PARTICIPA_CUSTO_OPERACIONAL <> 'S' OR PCX_PARTICIPA_CUSTO_OPERACIONAL IS NULL; 

ALTER TABLE CUSTOINDUST ADD CIO_APROVADO CHAR(1) DEFAULT 'N';
UPDATE CUSTOINDUST SET CIO_APROVADO = 'S';

ALTER TABLE SETOR ADD PCX_CODIGO VARCHAR(3);



