UPDATE  VERSAOSISTEMA 
SET    VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.516',
       VERSAOSISTEMA.DATA   = '25.06.2018',
	   VERSAO = '3.0.9.516'
 where VERSAOSISTEMA.CODIGO = 1;
 
commit work;

/* alter character set utf8; */

-- script 512 alguns clientes já foi rodado esta parte Burda e Collection
ALTER TABLE BAN0000 ADD BAN_LEIAUTE INTEGER;
COMMENT ON COLUMN BAN0000.BAN_LEIAUTE IS 'LEAIUTE DO CNAB : 1-CNAB400 2-CNAB240';
UPDATE BAN0000 SET BAN_LEIAUTE = 1;
commit work;
COMMENT ON COLUMN BAN0000.BAN_CONVENIO IS 'NUMERO DO CONVENIO DE COBRANCA';
COMMENT ON COLUMN BAN0000.BAN_ESPECIE_COB IS 'ESPECIE DO TITULO DE ACORDO COM O BANCO E LEAIUTE';

COMMENT ON TABLE INSTRUCAO_CNAB IS 'CODIGO DE MOVIMENTO DA REMESSA DOS BANCOS';
ALTER TABLE INSTRUCAO_CNAB ADD BAN_LEIAUTE INTEGER;
COMMENT ON COLUMN INSTRUCAO_CNAB.BAN_LEIAUTE IS 'LEAIUTE DO CNAB : 1-CNAB400 2-CNAB240';
UPDATE INSTRUCAO_CNAB SET BAN_LEIAUTE = 1;

commit work;

DELETE FROM INSTRUCAO_CNAB WHERE IST_COD_BANCO = 237;

commit work;


INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (106,237, '01','ENTRADA DE TÍTULOS',2);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (107,237, '02','PEDIDO DE BAIXA',2);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (108,237, '03','PROTESTO PARA FINS FALIMENTARES',2);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (109,237, '04','CONCESSÃO DE ABATIMENTO',2);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (110,237, '05','CANCELAMENTO DE ABATIMENTO',2);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (111,237, '06','ALTERAÇÃO DE VENCIMENTO',2);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (112,237, '07' ,'CONCESSÃO DE DESCONTO',2);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (113,237, '09','PROTESTAR',2);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (114,237, '10','SUSTAR PROTESTO E BAIXAR TÍTULO',2);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (115,237, '11','SUSTAR PROTESTO E MANTER EM CARTEIRA',2);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (116,237, '12','ALTERAÇÃO DE JUROS DE MORA',2);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (117,237, '13','DISPENSAR COBRANÇA DE JUROS DE MORA',2);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (118,237, '14','ALTERAÇÃO DE VALOR/PERCENTUAL DE MULTA',2);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (119,237, '15','DISPENSAR COBRANÇA DE MULTA',2);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (120,237, '16','ALTERAÇÃO DO VALOR DE DESCONTO',2);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (121,237, '18','ALTERAÇÃO DO VALOR DE ABATIMENTO',2);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (122,237, '21','ALTERAR NÚMERO DO TÍTULO DADO PELO BENEFICIARIO',2);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (123,237, '22','ALTERAR NÚMERO CONTROLE DO PARTICIPANTE',2);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (124,237, '23','ALTERAR DADOS DO PAGADOR',2);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (125,237, '24','ALTERAR DADOS DO SACADOR/AVALISTA',2);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (126,237, '31','ALTERAÇÃO DE OUTROS DADOS',2);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (127,237, '33','ALTERAÇÃO DOS DADOS DO RATEIO DE CRÉDITO',2);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (128,237, '34','PEDIDO DE CANCELAMENTO DOS DADOS DO RATEIO DE CRÉDITO',2);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (129,237, '35','PEDIDO DE DESAGENDAMENTO DO DÉBITO AUTOMÁTICO',2);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (130,237, '42','ALTERAÇÃO DE ESPÉCIE DE TÍTULO',2);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (131,237, '45','NEGATIVAÇÃO SEM PROTESTO',2);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (132,237, '46','SOLICITAÇÃO DE BAIXA DE TÍTULO NEGATIVADO SEM PROTESTO',2);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (133,237, '47','SOLICITAÇÃO EXCLUIR NEGATIVAÇÃO E MANTER PENDENTE',2);

COMMIT WORK;

COMMENT ON COLUMN BAN0000.BAN_LEIAUTE IS 'LEAIUTE DO CNAB : 1-CNAB400 2-CNAB240';
COMMENT ON COLUMN BAN0000.BAN_CONVENIO IS 'NUMERO DO CONVENIO DE COBRANCA';
COMMENT ON COLUMN BAN0000.BAN_ESPECIE_COB IS 'ESPECIE DO TITULO DE ACORDO COM O BANCO E LEAIUTE';
COMMENT ON TABLE INSTRUCAO_CNAB IS 'CODIGO DE MOVIMENTO DA REMESSA DOS BANCOS';
COMMENT ON COLUMN INSTRUCAO_CNAB.BAN_LEIAUTE IS 'LEAIUTE DO CNAB : 1-CNAB400 2-CNAB240';

ALTER TABLE PED_IT01 ADD PRF_ATUALIZOU_ESTOQUE VARCHAR(1);

COMMENT ON COLUMN PED_IT01.PRF_FLAG_ATUALIZA_ESTOQUE IS 'ITEM ATUALIZA ESTOQUE';
COMMENT ON COLUMN PED_IT01.PRF_ATUALIZOU_ESTOQUE IS 'ITEM NAO ATUALIZOU ESTOQUE AINDA QUE ATUALIZE ESTOQUE';
COMMENT ON TABLE PED_VENDA_PERDIDA IS 'PERDA DE VENDA';
COMMENT ON TABLE TRP0000 IS 'CADASTRO DE TRANSPORTE';

ALTER TABLE PED_VENDA_PERDIDA ADD PRF_PRECO NUMERIC (18,5);

/* FIM DO SCRIPT 512 */

ALTER TABLE PRD_CODIGOORIGINAL ADD PED_CODIGO VARCHAR(7);
COMMENT ON COLUMN PRD_CODIGOORIGINAL.PED_CODIGO IS 'CODIGO DO PEDIDO';
COMMENT ON TABLE PRD_CODIGOORIGINAL IS 'CODIGO ORIGINAL';



INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (134,748, '01','CADASTRO DE TÍTULOS',1);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (135,748, '02','PEDIDO DE BAIXA',1);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (136,748, '04','CONCESSÃO DE ABATIMENTO',1);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (137,748, '05','CANCELAMENTO DE ABATIMENTO CONCEDIDO',1);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (138,748, '06','ALTERAÇÃO DE VENCIMENTO',1);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (139,748, '09','PEDIDO DE PROTESTO',1);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (140,748, '18','SUSTAR PROTESTO E BAIXA TÍTULO',1);
INSERT INTO INSTRUCAO_CNAB ( IST_REGISTRO, IST_COD_BANCO, IST_CODIGO, IST_DESCRICAO,BAN_LEIAUTE) VALUES (141,748, '19','SUSTAR PROTESTO E MANTER EM CARTEIRA',1);

UPDATE BANCOS
SET BCO_DESCRICAO = 'SICREDI'
WHERE BCO_CODIGO = '748';

COMMIT WORK;

ALTER TABLE FAT_PC01 ADD FPC_ENVIOEMAIL_BOLETO VARCHAR(1) DEFAULT 'N';
COMMENT ON COLUMN FAT_PC01.FPC_ENVIOEMAIL_BOLETO IS 'BOLETO ENVIADO POR EMAIL ';

CREATE TABLE FAT_PC01_HISTORICO (
  FAT_REGISTRO INTEGER ,
  USU_CODIGO INTEGER,
  FPH_DATAHORA TIMESTAMP,
  FPH_DESCRICAO VARCHAR(255)
  );

COMMENT ON TABLE FAT_PC01_HISTORICO IS 'HISTORICO DE OCORRENCIAS DA PARCELA DE FATURAMENTO';

COMMENT ON COLUMN FAT_PC01_HISTORICO.FAT_REGISTRO IS 'REFERENCIA DA TABELA FAT_PC01.FAT_REGISTRO';
COMMENT ON COLUMN FAT_PC01_HISTORICO.USU_CODIGO IS 'REFERENCIA DA TABELA USUARIO ';
COMMENT ON COLUMN FAT_PC01_HISTORICO.FPH_DATAHORA IS 'DATA HORA DO OCORRIDO';
COMMENT ON COLUMN FAT_PC01_HISTORICO.FPH_DESCRICAO IS 'DESCRICAO DO OCORRIDO ';

SET TERM ^ ;
CREATE OR ALTER PROCEDURE PCD_KARDEX_EXTRATO (EMP_CODIGO VARCHAR(3), PRD_CODIGO VARCHAR(6), AMX_CODIGO VARCHAR(4), DATA_INICIAL TIMESTAMP, DATA_FINAL TIMESTAMP, SALDO_FINAL VARCHAR(1))
RETURNS (
    KEX_REGISTRO INTEGER,
    KEX_DATA_HORA TIMESTAMP,
    KEX_TIPO VARCHAR(1),
    KEX_QUANTIDADE NUMERIC,
    KEX_USUARIO_CODIGO INTEGER,
    KEX_USUARIO_DESCRICAO VARCHAR(30),
    KEX_SALDO NUMERIC,
    KEX_ORIGEM VARCHAR(40),
    KEX_DETALHE VARCHAR(255),
    KEX_OBSERVACAO VARCHAR(255),
    KEX_DOCUMENTO VARCHAR(255),
    KEX_PRECO NUMERIC,
    PRDL_LOTE VARCHAR(30),
    PRG_DESC_GRADE VARCHAR(100)
)
AS
declare variable SALDO numeric(15,4);
declare variable AMX_CODIGO_ORIGEM varchar(4);
declare variable LOTE varchar(30);
declare variable REGISTRO_INTERNO integer;
begin
  /* Procedure Text */
  saldo = 0;
  kex_saldo = 0;
  kex_detalhe = '';
  kex_documento = '';
        for
        SELECT
            T1.kar_registro_interno,
            T1.kar_registro,
            T1.data_hora,
            T1.kar_entrada_saida,
            T1.kar_quantidade,
            T1.kar_saldo,
            t1.usu_codigo,
            t2.usu_nome,
            T1.kar_tipo_registro,
            T1.kar_observacao,
            T1.amx_codigo_origem,
            T1.kar_documento,
            T1.kar_descricao,
            T1.kar_preco,
            t3.prdl_lote,
            t4.prg_descricao
        FROM
        KARDEX T1
        JOIN SHAREDB DB ON (ESTOQUES = 'C' OR T1.EMP_CODIGO = :emp_codigo)
        left join usuario t2 on (t2.usu_codigo = t1.usu_codigo)
        left join prd_lote t3 on (t3.prdl_registro = t1.prdl_registro)
        left outer join prd_grade t4 on (t4.prg_registro = t1.prg_registro)
        where t1.amx_codigo = :amx_codigo and t1.prd_codigo = :prd_codigo and t1.data_hora between :data_inicial and :data_final
        order by  t1.kar_registro
        into :registro_interno, :kex_registro, :kex_data_hora, :kex_tipo, :kex_quantidade, : saldo,:kex_usuario_codigo, :kex_usuario_descricao, :kex_ORIGEM, :kex_OBSERVACAO,
             :amx_codigo_ORIGEM, :kex_documento, :kex_detalhe, :kex_preco, :PRDL_LOTE, :PRG_DESC_GRADE
      DO
      BEGIN
        if (PRDL_LOTE <> '') then
            kex_OBSERVACAO = kex_OBSERVACAO ||' LOTE: '|| PRDL_LOTE ;
        kex_saldo = saldo;
        if (SALDO_FINAL <> 'S') then
        /*ORIGEM*/
        if (kex_ORIGEM = 'ENF') then
            begin
                kex_origem = 'ENTRADA NOTA FISCAL';
            end
        else
        if (kex_ORIGEM = 'PED') then
            begin
                select first 1 opv0000.opv_descricao from ped0000 join opv0000 on opv0000.opv_codigo = ped0000.opv_codigo where ped0000.ped_registro = :registro_interno into kex_origem;
                kex_origem = 'PEDIDO';
            end
        else
        if (kex_ORIGEM = 'NF') then
            begin
                kex_origem = 'NOTA FISCAL SAIDA';
            end
        else
        if (kex_ORIGEM = 'MAN') then
            begin
                kex_origem = 'MANUAL';
            end
        else
        if (kex_ORIGEM = 'BAL') then
            begin
                if (kex_observacao = 'ZERAR') then
                    BEGIN
                        kex_origem = 'ZERADO';
                    END
                ELSE
                    kex_origem = 'BALANÇO';
            end
        else
        if (kex_ORIGEM = 'TRA') then
            begin
                kex_origem = 'TRANSFERENCIA';
            end
        else
         if (kex_origem = 'PRO') then
         begin
                kex_origem = 'PRODUÇÃO';
         end
        suspend;
        END
end
^
SET TERM ; ^

COMMIT WORK;


CREATE TABLE ENTCTE (
ECTE_REGISTRO INTEGER,
ECTE_NUMERO VARCHAR(8),
EMP_CODIGO VARCHAR(3),
ECTE_MODELO_NF VARCHAR(2),
ECTE_SERIE VARCHAR(3),
ECTE_EMISSAO TIMESTAMP,
OPE_CODIGO VARCHAR(3),
OPE_NATUREZA VARCHAR(4),
FOR_CODIGO VARCHAR(4),
CCT_CODIGO VARCHAR(3),
ECTE_CST_ICMS VARCHAR(2), 
ECTE_ALIQ_ICMS NUMERIC(15,5) DEFAULT 0,
ECTE_BASEICMS NUMERIC(15,5) DEFAULT 0,
ECTE_VL_ICMS NUMERIC(15,5) DEFAULT 0,
CID_CODIGO_DEST_IBGE INTEGER,
CID_CODIGO_ORIG_IBGE INTEGER,
ECTE_VALOR_PREST NUMERIC(15,5),
ECTE_VALOR_NOTA  NUMERIC(15,5),
ECTE_CHAVE VARCHAR(60),
PAG_REGISTRO INTEGER ,
ECTE_XML BLOB SUB_TYPE 0
);

COMMENT ON TABLE ENTCTE IS 'ENTRADA DE CONHECIMENTO ELETRONICO - CTE';
COMMENT ON COLUMN ENTCTE.CID_CODIGO_DEST_IBGE IS 'CIDADE DE DESTINO- CODIGO IBGE';
COMMENT ON COLUMN ENTCTE.CID_CODIGO_ORIG_IBGE IS 'CIDADE DE ORIGEM - CODIGO IBGE';
CREATE SEQUENCE GEN_ENTRADA_CTE;