UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.540 patch 16',
       VERSAOSISTEMA.DATA   = '30.01.2020',
	    VERSAO = '3.0.9.540'
 where VERSAOSISTEMA.CODIGO = 1;
 
ALTER TABLE CLI0000 ADD CORI_CODIGO INTEGER;
COMMENT ON COLUMN CLI0000.CORI_CODIGO IS 'REFERENCIA DA ORIGEM (CLIENTE_ORIGEM)';

ALTER TABLE PED0000 ADD CORI_CODIGO INTEGER;
COMMENT ON COLUMN PED0000.CORI_CODIGO IS 'REFERENCIA DA ORIGEM (CLIENTE_ORIGEM)';


CREATE TABLE CLIENTE_ORIGEM (
   CORI_CODIGO INTEGER NOT NULL,
   CORI_DESCRICAO VARCHAR(150) NOT NULL);

ALTER TABLE CLIENTE_ORIGEM
ADD CONSTRAINT PK_CLIENTE_ORIGEM
PRIMARY KEY (CORI_CODIGO);

COMMENT ON COLUMN CLIENTE_ORIGEM.CORI_CODIGO IS 'CODIGO DA ORIGEM';
COMMENT ON COLUMN CLIENTE_ORIGEM.CORI_DESCRICAO IS 'DESCRICAO DA ORIGEM';

CREATE SEQUENCE GEN_CLIENTE_ORIGEM;

SET TERM ^ ;

create trigger cliente_origem_bi for cliente_origem
active before insert position 0
as
begin
  if (new.cori_codigo is null) then
    new.cori_codigo = gen_id(gen_cliente_origem,1);
end
^

SET TERM ; ^

COMMENT ON TABLE CLIENTE_ORIGEM IS 'cadastro de origem de clientes';


UPDATE ENF_IT01
SET ENF_UCOM = UPPER(ENF_UCOM)
WHERE ENF_UCOM IS NOT NULL;

UPDATE ENF_IT01
SET ENF_UTRIB = UPPER(ENF_UTRIB)
WHERE ENF_UTRIB IS NOT NULL;