UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.560',
    VERSAOSISTEMA.DATA   = '31.08.2021',
	VERSAO = '3.0.9.560'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE USUARIO_PARAMETRO ADD USP_VISUALIZA_ABA_VENDA CHAR(1);
UPDATE USUARIO_PARAMETRO SET USP_VISUALIZA_ABA_VENDA = 'S';
COMMIT WORK;

ALTER TABLE PRMT0001 ADD PMT_PRD_REFER_SCO_REFER VARCHAR(20);
COMMENT ON COLUMN PRMT0001.PMT_PRD_REFER_SCO_REFER is 'Referência genérica de Produto para a Solicitação de Compra';
UPDATE PRMT0001 set PMT_PRD_REFER_SCO_REFER = '999999' WHERE PMT_PRD_REFER_SCO_REFER IS NULL;
COMMIT WORK;
ALTER TABLE USUARIO_PARAMETRO ADD USP_AUTORIZA_COTACAO_MATERIAL CHAR(1);
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_AUTORIZA_COTACAO_MATERIAL is 'Responsável pela autorização da cotação dos materiais';
UPDATE USUARIO_PARAMETRO SET USP_AUTORIZA_COTACAO_MATERIAL = 'N';
COMMIT WORK;
ALTER TABLE USUARIO_PARAMETRO ADD USP_AUTORIZA_COMPRA_MATERIAL CHAR(1);
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_AUTORIZA_COMPRA_MATERIAL is 'Responsável pela compra dos materiais';
UPDATE USUARIO_PARAMETRO SET USP_AUTORIZA_COMPRA_MATERIAL = 'N';
COMMIT WORK;
ALTER TABLE USUARIO_PARAMETRO ADD USP_REALIZA_COTACAO_MATERIAL CHAR(1);
COMMENT ON COLUMN USUARIO_PARAMETRO.USP_REALIZA_COTACAO_MATERIAL is 'Responsável pela cotacao dos materiais';
UPDATE USUARIO_PARAMETRO SET USP_REALIZA_COTACAO_MATERIAL = 'N';
COMMIT WORK;

ALTER TABLE PRMT0001 ADD PMT_DESCRICAO_99_OUTROS VARCHAR(100);
UPDATE PRMT0001 SET PMT_DESCRICAO_99_OUTROS = 'NÃO IDENTIFICADO' WHERE PMT_DESCRICAO_99_OUTROS IS NULL ;
COMMIT WORK;

ALTER TABLE PED0000 ADD PED_ORS_CLI_CONSFINAL INTEGER;
ALTER TABLE PED0000 ADD PED_ORS_CLI_CONSU_PROPRIO INTEGER;
ALTER TABLE PED0000 ADD PED_ORS_CLI_REGIME_TRIBUTARIO INTEGER;
