UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.540 patch 15',
       VERSAOSISTEMA.DATA   = '28.01.2020',
	    VERSAO = '3.0.9.540'
 where VERSAOSISTEMA.CODIGO = 1;
 
ALTER TABLE PRD_UNIDADE ALTER COLUMN  PRD_UNISIGLA TYPE VARCHAR(6);
INSERT INTO PRD_UNIDADE  VALUES (40,40,'CENTO','CENTO','001');
INSERT INTO PRD_UNIDADE  VALUES (41,41,'UND','UND','001');

commit work;

ALTER TABLE PRD0000 ALTER COLUMN PRD_UND TYPE VARCHAR(6);
ALTER TABLE OCP_IT01 ALTER COLUMN PRD_UND TYPE VARCHAR(6);
ALTER TABLE PED_IT01 ALTER COLUMN PRD_UND TYPE VARCHAR(6);

CREATE INDEX FATPC_IDX1 ON NFSE_FATPC (EMP_CODIGO,FAT_CODIGO,FPC_NUMER);

SET TERM ^ ;
execute block
AS
BEGIN
 IF (EXISTS    (SELECT RDB$INDEX_NAME
              FROM RDB$INDICES
             WHERE RDB$INDEX_NAME='XFAT_CODIGO_EMPRESA')) THEN 
    EXECUTE STATEMENT 'DROP INDEX XFAT_CODIGO_EMPRESA';
END
^
SET TERM ; ^


SET TERM ^ ;
execute block
AS
BEGIN
 IF (EXISTS    (SELECT RDB$INDEX_NAME
              FROM RDB$INDICES
             WHERE RDB$INDEX_NAME='XNF_NU_N')) THEN 
    EXECUTE STATEMENT 'DROP INDEX XNF_NU_N';
END
^
SET TERM ; ^
