SET TERM ^ ;


Update VERSAOSISTEMA SET
       VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.0.443' ,
       VERSAOSISTEMA.DATA   = '01.01.2016'
 where VERSAOSISTEMA.CODIGO = 1^
 
UPDATE CLI0000 SET CLI_INSC = ''  WHERE CLI_PESSOA = 'F'^

UPDATE CLI0000 SET CLI_CONSFINAL = 'S' WHERE CLI_PESSOA = 'F'^


commit work^
