UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.560 patch 2',
    VERSAOSISTEMA.DATA   = '14.09.2021',
	VERSAO = '3.0.9.560'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE OPE0000 ADD OPE_FORMULA_BASE_ICMS INTEGER;
ALTER TABLE OPE0000 ADD OPE_ICMS_DESONERADO_DIMINUI CHAR(1);

ALTER TABLE PED0000 ADD PED_OBS_PRODUCAO BLOB;

