/* novas tabelas */
CREATE TABLE IBS (
    IBS_ID INTEGER NOT NULL PRIMARY KEY,
    IBS_CODIGO VARCHAR(20) NOT NULL,
    IBS_DESCRICAO VARCHAR(255),
    IBS_ALIQUOTA NUMERIC(10,4) NOT NULL,
    IBS_ALIQUOTA_UF NUMERIC(10,4) NOT NULL,
    CID_CODIGO INTEGER
);

CREATE TABLE CBS (
    CBS_ID INTEGER NOT NULL PRIMARY KEY,
    CBS_CODIGO VARCHAR(20) NOT NULL,
    CBS_DESCRICAO VARCHAR(255),
    CBS_ALIQUOTA NUMERIC(10,4) NOT NULL
);

CREATE SEQUENCE GEN_IBS_ID;
CREATE SEQUENCE GEN_CBS_ID;

/* alteração nas tabelas existentes */

/* Tabela de CFOP*/
ALTER TABLE OPE0000
ADD IBS_ID INTEGER,
ADD CBS_ID INTEGER;

ALTER TABLE OPE0000
  ADD CONSTRAINT FK_OPE0000_IBS FOREIGN KEY (IBS_ID) REFERENCES IBS (IBS_ID),
  ADD CONSTRAINT FK_OPE0000_CBS FOREIGN KEY (CBS_ID) REFERENCES CBS (CBS_ID);


/* Tabela de Produtos */
ALTER TABLE PRD0000
ADD IBS_ID INTEGER,
ADD CBS_ID INTEGER,
ADD IS_ALIQUOTA NUMERIC(10,4);

ALTER TABLE PRD0000
  ADD CONSTRAINT FK_PRD0000_IBS FOREIGN KEY (IBS_ID) REFERENCES IBS (IBS_ID),
  ADD CONSTRAINT FK_PRD0000_CBS FOREIGN KEY (CBS_ID) REFERENCES CBS (CBS_ID);

ALTER TABLE PRMT0001 ADD PMT_ATIVAR_IBS_CBS CHAR(1);
ALTER TABLE PRMT0001 ADD PMT_IBS_ALIQUOTA_MUNICIPAL NUMERIC(10,4); 
ALTER TABLE PRMT0001 ADD PMT_IBS_ALIQUOTA_ESTADUAL NUMERIC(10,4);
ALTER TABLE PRMT0001 ADD PMT_CBS_ALIQUOTA NUMERIC(10,4);
ALTER TABLE PRMT0001 ADD PMT_CST_IBS_CBS VARCHAR(3);



/* issue 2066*/
UPDATE PRMT0001 p 
	SET PMT_ATIVAR_IBS_CBS = 'S', 
	PMT_IBS_ALIQUOTA_MUNICIPAL = 0, 
	PMT_IBS_ALIQUOTA_ESTADUAL = 0.1,
	PMT_CBS_ALIQUOTA = 0.9,
	PMT_CST_IBS_CBS = '000'
WHERE p.PMT_CST_IBS_CBS IS NULL;

