UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.573 patch 2',
    VERSAOSISTEMA.DATA   = '20.10.2022',
	VERSAO = '3.0.9.573'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE CAPACIDADE ADD CAP_SUBSTITUICAO_TRIBUTARIA VARCHAR(1);

ALTER TABLE capacidade ADD EMP_CODIGO VARCHAR(3);
UPDATE CAPACIDADE SET EMP_CODIGO = '001';
COMMIT WORK;

ALTER TABLE ENF_IT01 ADD ENF_IT_ENVIADO_PCP_DEMANDA VARCHAR(1);
ALTER TABLE ENF_IT01 ADD ENF_IT_QTD_ENV_PCP_DEMANDA NUMERIC(18,5);
ALTER TABLE DEMANDA_PRODUCAO ADD ENF_REGISTRO INTEGER;
ALTER TABLE PED_IT01 ADD ENF_REGISTRO INTEGER;
ALTER TABLE ENF_IT01 ADD PED_CODIGO VARCHAR(7);

ALTER TABLE MATERIAPRIMA_ORDEMPRODUCAO ADD FTI_TRATAMENTO_TERMICO VARCHAR(255);
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.FTI_TRATAMENTO_TERMICO is 'Tratamento Térmico';
ALTER TABLE MATERIAPRIMA_ORDEMPRODUCAO ADD FTI_TRATAMENTO_SUPERFICIAL VARCHAR(255);
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.FTI_TRATAMENTO_SUPERFICIAL is 'Tratamento Superficial';
ALTER TABLE MATERIAPRIMA_ORDEMPRODUCAO ADD FTI_TOLERANCIA VARCHAR(255);
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.FTI_TOLERANCIA is 'Tolerancia';
ALTER TABLE MATERIAPRIMA_ORDEMPRODUCAO ADD FTI_GRAVACAO VARCHAR(255);
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.FTI_GRAVACAO is 'Gravação';
ALTER TABLE MATERIAPRIMA_ORDEMPRODUCAO ADD FTI_CORTE_QUANTIDADE VARCHAR(255);
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.FTI_CORTE_QUANTIDADE is 'Quantidade'; 
ALTER TABLE MATERIAPRIMA_ORDEMPRODUCAO ADD FTI_CORTE_COMPRIMENTO VARCHAR(255);
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.FTI_CORTE_COMPRIMENTO is 'Comprimento Corte';
ALTER TABLE MATERIAPRIMA_ORDEMPRODUCAO ADD FTI_CORTE_QTDE_METROS VARCHAR(255);
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.FTI_CORTE_QTDE_METROS is 'Quantidade de Metros';
ALTER TABLE MATERIAPRIMA_ORDEMPRODUCAO ADD FTI_CORTE_OBSERVACAO BLOB SUB_TYPE TEXT;
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.FTI_CORTE_OBSERVACAO is 'Observação do Corte';
ALTER TABLE MATERIAPRIMA_ORDEMPRODUCAO ADD FTI_USINAGEM_OBSERVACAO BLOB SUB_TYPE TEXT;
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.FTI_USINAGEM_OBSERVACAO is 'Observação da Usinagem';
ALTER TABLE MATERIAPRIMA_ORDEMPRODUCAO ADD FTI_PRENSA_TIPO_CABECA VARCHAR(255);
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.FTI_PRENSA_TIPO_CABECA is 'Tipo de Cabeça';
ALTER TABLE MATERIAPRIMA_ORDEMPRODUCAO ADD FTI_PRENSA_CHAVE VARCHAR(255);
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.FTI_PRENSA_CHAVE is 'Chave';
ALTER TABLE MATERIAPRIMA_ORDEMPRODUCAO ADD FTI_PRENSA_ALT_CABECA VARCHAR(255);
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.FTI_PRENSA_ALT_CABECA is 'Altura da Cabeça';
ALTER TABLE MATERIAPRIMA_ORDEMPRODUCAO ADD FTI_PRENSA_MASSA VARCHAR(255);
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.FTI_PRENSA_MASSA is 'Massa';
ALTER TABLE MATERIAPRIMA_ORDEMPRODUCAO ADD FTI_PRENSA_CAIXA_N VARCHAR(255);
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.FTI_PRENSA_CAIXA_N is 'Caixa N';
ALTER TABLE MATERIAPRIMA_ORDEMPRODUCAO ADD FTI_PRENSA_MATRIZ VARCHAR(255);
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.FTI_PRENSA_MATRIZ is 'Matriz';
ALTER TABLE MATERIAPRIMA_ORDEMPRODUCAO ADD FTI_PRENSA_PINO VARCHAR(255);
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.FTI_PRENSA_PINO is 'Pino';
ALTER TABLE MATERIAPRIMA_ORDEMPRODUCAO ADD FTI_PRENSA_BUCHA VARCHAR(255);
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.FTI_PRENSA_BUCHA is 'Bucha';
ALTER TABLE MATERIAPRIMA_ORDEMPRODUCAO ADD FTI_PRENSA_CONTRA_BUCHA VARCHAR(255);
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.FTI_PRENSA_CONTRA_BUCHA is 'Contra Bucha';
ALTER TABLE MATERIAPRIMA_ORDEMPRODUCAO ADD FTI_PRENSA_OBSERVACAO BLOB SUB_TYPE TEXT;
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.FTI_PRENSA_OBSERVACAO is 'Observação da Prensa';
ALTER TABLE MATERIAPRIMA_ORDEMPRODUCAO ADD FTI_LAMINACAO_CAIXA_N VARCHAR(255);
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.FTI_LAMINACAO_CAIXA_N is 'Laminação da Caixa N.';
ALTER TABLE MATERIAPRIMA_ORDEMPRODUCAO ADD FTI_LAMINACAO_TIPO_ROLO VARCHAR(255);
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.FTI_LAMINACAO_TIPO_ROLO is 'Laminação Tipo de Rolo';
ALTER TABLE MATERIAPRIMA_ORDEMPRODUCAO ADD FTI_LAMINACAO_TIPO_ROSCA VARCHAR(255);
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.FTI_LAMINACAO_TIPO_ROSCA is 'Laminação Tipo Rosca';
ALTER TABLE MATERIAPRIMA_ORDEMPRODUCAO ADD FTI_LAMINACAO_ALT_USINAGEM VARCHAR(255);
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.FTI_LAMINACAO_ALT_USINAGEM is 'Alt Usinagem';
ALTER TABLE MATERIAPRIMA_ORDEMPRODUCAO ADD FTI_LAMINACAO_COMP_ROSCA VARCHAR(255);
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.FTI_LAMINACAO_COMP_ROSCA is 'Laminação da Caixa N.';
ALTER TABLE MATERIAPRIMA_ORDEMPRODUCAO ADD FTI_LAMINACAO_OBSERVACAO BLOB SUB_TYPE TEXT;
COMMENT ON COLUMN MATERIAPRIMA_ORDEMPRODUCAO.FTI_LAMINACAO_OBSERVACAO is 'Observação da Laminação';

