UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.543',
       VERSAOSISTEMA.DATA   = '02.04.2020',
	    VERSAO = '3.0.9.543'
 where VERSAOSISTEMA.CODIGO = 1;

commit work; 


ALTER TABLE OPV0000 ADD OPV_EXPEDICAO VARCHAR(1);
comment ON COLUMN OPV0000.opv_expedicao IS 'HABILITA ENVIO A EXPEDICAO'; 

UPDATE OPV0000
SET opv_expedicao = 'N';

commit work;

ALTER TABLE ORDEMPRODUCAO ADD OPR_DATAFATURA TIMESTAMP;
COMMENT ON COLUMN ORDEMPRODUCAO.OPR_DATAFATURA IS 'DATA QUE FOI FATURADO';
  
ALTER TABLE ORDEMPRODUCAO ADD OPR_LEADTIME NUMERIC (18,4);
COMMENT ON COLUMN ORDEMPRODUCAO.OPR_LEADTIME IS 'TEMPO GASTO DO PEDIDO ATE ENTREGA';

UPDATE PROCESSOS_PRODUCAO pcp
SET PCP_DATAINI = (SELECT MIN(app_dataini) FROM APONTAMENTO_PROCESSO ap WHERE ap.PCP_CODIGO = pcp.PCP_CODIGO)  ;

COMMIT WORK;

UPDATE PROCESSOS_PRODUCAO pcp
SET PCP_DATAFIM = (SELECT MAX(app_dataini) FROM APONTAMENTO_PROCESSO ap WHERE ap.PCP_CODIGO = pcp.PCP_CODIGO)  ; 

COMMIT WORK;

UPDATE CARGA CAR
SET CAR_DATAINI = (SELECT MIN(app_dataini) FROM APONTAMENTO_PROCESSO ap WHERE ap.CAR_CODIGO = car.CAR_CODIGO) ;  

COMMIT WORK;

UPDATE CARGA CAR
SET CAR_DATAFIM = (SELECT MAX(app_dataini) FROM APONTAMENTO_PROCESSO ap WHERE ap.CAR_CODIGO = car.CAR_CODIGO) ;  


COMMIT WORK;


UPDATE OCP0000 OCP
SET OCP_TOTAL =  CAST((SELECT SUM(OCI_QTDES*OCI_PRECO *( 1+CAST(OCI_IPI/100 AS NUMERIC(2,2))) * 
				    ( 1+CAST(COALESCE(OCI_PERC_ICMS_ST,0)/100 AS NUMERIC(2,2))))
				     FROM  OCP_IT01 IT
				     WHERE IT.OCP_CODIGO = OCP.OCP_CODIGO) AS NUMERIC (18,5))
WHERE OCP_STATUS = 'P';

COMMIT WORK;