UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.541 patch 6',
       VERSAOSISTEMA.DATA   = '18.02.2020',
	    VERSAO = '3.0.9.541'
 where VERSAOSISTEMA.CODIGO = 1;

commit work;

ALTER TABLE PED0000 ADD PED_FOI_ORCAMENTO VARCHAR(1);
COMMENT ON COLUMN PED0000.PED_FOI_ORCAMENTO IS 'PEDIDO FOI ORCAMENTO ';
      
UPDATE PED0000 PE
SET PED_FOI_ORCAMENTO = 'N'
WHERE NOT EXISTS (SELECT *  FROM OPV0000 OP WHERE OP.OPV_ORCAMENTO = 'S' AND OP.OPV_CODIGO = PE.OPV_CODIGO);
      
commit work;
	  
UPDATE PED0000 PE
SET PED_FOI_ORCAMENTO = 'S'
WHERE EXISTS (SELECT *  FROM OPV0000 OP WHERE OP.OPV_ORCAMENTO = 'S' AND OP.OPV_CODIGO = PE.OPV_CODIGO);

commit work;

ALTER TABLE OPE0000 ADD ope_oculta varchar(1);
COMMENT ON COLUMN OPE0000.OPE_OCULTA IS 'OCULTA CFOP NA LISTA QUE APARECE NO PEDIDO E FATURAMENTO, SERVE PARA REGRA FISCAL';

UPDATE OPE0000
SET ope_oculta = 'N';

commit work;
	  
CREATE OR ALTER VIEW OPE0000_VIEW_PESQUISA (OPE_CODIGO, CFOP, OPE_NATUREZA, OPE_DESCRI, OPE_TIPO, OPE_DENTRO, OPE_ATIVA, EMP_CODIGO, OPE_SERVICO,ope_oculta)
AS
select  ope_codigo,
        ope_natureza||' - '||ope_descri as Cfop,
        ope_natureza,
        ope_descri, ope_tipo, OPE_DENTRO, OPE_ATIVA, emp_codigo, OPE_SERVICO,ope_oculta
from ope0000
WHERE OPE_ATIVA = 'S'	;  
	  
ALTER TABLE OPERACOES ADD OPE_FORMULARIO INTEGER;
	  
	  