UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.573 patch 1',
    VERSAOSISTEMA.DATA   = '13.10.2022',
	VERSAO = '3.0.9.573'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE BAN_TRANSFERENCIA ADD BTR_REGISTRO_CONTRAPARTIDA INTEGER;

CREATE TABLE BAN_TRANSFERENCIA_MANUT_HIST (
  EMP_CODIGO VARCHAR(3), 
  BTH_DATA_EXCLUSAO TIMESTAMP,
  BTR_DATA DATE,
  BTR_DOCUMENTO VARCHAR(12),
  BTR_OBSERVACAO VARCHAR(255),
  BTR_VALOR NUMERIC(18, 5),
  USU_CODIGO INTEGER,
  BTH_USU_CODIGO INTEGER  
);


