UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.542',
       VERSAOSISTEMA.DATA   = '02.03.2020',
	    VERSAO = '3.0.9.542'
 where VERSAOSISTEMA.CODIGO = 1;

commit work;

ALTER TABLE PRMT0001 ADD PMT_INCLUIRRAPIDO VARCHAR(1);

COMMENT ON COLUMN PRMT0001.PMT_INCLUIRRAPIDO IS 'INCLUIR PRODUTOS MODO RAPIDO NA ENTRADA DE NOTA DE XML';

UPDATE PRMT0001
SET PMT_INCLUIRRAPIDO = 'N';

     