UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.565 patch 5',
    VERSAOSISTEMA.DATA   = '24.02.2022',
	VERSAO = '3.0.9.565'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

CREATE TABLE USUARIO_ALMOXARIFADO (USU_CODIGO INTEGER, AMX_CODIGO VARCHAR(4));

