ALTER TABLE OPE_REGRA ADD OPR_ISENTARICIMS VARCHAR(1);
COMMENT ON COLUMN OPE_REGRA.OPR_ISENTARICIMS IS 'QUANDO UM DETERMINADO NCM EH ISENTO DE ICMS E O CST FICA 41 E ICMS 0';

UPDATE OPE_REGRA
SET OPR_ISENTARICIMS = 'N';
COMMIT WORK;

COMMENT ON COLUMN CLI0000.CLI_CONSU_PROPRIO IS 'FIM DA VENDA : CONSUMO PROPRIO : S; REVENDA : N';

ALTER TABLE FAT_PC01 ALTER FPC_MOTIVO_EXCLUSAO TYPE VARCHAR(60);
COMMENT ON COLUMN FAT_PC01.FPC_MOTIVO_EXCLUSAO IS 'MOTIVO DE EXCLUSAO DA FATURA';
COMMENT ON COLUMN FAT_PC01.FPC_DATA_EXCLUSAO IS 'DATA DA EXCLUSAO';
COMMENT ON COLUMN FAT_PC01.FPC_HORA_EXCLUSAO IS 'HORA DA EXCLUSAO';