UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.569 patch 1',
    VERSAOSISTEMA.DATA   = '21.06.2022',
	VERSAO = '3.0.9.569'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE COTACAO ADD COT_OBSERVACAO_TEMP VARCHAR(1024);
UPDATE COTACAO SET COT_OBSERVACAO_TEMP = COT_OBSERVACAO; 
ALTER TABLE COTACAO DROP COT_OBSERVACAO;
ALTER TABLE COTACAO ALTER COLUMN COT_OBSERVACAO_TEMP TO COT_OBSERVACAO;

ALTER TABLE COTACAO_ITEM ADD PRD_DESCRICAO_TEMP VARCHAR(1024);
UPDATE COTACAO_ITEM SET PRD_DESCRICAO_TEMP = PRD_DESCRICAO; 
ALTER TABLE COTACAO_ITEM DROP PRD_DESCRICAO;
ALTER TABLE COTACAO_ITEM ALTER COLUMN PRD_DESCRICAO_TEMP TO PRD_DESCRICAO;

ALTER TABLE COTACAO_FORNECEDOR DROP COF_DATA_PRAZO_PAGAMENTO;
ALTER TABLE COTACAO_FORNECEDOR ADD PCL_CODIGO VARCHAR(3);
COMMENT ON COLUMN COTACAO_FORNECEDOR.PCL_CODIGO IS 'Prazo para Pagamento';

ALTER TABLE PRMT0001 ADD PMT_MSG_ORCAMENTO_INDUST VARCHAR(255);
COMMENT ON COLUMN PRMT0001.PMT_MSG_ORCAMENTO_INDUST IS 'Mensagem Padrão para o Relatório do Orçamento Industrial';
UPDATE PRMT0001 SET PMT_MSG_ORCAMENTO_INDUST = 'Para cada tipo de serviço' WHERE PMT_MSG_ORCAMENTO_INDUST IS NULL;

ALTER TABLE PRMT0001 ADD PMT_DESC_ORIGINAL_INDUST VARCHAR(1) DEFAULT 'N';
COMMENT ON COLUMN PRMT0001.PMT_DESC_ORIGINAL_INDUST IS 'Ativa referência e descrição original para remessa de industrialização';
ALTER TABLE PED_IT01 ALTER PRF_PRDDESCRI TYPE VARCHAR(255);




