UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.537 patch 5',
       VERSAOSISTEMA.DATA   = '16.10.2019',
	    VERSAO = '3.0.9.537'
 where VERSAOSISTEMA.CODIGO = 1;

COMMIT WORK;

ALTER TABLE cnae ADD cnae_ativo varchar(1);
comment ON COLUMN cnae.cnae_ativo IS 'A - ATIVO ; I : INATIVO';
 
UPDATE CNAE
SET CNAE_ATIVO = 'I';

COMMIT WORK;

CREATE OR ALTER VIEW CLIENTES_ATIVOS_VIEW (MON$ATTACHMENT_NAME, MON$REMOTE_ADDRESS, QTY)
AS
select MON$ATTACHMENT_NAME,SUBSTRING (MON$REMOTE_ADDRESS FROM 1 FOR 
case when POSITION('/' IN MON$REMOTE_ADDRESS)> 0 then  POSITION('/' IN MON$REMOTE_ADDRESS)-1
     else CHAR_LENGTH(MON$REMOTE_ADDRESS) end  ) as MON$REMOTE_ADDRESS   
, Count(*) as qty
from MON$ATTACHMENTS
WHERE "MON$STATE" = 1
AND MON$REMOTE_ADDRESS IS NOT NULL
group by MON$ATTACHMENT_NAME, MON$REMOTE_ADDRESS;