UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.556',
    VERSAOSISTEMA.DATA   = '06.05.2021',
	VERSAO = '3.0.9.556'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

CREATE SEQUENCE GEN_CONTROLE_DE_QUALIDADE;
ALTER SEQUENCE GEN_CONTROLE_DE_QUALIDADE RESTART WITH 6;
COMMENT ON SEQUENCE GEN_CONTROLE_DE_QUALIDADE IS 'Gerador de Códigos para o Controle de Qualidade';

CREATE SEQUENCE GEN_PARAMETROS_DA_QUALIDADE;
ALTER SEQUENCE GEN_PARAMETROS_DA_QUALIDADE RESTART WITH 1;
COMMENT ON SEQUENCE GEN_PARAMETROS_DA_QUALIDADE IS 'Gerador de Códigos para os Parâmetros da Qualidade';

RECREATE TABLE CONTROLE_DE_QUALIDADE (
	CQUA_CODIGO INT PRIMARY KEY,
	CQUA_PRDL_LOTE VARCHAR(30) DEFAULT '',
	CQUA_IOP_NORDEM VARCHAR(20),
	CQUA_PAR_CODIGO INT,
	CQUA_RESULTADO VARCHAR(255) );

RECREATE TABLE PARAMETROS_DA_QUALIDADE (
	PAR_CODIGO INT,
	PAR_DESCRICAO VARCHAR(255),
	PAR_VALOR_MIN VARCHAR(255),
	PAR_VALOR_MAX VARCHAR(255) );	

RECREATE TABLE TIPO_EMBALAGEM(
	TEM_CODIGO INT PRIMARY KEY,
	TEM_DESCRICAO VARCHAR (255),
	EMP_CODIGO VARCHAR(3));
CREATE SEQUENCE GEN_TIPO_EMBALAGEM;
ALTER SEQUENCE GEN_TIPO_EMBALAGEM RESTART WITH 1;
COMMENT ON SEQUENCE GEN_TIPO_EMBALAGEM IS 'Gerador de Códigos para os Tipos de Embalagem';
ALTER TABLE MOLA_MATERIA ADD TEM_CODIGO INT;

ALTER TABLE MOLA_MATERIA ALTER COLUMN MMO_ALT_GANCHO TYPE VARCHAR(50);
ALTER TABLE MOLA_MATERIA ALTER COLUMN MMO_ABERT_GANCHO TYPE VARCHAR(50);	

ALTER TABLE MOLA_MATERIA ALTER COLUMN MMO_DIAMETRO_INT_MENOR TYPE VARCHAR(50);
ALTER TABLE MOLA_MATERIA ALTER COLUMN MMO_DIAMETRO_INT_MAIOR TYPE VARCHAR(50);
