SET TERM ^ ;

alter table prmt0001 add pmt_exibirmesimpostosparana char(1) ^
COMMIT WORK^
Update prmt0001 set pmt_exibirmesimpostosparana='S'^
COMMIT WORK^
DELETE FROM PED_MOTIVO^
COMMIT WORK^
INSERT INTO PED_MOTIVO (PMT_REGISTRO, EMP_CODIGO, PMT_MOTIVO) VALUES (1, '001', 'NÃO APROVADO')^
INSERT INTO PED_MOTIVO (PMT_REGISTRO, EMP_CODIGO, PMT_MOTIVO) VALUES (2, '001', 'CANCELADO')^
INSERT INTO PED_MOTIVO (PMT_REGISTRO, EMP_CODIGO, PMT_MOTIVO) VALUES (3, '001', 'PERDIDO POR PREÇO')^
INSERT INTO PED_MOTIVO (PMT_REGISTRO, EMP_CODIGO, PMT_MOTIVO) VALUES (4, '001', 'PERDIDO POR PRAZO')^
INSERT INTO PED_MOTIVO (PMT_REGISTRO, EMP_CODIGO, PMT_MOTIVO) VALUES (5, '001', 'PERDIDO POR PRODUTO')^
INSERT INTO PED_MOTIVO (PMT_REGISTRO, EMP_CODIGO, PMT_MOTIVO) VALUES (6, '001', 'PERDIDO POR PRAÇA')^
INSERT INTO PED_MOTIVO (PMT_REGISTRO, EMP_CODIGO, PMT_MOTIVO) VALUES (7, '001', 'OUTROS')^
COMMIT WORK^

Update VERSAOSISTEMA SET
       VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.0.452' ,
       VERSAOSISTEMA.DATA   = '06.06.2016'
 where VERSAOSISTEMA.CODIGO = 1^

COMMIT WORK^



SET TERM ; ^


