UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.568',
    VERSAOSISTEMA.DATA   = '09.05.2022',
	VERSAO = '3.0.9.568'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE NFSERVICO ALTER NFSE_CODVERIFICACAO TYPE VARCHAR(50);

ALTER TABLE ICM0000 ADD ICM_TIPO_CALCULO_DIFAL INTEGER;
COMMENT ON COLUMN ICM0000.ICM_TIPO_CALCULO_DIFAL is 'Tipo de Cálculo para difal - Consumidor Final - [0] Base Simples, [1] Base Por Dentro';
UPDATE ICM0000 SET ICM_TIPO_CALCULO_DIFAL = 1;
COMMIT TRANSACTION;


