UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.557 patch 1',
    VERSAOSISTEMA.DATA   = '11.06.2021',
	VERSAO = '3.0.9.557'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE PRMT0001 ADD PMT_AUTORIZA_EMPENHO CHAR(1);
UPDATE PRMT0001 SET PMT_AUTORIZA_EMPENHO = 'N' WHERE EMP_CODIGO <> '999'; 
commit work;

ALTER TABLE USUARIO_PARAMETRO ADD USP_STAT_CAMPO_TECNICO CHAR(1);
UPDATE USUARIO_PARAMETRO SET USP_STAT_CAMPO_TECNICO = 'N';
commit work;
