UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.587',
    VERSAOSISTEMA.DATA   = '04.12.2023',
	VERSAO = '3.0.9.587'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

/* issue 1662 */
ALTER TABLE PRMT0001 ADD PMT_RESP_TECNICO_QUALIDADE VARCHAR(255);
COMMENT ON COLUMN PRMT0001.PMT_RESP_TECNICO_QUALIDADE IS 'Responsável Técnico da Qualidade';
ALTER TABLE PRMT0001 ADD PMT_CRQ_RESP_TECNICO_QUALIDADE VARCHAR(255);
COMMENT ON COLUMN PRMT0001.PMT_CRQ_RESP_TECNICO_QUALIDADE IS 'CRQ do Responsável Técnico da Qualidade';

/* issue 1745 */
ALTER TABLE FAT_PC01 ADD FPC_CODIGO_REGISTRO_RETORNO VARCHAR(100);
COMMENT ON COLUMN FAT_PC01.FPC_CODIGO_REGISTRO_RETORNO IS 'Código do registro no arquivo de retorno';


