UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.578 patch 2',
    VERSAOSISTEMA.DATA   = '23.03.2023',
	VERSAO = '3.0.9.578'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE PRD_TIPO ALTER PTI_DESCRI TYPE VARCHAR(100);
COMMENT ON COLUMN PRD_TIPO.PTI_DESCRI  is 'Descrição do Tipo do Produto';

ALTER TABLE CLI0000 ADD CLI_DTNASCIMENTO TIMESTAMP;
COMMENT ON COLUMN CLI0000.CLI_DTNASCIMENTO  is 'Data de Nascimento do Cliente';

ALTER TABLE PRMT0001 ADD PMT_VALOR_DIFAL_PEDIDO VARCHAR(1) DEFAULT 'N';
COMMENT ON COLUMN PRMT0001.PMT_VALOR_DIFAL_PEDIDO is 'Mostrar o Valor do DIFAL no Pedido | [S] Sim [N] Não';
UPDATE PRMT0001 SET PMT_VALOR_DIFAL_PEDIDO = 'N' WHERE PMT_VALOR_DIFAL_PEDIDO IS NULL;
COMMIT;
ALTER TABLE PED0000 ADD PED_VLDIFAL NUMERIC(18,5); 
COMMENT ON COLUMN PED0000.PED_VLDIFAL is 'Valor do DIFAL no Pedido';

ALTER TABLE PRMT0001 ADD PMT_VENDA_CLI_SEM_CAD_OBRIG VARCHAR(1) DEFAULT 'N';
COMMENT ON COLUMN PRMT0001.PMT_VENDA_CLI_SEM_CAD_OBRIG is 'Obrigatório informar os campos do cliente sem cadastro | [S] Sim [N] Não';
UPDATE PRMT0001 SET PMT_VENDA_CLI_SEM_CAD_OBRIG = 'N' WHERE PMT_VENDA_CLI_SEM_CAD_OBRIG IS NULL;

ALTER TABLE NF0001 ADD NF_VLDIFAL NUMERIC(18,5);
COMMENT ON COLUMN NF0001.NF_VLDIFAL IS 'Valor do DIFAL'; 