UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.566 patch 4',
    VERSAOSISTEMA.DATA   = '25.03.2022',
	VERSAO = '3.0.9.566'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE PCL0000 ADD PCL_VALOR_MINIMO_VENDA NUMERIC(18,5) DEFAULT 0;
UPDATE PCL0000 SET PCL_VALOR_MINIMO_VENDA = 0;
COMMIT WORK;
ALTER TABLE USUARIO_PARAMETRO ADD USP_PEDIDO_ABAIXO_PRAZO_MINIMO CHAR(1) DEFAULT 'N';
ALTER TABLE PED0000 ADD PED_PERMITE_VL_ABAIXO_PRAZO_MIN CHAR(1) DEFAULT 'N';

ALTER TABLE PRMT0001 ADD PMT_CAMINHO_IMAGEM_OP VARCHAR(255);
