UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.571 patch 3',
    VERSAOSISTEMA.DATA   = '25.08.2022',
	VERSAO = '3.0.9.571'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

UPDATE OCP0000 SET OCP_TPPAGTO = '1' WHERE OCP_TPPAGTO = 'C';
UPDATE OCP0000 SET OCP_TPPAGTO = '2' WHERE OCP_TPPAGTO = 'F';
UPDATE OCP0000 SET OCP_TPPAGTO = '9' WHERE OCP_TPPAGTO = 'O';
COMMIT;

ALTER TABLE PRD0000 ADD PRD_DESCONTO NUMERIC(18,5);

ALTER TABLE PRMT0001 ADD PMT_VINC_NF_ITEM_RETORNO VARCHAR(1) DEFAULT 'N';
COMMENT ON COLUMN PRMT0001.PMT_VINC_NF_ITEM_RETORNO is 'Vincula nota fiscal ao item de retorno';

ALTER TABLE COTACAO_FORNECEDOR ADD COF_VIA_TRANSPORTE INTEGER;


