UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.540 patch 2',
       VERSAOSISTEMA.DATA   = '09.01.2020',
	    VERSAO = '3.0.9.540'
 where VERSAOSISTEMA.CODIGO = 1;

 commit work;

-- PEDIDO FATURADOS TOTAIS
UPDATE PED0000 p
  SET PED_VLFATURADO = PED_VLTOTAL_BRUTO
  WHERE PED_SITUACAO = 'T';
  
  
  COMMIT WORK;
  
  
ALTER TABLE PEDIDO_WEB ADD PW_PEDIDO_MERCOS INTEGER; 
COMMENT ON COLUMN PEDIDO_WEB.PW_PEDIDO_MERCOS IS 'CODIGO DO PEDIDO QUE APARECE NO SITE';