UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.562',
    VERSAOSISTEMA.DATA   = '03.11.2021',
	VERSAO = '3.0.9.562'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE OPV0000 ADD OPV_INDUST_POR_KIT CHAR(1);
CREATE TABLE PED_IND_KIT (
	ENF_NOTANUMBER VARCHAR(10),
	PRD_REFER VARCHAR(20),
	QTD_RETORNADO FLOAT	
);
CREATE INDEX IDX_PED_IND_KIT ON PED_IND_KIT(ENF_NOTANUMBER, PRD_REFER);

