UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.611 patch 1',
    VERSAOSISTEMA.DATA   = '10.02.2026',
	VERSAO = '3.0.9.611'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

/* issues 2164 */

ALTER TABLE PED_IT01_DI ADD PID_NUMERO_DI_TMP VARCHAR(15);
UPDATE PED_IT01_DI SET PID_NUMERO_DI_TMP = PID_NUMERO_DI;
ALTER TABLE PED_IT01_DI DROP PID_NUMERO_DI;
ALTER TABLE PED_IT01_DI ALTER PID_NUMERO_DI_TMP TO PID_NUMERO_DI;


