UPDATE  VERSAOSISTEMA 
SET    VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.526',
       VERSAOSISTEMA.DATA   = '24.01.2018',
       VERSAO = '3.0.9.526'
where VERSAOSISTEMA.CODIGO = 1;


ALTER TABLE PED_IT01 ADD  PRF_QTDEPEND NUMERIC(18,5);
ALTER TABLE PED_IT01 DROP PRF_ATUALIZOU_ESTOQUE;

ALTER TABLE PRMT0001 ADD PMT_FATURAR_PENDENCIAS VARCHAR(1);

UPDATE PRMT0001
SET PMT_FATURAR_PENDENCIAS = 'N';

alter table NFSERVICO alter column NFSE_CODVERIFICACAO type varchar(18);