UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.558',
    VERSAOSISTEMA.DATA   = '07.07.2021',
	VERSAO = '3.0.9.558'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

CREATE INDEX USUARIO_PARAMETRO_IDX1 ON USUARIO_PARAMETRO (USP_COD_USUARIO);
CREATE INDEX USUARIO_PARAMETRO_IDX2 ON USUARIO_PARAMETRO (USP_REGISTRO);
CREATE INDEX USUARIO_EMPRESA_IDX1 ON USUARIO_EMPRESA (USU_CODIGO);
CREATE INDEX USUARIO_IDX1 ON USUARIO (USU_CODIGO);

CREATE INDEX USUARIO_ACESSO_IDX1 ON USUARIO_ACESSO (USA_COD_USUARIO);
CREATE INDEX USUARIO_ACESSO_IDX2 ON USUARIO_ACESSO (USA_REGISTRO);

CREATE INDEX NFSERVICO_IDX1 ON NFSERVICO (RPS_CODIGO);
CREATE INDEX NFSERVICO_IDX2 ON NFSERVICO (EMP_CODIGO);
CREATE INDEX NFSE_FATPC_IDX2 ON NFSE_FATPC (NFSE_CODIGO);

CREATE INDEX NFSE_XML_IDX1 ON NFSE_XML (NFSE_CODIGO);
CREATE INDEX NFSE_XML_IDX2 ON NFSE_XML (NSX_DTGERADO);

CREATE INDEX NFSE_FATPC_IDX1 ON NFSE_FATPC (NFSE_CODIGO);
CREATE INDEX NFSE_FATPC_IDX2 ON NFSE_FATPC (FAT_CODIGO);

CREATE INDEX LOTE_NFSE_IDX2 ON LOTE_NFSE (NUM_LOTE);

CREATE INDEX NFSE_IT_IDX1 ON NFSE_IT (NFSE_CODIGO);

CREATE INDEX NFSE_XML_IDX1 ON NFSE_XML (NFSE_CODIGO);
CREATE INDEX SRV0000_IDX1 ON SRV0000 (SRV_CODIGO);
CREATE INDEX SRV0000_IDX2 ON SRV0000 (SRV_LANCAMENTO);
CREATE INDEX CID0000_IDX1 ON CID0000 (CID_CODIGO);
CREATE INDEX DANFSE_IDX1 ON DANFSE (NFSE_CODIGO);
CREATE INDEX DANFSE_IDX2 ON DANFSE (DFS_CODIGO);
CREATE INDEX NFS_HISTORICO_IDX1 ON NFS_HISTORICO (NFSE_CODIGO);
CREATE INDEX NFS_HISTORICO_IDX2 ON NFS_HISTORICO (NFH_CODIGO);
