ALTER TABLE OSV0001
   ADD OSV_QTDE_CONCLUIDA DECIMAL6;
COMMIT WORK;

UPDATE osv0001 SET OSV_QTDE_CONCLUIDA = OSV_QTDE
  WHERE OSV_STATUS = 'C';
COMMIT WORK; 

ALTER TABLE PEDIDO_WEB_ITEM
    ADD SPWI_DESCTO_VALOR DECIMAL6,
    ADD SPWI_DESCTO_PERCENT DECIMAL6,
    ADD SPWI_PRECO_LIQUIDO DECIMAL6;
COMMIT WORK;    
    
ALTER TABLE PEDIDO_WEB
    ALTER PW_DATA_STATUS TYPE TIMESTAMP,
    ALTER PW_DATA TYPE TIMESTAMP;
COMMIT WORK;

ALTER TABLE PEDIDO_WEB
    ADD SPW_TIPOPEDIDO VARCHAR(20),
    ADD SPW_DATA_ENTREGA DATE,
    ADD SPW_CLI_RAZAO VARCHAR(55),
    ADD SPW_CLI_CIDADE VARCHAR(30),
    ADD SPW_CLI_UF VARCHAR(2),
    ADD SPW_CLI_CEP VARCHAR(8),
    ADD SPW_CLI_ENDERE VARCHAR(50),
    ADD SPW_CLI_NUMERO INTEGER,
    ADD SPW_CLI_COMPLEMENTO VARCHAR(15),
    ADD SPW_CLI_TELEFONE1 VARCHAR(11),
    ADD SPW_CLI_TELEFONE2 VARCHAR(11),
    ADD SPW_CLI_CELULAR VARCHAR(11),
    ADD SPW_CLI_EMAIL VARCHAR(150),
    ADD SPW_CLI_EMAIL_NFE VARCHAR(150),
    ADD SPW_CLI_OBS VARCHAR(500),
    ADD SPW_CLI_INSCRICAO VARCHAR(18),
    ADD SPW_ORDEM VARCHAR(18),
    ADD SPW_OBS_PED VARCHAR(500),
    ADD SPW_OBS_NOTA VARCHAR(500);
COMMIT WORK;    


ALTER TABLE CLI0000
    ADD CLI_VALORFRETE DECIMAL6,
    ADD CLI_VALORDESPESAS DECIMAL6;
COMMIT WORK;
    
CREATE TABLE OPERACOES (
    CODIGO INTEGER NOT NULL,
    DESCRICAO VARCHAR(60),
    COD_PRODUTO VARCHAR(5));
    
COMMIT WORK;    

ALTER TABLE OPERACOES
ADD CONSTRAINT PK_OPERACOES
PRIMARY KEY (CODIGO);    

COMMIT WORK;
    
CREATE TABLE OCORRENCIA (
    CODIGO INTEGER NOT NULL,
    DESCRICAO VARCHAR(60));

COMMIT WORK;
    
ALTER TABLE OCORRENCIA
ADD CONSTRAINT PK_OCORRENCIA
PRIMARY KEY (CODIGO);
    
COMMIT WORK;
    
CREATE TABLE EQUIP (
    CODIGO INTEGER NOT NULL,
    DESCRICAO VARCHAR(60));

COMMIT WORK;

ALTER TABLE EQUIP
ADD CONSTRAINT PK_EQUIP
PRIMARY KEY (CODIGO)    ;

COMMIT WORK;

CREATE SEQUENCE GEN_EQUIP;

COMMIT WORK;

CREATE SEQUENCE GEN_SETOR;

COMMIT WORK;

CREATE SEQUENCE GEN_OCORRENCIA_CODIGO;

COMMIT WORK;

CREATE SEQUENCE GEN_OPERACOES;

COMMIT WORK;

ALTER TABLE FOR0000
    ALTER FONE_RESIDENCIAL TYPE VARCHAR(16) CHARACTER SET NONE,
    ALTER FONE_CELULAR TYPE VARCHAR(20) CHARACTER SET NONE,
    ALTER CBO TYPE VARCHAR(100),
    ALTER PIS_AGENCIA TYPE VARCHAR(11);
COMMIT WORK;

ALTER TABLE USUARIO_PARAMETRO
   ADD LIBERA_COLABORADOR CHAR(1);
COMMIT WORK;

CREATE OR ALTER VIEW USUARIO_TUDO_VIEW(
    USP_REGISTRO,
    USP_COD_USUARIO,
    USP_STAT_PRECO_BRUTO_P,
    USP_STAT_PRECO_LIQUIDO_P,
    USP_STAT_DESC_AUTOMATICO_P,
    USP_DESCONTO_MAX_P,
    USP_REEMISSAO_PEDIDO_P,
    USP_EXCLUSAO_PEDIDO_P,
    USP_STAT_PRECO_BRUTO_T,
    USP_STAT_PRECO_LIQUIDO_T,
    USP_STAT_DESC_AUTOMATICO_T,
    USP_DESCONTO_MAX_T,
    USP_REEMISSAO_PEDIDO_T,
    USP_EXCLUSAO_PEDIDO_T,
    USP_STAT_COMISSAO,
    USP_STAT_CUSTO,
    USP_STAT_MARGEM,
    USP_STAT_PRECO_VENDA,
    USP_STAT_MARGEM_MINIMA,
    USP_STAT_PRECO_OFERTA,
    USP_ALTERA_DESCONTO_P,
    USP_ALTERA_DESCONTO_T,
    USP_DESCONTO_OFERTA_P,
    USP_DESCONTO_OFERTA_T,
    USP_ALTERA_NF_ENTRADA,
    USP_RELATORIOS_P,
    USP_VISUALIZA_PEDIDOS_P,
    USP_ALTERA_COMISSAO,
    USP_KARDEX_LANC_ENTRADA,
    USP_KARDEX_LANC_SAIDA,
    USP_KARDEX_LANC_BALANCO,
    USP_LIBERA_ANALISE_CREDITO,
    USP_LIBERA_ANALISE_PRODUCAO,
    USP_VENDA_CADASTRO_PRODUTO,
    USP_VENDA_REAJUSTE,
    USP_VISUALIZA_CLIENTES_P,
    USP_VISUALIZA_ANALISE_CREDITO_,
    USP_ALTERA_CUSTOS_PRODUTO,
    USP_VISUALIZA_MARKUP_PEDIDO,
    USP_VENDA_TRANSFERENCIA,
    USP_ALTERA_TABELA_PRECOS,
    USP_USAPRAZODESABILITADO,
    USU_CODIGO,
    USU_DATA_CADASTRO,
    USU_DATA_ATUALIZACAO,
    USU_NOME,
    USU_SENHA,
    USU_TIPO_USUARIO,
    USU_LIBERA_CREDITO,
    USU_LIBERA_PRECO,
    USU_LIBERA_DESCONTO,
    USU_MENU01,
    USU_MENU02,
    USU_MENU03,
    USU_MENU04,
    USU_MENU05,
    USU_MENU06,
    USU_MENU07,
    USU_MENU08,
    USU_MENU09,
    USU_MENU010,
    USU_MENU011,
    USU_MENU012,
    USU_MENU013,
    USU_MENU014,
    USU_MENU015,
    USU_INCLUSAO,
    USU_ALTERACAO,
    USU_EXCLUSAO,
    USU_ESTATISTICA,
    USU_LOGIN,
    USU_EMAIL,
    USU_REEMISSAO_PED,
    REP_CODIGO,
    PERMITE_VENDA_ABAIXO_CUSTO,
    PERMITE_VER_CUSTO,
    LIBERA_COLABORADOR)
AS
select a.*, c.*
from USUARIO_PARAMETRO a, usuario c
where c.usu_codigo = a.usp_cod_usuario;
COMMIT WORK;

    
UPDATE  VERSAOSISTEMA SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.0.485',
       VERSAOSISTEMA.DATA   = '17.05.2017'
 where VERSAOSISTEMA.CODIGO = 1;
 
COMMIT WORK;
