UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.566',
    VERSAOSISTEMA.DATA   = '28.02.2022',
	VERSAO = '3.0.9.566'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE OPV0000 ADD OPV_BAIXAR_ESTOQUE_PELO_FAT CHAR(1) DEFAULT 'N';
UPDATE OPV0000 SET OPV_BAIXAR_ESTOQUE_PELO_FAT ='N';
commit work;
