ALTER TABLE FAT_PC01 ADD FPG_REGISTRO INTEGER;
ALTER TABLE NF0001 ADD FPG_REGISTRO INTEGER;
COMMENT ON COLUMN FAT_PC01.FPG_REGISTRO IS 'CHAVE REFERENCIA A FORMA PAGAMENTO';
COMMENT ON COLUMN NF0001.FPG_REGISTRO IS 'CHAVE REFERENCIA A FORMA PAGAMENTO';

UPDATE FAT_PC01 
SET FPG_REGISTRO = (SELECT first 1 FPG_REGISTRO FROM FAT0000 FAT 
                    JOIN PED0000 PE ON (PE.PED_CODIGO = FAT.PED_CODIGO AND PE.EMP_CODIGO = FAT.EMP_CODIGO) 
                    WHERE FAT_PC01.FAT_CODIGO = FAT.FAT_CODIGO 
                    AND FAT.EMP_CODIGO = FAT_PC01.EMP_CODIGO
                    AND FPG_REGISTRO > 0 
                    );

					
					
commit work;					


UPDATE NF0001
SET FPG_REGISTRO = (SELECT first 1 pe.FPG_REGISTRO 
                    FROM PED0000 PE WHERE  PE.PED_CODIGO = NF0001.PED_CODIGO AND PE.EMP_CODIGO = NF0001.EMP_CODIGO
                    AND  pe.FPG_REGISTRO > 0 
                    ) ;
					
					
					
