ALTER TABLE PED0000
    ADD PED_PLACA VARCHAR(7);
	
COMMIT WORK;
	
UPDATE  VERSAOSISTEMA SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.0.483',
       VERSAOSISTEMA.DATA   = '10.04.2017'
 where VERSAOSISTEMA.CODIGO = 1;
 
COMMIT WORK;

 