UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.572',
    VERSAOSISTEMA.DATA   = '06.09.2022',
	VERSAO = '3.0.9.572'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE LOTE_NFSE ALTER LSE_PROTOCOLO TYPE VARCHAR(36);
ALTER TABLE EMP0000  ADD EMP_NFS_SENHA VARCHAR(255);

ALTER TABLE FTC_IT01 ADD FTI_TRATAMENTO_TERMICO VARCHAR(255);
COMMENT ON COLUMN FTC_IT01.FTI_TRATAMENTO_TERMICO is 'Tratamento Térmico';
ALTER TABLE FTC_IT01 ADD FTI_TRATAMENTO_SUPERFICIAL VARCHAR(255);
COMMENT ON COLUMN FTC_IT01.FTI_TRATAMENTO_SUPERFICIAL is 'Tratamento Superficial';
ALTER TABLE FTC_IT01 ADD FTI_TOLERANCIA VARCHAR(255);
COMMENT ON COLUMN FTC_IT01.FTI_TOLERANCIA is 'Tolerancia';
ALTER TABLE FTC_IT01 ADD FTI_GRAVACAO VARCHAR(255);
COMMENT ON COLUMN FTC_IT01.FTI_GRAVACAO is 'Gravação';

ALTER TABLE FTC_IT01 ADD FTI_CORTE_QUANTIDADE VARCHAR(255);
COMMENT ON COLUMN FTC_IT01.FTI_CORTE_QUANTIDADE is 'Quantidade'; 
ALTER TABLE FTC_IT01 ADD FTI_CORTE_COMPRIMENTO VARCHAR(255);
COMMENT ON COLUMN FTC_IT01.FTI_CORTE_COMPRIMENTO is 'Comprimento Corte';
ALTER TABLE FTC_IT01 ADD FTI_CORTE_QTDE_METROS VARCHAR(255);
COMMENT ON COLUMN FTC_IT01.FTI_CORTE_QTDE_METROS is 'Quantidade de Metros';
ALTER TABLE FTC_IT01 ADD FTI_CORTE_OBSERVACAO BLOB SUB_TYPE TEXT;
COMMENT ON COLUMN FTC_IT01.FTI_CORTE_OBSERVACAO is 'Observação do Corte';

ALTER TABLE FTC_IT01 ADD FTI_USINAGEM_OBSERVACAO BLOB SUB_TYPE TEXT;
COMMENT ON COLUMN FTC_IT01.FTI_USINAGEM_OBSERVACAO is 'Observação da Usinagem';

ALTER TABLE FTC_IT01 ADD FTI_PRENSA_TIPO_CABECA VARCHAR(255);
COMMENT ON COLUMN FTC_IT01.FTI_PRENSA_TIPO_CABECA is 'Tipo de Cabeça';
ALTER TABLE FTC_IT01 ADD FTI_PRENSA_CHAVE VARCHAR(255);
COMMENT ON COLUMN FTC_IT01.FTI_PRENSA_CHAVE is 'Chave';
ALTER TABLE FTC_IT01 ADD FTI_PRENSA_ALT_CABECA VARCHAR(255);
COMMENT ON COLUMN FTC_IT01.FTI_PRENSA_ALT_CABECA is 'Altura da Cabeça';
ALTER TABLE FTC_IT01 ADD FTI_PRENSA_MASSA VARCHAR(255);
COMMENT ON COLUMN FTC_IT01.FTI_PRENSA_MASSA is 'Massa';
ALTER TABLE FTC_IT01 ADD FTI_PRENSA_CAIXA_N VARCHAR(255);
COMMENT ON COLUMN FTC_IT01.FTI_PRENSA_CAIXA_N is 'Caixa N';
ALTER TABLE FTC_IT01 ADD FTI_PRENSA_MATRIZ VARCHAR(255);
COMMENT ON COLUMN FTC_IT01.FTI_PRENSA_MATRIZ is 'Matriz';
ALTER TABLE FTC_IT01 ADD FTI_PRENSA_PINO VARCHAR(255);
COMMENT ON COLUMN FTC_IT01.FTI_PRENSA_PINO is 'Pino';
ALTER TABLE FTC_IT01 ADD FTI_PRENSA_BUCHA VARCHAR(255);
COMMENT ON COLUMN FTC_IT01.FTI_PRENSA_BUCHA is 'Bucha';
ALTER TABLE FTC_IT01 ADD FTI_PRENSA_CONTRA_BUCHA VARCHAR(255);
COMMENT ON COLUMN FTC_IT01.FTI_PRENSA_CONTRA_BUCHA is 'Contra Bucha';
ALTER TABLE FTC_IT01 ADD FTI_PRENSA_OBSERVACAO BLOB SUB_TYPE TEXT;
COMMENT ON COLUMN FTC_IT01.FTI_PRENSA_OBSERVACAO is 'Observação da Prensa';

ALTER TABLE FTC_IT01 ADD FTI_LAMINACAO_CAIXA_N VARCHAR(255);
COMMENT ON COLUMN FTC_IT01.FTI_LAMINACAO_CAIXA_N is 'Laminação da Caixa N.';
ALTER TABLE FTC_IT01 ADD FTI_LAMINACAO_TIPO_ROLO VARCHAR(255);
COMMENT ON COLUMN FTC_IT01.FTI_LAMINACAO_TIPO_ROLO is 'Laminação Tipo de Rolo';
ALTER TABLE FTC_IT01 ADD FTI_LAMINACAO_TIPO_ROSCA VARCHAR(255);
COMMENT ON COLUMN FTC_IT01.FTI_LAMINACAO_TIPO_ROSCA is 'Laminação Tipo Rosca';
ALTER TABLE FTC_IT01 ADD FTI_LAMINACAO_ALT_USINAGEM VARCHAR(255);
COMMENT ON COLUMN FTC_IT01.FTI_LAMINACAO_ALT_USINAGEM is 'Alt Usinagem';
ALTER TABLE FTC_IT01 ADD FTI_LAMINACAO_COMP_ROSCA VARCHAR(255);
COMMENT ON COLUMN FTC_IT01.FTI_LAMINACAO_COMP_ROSCA is 'Laminação da Caixa N.';
ALTER TABLE FTC_IT01 ADD FTI_LAMINACAO_OBSERVACAO BLOB SUB_TYPE TEXT;
COMMENT ON COLUMN FTC_IT01.FTI_LAMINACAO_OBSERVACAO is 'Observação da Laminação';

ALTER TABLE PED_IT01 ADD ACO_CODIGO INTEGER;
COMMENT ON COLUMN PED_IT01.ACO_CODIGO IS 'Chave Primária da Cor do Item do Pedido';

ALTER TABLE ENF0001 ADD ENF_PESO_L NUMERIC(18,5);


