UPDATE  VERSAOSISTEMA 
SET    VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.520',
       VERSAOSISTEMA.DATA   = '23.08.2018',
	   VERSAO = '3.0.9.520'
 where VERSAOSISTEMA.CODIGO = 1;
 
commit work;

ALTER TABLE NF0001 ADD NF_INTEGRADO VARCHAR(1);
ALTER TABLE NF0001 ADD NF_TIPONOTA VARCHAR(1);
ALTER TABLE FAT_PC01 ADD FPC_VALR_SERVICOS NUMERIC(18,5);
ALTER TABLE FAT0000 ADD FPC_VALORSERV_LIQ NUMERIC(18,5);
ALTER TABLE FAT0000 ADD FPC_VALORSERV_FAT NUMERIC(18,5);

COMMENT ON COLUMN NF0001.NF_INTEGRADO IS 'MARCADO PARA INTEGRAR NOTAS DE SERVICO E NFE';
COMMENT ON COLUMN NF0001.NF_TIPONOTA IS 'TIPO DE NOTA: P - NFE(PRODUTO), S  - NFSE';
COMMENT ON COLUMN FAT_PC01.FPC_VALR_SERVICOS IS 'VALOR DA PARCELA DE SERVICOS';
COMMENT ON COLUMN FAT0000.FPC_VALORSERV_LIQ IS 'VALOR LIQUIDO DO SERVICO';
COMMENT ON COLUMN FAT0000.FPC_VALORSERV_FAT IS 'VALOR FATURADO DO SERVICO';

ALTER TABLE FTC_IT01 ADD OPE_CODIGO INTEGER ;
COMMENT ON COLUMN FTC_IT01.OPE_CODIGO IS 'CHAVE REFERENCIA DA OPERACAO TAB (OPERACOES)';

ALTER TABLE OSV_IT02 ADD OPE_CODIGO INTEGER ;
COMMENT ON COLUMN OSV_IT02.OPE_CODIGO IS 'CHAVE REFERENCIA DA OPERACAO TAB (OPERACOES)';

ALTER TABLE SRV0000 ADD CODIGOSERVICO VARCHAR(5);
COMMENT ON COLUMN SRV0000.CODIGOSERVICO IS 'CODIGO DO SERVICO';
COMMENT ON COLUMN SRV0000.SRV_CODIGO IS 'ITEM DO SERVICO';


CREATE INDEX TAREFAS_CRM_IDX1
ON TAREFAS_CRM (TRF_ACAO,EMP_CODIGO,TRF_EXCLUIDO,CLI_CODIGO);

CREATE INDEX FAT_PC01_IDX7
ON FAT_PC01 (FPC_EXCLUSAO,EMP_CODIGO,CLI_CODIGO);

DROP INDEX XFATPCOMPOSTO;

