UPDATE  VERSAOSISTEMA 
SET VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.574 patch 1',
    VERSAOSISTEMA.DATA   = '11.11.2022',
	VERSAO = '3.0.9.574'
 where VERSAOSISTEMA.CODIGO = 1;
commit work;

ALTER TABLE PRMT0001 ADD PMT_ATUALIZA_LOTE VARCHAR(1);

CREATE TABLE PEDIDO_ITEM_LOTE (
  PRF_REGISTRO INTEGER PRIMARY KEY NOT NULL,
  PRDL_REGISTRO INTEGER,
  PIL_UTILIZADO NUMERIC(18,5)
);

INSERT INTO PEDIDO_ITEM_LOTE (PRF_REGISTRO, PRDL_REGISTRO,  PIL_UTILIZADO )
  SELECT PRF_REGISTRO, PRDL_REGISTRO, PRF_QTDE FROM PED_IT01 WHERE PRDL_REGISTRO > 0 ;
  

  