UPDATE  VERSAOSISTEMA 
SET    VERSAOSISTEMA.SCRIPTADJUTOR = '3.0.9.518',
       VERSAOSISTEMA.DATA   = '08.08.2018',
	   VERSAO = '3.0.9.519'
 where VERSAOSISTEMA.CODIGO = 1;
 
commit work;


 CREATE TABLE TAREFAS_CRM
 (TRF_REGISTRO INTEGER NOT null,
 TRF_DATA_REGISTRO TIMESTAMP NOT NULL,
 EMP_CODIGO VARCHAR(3) NOT null,
 REP_CODIGO VARCHAR(3),
 TRF_PRAZO TIMESTAMP,
 TRF_ASSUNTO BLOB SUB_TYPE 0,
 TRF_FINALIZADA VARCHAR(1),
 TRF_DATA_FINA TIMESTAMP,
 TRF_EXCLUIDO VARCHAR(1),
 TRF_DATA_EXCL TIMESTAMP,
 TRF_NIVEL INTEGER,
 CLI_CODIGO VARCHAR(5),
 TRF_NOMEEMPRESA VARCHAR(60),
 TRF_CONTATO VARCHAR(60),
 TRF_EMAILCONTATO VARCHAR(60),
 TRF_CONTATOFONE VARCHAR(11),
 TRF_CONTATOFONE2 VARCHAR(11),
 TRF_ENDERECO VARCHAR(100),
 TRF_ACAO INTEGER,
 TRF_ORIGEM INTEGER,
 CONSTRAINT PK_TAREFAS PRIMARY KEY (TRF_REGISTRO)
 );
CREATE SEQUENCE GEN_TAREFAS;

COMMENT ON TABLE TAREFAS_CRM IS 'TAREFAS DO CRM';
COMMENT ON COLUMN TAREFAS_CRM.TRF_REGISTRO IS 'IDENTIFICADOR DA TAREFA';
COMMENT ON COLUMN TAREFAS_CRM.REP_CODIGO IS 'REFERENCIA DA TABELA DE REPRESENTANTE/VENDEDOR';
COMMENT ON COLUMN TAREFAS_CRM.TRF_PRAZO IS 'PRAZO DA TAREFA';
COMMENT ON COLUMN TAREFAS_CRM.TRF_ASSUNTO IS 'ASSUNTO';
COMMENT ON COLUMN TAREFAS_CRM.TRF_FINALIZADA IS 'TAREFA FINALIZADA SE FOR IGUAL S';
COMMENT ON COLUMN TAREFAS_CRM.TRF_DATA_FINA IS 'DATA DE FINALIZACAO DA TAREFA';
COMMENT ON COLUMN TAREFAS_CRM.TRF_EXCLUIDO IS 'TAREFA FOI EXCLUIDA SE FOR S';
COMMENT ON COLUMN TAREFAS_CRM.TRF_DATA_EXCL IS 'DATA DA TAREFA EXCLUIDA';
COMMENT ON COLUMN TAREFAS_CRM.TRF_NIVEL IS 'NIVEL DE RELACIONAMENTO : 0 - PROSPECT ; 1 - LEAD ; 2 - CLIENTE; 3 -FORNECEDOR';
COMMENT ON COLUMN TAREFAS_CRM.CLI_CODIGO IS 'REFERENCIA DO CLIENTE DA TABELA CLI0000';
COMMENT ON COLUMN TAREFAS_CRM.TRF_CONTATO IS 'CONTATO DO CLIENTE, QUANDO AINDA NAO EH CLIENTE';
COMMENT ON COLUMN TAREFAS_CRM.TRF_EMAILCONTATO IS 'EMAIL DO CLIENTE ,QUANDO AINDA NAO EH CLIENTE';
COMMENT ON COLUMN TAREFAS_CRM.TRF_CONTATOFONE IS 'FONE DO CLIENTE, QUANDO AINDA NAO EH CLIENTE';
COMMENT ON COLUMN TAREFAS_CRM.TRF_ENDERECO IS 'ENDERECO DO CLIENTE, QUANDO AINDA NAO EH CLIENTE';
COMMENT ON COLUMN TAREFAS_CRM.TRF_ACAO IS 'ACAO PARA SE TOMAR NA TAREFA : 0 -EMAIL, 1-LIGACAO, 2-VISITA,3- PROPOSTA, 4-RENOVACAO';
COMMENT ON COLUMN TAREFAS_CRM.TRF_ORIGEM IS 'ORIGEM DO CONTATO FOI : 0 -CLIENTE, 1-EMAIL MKT, 2-SITE,3- INDICACAO, 4-PROSPRECCAO; 5-OUTROS';
COMMENT ON COLUMN TAREFAS_CRM.TRF_NOMEEMPRESA IS 'NOME DA EMPRESA ';
COMMENT ON COLUMN TAREFAS_CRM.TRF_CONTATOFONE2 IS 'TELEFONE 2';


ALTER TABLE PRD0000 ADD PRD_OUTROSCUSTOS NUMERIC(18,5);
COMMENT ON COLUMN PRD0000.PRD_OUTROSCUSTOS IS 'OUTROS CUSTOS';
COMMENT ON COLUMN PRD0000.PRD_PERC_COMISSAO IS 'PERCENTUAL DE COMISSAO ESCALONADO 1';
COMMENT ON COLUMN PRD0000.PRD_PERC_COMISSAO2  IS 'PERCENTUAL DE COMISSAO ESCALONADO 2';
COMMENT ON COLUMN PRD0000.PRD_PERC_COMISSAO3 IS 'PERCENTUAL DE COMISSAO ESCALONADO 3';
COMMENT ON COLUMN PRD0000.PRD_PERC_COMISSAO4 IS 'PERCENTUAL DE COMISSAO ESCALONADO 4';
COMMENT ON COLUMN PRD0000.PRD_PERC_COMISSAO5 IS 'PERCENTUAL DE COMISSAO ESCALONADO 5';
COMMENT ON COLUMN PRD0000.PRD_PERC_COMISSAO6 IS 'PERCENTUAL DE COMISSAO ESCALONADO 6';
COMMENT ON COLUMN PRD0000.PRD_PVENDA2 IS 'PRECO DE VENDA TABELA 2';
COMMENT ON COLUMN PRD0000.PRD_PVENDA3 IS 'PRECO DE VENDA TABELA 3';
COMMENT ON COLUMN PRD0000.PRD_PVENDA4 IS 'PRECO DE VENDA TABELA 4';
COMMENT ON COLUMN PRD0000.PRD_PVENDA5 IS 'PRECO DE VENDA TABELA 5';
COMMENT ON COLUMN PRD0000.PRD_PVENDA6 IS 'PRECO DE VENDA TABELA 6';
COMMENT ON COLUMN PRD0000.PRD_PERC_VENDA IS 'PERCENTUAL VERBA 1';
COMMENT ON COLUMN PRD0000.PRD_PERC_VENDA2 IS 'PERCENTUAL VERBA 2';
COMMENT ON COLUMN PRD0000.PRD_PERC_VENDA3 IS 'PERCENTUAL VERBA 3';
COMMENT ON COLUMN PRD0000.PRD_PERC_VENDA4 IS 'PERCENTUAL VERBA 4';
COMMENT ON COLUMN PRD0000.PRD_PERC_VENDA5 IS 'PERCENTUAL VERBA 5';
COMMENT ON COLUMN PRD0000.PRD_PERC_VENDA6 IS 'PERCENTUAL VERBA 6';

ALTER TABLE ENF0001 ADD ENF_VLFRETEPORFORA NUMERIC(18,5);
ALTER TABLE ENF0001 ADD ENF_VLRDIFICMS NUMERIC(18,5);
ALTER TABLE ENF0001 ADD ENF_VLOUTROS NUMERIC(18,5);

COMMENT ON COLUMN ENF0001.ENF_VLFRETEPORFORA IS 'VALOR DO FRETE POR FORA';
COMMENT ON COLUMN ENF0001.ENF_VLRDIFICMS IS 'VALOR DA DIFERENCA DE ICMS';
COMMENT ON COLUMN ENF0001.ENF_VLOUTROS IS 'OUTROS VALORES NAO ESPECIFICADOS NOS OUTROS CAMPOS';
COMMENT ON COLUMN ENF0001.ENF_VLFRETE IS 'VALOR DO FRETE VINDO NA NOTA';
COMMENT ON COLUMN ENF0001.ENF_XML IS 'XML DA NOTA';
COMMENT ON COLUMN ENF0001.FOR_CODIGO IS 'REFERENCIA DO CADASTRO DE FORNECEDORES';
COMMENT ON COLUMN ENF0001.ENF_EMISSAO IS 'EMISSAO DA NOTA FISCAL';
COMMENT ON COLUMN ENF0001.ENF_ENTRADA IS 'DATA DE ENTRADA';
COMMENT ON COLUMN ENF0001.OPE_CODIGO IS 'REFERENCIA DO CADASTRO DE OPERACOES FISCAIS';
COMMENT ON COLUMN ENF0001.OPE_NATUREZA IS 'CFOP DA OPERACAO FISCAL';
COMMENT ON COLUMN ENF0001.PCL_CODIGO IS 'REFERENCIA DE PRAZO DE PAGAMENTO';
COMMENT ON COLUMN ENF0001.ENF_MODELO_NF IS 'MODELO DA NOTA FISCAL';
COMMENT ON COLUMN ENF0001.ENF_SERIE IS 'SERIE DA NOTA';
COMMENT ON TABLE OPE0000 IS 'OPERACOES FISCAIS';
