unit ClasseListaPreco;

{*******************************************************************************
    Generated By   : JsonToDelphiClass - 0.65 (http://jsontodelphi.com)
    Projeto        : Mercos
    Gerado         : 2019-07-10 16:41:40
	Classe         : Lista de preços
    Criado por     : Jairo Monassa
    
*******************************************************************************}

interface

uses Generics.Collections, Rest.Json;

type

TListaPreco = class
private
  FDesconto: Extended;
  FExcluido: Boolean;
  FNome: String;
  FTipo: String;
public
  property desconto: Extended read FDesconto write FDesconto;
  property excluido: Boolean read FExcluido write FExcluido;
  property nome: String read FNome write FNome;
  property tipo: String read FTipo write FTipo;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TListaPreco;
end;

TItemLista = class
private
  FPreco: Extended;
  FProduto_id: Extended;
  FTabela_id: Extended;
public
  property preco: Extended read FPreco write FPreco;
  property produto_id: Extended read FProduto_id write FProduto_id;
  property tabela_id: Extended read FTabela_id write FTabela_id;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TItemLista;
end;

implementation

{TListaPreco}


function TListaPreco.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TListaPreco.FromJsonString(AJsonString: string): TListaPreco;
begin
  result := TJson.JsonToObject<TListaPreco>(AJsonString)
end;

{TItemLista}

function TItemLista.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TItemLista.FromJsonString(AJsonString: string): TItemLista;
begin
  result := TJson.JsonToObject<TItemLista>(AJsonString)
end;

end.