unit ClassePagamento;

{*******************************************************************************
    Generated By   : JsonToDelphiClass - 0.65 (http://jsontodelphi.com)
    Projeto        : Mercos
    Gerado         : 2019-07-10 16:41:40
	Classe         : Condições de pagamento https://sandbox.mercos.com/api/v1/condicoes_pagamento
    Criado por     : Jairo Monassa
    
*******************************************************************************}


interface

uses Generics.Collections, Rest.Json;

type

TCondicaoPagamento = class
private
  FExcluido: Boolean;
  FNome: String;
  FValor_minimo: Extended;
public
  property excluido: Boolean read FExcluido write FExcluido;
  property nome: String read FNome write FNome;
  property valor_minimo: Extended read FValor_minimo write FValor_minimo;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TCondicaoPagamento;
end;

implementation

{TCondicaoPagamento}


function TCondicaoPagamento.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TCondicaoPagamento.FromJsonString(AJsonString: string): TCondicaoPagamento;
begin
  result := TJson.JsonToObject<TCondicaoPagamento>(AJsonString)
end;

end.