unit ClasseTransportador;

{*******************************************************************************
    Generated By   : JsonToDelphiClass - 0.65 (http://jsontodelphi.com)
    Projeto        : Mercos
    Gerado         : 2019-07-10 16:41:40
	Classe         : Transportador https://sandbox.mercos.com/api/v1/transportadoras
    Criado por     : Jairo Monassa
    
*******************************************************************************}


interface

uses Generics.Collections, Rest.Json;

type

TTrasportador = class
private
  FCidade: String;
  FEstado: String;
  FExcluido: Boolean;
  FInformacoes_adicionais: String;
  FNome: String;
public
  property cidade: String read FCidade write FCidade;
  property estado: String read FEstado write FEstado;
  property excluido: Boolean read FExcluido write FExcluido;
  property informacoes_adicionais: String read FInformacoes_adicionais write FInformacoes_adicionais;
  property nome: String read FNome write FNome;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TTrasportador;
end;

implementation

{TTrasportador}


function TTrasportador.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TTrasportador.FromJsonString(AJsonString: string): TTrasportador;
begin
  result := TJson.JsonToObject<TTrasportador>(AJsonString)
end;

end.