unit TabelaPrecos;

{*******************************************************************************
    Generated By   : JsonToDelphiClass - 0.65 (http://jsontodelphi.com)
    Projeto        : Mercos
    Gerado         : 2019-10-11 11:25:40
	Classe         : Tabela de preços
    Criado por     : Jairo Monassa
    
*******************************************************************************}

interface

uses Generics.Collections, Rest.Json;

type

TTabelaPreco = class
private
  FExcluido: Boolean;
  FId: Extended;
  FNome: String;
  FTipo: String;
  FUltima_alteracao: TDateTime;
public
  property excluido: Boolean read FExcluido write FExcluido;
  property id: Extended read FId write FId;
  property nome: String read FNome write FNome;
  property tipo: String read FTipo write FTipo;
  property ultima_alteracao: TDateTime read FUltima_alteracao write FUltima_alteracao;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TTabelaPreco;
end;

implementation

{TTabelaPreco}


function TTabelaPreco.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TTabelaPreco.FromJsonString(AJsonString: string): TTabelaPreco;
begin
  result := TJson.JsonToObject<TTabelaPreco>(AJsonString)
end;

end.
