SELECT
    T1.fat_codigo,
    T2.cli_codigo,
    T2.REP_CODIGO,
    T7.REP_NOME,
    T5.CLI_RAZAO,
    T3.FAT_DTEMIS,
    T2.FPC_VENCTO,
    T2.FPC_PAGTO,
    T1.PRD_REFER,
    T4.PRD_DESCRI,
    T4.LIN_CODIGO,
    T1.FIT_QTDE,
    T1.FIT_PRECO,
    T1.FIT_COMIS,
    T8.LIN_DESCRI
FROM FAT_IT02 T1
JOIN FAT_PC01 T2 on (T2.fat_registro IN (SELECT FIRST 1 T6.fat_registro FROM fat_pc01 T6 WHERE T6.fat_codigo = T1.fat_codigo))
JOIN FAT0000 T3 ON (T3.FAT_CODIGO = T2.FAT_CODIGO)
JOIN PRD0000 T4 ON (T4.PRD_REFER = T1.PRD_REFER)
JOIN CLI0000 T5 ON (T5.CLI_CODIGO = T3.CLI_CODIGO)
JOIN REP0000 T7 ON (T7.REP_CODIGO = T2.REP_CODIGO)
JOIN PRD_LINHA T8 ON (T8.LIN_CODIGO = T4.LIN_CODIGO)
GROUP BY
    T1.fat_codigo,
    T2.cli_codigo,
    T2.REP_CODIGO,
    T7.REP_NOME,
    T5.CLI_RAZAO,
    T3.FAT_DTEMIS,
    T2.FPC_VENCTO,
    t2.FPC_PAGTO,
    T1.PRD_REFER,
    T4.PRD_DESCRI,
    T4.LIN_CODIGO,
    T1.FIT_QTDE,
    T1.FIT_PRECO,
    T1.FIT_COMIS,
    T8.LIN_DESCRI
ORDER BY T2.REP_CODIGO,T4.LIN_CODIGO
