DROP INDEX FAT0000_IDX1;
DROP INDEX XFAT_CODIGO;
DROP INDEX XFAT_CODIGO_EMPRESA;
DROP INDEX XFAT_COMPOSTO;

DROP INDEX FAT_PC01_IDX4;
DROP INDEX FAT_PC01_IDX5;
DROP INDEX XFATPCCOMPOSTO;
DROP INDEX XFATPCOMPOSTO;

UPDATE FAT0000 SET FAT_CODIGO = SUBSTRING (FAT_CODIGO FROM 3 FOR 4)
WHERE CAST(FAT_CODIGO AS NUMERIC) < 9999
AND FAT_DTEMIS < '09.05.2008'
AND FAT_CODIGO <> 'orçpla'
AND FAT_CODIGO <> '00inv.'
AND FAT_CODIGO <> '00FERT'
AND FAT_CODIGO <> 'ORÇ023'
AND FAT_CODIGO <> '000CBB'
AND FAT_CODIGO <> '0PIAZZ'
AND FAT_CODIGO <> '0034/0'
AND FAT_CODIGO <> '0GRECA';

UPDATE FAT0000 SET FAT_CODIGO = '99'||FAT_CODIGO
WHERE CAST(FAT_CODIGO AS NUMERIC) < 9999
AND FAT_DTEMIS < '09.05.2008'
AND FAT_CODIGO <> 'orçpla'
AND FAT_CODIGO <> '00inv.'
AND FAT_CODIGO <> '00FERT'
AND FAT_CODIGO <> 'ORÇ023'
AND FAT_CODIGO <> '000CBB'
AND FAT_CODIGO <> '0PIAZZ'
AND FAT_CODIGO <> '0034/0'
AND FAT_CODIGO <> '0GRECA';

UPDATE FAT_PC01 SET FAT_CODIGO = SUBSTRING (FAT_CODIGO FROM 3 FOR 4)
WHERE CAST(FAT_CODIGO AS NUMERIC) < 9999
AND FPC_DTEMIS < '09.05.2008'
AND FAT_CODIGO <> 'orçpla'
AND FAT_CODIGO <> '00inv.'
AND FAT_CODIGO <> '00FERT'
AND FAT_CODIGO <> 'ORÇ023'
AND FAT_CODIGO <> '000CBB'
AND FAT_CODIGO <> '0PIAZZ'
AND FAT_CODIGO <> '0034/0'
AND FAT_CODIGO <> '0GRECA';

UPDATE FAT_PC01 SET FAT_CODIGO = '99'||FAT_CODIGO
WHERE CAST(FAT_CODIGO AS NUMERIC) < 9999
AND FPC_DTEMIS < '09.05.2008'
AND FAT_CODIGO <> 'orçpla'
AND FAT_CODIGO <> '00inv.'
AND FAT_CODIGO <> '00FERT'
AND FAT_CODIGO <> 'ORÇ023'
AND FAT_CODIGO <> '000CBB'
AND FAT_CODIGO <> '0PIAZZ'
AND FAT_CODIGO <> '0034/0'
AND FAT_CODIGO <> '0GRECA';

CREATE INDEX FAT0000_IDX1 ON FAT0000 (EMP_CODIGO, FAT_CODIGO);
CREATE INDEX XFAT_CODIGO ON FAT0000 (FAT_CODIGO);
CREATE INDEX XFAT_CODIGO_EMPRESA ON FAT0000 (FAT_CODIGO, EMP_CODIGO);
CREATE INDEX XFAT_COMPOSTO ON FAT0000 (FAT_CODIGO, CLI_CODIGO, FAT_DTEMIS);

CREATE INDEX FAT_PC01_IDX4 ON FAT_PC01 (FAT_CODIGO);
CREATE INDEX FAT_PC01_IDX5 ON FAT_PC01 (EMP_CODIGO, FAT_CODIGO);
CREATE INDEX XFATPCCOMPOSTO ON FAT_PC01 (FAT_CODIGO, CLI_CODIGO, FPC_DTEMIS, FPC_NUMER);
CREATE INDEX XFATPCOMPOSTO ON FAT_PC01 (FAT_CODIGO, CLI_CODIGO, FPC_DTEMIS, FPC_NUMER);


