UPDATE PED_IT01
    SET PED_IT01.PRF_FLAG_ATUALIZA_ESTOQUE = 'N'
WHERE PED_IT01.PRF_SITUACAO = 'F' AND
      PED_IT01.PED_CODIGO IN (
    SELECT
    PED0000.PED_CODIGO
    from PED0000
    WHERE PED0000.OPV_CODIGO = 16);

